### PR TITLE
Modified style for step remove notification

### LINKED ISSUE #610: Center Align Step Removed Notification
### Please describe the problem (or idea)

The notification toast which appears when a step is removed is not center aligned on smaller screens.

not-center-aligned toast

screenshot_20190105-191448

### Possible fixes

Instead of appending a `span`, appending a `div` with `display: flex` and `width: 100%` could solve the issue. Instead of using `$.fadeIn`, `$.animate` the opacity from `0` to `1`.

### Where to look

https://github.com/publiclab/image-sequencer/blob/107b4c22e44dd3363095104a2df51cc5b2a07597/examples/lib/defaultHtmlStepUi.js#L10-L20

https://github.com/publiclab/image-sequencer/blob/107b4c22e44dd3363095104a2df51cc5b2a07597/examples/demo.css#L204-L216

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #610 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Now the step removed notification appears in the centre even for smaller screens.
capture

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this is cool -- is there a standard bootstrap style we might use for this? If not, happy to merge this. Thanks!

**Comment by aashna27** [comment]
> Hi, this is cool -- is there a standard bootstrap style we might use for this? If not, happy to merge this. Thanks!

I did not go in that direction just searched related to what was already there. I think this works pretty well and bootstrap isnt needed.What say ??

**Comment by jywarren** [comment]
Ok, I'm not super opinionated and this does look good. Mainly I'm looking to keep custom styles to a minimum to reduce maintenance and achieve compatibility as our project grows. Thanks, I'll merge this!

**Comment by aashna27** [comment]
> Ok, I'm not super opinionated and this does look good. Mainly I'm looking to keep custom styles to a minimum to reduce maintenance and achieve compatibility as our project grows. Thanks, I'll merge this!

Yeah !! Totally understand it.. 😄

**Pull request merged**
