### PR TITLE
improved way of displaying docs link

### LINKED ISSUE #1526: More General Method of Displaying Docs Links
### Please describe the problem (or idea)
The following code is used to display the docs links for each module in the UI.
https://github.com/publiclab/image-sequencer/blob/d1b9b8beccdbe5ba98cf4e352af103b4913a5fe6/examples/lib/defaultHtmlStepUi.js#L48-L50

The code just links to a general link that may not work for every module. Instead, the link should be imported from every module's `info.json` file instead.
https://github.com/publiclab/image-sequencer/blob/d1b9b8beccdbe5ba98cf4e352af103b4913a5fe6/src/modules/BlobAnalysis/info.json#L6

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by vivek-30**
Fixes #1526

### CODE REVIEW

**Comment by vivek-30** [comment]
apologies for the blunder 😅

**Comment by HarshKhandeparkar** [comment]
Even Linus Torvalds(creator of git) must have made mistakes in committing or merging branches. It is all fine :smile:

**Comment by jywarren** [comment]
Thanks @vivek-30 and thanks @HarshKhandeparkar!

@vivek-30 indeed don't worry, we're here to help!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Great work, thank you very much!!!

**Comment by vivek-30** [comment]
Thanks you @jywarren , @HarshKhandeparkar  you both have helped me out while solving these issues , may be without your help @HarshKhandeparkar it becomes difficult to solve this.loved to contribute here ☺️

**Pull request merged**
