### PR TITLE
Display width and height of image at each step

### LINKED ISSUE #1023: Display width and height of image at each step
### Please describe the problem (or idea)

What we very casually come across is getting the dimensions of the image we are processing, so I think we can provide these details somewhere in our panel. Maybe we can provide a button which can show or hide these details as per the choice of user.

### PR DESCRIPTION
**Pull request by blurry-x-face**
Fixes #1023 

Screenshot from 2019-11-28 16-03-11

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers @Divy123   please review this

**Comment by Divy123** [comment]
Can you please share a working GIF?

Thanks!!

**Comment by Divy123** [comment]
Alsi please test the function added. You can add a unit test fir this.

**Comment by jywarren** [comment]
Thanks! Yes this is looking really good!

**Comment by jywarren** [comment]
Awesome! Thanks!!!!

**Pull request merged**
