### PR TITLE
Added Download button

### LINKED ISSUE #1020: Image downloading on image click is undesirable
### Please describe the problem (or idea)
Every time and most of the time by mistake, we click on an image it gets downloaded which is most of the time undesirable

### Solution

A download image button can be added to the panel for this purpose .

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #1020 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

Screenshot from 2019-06-04 04-20-46
down

### CODE REVIEW

**Comment by aashna27** [comment]
@publiclab/reviewers @jywarren

**Comment by jywarren** [comment]
Awesome!

Hey, i found a bug and so did @aashna27 -- the top 2 issues right now. Maybe we should take a short break and do a bit of core code fixing and test-adding? What do you think?

**Comment by Divy123** [comment]
Yeah I think we should have these things fixed as soon as possible.
And write as many tests as possible.

**Comment by jywarren** [comment]
Awesome work folks!

**Pull request merged**
