### PR TITLE
Change dimension upon loading through camera

### PR DESCRIPTION
**Pull request by ataata107**
Concerns #1391 
In PR #1395 Only the case of loading image was taken care of not the loading through camera. This PR fixes that

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] ask `@publiclab/is-reviewers` for help, in a comment below
* [X] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by ataata107** [comment]
@publiclab/is-reviewers

**Comment by ataata107** [comment]
@HarshKhandeparkar do i need to refactor in order to fix the codeclimate issue

**Comment by HarshKhandeparkar** [comment]
Nah. Let it be.

**Review by HarshKhandeparkar — APPROVED** [review]

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Great, thanks!!!!

**Comment by jywarren** [comment]
Nice!!

**Pull request merged**
