### PR TITLE
Module tests

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #0000  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren I have currently changed the old tests but did not add any new ones. Just refactored some old ones. The tests for webgl-distort do not work so I commented those. It shows some puppeteer error.

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers modules left are:
- blend
- colorbar
- crop
- dynamic
- fisheye-gl
- gamma-correction
- overlay
- webgl-distort

**Comment by Divy123** [comment]
Crop module has been tested.

**Comment by HarshKhandeparkar** [comment]
I ran into problems so I removed it.

**Comment by Divy123** [comment]
Please specify your problem so that I can help you with that!!

**Comment by HarshKhandeparkar** [comment]
I don't even remember now. Sorry. I will try testing it tomorrow and if I
run into problems again, I will surely let you know. Thanks a lot!

**Comment by Divy123** [comment]
Sure! No problem.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I managed to add tests for the crop module but I did run into problems initially. `number` inputs for options do not work. i.e
```js
{
  x: 20,
  y: 30,
  w: 20,
  h: 20
}
```
is not valid, but 
```js
{
  x: '20',
  y: '30',
  w: '20',
  h: '20'
}
```
is valid.

**Comment by HarshKhandeparkar** [comment]
Same happens in the case of colorbar module because it uses crop module in it.

**Comment by Divy123** [comment]
@HarshKhandeparkar you may leave these two.
I will look into as from tomorrow my semester exams are starting..
I will look them after they end in a separate PR.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I fixed the problems by passing string options but the big has to be fixed.

**Comment by Divy123** [comment]
@HarshKhandeparkar I think somehow someone changed the defaults in crop to number though it was not supposed to be. Actually we can take % inputs as well so string is what is expected actually.
Maybe this helps!!

**Comment by HarshKhandeparkar** [comment]
I know we can add `%` string inputs but number inputs should still work right?

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers all tests added. Please review :)

**Comment by Divy123** [comment]
Will look into it..
Maybe importing at the steps is not allowing it!!

**Comment by HarshKhandeparkar** [comment]
@Divy123 could you please review the PR too?

**Comment by jywarren** [comment]
Wowwwwww!!!! 

> Merging #1058 into main will increase coverage by 21%.

We should merge this right after Aashna's linting PR!!!

**Comment by HarshKhandeparkar** [comment]
Ok

**Comment by HarshKhandeparkar** [comment]
@jywarren when will Aashna's PR be merged?

**Comment by aashna27** [comment]
I am trying to fix the installation process which shows errors related to
gl installation. As soon as I fix the installation I ll push changes.

**Comment by HarshKhandeparkar** [comment]
So you are going to push once more right? What if this PR is merged and you
lint the newly added code after rebasing? Is that ok with you? @jywarren?

**Comment by aashna27** [comment]
I have no problem with merging this pr, but I would really appreciate your help to solve this installation error as its related to gl, the recent pr by you.
image

**Comment by HarshKhandeparkar** [comment]
Let's discuss this in your PR, ok?

**Comment by jywarren** [comment]
Oh, Aashna, which do you think we should merge first? Thanks!

**Comment by HarshKhandeparkar** [comment]
@jywarren I am currently working on `scopeQuery`. And why do I have the permissions to merge this PR?

**Comment by aashna27** [comment]
Yeah sure @jywarren I really appreciate your concern for merging my pr
first! Thanks a lot! And it will be great to merge this one before mine,
the coverage is great! 👍😊

**Comment by HarshKhandeparkar** [comment]
Thanks a lot @aashna27. I have commented on your PR about the install error. I will help you in fixing the error as fast as possible.

**Comment by HarshKhandeparkar** [comment]
@jywarren @aashna27 I am also done with https://github.com/publiclab/image-sequencer/pull/710. Please review those too. Thanks.

**Comment by jywarren** [comment]
OK! Great work here, this is such a great chart to see:

image

🎉

**Comment by jywarren** [comment]
image
https://codecov.io/gh/publiclab/image-sequencer

**Comment by jywarren** [comment]
This is especially a nice folder to look at! https://codecov.io/gh/publiclab/image-sequencer/tree/main/src/modules

**Comment by HarshKhandeparkar** [comment]
Thanks a lot!

**Comment by aashna27** [comment]
This is really great !! was going across tests and came across the changes. Amazing this is !! :smiley:

**Pull request merged**
