### PR TITLE
New shadow module added

### PR DESCRIPTION
**Pull request by niravasher**
working on issue #806 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Nirav. I have a few suggestions.
1. Please refer to [this](https://github.com/publiclab/image-sequencer/blob/main/CONTRIBUTING.md#meta-module) to create a meta-module.
2. Also build the dist files by running `grunt build`.
3. Clear the cache in the browser.

**Comment by niravasher** [comment]
After doing grunt build, the shadow module is visible on my local. I changed info.json and Module.js to create a new metamodule, on module load I get this error

image-sequencer.js:72130 Uncaught TypeError: Cannot read property 'format' of undefined
    at image-sequencer.js:72130
    at Image.img.onload (image-sequencer.js:9605)

I think something is wrong with info.json , I am updating this PR, please have a look at the code @HarshKhandeparkar

**Comment by Harshithpabbati** [comment]
@niravasher please mention @publiclab/is-reviewers  for reviewing it.

**Comment by Harshithpabbati** [comment]
Please checkout as your travis-ci failed...
Thanks

**Comment by HarshKhandeparkar** [comment]
I think you will have to improve upon the gradient module:

1. To choose the direction of gradient. It can be anything like horizontal, vertical, radial(maybe), both horizontal and vertical (somehow).

2. Percentage of starting grading to ending gradient. Maybe the gradient can go from being x% dark to y% dark. E.g 70% to 60%.

You can try implementing these features 😊. Thanks

**Comment by niravasher** [comment]
Gradients for issue #822 right @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
@niravasher what I meant was that limitations of the gradient module will only create a shadow in a single direction and single intensity in this shadow module. So I felt like the gradient module can be improved upon by implementing the changes I suggested. Thanks.

**Comment by niravasher** [comment]
Ok, looking into it @HarshKhandeparkar

**Comment by jywarren** [comment]
I wonder if we tried the sequence i suggested before, like:

>  I could imagine creating a black mask by turning darkness to max, then blurring that mask. It seems we would also need to increase the image size to make space for the shadow. 

So

1. brightness all the way dark
2. blur that dark image
3. expand canvas
4. overlay original image over blurred darkened image

**Pull request closed without merging**
