### PR TITLE
Format the "Take a Photo" button  

### PR DESCRIPTION
**Pull request by lokesh541**
Fixes  https://github.com/publiclab/image-sequencer/issues/737

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!
screenshot_2019-02-01 image sequencer 2

### CODE REVIEW

**Comment by lokesh541** [comment]
hi @publiclab/is-reviewers  can you review my changes

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
@lokesh541 can you please share a screenshot/GIF?

**Comment by HarshKhandeparkar** [comment]
Also please replace the `#[add isue number here.]` with a link to the concerning issue. Thanks!

**Comment by HarshKhandeparkar** [comment]
@lokesh541 there is bo need for closing the PR

**Comment by HarshKhandeparkar** [comment]
Also while linking what you can do is
`https://link-to-issue` will be converted to `#issue-number` directly be github

**Comment by HarshKhandeparkar** [comment]
Lokesh why have you closed the PR?

**Comment by lokesh541** [comment]
I didn't close it

**Comment by lokesh541** [comment]
sorry it might be an accident can't we reopen it

**Comment by HarshKhandeparkar** [comment]
Also please provide a screenshot. Thanks!

**Comment by lokesh541** [comment]
thank you should I add screenshot of the issue or the code ?

**Comment by HarshKhandeparkar** [comment]
Screenshot of the button in a browser.

**Comment by lokesh541** [comment]
how to add the screenshot?

**Comment by HarshKhandeparkar** [comment]
There is an upload file button at the end of the text input field for
comments/PR

**Comment by lokesh541** [comment]
screenshot_2019-02-01 image sequencer

**Comment by HarshKhandeparkar** [comment]
@lokesh can you please provide a screenshot of the whole page? Sot that we can see how it mixes with the rest of the page.

**Comment by lokesh541** [comment]
screenshot_2019-02-01 image sequencer 1

**Comment by HarshKhandeparkar** [comment]
@lokesh541 the button looks almost the same as before. Can you try something different like a different colored btn?

**Comment by lokesh541** [comment]
this is how it looks after making changes

screenshot_2019-02-01 image sequencer 2

**Comment by HarshKhandeparkar** [comment]
:+1:

**Comment by lokesh541** [comment]
thank you for answering all my questions patiently

**Comment by HarshKhandeparkar** [comment]
Np Lokesh. Troubleshooting/reviewing a PR is only my work and I love doing that 😊

**Comment by jywarren** [comment]
Great work! 🙌🏽👍🏽👍🏽

**Pull request merged**
