### PR TITLE
Fix no file chosen place

### LINKED ISSUE #356: 'No file chosen' wrongly placed in Import Image module
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem
'No file chosen' option in import image module is misplaced, ie. out of the box
 
screenshot from 2018-09-29 22-14-47

## The Solution
We need to modify css such that it comes inside border or under Choose file button.
The line which needs to be mdified is:

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/src/modules/ImportImage/Ui.js#L16

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/src/modules/ImportImage/Ui.js#L11

You need to add class to it and add the new css for the specific class. 

**Instance Count = 1**

### PR DESCRIPTION
**Pull request by adiwahyudi02**
Fixes #356

Before

After

Add some styles for wrapper div
Thanks!

### CODE REVIEW

**Comment by adiwahyudi02** [comment]
i'm not sure, because i've set min-width statically

**Comment by tech4GT** [comment]
Oh, It would be great if you can try it in different sized viewports, for that you can use you chrome dev tools, just inspect the page and try different screen sizes there. Thanks and great work! :smile:

**Comment by HarshKhandeparkar** [comment]
Will it look good if the text is rendered below the button.

**Comment by Dhiraj240** [comment]
> Will it not look good if the text is rendered below the button?

@tech4GT This way will reduce the box size too. @adiwahyudi02  Follow up with this suggestion.

**Comment by tech4GT** [comment]
I guess that can work too.

**Comment by HarshKhandeparkar** [comment]
@adiwhyudi are you still working on this? If yes then you should probably move the changes to `examples/demo.css`

**Comment by HarshKhandeparkar** [comment]
Seems like this has been fixed. This PR is redundant. Can it be closed? @jywarren @gauravano

**Comment by gauravano** [comment]
Thanks for status update @HarshKhandeparkar. This fix is not required due to change in page design @jywarren @tech4GT. Feel free to open the PR if you think anything can be optimized with this. Thanks @adiwahyudi02 for working on it!

**Pull request closed without merging**
