### PR TITLE
Added resize button in examples/index.html

### LINKED ISSUE #499: Add resize module to list of quick buttons
This issue is a sub-issue of #487 , which is to be broken down into smaller issues.

In the image-sequencer, there are a list of quick-buttons so the user can add commonly-used layers quickly:
image

What we want to do is to add another quick-add button for the resize functionality. Here's the todo for this task:

- [ ] Find a suitable icon on font-awesome and link it here **make sure it's from the v4.5 icon set!**
- [ ] Add the icon in the appropriate button style in examples/index.html.
image
- [ ] Keep in mind the proper syntax for data-value, which can be checked by navigating to the proper component in src/modules. It is lowercase

### Please show us where to look

http://sequencer.publiclab.org/examples/#steps=

### What's your PublicLab.org username?

JonathanXu1

### Browser, version, and operating system

Firefox63, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by TG1999**
Fixes #499 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by TG1999** [comment]
image

**Comment by HarshKhandeparkar** [comment]
Try to fix the overflow.

**Comment by TG1999** [comment]
I am not able to fix the overflow

**Comment by gauravano** [comment]
Hi @TG1999, you could try @HarshKhandeparkar suggestion for fixing overflow. Thanks!

**Comment by jywarren** [comment]
Hi! I think we've solved the overflow issue using a style in the latest main branch. Would you like to try rebasing this to get it merged? Thanks!

**Comment by HarshKhandeparkar** [comment]
@TG1999 this PR is good to go. Can you please do the suggested changes? Comment if you need any help. Thanks!

**Comment by HarshKhandeparkar** [comment]
Also please rebase the branch and merge with main.

**Comment by TG1999** [comment]
I have opened a new PR #699 please check it I had pull the recent main branch and then committed the changes please have a look and merge it into the main branch

**Comment by HarshKhandeparkar** [comment]
@TG1999 thanks. Closing this one

**Pull request closed without merging**
