### PR TITLE
Alphabetically arranged the MODULES.md file #1167

### LINKED ISSUE #1167: Alphabetically arrange modules in Module docs
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

_**To gain a sense of what the issue targets go to [MODULES.md](https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md) , we see the module names are arranged somewhat randomly. So the task is to arrange them to make it visibly easy to search for some specific module doc.**_

- [ ] 📝 **Update** the following file

   **1. [MODULES.md](https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md) and arrange the module names' list alphabetically.**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by kirito-k**
Fixes #1167  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by aashna27** [comment]
@kirito-k Thank you so much you have done great work! Really helpful.. Welcome to the community and we all would really appreciate more contributions!! :clinking_glasses: :tada:

**Comment by Divy123** [comment]
@kirito-k awesome work! :tada: :tada: 

Your help is greatly appreciated and looking for more for it in near future and thanks a lot for making the docs a more organised one!!

:+1: :tada: :rocket:

**Comment by Divy123** [comment]
@jywarren this is ready to be merged!

**Comment by aashna27** [comment]
Harsh we can also leave them like that as they do link to the docs! What do
you think?

**Comment by HarshKhandeparkar** [comment]
It is always better if we alphabetically arrange it. Isn't it so? It looks
better and properly formatted.

**Comment by aashna27** [comment]
Yeah great then!

**Comment by jywarren** [comment]
This looks awesome! I'm 👍 alphabetizing in other places too, and we can do this in another PR! Thanks, all, and thanks for the reviews too! Great work, @kirito-k !!! 🎉

**Comment by aashna27** [comment]
So i guess the merge is waiting for the conflicts to be resolved. @kirito-k this would be ready to merge as soon as the conflicts are resolved! You will need to update your main and this pr's branch and then see which changes you need to keep as you resolve conflicts.

**Comment by aashna27** [comment]
@kirito-k are you facing any issues! I went through the conflicts they are pretty minimal what you have to do is just accept your changes ie the alphabetic changes you have made and then also add to the list the text-overlay list and also accept the text overlay documentation!

**Comment by kirito-k** [comment]
@aashna27 Hey. I changed the sequence of all the text below index accordingly. Now do I have to make a new PR or when I changed my own code it automatically got reflected here? Also, I am not able to understand how to resolve conflicts. Do I resolve the conflicts or you do?

**Comment by aashna27** [comment]
The changes you made locally need to be pushed to your brach.

**Comment by aashna27** [comment]
So the procedure I follow for resolving conflicts is, to first checkout to
main branch and update it, using fetch upstream.

Then you switch to your branch and do git rebase -i upstream/main
This will show the conflicting files and then you resolve the conflicts
locally in editor and push it again to branch.

**Comment by aashna27** [comment]
@kirito-k if you are stuck just open a new pr by updating your main and that one can be merged!

**Comment by HarshKhandeparkar** [comment]
I guess the new PR is here https://github.com/publiclab/image-sequencer/pull/1186

**Pull request closed without merging**
