### PR TITLE
Removed Global Variables, Added a Test to check this

### PR DESCRIPTION
**Pull request by ccpandhare**
While making a demo, I realized that ImageSequencer was producing 22 Global Variables:
`v`,`formatInput`,`args`,`arg`,`json_q`,`format_i`,`i`,`loadedimages`,`datauri`,`image`,`insert`,`img`,`s`,`j`,`indices`,`callback`,`prevstep`,`drawarray`,`no_steps`,`init`,`input`,`this_`.

I have fixed this issue and created a new Unit test to check that no Global Variables are being created.

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great but are the Travis tests stalled?

Should this be needed before or after the fisheyegl PR?

Thanks!

**Comment by ccpandhare** [comment]
This can be merged in Anytime... Shouldn't be a problem.
I am restarting the TravisCI Build

**Comment by ccpandhare** [comment]
But preferably after FisheyeGl.

**Comment by ccpandhare** [comment]
The build has passed!

**Comment by jywarren** [comment]
:-) -- since fisheyegl may take a bit longer to open a PR on and such, go
ahead and merge this if you'd like to get it off your plate! Great catch
and good refactor. Thanks!

**Comment by ccpandhare** [comment]
Okay, will merge! Actually, FisheyeGl is pretty god as of now.
Please have a look at #61, #62. Also, I have a demo for FisheyeGl running at https://ccpandhare.github.io/image-sequencer/examples/fisheyegl

**Comment by ccpandhare** [comment]
And thanks for the compliment!
It really means a lot :-)

**Pull request merged**
