### PR TITLE
Added DecodeQr Module, Test

### PR DESCRIPTION
**Pull request by ccpandhare**
I have added the Decode QR Module. It supports logos and colors on QR Codes too.
I have also added a short test to check if the following QR Code resolves to "http://github.com/publiclab/image-sequencer":
Image Sequencer QR Code

### CODE REVIEW

**Comment by ccpandhare** [comment]
@jywarren I think this is ready to go, if you may!

**Comment by jywarren** [comment]
Hi, can you resolve conflicts? And should this relate to the generation of metadata?

**Comment by ccpandhare** [comment]
No, I think the conflicts have to do with the UI Pull Request.
Yes, this module will generate metadata too, but the metadata PR isn't merged yet.

**Comment by ccpandhare** [comment]
I have fixed the conflict. But, The UI component for this is not over yet.
`UI.onComplete` expects an image to be given in the parameters, but the main output of this Module is text. I am not sure how to go about this.

**Comment by jywarren** [comment]
did you think it should wait until metadata is complete and then send the
text there? or is there an additional question? Thanks!

**Comment by ccpandhare** [comment]
I have an additional query. The UI system currently expects every module to give an output DataURL. This module produces a text output, and passes on the original image to the next module.

So that is a problem.

**Comment by jywarren** [comment]
ah, but I think it's fine for the output to be the same as the input if the
module is not intended to modify the image.

On Wed, Jul 26, 2017 at 10:54 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
Yes, but we still have no system to give the textual output to the user...

**Comment by ccpandhare** [comment]
I have resolved conflicts and updated the structure of `decode-qr` module

**Comment by ccpandhare** [comment]
I realized that the latest UI System has solved this problem!
Since user has access to the `step` namespace,
The module can set up `step.VarName` and `onComplete` will then be called!

This system basically gives modules their own I/O!

**Comment by jywarren** [comment]
Hmm, I don't quite follow but this sounds great - I love when good
architecture produces unintended extra benefits. Could you walk through an
example though as part of the documentation?

On Jul 31, 2017 4:00 PM, "Chinmay Pandhare" <notifications@github.com>
wrote:

I realized that the latest UI System has solved this problem!
Since user has access to the step namespace,
The module can set up step.VarName and onComplete will then be called!

This system basically gives modules their own I/O!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/pull/72#issuecomment-319179330>,
or mute the thread

**Comment by ccpandhare** [comment]
I am sorry, I might have not explained this correctly.

Under the new UI System, every step was given a new object `options.step`
This object stores data like image output, module name, step ID, name of image, etc.
This object is passed in to the UI functions.

```js
sequencer.setUI(
    onComplete: function(step) {
       console.log(step.imageName);
    }
);
```

The properties of this object can be defined and accessed by both the module and the user:

```js
sequencer.setUI(
    onSetup: function(step) {
       step.img = document.createElement('img');
    }
);
```

So in this context we can do

* The module file
    ```
    options.step.qrcode = "Value";
    UI.onComplete(options.step);
    ```
* The User Script
    ```
    sequencer.setUI(
        onComplete: function(step) {
            console.log(step.qrcode);
        }
    );
    ```

This is how modules got their own I/O with non-image data

**Comment by ccpandhare** [comment]
So can this go in?

**Comment by jywarren** [comment]
Ack, looks like it has some conflicts. But yes, this sounds great!

**Comment by ccpandhare** [comment]
Okay then! I shall resolve the conflicts and merge this in!

**Comment by jywarren** [comment]
+1! :-)

**Pull request merged**
