### PR TITLE
Colorbar added

### PR DESCRIPTION
**Pull request by tech4GT**

### CODE REVIEW

**Comment by jywarren** [comment]
Can the color are module have x,y,w,h parameters w overridable defaults? This is looking good!

Any ideas on text overlay for labels? It sounds like it may be hard ...

**Comment by tech4GT** [comment]
@jywarren yeah I guess it’ll take some research 😄

**Comment by tech4GT** [comment]
@jywarren So the current functionality is that what we can say is `#steps=colorbar{h:100}` to get a colorbar of height 100 but once it's loaded in the UI we have to change inputs for individual modules. I'll improve upon this in a future version but I think this should do for v1.
so now colorbar has following inputs 
```json
"colormap": {
            "type": "select",
            "desc": "Name of the Colormap",
            "default": "default",
            "values": [
                "default",
                "greyscale",
                "stretched",
                "fastie"
            ]
        },
        "x": {
            "type": "integer",
            "desc": "X-position of the image on which the new image is overlayed",
            "default": 0
        },
        "y": {
            "type": "integer",
            "desc": "Y-position of the image on which the new image is overlayed",
            "default": 0
        },
        "h": {
            "type": "iinteger",
            "desc": "height of the colorbar",
            "default": 10
        }
```
so we can say `#steps=colorbar{colormap:grayscale|h:50}`

**Comment by jywarren** [comment]
Can you post a new screenshot? It looked like the colorbar at the top of the previous screenshot has 2 spectrums side by side, no? 

https://publiclab.org/notes/cfastie/08-26-2014/new-ndvi-colormap

That post actually has some good examples of colorbars in active use.

Do you think we could implement a "scale" or "resize" module and include it here in order to do the colorbars not full-width? 

Anyhow, looking good and these things could be done in a follow-up... if you can post the updated screenshot we can likely merge here!

Great work!

**Comment by tech4GT** [comment]
@jywarren Yeah!! That bugged me too, but the thing is that running colormap on the gradient is giving that only, I tried it a few different ways, I am posting another screenshot here but can you please go through the code once and check that my algorithm is correct. Thanks!!

**Comment by tech4GT** [comment]
screen shot 2018-08-06 at 8 19 29 pm
screen shot 2018-08-06 at 8 19 38 pm

**Comment by jywarren** [comment]
can you try a different colormap? Like stretched?

**Comment by tech4GT** [comment]
screen shot 2018-08-06 at 9 13 26 pm

**Comment by tech4GT** [comment]
screen shot 2018-08-06 at 9 14 20 pm

**Comment by jywarren** [comment]
Ah those two look right! Maybe the implementation for the default is wrong
and this module helped discover it???

**Comment by tech4GT** [comment]
hmm that maybe right!! I think we can merge this one in and raise a separate issue for ndvi. For now I'll make stretched the default colormap in colorbar. What say?

**Comment by jywarren** [comment]
That sounds great.

**Comment by jywarren** [comment]
Shall we publish to gh-pages now, then?

**Comment by tech4GT** [comment]
Awesome!!!!!🎉

**Comment by tech4GT** [comment]
I think we should after a version update..

**Comment by tech4GT** [comment]
should we do x.0.0 or 0.x.0

**Comment by jywarren** [comment]
ok, go ahead and bump the version, then i'll publish to gh-pages!

**Comment by jywarren** [comment]
does it break any previously-relied-upon APIs or documentation?

**Comment by tech4GT** [comment]
I'm not sure, I think we have changed the string syntax but since we are supporting previous versions it should be fine!!

**Pull request merged**
