### PR TITLE
add histogram module

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>
@jywarren Currently this generates a 256x256 histogram, I have not used a plotting library because of their slower performance.
Sample
image1_1
Issue #69

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren Please take a look at this one  as well, does the histogram look okay to you? It's not very pretty but almost all plotting libraries are kind of slow.

**Comment by tech4GT** [comment]
@jywarren Do the visuals look okay to you? Or should we use some plotting library?

**Comment by jywarren** [comment]
Wow, this is cool! What's the gradient at bottom? Perhaps we should have it generate a black graph, which can be changed in color with another module. 

Thanks, Varun!

**Comment by tech4GT** [comment]
Hmm, I don't get you exactly, I added the gradient just to make it easier to visualize. Can you please elaborate?

**Comment by jywarren** [comment]
Hi, oh i get it -- the gradient is like the x-axis label. OK i feel silly not getting that. 

Can we specify the height and width of the generated histogram? Maybe that could be a follow-up issue.

I was thinking the color of the graph could be black instead of green... just because the green is nice but it's a little arbitrary. Do you think we could make that change and then people can colorize this if they want. 

Another follow-up issue is that we could have the gradient toggle-able using a boolean parameter!

Great work, Varun!

**Comment by tech4GT** [comment]
@jywarren Good to go?

**Comment by tech4GT** [comment]
@jywarren Also if we make the histogram black, it would make the gradient indistinguishable from the actual data, so should I change the color pf the gradient bar?

**Comment by jywarren** [comment]
Sorry yeah I think this is good to go. If you'd like maybe we can change the graph from green to a pure red or blue so it's simply 100% in one channel. But either way, I'll merge this if you're ready!!

**Comment by tech4GT** [comment]
Hmm, @jywarren don't you think having pure blue or red is a little displeasing to the eye? I mean we can always colormap this to greyscale anyway..

**Comment by jywarren** [comment]
Ok! I'm happy to merge this then? Thanks!

**Comment by tech4GT** [comment]
Thanks!

**Comment by jywarren** [comment]
👍👍👍 Thanks, Varun!!!

**Pull request merged**
