### PR TITLE
Add UI JS files to watch

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
Sounds good! We are not using the minified files, and it will update the website faster! @jywarren thoughts?

**Comment by HarshKhandeparkar** [comment]
@jywarren this can potentially be an advantage to the pre-commit hook which
is under planning. I also had an idea of adding a stop caching button for
faster development and reloading the browser can be enough which can even
be done using browsersync I think

**Comment by jywarren** [comment]
This sounds great as does the suggested compile option!

**Comment by jywarren** [comment]
Just wondering if the removal of `sw.js` and `scrollToTop.js` was intentional here?

**Comment by Mridul97** [comment]
Yes, actually scrollToTop.js was not doing anything, and sw.js was shifted examples/lib but was also present in examples/ folder so removed those!

**Pull request merged**
