### PR TITLE
The load image is not appending.

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@jywarren You removed the class container but there are many things depending on it and that's the reason the load image is not appending now i changed it to a different class "main" and now everything is working. :+1:

**Comment by Harshithpabbati** [comment]
@jywarren merge this major one!!!

**Comment by Harshithpabbati** [comment]
error
This is the error see in console and now I fixed it.

**Comment by Harshithpabbati** [comment]
fin
Now it's working fine!!.

**Comment by jywarren** [comment]
Aaah oops, i caused this!!!! Sorry!!!

**Pull request merged**
