### PR TITLE
Rearrange Sequence Buttons

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/493

Rearranged the GIF and save sequence buttons and grouped them together.

screenshot from 2018-12-22 18-39-05

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@publiclab/reviewers I am having some issues with this. I have mentioned them in the issue page.

**Comment by HarshKhandeparkar** [comment]
> I'm facing some issue. The download PNG button adds a crop step now and the step doesn't even work.
> 
> png-btn-img-seq

**Comment by HarshKhandeparkar** [comment]
> The previous black step was also created the same way. The only files I've touched are index.html and demo.css. @publiclab/reviewers please help.

**Comment by HarshKhandeparkar** [comment]
> update: The step works
> 
> crop-works

**Comment by tech4GT** [comment]
Great! I'll take a look at this, can you also open a separate issue for the problem with the download button. Thanks :)

**Comment by HarshKhandeparkar** [comment]
Actually I found the problem.

**Comment by HarshKhandeparkar** [comment]
It is in demo.js. 

https://github.com/publiclab/image-sequencer/blob/94e4dfe1b9e694253cf9a6b1b32c15484017fc8a/examples/demo.js#L12-L17

**Comment by HarshKhandeparkar** [comment]
It is happening because this also has a class of `img-thumbnail`.

**Comment by HarshKhandeparkar** [comment]
This is the problem.

https://github.com/publiclab/image-sequencer/blob/94e4dfe1b9e694253cf9a6b1b32c15484017fc8a/examples/demo.js#L84-L87

**Comment by HarshKhandeparkar** [comment]
Should I open an issue and then a PR to fix this?

**Comment by HarshKhandeparkar** [comment]
I have a fix for this.

**Comment by HarshKhandeparkar** [comment]
` <a></a>\`

```
  $('#download-btn').click(function() {
    $('.step-thumbnail:last()').trigger("click");
    return false;
  });
```

This is a very small fix. Should I add this to the same PR?

**Comment by HarshKhandeparkar** [comment]
@tech4GT please have a look at this.

**Comment by tech4GT** [comment]
@HarshKhandeparkar I think you can include this fix in your pr only since we don't want this button to be broken when we deploy the latest build.

**Comment by HarshKhandeparkar** [comment]
Ok I will do this when I reach home.

**Comment by HarshKhandeparkar** [comment]
The requested changes have been made. @publiclab/reviewers please have a look.

**Comment by HarshKhandeparkar** [comment]
@publiclab/reviewers please look at my PR.

**Comment by tech4GT** [comment]
@HarshKhandeparkar Sorry for the delay! I'll take a look :)

**Comment by HarshKhandeparkar** [comment]
Thanks!

**Pull request merged**
