### PR TITLE
Fix toggle-able collapse

### LINKED ISSUE #666: Module step not getting displayed
### Please describe the problem (or idea)

The modules are not getting displayed, this is a bug introduced after implementing the toggle-able collapse for modules.

Screenshot:
screen shot 2019-01-12 at 9 29 09 pm

Upon inspection, this bug has been introduced in e5d26815d7e02310a6463f48240c4027b3e4bce3
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #666 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
@jywarren Please review this!
Error occuring before : 

toggle

Output : 

toggle2

**Comment by jywarren** [comment]
This looks good but are the dist files required? Thanks!

**Comment by Mridul97** [comment]
@jywarren These are dist-ui files!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 can you merge https://github.com/publiclab/image-sequencer/pull/643/commits/c3b039fb31e49174f37e2038e79e932973b3b8c7

**Comment by HarshKhandeparkar** [comment]
Works better 


collapse-fix

**Comment by Mridul97** [comment]
@HarshKhandeparkar How can I merge it, you will have to open a PR to this branch I suppose, and it seems like there will be conflicting files, I think I can make the required changes here only, that would be easier! :)

**Comment by HarshKhandeparkar** [comment]
Can you copy the changes manually?

**Comment by Mridul97** [comment]
Yes, I will do that!

**Comment by HarshKhandeparkar** [comment]
> Yes, I will do that!

Cool

**Comment by aashna27** [comment]
@HarshKhandeparkar yeah i saw them , you posted these in the pr opened previously by bhavaya. I was gonna check them and make a pr .(was a little busy)

**Comment by Mridul97** [comment]
@HarshKhandeparkar can you check one thing, in your branch when a new step is added is it in collapsed form?

**Comment by HarshKhandeparkar** [comment]
> @HarshKhandeparkar yeah i saw them , you posted these in the pr opened previously by bhavaya. I was gonna check them and make a pr .(was a little busy)

Ok cool

**Comment by aashna27** [comment]
@Mridul97 that problem is in the node modules

**Comment by Mridul97** [comment]
Nope it is fixed in this pr please see the gif posted above!

**Comment by HarshKhandeparkar** [comment]
> @HarshKhandeparkar can you check one thing, in your branch when a new step is added is it in collapsed form?

Yes, it is. You need to add the new class. 

Also, can you add a new remove step button to the step title? maybe with just an `X` fa-icon for easy step removal? Insert step button can also be added if you want

**Comment by Mridul97** [comment]
> > @HarshKhandeparkar can you check one thing, in your branch when a new step is added is it in collapsed form?
> 
> Yes, it is. You need to add the new class.
> 
> Also, can you add a new remove step button to the step title? maybe with just an `X` fa-icon for easy step removal? Insert step button can also be added if you want

Yes, that's the reason I changed .collapse to .cal!

**Comment by aashna27** [comment]
I checked it for main branch it works fine for me

**Comment by Mridul97** [comment]
But it is not working for me @HarshKhandeparkar can you also please check!

**Comment by aashna27** [comment]
image
That's the reason it appears collapsed, I ll recommend adding a more descriptive class name than cal , this style exists in bootstrap file.

**Comment by HarshKhandeparkar** [comment]
> But it is not working for me @HarshKhandeparkar can you also please check!

What is not working?

**Comment by Mridul97** [comment]
> > But it is not working for me @HarshKhandeparkar can you also please check!
> 
> What is not working?

The functionality even after clicking on the caret button, it is not expanding!

**Comment by HarshKhandeparkar** [comment]
> > > But it is not working for me @HarshKhandeparkar can you also please check!
> > 
> > 
> > What is not working?
> 
> The functionality even after clicking on the caret button, it is not expanding!

That is working in my pr

**Comment by Mridul97** [comment]
No not in your pr, in the main branch!

**Comment by HarshKhandeparkar** [comment]
I pushed a new commit https://github.com/publiclab/image-sequencer/pull/643/commits/bc5a18818750b5e1949379751f823304b2e8e734

works fine

collpase works

**Comment by HarshKhandeparkar** [comment]
> No not in your pr, in the main branch!

I'll check

**Comment by HarshKhandeparkar** [comment]
> No not in your pr, in the main branch!

Nope

not-working-on-main

**Comment by Mridul97** [comment]
> > No not in your pr, in the main branch!
> 
> Nope
> 
> not-working-on-main

See That's what I am saying @aashna27 it is not working!

**Comment by jywarren** [comment]
Be sure to clear cache and be sure you're working on a properly compiled
version of the code! I know this has gotten me in the past 😁

**Comment by aashna27** [comment]
> 
> 
> > > No not in your pr, in the main branch!
> > 
> > 
> > Nope
> > not-working-on-main
> 
> See That's what I am saying @aashna27 it is not working!

Have a look here https://github.com/publiclab/image-sequencer/pull/651#issuecomment-453615653 😄 That's why!

**Comment by Mridul97** [comment]
> > > > No not in your pr, in the main branch!
> > > 
> > > 
> > > Nope
> > > not-working-on-main
> > 
> > 
> > See That's what I am saying @aashna27 it is not working!
> 
> Have a look here [#651 (comment)](https://github.com/publiclab/image-sequencer/pull/651#issuecomment-453615653)  That's why!

Even on clicking the caret button it was not expanding! :sweat_smile:

**Comment by HarshKhandeparkar** [comment]
> > > > No not in your pr, in the main branch!
> > > 
> > > 
> > > Nope
> > > not-working-on-main
> > 
> > 
> > See That's what I am saying @aashna27 it is not working!
> 
> Have a look here [#651 (comment)](https://github.com/publiclab/image-sequencer/pull/651#issuecomment-453615653) smile That's why!

The class name can be changed easily. What needs to be fixed/improved is the function which doesn't even work and throws an error.

**Comment by Mridul97** [comment]
> > > > > No not in your pr, in the main branch!
> > > > 
> > > > 
> > > > Nope
> > > > not-working-on-main
> > > 
> > > 
> > > See That's what I am saying @aashna27 it is not working!
> > 
> > 
> > Have a look here [#651 (comment)](https://github.com/publiclab/image-sequencer/pull/651#issuecomment-453615653) smile That's why!
> 
> The class name can be changed easily. What needs to be fixed/improved is the function which doesn't even work and throws an error.

Exactly! my aim was to fix that not just change a class name!

**Comment by jywarren** [comment]
Also, this is a great example of why our upcoming UI testing will be
helpful!

Sorry to keep chiming in without contributing. But you're doing great
problem solving. Thanks!

**Comment by Mridul97** [comment]
@jywarren @HarshKhandeparkar @aashna27 please review this!

**Comment by HarshKhandeparkar** [comment]
> @HarshKhandeparkar it is updating fa-icon! :)

Does it update it if the icon is the `e.target`? that is if it is directly clicked?

**Comment by HarshKhandeparkar** [comment]
Oh ok. But it will not toggle anything if the step name is clicked which is what I changed in my PR. It is really annoying to click the icon properly. Instead clicking the whole span is better which is what I changed in my PR.

**Comment by Mridul97** [comment]
> Oh ok. But it will not toggle anything if the step name is clicked which is what I changed in my PR. It is really annoying to click the icon properly. Instead clicking the whole span is better which is what I changed in my PR.

I don't think we require that if we do, will make the changes!

**Comment by HarshKhandeparkar** [comment]
> > Oh ok. But it will not toggle anything if the step name is clicked which is what I changed in my PR. It is really annoying to click the icon properly. Instead clicking the whole span is better which is what I changed in my PR.
> 
> I don't think we require that if we do, will make the changes!

I think It's better that way and easier to use the UI.

**Comment by HarshKhandeparkar** [comment]
Also can we delete some of the older comments with GIFs etc. this page takes very long to load.

**Comment by Mridul97** [comment]
@jywarren @publiclab/is-reviewers please review this!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 if the icon is clicked directly then it does not contain any element with `querySelector('.fa')` so an if statement is required to check if e.target has the class `.fa` or not.

**Comment by Mridul97** [comment]
> @Mridul97 if the icon is clicked directly then it does not contain any element with `querySelector('.fa')` so an if statement is required to check if e.target has the class `.fa` or not.

That won't be a problem because click function is linked on span element which contains both step name and caret icon!

**Comment by HarshKhandeparkar** [comment]
No but e.target is specific and will take the element that is directly clicked.

**Comment by Mridul97** [comment]
> No but e.target is specific and will take the element that is directly clicked.

No e.target will take span because it has id of toggle and function is set on element with id toggle, I have tried it out as well!

**Comment by HarshKhandeparkar** [comment]
Isn't e.target supposed to be the element that is directly clicked?

**Comment by Mridul97** [comment]
> Isn't e.target supposed to be the element that is directly clicked?

e.target is that element on which .onClick function is defined!

**Comment by HarshKhandeparkar** [comment]
If you have tried it out then its ok. I was telling you about this as it did not work for me when I was testing it in my PR.

**Comment by Mridul97** [comment]
> If you have tried it out then its ok. I was telling you about this as it did not work for me when I was testing it in my PR.

Yes, I have! Thanks!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 I checked it out online and also locally. e.target is the element that is clicked.

https://developer.mozilla.org/en-US/docs/Web/API/Event/target

**Comment by Mridul97** [comment]
@jywarren please review this!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 will it be better if you use 

```js
$(step.ui.querySelector('.cal')).collapse('toggle');
```

?

**Comment by HarshKhandeparkar** [comment]
@Mridul97 I checked it out on your branch.


toggle-not-working



See the icon doesn't update if it is clicked directly.

**Comment by HarshKhandeparkar** [comment]
I had cleared the cache too!


cache-sleared

**Comment by HarshKhandeparkar** [comment]
This is my htmlType-in-info-files


should-work


It should work like this. The only thing is that it is collapsed by default.
My code:

https://github.com/HarshKhandeparkar/image-sequencer/blob/bc5a18818750b5e1949379751f823304b2e8e734/examples/lib/defaultHtmlStepUi.js#L158-L166

**Comment by Mridul97** [comment]
> @Mridul97 I checked it out on your branch.
> 
> cache-sleared
> 
> See the icon doesn't update if it is clicked directly.

Oh, you meant updating the icon, I thought you said it didn't work on clicking the icon!

**Comment by Mridul97** [comment]
I have made the changes, please check!

**Comment by HarshKhandeparkar** [comment]
Awesome!!

**Comment by aashna27** [comment]
@Mridul97 I ll request you to make the class name collapse and remove the console.log() line and try again. The load-image doesn't appear collapsed then.

**Comment by HarshKhandeparkar** [comment]
@aashna27 the class was `.collapse` im my branch and therefore the load-image appears collapsed in tge GIF

**Comment by aashna27** [comment]
> 
> 
> @Mridul97 I ll request you to make the class name collapse and remove the console.log() line and try again. The load-image doesn't appear collapsed then.

And use this pr to maybe make the code efficient, using the changes @HarshKhandeparkar suggested.

**Comment by Mridul97** [comment]
I think I have implemented the changes that @HarshKhandeparkar has suggested! Would love to know if any more changes are required. Thanks!

**Comment by aashna27** [comment]
> 
> 
> @aashna27 the class was `.collapse` im my branch and therefore the load-image appears collapsed in the GIF
okayy, and the console() had been deleted ? @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
@Mridul97 you can use `$.collapse('toggle');` instead of toggling the class. This will shorten the code and also implement some cool looking animations

**Comment by Mridul97** [comment]
> @Mridul97 you can use `$.collapse('toggle');` instead of toggling the class. This will shorten the code and also implement some cool looking animations

I will do that. Thanks!

**Comment by HarshKhandeparkar** [comment]
I have an idea

```js
var icon = $(e.target).class('fa') ? $(e.target) : $(e.target.querySelector('.fa');

icon.toggleClass('fa......

```

**Comment by Mridul97** [comment]
> I have an idea
> 
> ```js
> var icon = $(e.target).class('fa') ? $(e.target) : $(e.target.querySelector('.fa');
> 
> icon.toggleClass('fa......
> ```

we can do one more thing we can give the icon an id 'toggleIcon' and use $('#toggleIcon') and toggle class fa ... on it!

**Comment by HarshKhandeparkar** [comment]
> > I have an idea
> > ```js
> > var icon = $(e.target).class('fa') ? $(e.target) : $(e.target.querySelector('.fa');
> > 
> > icon.toggleClass('fa......
> > ```
> 
> we can do one more thing we can give the icon an id 'toggleIcon' and use $('#toggleIcon') and toggle class fa ... on it!

Yes you can do anything else my suggestion was just to remove the if...else block

**Comment by HarshKhandeparkar** [comment]
@Mridul97 you cannot give it an id beacuse the page will then have more than one element with same id but a class will be good and you can refer to the class using ```step.ui.querySelector`

**Comment by HarshKhandeparkar** [comment]
A suggestion I think using `$.collapse('toggle')` will be better. Sorry for suggesting changes againa nd again.

**Comment by HarshKhandeparkar** [comment]
Oh wow, I looked into the new commit. I would have never thought of doing that. I always think of some convolited way of doing such things.

**Comment by HarshKhandeparkar** [comment]
> > A suggestion I think using `$.collapse('toggle')` will be better. Sorry for suggesting changes againa nd again.
> 
> I actually tried that but it is giving a error, when we first click to collapse the step, it is not collapsing but the icon gets changed!

It was working for me actually

**Comment by Mridul97** [comment]
> > > A suggestion I think using `$.collapse('toggle')` will be better. Sorry for suggesting changes againa nd again.
> > 
> > 
> > I actually tried that but it is giving a error, when we first click to collapse the step, it is not collapsing but the icon gets changed!
> 
> It was working for me actually

I suppose when it gets first clicked it opens the step, so in your case the step was collapsed so it worked fine but if step is open then it doesn't collapses it, it only happens for the first time after that it works fine!

**Comment by HarshKhandeparkar** [comment]
Maybe you are right but collapse('toggle') should toggle its collapse state. I'll check the docs.

**Comment by HarshKhandeparkar** [comment]
I found something  https://www.w3schools.com/bootstrap/bootstrap_ref_js_collapse.asp

It needs to have a class of collapse to let it work with that method and also a class on in so that it is open by default.

**Comment by Mridul97** [comment]
Oh! so then I don't think we should make this change!

**Comment by HarshKhandeparkar** [comment]
Do you mean to say that adding two classes is not necessary? If that is so then I guess you are right.

**Comment by HarshKhandeparkar** [comment]
Adding two classes to use a method which will add some animation is not really necessary.

**Comment by jywarren** [comment]
> Oh! so then I don't think we should make this change!

Oops, is this ready to go yet? Just checking! It'll need a rebase and recompile, as well. Thank you so much!

**Comment by Mridul97** [comment]
@jywarren I have rebased the branch, I think it is ready to be merged. Thanks!

**Comment by jywarren** [comment]
Thanks, this is super! Great teamwork too, folks!

**Pull request merged**
