### PR TITLE
Added uppy for file uploading

### LINKED ISSUE #212: explore standard multi-source upload with Uppy package
https://www.npmjs.com/package/uppy

Demo: https://uppy.io/examples/dashboard/

image

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Fixes #212 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers review this!!

**Comment by HarshKhandeparkar** [comment]
Harshith has-pull-request label is for issues not PRs 😅

**Comment by Harshithpabbati** [comment]
> Harshith has-pull-request label is for issues not PRs

sorry that was by mistake

**Comment by HarshKhandeparkar** [comment]
Haha. NP. We all do mistakes.

**Comment by Harshithpabbati** [comment]
@jywarren review it :)

**Comment by jywarren** [comment]
Can you post a final screenshot, please? thank you!!!

**Comment by Harshithpabbati** [comment]
uppy

**Comment by jywarren** [comment]
cool, and it's working well? Ready for a merge then? Very awesome!

**Comment by Harshithpabbati** [comment]
Yeah it's working and ready to merge !!

**Comment by jywarren** [comment]
Ah I think this needs rebase, sorry! 👍🏽

**Comment by Harshithpabbati** [comment]
I guess I am lost with the git commands and I will try to make changes @jywarren

**Comment by Harshithpabbati** [comment]
@jywarren  i will close this and send a new pr . Sorry for that.

**Comment by Harshithpabbati** [comment]
Was that ok ?? or do i need any changes to be done ??

**Comment by Harshithpabbati** [comment]
https://github.com/publiclab/image-sequencer/pull/831/commits/29a4d8b68f5931752a481caf135a05914c6409cc 
checkout this @jywarren

**Pull request closed without merging**
