### PR TITLE
Change the style of "improve this tool" button

### LINKED ISSUE #810: Change the "improve this tool" button.
### Change the improve this tool button to primary.
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!
###  What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

###  Step by Step
* [ ]  :raising_hand_woman: **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
* [ ]  :memo: **Update**: All that needs to be done is replace this line
* [image-sequencer/examples/index.html]
      
           Line 214
                   <a class="btn btn-default" href="https://github.com/publiclab/image-sequencer">View the code</a>
  with this line
 `<a class="btn btn-primary" href="https://github.com/publiclab/image-sequencer">View the code &raquo;</a>`
* [ ]  :floppy_disk: **Commit** your changes
* [ ]  :twisted_rightwards_arrows: **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

* [ ]  :checkered_flag: **Done** Ask in comments for a review :)

###  Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by marieram**
Replaced line 214 with by changing the "improve this tool" button to primary.

Fixes #810 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Oh wait . This is a duplicate of #814

**Comment by HarshKhandeparkar** [comment]
You can mention @publiclab/is-reviewers to ask for a review

**Comment by marieram** [comment]
@publiclab/is-reviewers for review. @HarshKhandeparkar it doesn't look like the @mention function works for me.

**Comment by HarshKhandeparkar** [comment]
Sometimes mentioning publiclab/is-reviewers doesn't work. I don't know why it doesn't work. I had already mentioned the reviewers once before. They will get the message. Thanks! 😊

**Comment by jywarren** [comment]
Fantastic, thank you so much!!!

**Comment by jywarren** [comment]
@HarshKhandeparkar sadly, only those we've added to the collaborators list can use group mentions like that -- we haven't figured out a way around that! And yet people who most often need to use such mentions are often newcomers, and on their first time trying to use a mention like that, we haven't yet become aware of them, so it's a bit of a paradox!

Maybe there's a bot that can help us with this... but we are a bit stuck on the problem. Thanks for helping out!!!

**Pull request merged**
