### PR TITLE
Added documentation for all remaining modules in Modules.md and added a link in info.json for every Module. 

### LINKED ISSUE #506: Documentation of MODULES is incomplete
### Please describe the problem (or idea)
MODULES.md is complete.
It has information only about 3 modules which are:-
* Crop Module
* FisheyeGI
* Colormap

We can add information about the other modules as well so it is a complete file.
Also, when someone adds a new module, he/she could also add info about it here.

This could be a good **documentation** issue for newcomers or maybe frequent contributors too.
@publiclab/mentors what say? 😄 
### Please show us where to look
https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Divy123**
… info.json of each Module

Fixes #506 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@tech4GT please review.

**Comment by HarshKhandeparkar** [comment]
@Divy123 can you please change the position of already existing module docs so that they are in alphabetical order too.

**Comment by HarshKhandeparkar** [comment]
You can also add an index at the start if you want to.

**Comment by Divy123** [comment]
Cool! I am adding the index at the top of Modules.md file.
Just one thing that I was thinking to add a clickable index and for that I require an additional dependency.
Should I go ahead with this?

**Comment by HarshKhandeparkar** [comment]
@Divy123, you can just add link like `[link-name](#link-to-module)`. You just have to replace spaces with hyphens '-' and remove all brackets.

E.G: `[Average](#average-module-average)

**Comment by Divy123** [comment]
@HarshKhandeparkar it works as required now. Sorry for two extra commits as I was doing some task and forgot to do some changes. Please review.

**Comment by HarshKhandeparkar** [comment]
@Divy123 you don't require two hashes '##' one would work.

**Comment by HarshKhandeparkar** [comment]
Awesome work btw!

**Comment by HarshKhandeparkar** [comment]
And the two commits are not a problem the pr is merged as a single commit.

**Comment by Divy123** [comment]
Thanks @HarshKhandeparkar .

**Comment by Divy123** [comment]
@tech4GT I have changed/updated Modules.md file by adding the documentation of all remaining modules.
Next I have added a link in info.json of every module to Modules.md file.

**Comment by tech4GT** [comment]
Great!! Divy if you have spell checked we can go ahead and merge here!

**Comment by Divy123** [comment]
@tech4GT  please have a look. I have made the necessary changes.

**Comment by tech4GT** [comment]
Oh I should have squashed your commits! My bad :sweat_smile:

**Pull request merged**
