### PR TITLE
(WIP)Use Alternative Materialize UI Alongside Bootstrap

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #[Add issue number here.]

This  PR uses materliaze instead of bootstrap for the UI code and depracates bootstrap.

Please check https://github.com/publiclab/image-sequencer/issues/708 for GIFs

This branch is live on my [gh-pages](https://harshkhandeparkar.github.io/image-sequencer/). Be sure to clear cache!

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren I have added the branch to gh-pages but it is not working since I don't have node-modules. What shall I do?

**Comment by HarshKhandeparkar** [comment]
Also it is giving me a CNAME error saying that sequencer.publiclab.org is already taken

**Comment by HarshKhandeparkar** [comment]
Should I use CDNs for the time being?

**Comment by HarshKhandeparkar** [comment]
@jywarren update! The page is working with CDNs. The CNAME is still a problem though.

The [page](https://harshkhandeparkar.github.io/image-sequencer/)

**Comment by HarshKhandeparkar** [comment]
@Divy123 @publiclab/is-reviewers please have a look at my branch from your device.

**Comment by HarshKhandeparkar** [comment]
@Divy123 @jywarren @publiclab/is-reviewers please check out my new changes. Here as well as on my gh-pages

**Comment by HarshKhandeparkar** [comment]
This is the new theme color

screenshot_20190130_195950_com android chrome

I have fixed the overflow of preview icons and the page size is normal. I just forgot to commit them

**Comment by jywarren** [comment]
Just a couple notes, I'd like to ask that you copy these files to newly
named files or into a second UI folder, rather than remove the originals,
to demonstrate the ability to attach multiple UIs. Second I think the file
'CNAME' in the root directory can be used to set the correct address, or
removed to default to the gh-pages default. Thanks, I hope that works!!!

**Comment by jywarren** [comment]
And do you think you could rename to be "as an alternative to bootstrap"
instead of "instead of"? Thanks!

**Comment by Divy123** [comment]
Awesome work @HarshKhandeparkar . Looks great. Jus two things I want to suggest that if you can improve on select image and take a photo section.
Also please make clear offline cache a button.
Thanks for such an awesome work.

**Comment by HarshKhandeparkar** [comment]
@jywarren I sure I will make the changes. @Divy123 I have seen the take photo and the modal etc. I will change that soon(this is still a WIP). Thanks for the suggestion!

**Comment by HarshKhandeparkar** [comment]
@jywarren I will add the new UI inside examples/new and the old one inside examples/legacy. I will also add a link to the new one inside the legacy UI and by default, the legacy one will open.

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers I have added both the UIs now. Fixed the overflow on small screens.

twoui


Seems like the new UI loads significantly faster than the old one.


fix-overflow


The build is online [here](https://harshkhandeparkar.github.io/image-sequencer/) and it will open the legacy by default. I have changed the cache name to `image-sequencer-new-v3` for the new UI. Thanks!

**Comment by Divy123** [comment]
@HarshKhandeparkar I think the 'Go to new UI' button is not working.
Can you please go through it?
Thanks and great things done.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I have fixed it just now. The build will take a few secs.

**Comment by HarshKhandeparkar** [comment]
Oh, the build is done. Check it out

**Comment by HarshKhandeparkar** [comment]
Be sure to clear the cache!

**Comment by HarshKhandeparkar** [comment]
@Divy123 it seems like the page links work differently. Please wait a minute. I'll try to fix it. BTW the link for new UI is https://harshkhandeparkar.github.io/image-sequencer/new/

**Comment by Divy123** [comment]
Actually I am not able to clear cache right now, the button is not working.

**Comment by HarshKhandeparkar** [comment]
@Divy123 sorry for the trouble, I found a fix for that, Will commit in a min.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I have fixed it and committed it. The build should update in a min. Be sure to clear the cache. You can clear the cache from the storage tab in devTools

**Comment by HarshKhandeparkar** [comment]
@jywarren @Divy123 everything works fine on gh-pages and on localhost as well. Please check it out. Thanks!

**Comment by HarshKhandeparkar** [comment]
@jywarren @Divy123 @publiclab/is-reviewers the new UI is online on examples/new and the old in examples/legacy,
Also there are buttons in both which let the user switch between the UIs saving any kind of steps or options. The modal/take-photo and everything else still need work and I will do that soon. Until then you can check the current status of the [page](https://harshkhandeparkar.github.io/image-sequencer/).

**Comment by HarshKhandeparkar** [comment]
One thing that I'm seeing is that the body height is not equal to the viewport height when desktop render is forced. Nothing like this happens on my PC but on my phone, force desktop site does this. This might be a problem of the forced rendering. I have tried using min-height:100vh but had no luck. Seems like this happens on both the UIs


screenshot_20190131-134048


screenshot_20190131-134103
Look the position of the clear cache button

**Comment by HarshKhandeparkar** [comment]
@jywarren @Divy123 @publiclab/is-reviewers update!

- Choose File Design

file-select-fixed


- Shortcut for clear cache
  Pressing `CTRL/CMD + E` will clear the cache. A tooltip will be displayed above the clear cache button.

clear-cache-shortcut


- New duration property for notify function
The notify function takes a new parameter(optional) duration in ms. This has been implemented for the save sequence message. The notification still doesn't look good so I will implement materialize toasts next time.

- Insert Step Fix
Insert step was not working because of a typo. That has been fixed now.

- General refactoring
 1. Two folders were created inside `lib/sequencer` i.e. `sequence` and `step` and all the files have been divided among them.

2. Some demo.js functions were migrated to other files. Planning on doing this for others too.

###### Note: This is still a WIP. Expect half-baked/broken stuff. Please let me know of you found any such thing.
###### Note: These changes are only made to the new UI and not the old UI.
###### Note: The changes are live [here](https://harshkhandeparkar.github.io/image-sequencer/)
###### Note: Clear cache will probably be broken because of the extra `/image-sequencer/` in the URL

##### Please let me know if any changes/fallbacks are required. All suggestions are welcomed.

#### Thanks!

**Comment by Divy123** [comment]
Awesome work @HarshKhandeparkar .
Just one thing that if we can make the clear offline cache part appear more distinctly.
What do you think?

**Comment by HarshKhandeparkar** [comment]
@Divy123 thanks for the suggestion. I will do that.

**Comment by Divy123** [comment]
Look awesome to me. :smile:

**Comment by Divy123** [comment]
I think the PR is ready to be merged.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I don't want this to be merged yet. Some changes are still necessary. Check out the gif modal.

**Comment by Divy123** [comment]
Sure @HarshKhandeparkar .

**Comment by HarshKhandeparkar** [comment]
@jywarren do you think this will be ready to merge after some cleanup? Btw I have merged the changes in the mapHtmlTypes pr with this one as invalid html types would break materialize.

**Comment by HarshKhandeparkar** [comment]
@jywarren should I try implementing https://github.com/publiclab/image-sequencer/issues/735 ?

**Comment by jywarren** [comment]
Hi, @HarshKhandeparkar - first of all, this is really impressive, thank you.

I'm a bit hesitant about this, however, and I want to talk transparently about it. I worried about this project a bit because one of the first things it does is potentially double the size of our UI codebase at a time when we're already working hard to complete some big priority projects like these: https://github.com/publiclab/image-sequencer/labels/project. If we make changes like in #735, will we now have to implement them in both UIs, or will contributors have to choose which UI to support or improve? 

I'm also hesitant because you've named the materialize UI "new" and the bootstrap UI "old" but we haven't really had a discussion as a community about replacing the default ui, or weighed the pros/cons of this project. This is really not to say that I'm against it -- i'm super impressed by the work ❤️ , and it's really magical to see how our work to make the UI modular has made it possible to so quickly develop a new UI! But I think it's important to think about what this means for our project and our community. 

This has broad ramifications for code maintenance -- are there UI functions that could be shared, like `urlHash.js` or `gif.js`, perhaps in their own NPM modules or in a common `/ui/lib/` directory?

We're also not completely done modularizing the existing default UI. Lots of things may need to be moved out of the core Sequencer code and into the UI code, like `sequencer.setInputStep()`, which deals with HTML. These would now need to be re-implemented in a second UI in order not to break it. This is all possible, and I want to repeat that it's eventually our goal ❤️ however it does draw more of our time away from top priority projects, several of which may help to make the development of new stand-alone UIs easier, actually.

I want to say one more time that I think your work here is amazing, and I feel an excitement and happiness at your work. But I want to think of the best way to approach a big project like this in a way that will be best for our community and for the library, while respecting and affirming the work you've done. 

What I'm thinking is this: perhaps we should leave the current codebase untouched, without moving or renaming the current UI to "old". Instead, we can actually move all of this code into its own repository, called `image-sequencer-materialize-ui`, which I'm happy to create, and publish it on NPM. What this can demonstrate is, that the creation of a completely new and compatible UI is possible -- and is one of the great parts about IS as a project. The completely separate implementation of a new UI will be an inspiration to others looking for ways to build new and creative interfaces around this library, kind of like how I've started a map library using it with https://github.com/publiclab/leaflet-tile-filter. 

We can add to the documentation how to instantiate a sequencer in a custom UI -- using your code as an example:

https://github.com/publiclab/image-sequencer/blob/91e243494918186e117f5041eb6d0de657066a20/examples/new/demo.js#L29-L34

And we can link to the code running on gh-pages to prove that this is possible. 

This will also force us to get more serious about a stable API that's offered to the UIs. Anything we document and test will have to be supported and respected so that downstream UIs can rely upon them. This is good for the library. 

We don't have to make a final decision now, but I want to ask you to think about this as a proposal, and we can discuss the pros/cons of this approach. One advantage is that your code could copy out the Gruntfile, /src/ folder, and be a much simpler standalone codebase that encompasses just your materialize UI code. 

What do you think about this as an option? Thanks for reading my long response and I hope you find it reasonable and fair. I'm happy to discuss and think through this together with other folks. 

Congratulations on this very cool project and again, thank you!!!

**Comment by HarshKhandeparkar** [comment]
@jywarren how about keeping the UI source separate and pushing the dist to the current repo occasionally like it is done for gh-pages. Also when are you going to push to gh-pages?

**Comment by HarshKhandeparkar** [comment]
We could do this for all UIs. We can modularize all the default sequence and step actions and pass the functions to the UI files which can return any UI. A dropdown can be added to the top/bottom of the page to select between different UIs? Thoughts?

**Comment by jywarren** [comment]
Yes, actually the default UI is increasingly being condensed into fewer independent folders and we have some more work to do in demo.js to decide what is part of the UI implementation vs just nice in the demo... I think eventually we may actually remove the default UI entirely from this repo too as `image-sequencer-default-ui`! But I haven't wanted to split up the community just yet, and we're not /quite/ ready to do that... we are working in that direction though! 👍

**Comment by jywarren** [comment]
And yes, once completely modular, we could remotely include in the materialize ui and hook it into the demo!

**Comment by HarshKhandeparkar** [comment]
@jywarren shall I modularize the default UI? I can do that in this pr.

**Comment by HarshKhandeparkar** [comment]
I have a cool idea....
A ui.js file can be made which can be required be ui files. It can return an object of funcs like defaultHtmlStepUi and defaultHtmlSequencerUi. Step.ui can be passed into these functions as a function like
```js
function stepUi(step){
return `
<h1>${step.name}</h1>
<p>${step.desc}</p>
`
}
defaultHtmlStepUi(stepUi);
```
Everything else will be taken care of by the defaultHtmlStepUi func. Thoughts?

**Comment by HarshKhandeparkar** [comment]
The different UI styles can be called UI renderers or something similar. All that has to be done is add buttons to the index.html. e.g. save sequence btn. The save sequence function can be provided by `ui.js` only thing would be to do `$(btn).click(saveSequence)`. There is no need for a separate repo right now. But shall I split it up into ui.js and renderers?

**Comment by jywarren** [comment]
I think we should still consider putting this code in an independent repository, because that really demonstrates its modularity. But i think i see what you're saying -- we could provide some commonly needed utilities to any UI in the core library. We could have, for example, files in /src/ui/util/ any of which could be included, and we could even move all those utils into its own repository and publish it as a separate node module like `image-sequencer-ui-utils`?

**Comment by HarshKhandeparkar** [comment]
@jywarren I have refactored the code in a separate branch. It still has both materialize and bootstrap (though neither of them is refactored or work at this point). The main code is refactored into `ui/` dir. Shall I open a PR?

**Comment by HarshKhandeparkar** [comment]
[branch](https://github.com/HarshKhandeparkar/image-sequencer/commit/215dc78c03e39fbd5b274fb0d392b0ad28d02ca8)

**Comment by HarshKhandeparkar** [comment]
Please check [this](https://github.com/HarshKhandeparkar/image-sequencer/tree/refactor-ui/ui) out instead of the whole branch.

**Pull request closed without merging**
