### PR TITLE
Header opens new page

### LINKED ISSUE #568: Make "Image Sequencer header" reload the page with no steps.
This is a sub-issue of #487 .
####  where to look

http://sequencer.publiclab.org...

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #568 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Will `href="/"` redirect to `/` instead of `examples/` which is the required directory?

**Comment by aashna27** [comment]
no it will redirect to examples only

**Comment by HarshKhandeparkar** [comment]
Ok then NP. Sorry for disturbing.

**Comment by aashna27** [comment]
> Ok then NP. Sorry for disturbing.

no not at all, happy to learn from you.

**Comment by aashna27** [comment]
Also @HarshKhandeparkar I was testing for that touch-action on emulator but it doesnt seem to work on firefox but does on chrome.

**Comment by HarshKhandeparkar** [comment]
> no not at all, happy to learn from you.

I'm here only to learn

**Pull request closed without merging**
