### PR TITLE
reduce redundancy of add and insert fixes #261

### LINKED ISSUE #261: Set of smaller issues for Run() and AddStep/InsertStep
* [ ] rename `Run()` parameters to be a bit easier to follow (instead of "ref", "json_q", something descriptive)
* [ ] reduce redundancy of `AddStep` and `InsertStep` -- `AddStep` should be a more specific use of `InsertStep` and largely use the same code but just have a position (at the end of the sequence) hard-coded

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by jywarren** [comment]
Nice and simple! Ready to merge?

**Comment by jywarren** [comment]
Can you link it to the issue it solves?

**Comment by tech4GT** [comment]
#261

**Comment by jywarren** [comment]
Ready? Shall we use a label to indicate when things are ready to merge? Thanks Varun!

**Comment by tech4GT** [comment]
Oh yeah sure!! Sorry I did not do it!

**Pull request merged**
