### PR TITLE
Added Image Sequencer Demo

### PR DESCRIPTION
**Pull request by ccpandhare**
Hey, I made a makup, and I'd want you to have a look at it. This is just marup - non functional.

https://ccpandhare.github.io/image-sequencer/examples

### CODE REVIEW

**Comment by jywarren** [comment]
Ah! Like it. Will you be able to change parameters after adding? Doesn't
need to be a feature initially but thinking ahead a bit.

Cool! But let's use the default bootstrap fonts to keep things simple and
familiar, if that's ok!

Great thinking!

On Aug 12, 2017 7:49 PM, "Chinmay Pandhare" <notifications@github.com>
wrote:

Hey, I made a makup, and I'd want you to have a look at it. This is just
marup - non functional.

https://ccpandhare.github.io/image-sequencer/examples
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/publiclab/image-sequencer/pull/92
Commit Summary

   - demo for FisheyeGl
   - demo for FisheyeGl - Bugfixes
   - Demo Created
   - Demo Created
   - Changed Title in Demo
   - Improved Demo
   - Merge Commit
   - Organize examples directory, Recreate FisheyeGl Demo of fisheyegl
   using Image Sequencer UI
   - Modified tests
   - Made Requested Changes
   - Merge branch 'master' of https://github.com/publiclab/image-sequencer
   into demo
   - Added Single Image Demo Markup

File Changes

   - *A* examples/images/grid-crop.png
   <https://github.com/publiclab/image-sequencer/pull/92/files#diff-0> (0)
   - *A* examples/index.html
   <https://github.com/publiclab/image-sequencer/pull/92/files#diff-1>
   (111)

Patch Links:

   - https://github.com/publiclab/image-sequencer/pull/92.patch
   - https://github.com/publiclab/image-sequencer/pull/92.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/pull/92>, or mute the thread

**Comment by ccpandhare** [comment]
Yes, it is okay, but I didn't use bootstrap for this... Should I use bootstrap?

**Comment by ccpandhare** [comment]
Yes that can be a feature, I agree. Will implement it later

**Comment by ccpandhare** [comment]
I have now added the features : loadStep, addStep, removeStep to the Demo

**Comment by ccpandhare** [comment]
I am now implementing a new sequencer method : `modules`.
This can be used by the user for getting data of modules, such as which are the input fields, what are their default values, etc.

**Comment by jywarren** [comment]
This is looking great. Yes, let's use Bootstrap, it saves us some styling and is very familiar to people. 

I wasn't sure how the `key:_____` inputs are supposed to work. Should it offer a set of possible proper input keynames?

Great work!

**Comment by ccpandhare** [comment]
umm , no
the "key" is a placeholder

**Comment by ccpandhare** [comment]
It will hold the name of the actual input, please check out the demo,
https://ccpandhare.github.io/image-sequencer/examples
I have already implemented it :-)

**Comment by jywarren** [comment]
Super, just catching up. I know we're talking about the same thing, but I'm not sure we're seeing the same thing; is this right?

**Comment by jywarren** [comment]
screenshot_20170820-104838

**Comment by ccpandhare** [comment]
I am very sorry, I must've pushed my changes to the `demo` branch and forgotten to publish the same to `gh-pages` :-(

I have updated it now

Screen Shot

**Comment by ccpandhare** [comment]
Does this look fine?

**Comment by jywarren** [comment]
Perfect! So great. Can you add bootstrap and merge in? Thanks!

**Comment by ccpandhare** [comment]
Okay I will do so :-)

**Comment by ccpandhare** [comment]
Let's have a final look at https://ccpandhare.github.io/image-sequencer/examples before merging this in!

**Comment by ccpandhare** [comment]
Also, I think the NPM Version can be bumped after this.

**Comment by ccpandhare** [comment]
This is how outputs are shown in the demo:
Screen Shot

Also, I have removed the test modules : "do-nothing" and "do-nothing-pix"

**Comment by ccpandhare** [comment]
I have now added comments to the demo HTML file. This will guide future users as to how a demo can be built. Updated CONTIBUTING.md about the output fields in `info.json`

**Comment by jywarren** [comment]
Looking good!

**Comment by ccpandhare** [comment]
Merging this in and will open a separate PR for #91

**Comment by jywarren** [comment]
Hooray!

On Mon, Aug 21, 2017 at 12:19 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
I have now added comments to the demo HTML file. This will guide future users as to how a demo can be built. Updated CONTIBUTING.md about the output fields in `info.json`

-- Sorry this should have been posted earlier; posting this just for the sake of ompleteness

**Pull request merged**
