### PR TITLE
resolves #129 message to user informing about the async execution

### LINKED ISSUE #129: notify user that the CLI won't be synchronous (yet)
It was a little confusing at first that the CLI doesn't synchronously complete. For now, let's just tell the user that it'll execute asynchronously and that you won't see the output for a moment depending on the filesize and number of steps. Then let's implement a synchronous CLI in #130!

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren please review this

**Comment by jywarren** [comment]
Hi, looks like you triggered some kind of test issue; try taking a look at he test logs by clicking the little red X to see what went wrong!


Thanks for your help!!!

**Comment by tech4GT** [comment]
@jywarren please have a look

**Comment by tech4GT** [comment]
@ccpandhare the grunt-contrib-uglify module does not support const hence we would have to use https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony and this module is called grunt-contrib-uglify-es

**Comment by tech4GT** [comment]
i added uglify-es for good measure it can be removed

**Comment by tech4GT** [comment]
grunt build will not succeed without grunt-contrib-uglify-es module, grunt-contrib-uglify branch harmony is now grunt-contrib-uglify-es. I was reluctant to deleting code so please have a look and then i will delete that

**Comment by tech4GT** [comment]
@jywarren please have a look...if you want i will remove the extra modules

**Comment by ccpandhare** [comment]
This looks fine @jywarren

**Comment by jywarren** [comment]
Awesome, thanks both of you!!

**Pull request merged**
