### PR TITLE
simplify code contributions + reviews by fully automating the dev setup.

### LINKED ISSUE #1665: Auto-generate testable demos from all pull requests with GitPod.io
To make testing out new PRs faster and easier, we could integrate with GitPod.io, which auto-builds and hosts a browser-based version. I think, though i'm not sure, that we could do this with IS: 

https://www.gitpod.io/

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #1665 

Hi! 

This Pr simplifies code contributions by fully automating the dev setup with Gitpod(An online VS Code like IDE). With a single click, it'll launch a workspace and automatically:

- clone the repo.
- install the dependencies.
- run `npm start`.

You can give it a try on my fork of the repo via the following link:

https://gitpod.io/#https://github.com/nisarhassan12/image-sequencer/

This is how it looks:

image

Also for having these review comments in PRs and [pre-built](https://www.gitpod.io/docs/prebuilds/) workspaces, the Gitpod App has to be installed https://github.com/apps/gitpod-io I have added the configuration required you just have to install the app.

image

The app can only be installed by individual developers on their own account (i.e. there is no org billing or so). It can then be enabled/disabled & configured for any accounts or organizations that the developer maintains:

image

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Also, there are some errors when the `npm run setup` command is run:

image

and the test suite is not working although I have not made any change to the JS and so:

image

**Comment by jywarren** [comment]
Oh my gosh, this is amazing! I'm so sorry to have missed this, things have been very busy and also... pandemic and such. Thank you for your patience. Do you see these same errors happening in Travis? Perhaps it has to do with node version? Wait, travis is stalled, so let me try to get that running again. 

This is super appreciated as it will really help us review PRs in an efficient way!

**Comment by jywarren** [comment]
Ooohhhhhhhh......

**Comment by jywarren** [comment]
Wow! Super cool!

image

very impressive:

https://3000-a96d3b05-e574-4067-b164-ec83b37b94a0.ws-us02.gitpod.io/examples/#steps=color-halftone{}

**Comment by jywarren** [comment]
Merging!

**Comment by jywarren** [comment]
cc @publiclab/is-reviewers @publiclab/image-sequencer-guides check this out! It should hopefully make our reviewing MUCH easier and get things moving again a bit more :-) ❤️

**Comment by jywarren** [comment]
@sashadev-sky maybe we ought to do this for https://github.com/publiclab/Leaflet.DistortableImage/ ?

**Comment by jywarren** [comment]
Ah - one more thing - do we need to change `master` to `main` here? I'll try in a new PR.

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer/pull/1680

**Comment by jywarren** [comment]
Ah, i do see that although GitPod is building it, it is not passing tests (though Travis is, or is at least ignoring failed tests). I'll open an issue.

**Comment by jywarren** [comment]
OK, doing follow-up in #1681 and #1685!

**Comment by jywarren** [comment]
Hello @nisarhassan12, i'm sorry to bother you -- I've been trying to get this to activate on https://github.com/jywarren/woofmark/pull/16, and have approved the GitPod app on my `jywarren` personal account, but it just doesn't show up in a comment by the bot! Do you have any idea what I'm doing wrong? 

Thank you! ❤️ 🤖

**Comment by nisarhassan12** [comment]
Thanks, @jywarren I'm also not sure yet. I'll try to figure out and will try to let you know.

**Comment by nisarhassan12** [comment]
I have replied https://github.com/jywarren/woofmark/pull/16#issuecomment-660584850.

**Comment by sashadev-sky** [comment]
@jywarren definitely agree we need make some updates to our development workflow in LDI. I'll add this as a "todo" and look into it later!

**Comment by sashadev-sky** [comment]
> @sashadev-sky maybe we ought to do this for https://github.com/publiclab/Leaflet.DistortableImage/ ?

@jywarren Looks like you got ahead and did it yourself! Awesome Thank you

**Pull request merged**
