### PR TITLE
Add: Module tests

### LINKED ISSUE #546: Tests for more modules; starting with QR code module jsqr
We are starting to grow this library substantially and could really use more tests for specific modules. One example is that this pull request is trying to update `jsqr` but we don't test that module, so we don't know if that update breaks the module: #532 

The test could look something like this one, and be in the same folder; we could use a data-url encoded QR code as test data, and confirm that we get the correct data out of the module!

Here's the module code itself:

https://github.com/publiclab/image-sequencer/tree/main/src/modules/DecodeQr

Once this is done, we could move on to each other module. This would be a great repeat first-timers-only issue!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #546 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
`looks-same` package compares PNG images, so the base64 encoding is converted to PNG images first, and they are saved in `test/core/modules/test_outputs` when the tests are run. This folder is put inside `.gitignore`

**Comment by aashna27** [comment]
great work , can you share snapshots of the tests.

**Comment by VibhorCodecianGupta** [comment]
screen shot 2019-02-05 at 9 18 28 pm
screen shot 2019-02-05 at 9 18 56 pm
screen shot 2019-02-05 at 9 19 17 pm
screen shot 2019-02-05 at 9 19 37 pm

**Comment by jywarren** [comment]
This is fantastic. Thanks so much @VibhorCodecianGupta ! I'm merging now because it's so thorough and... well, tested! 😂

**Pull request merged**
