### PR TITLE
Fix Module Tests

### LINKED ISSUE #75: Pixel Manipulation and GIFs
Thanks to #73, GIFs are fully supported by PixelManipulation!

But It doesn't really work as expected. I inverted the following GIF using IS :

ani-pm-hammer

This is the result:

gif

It doesn't apply to all frames, I guess. Also, now the GIF doesn't play infinitely. It just plays once.
(Try opening the image in a browser tab and then `Cmd+Shift+R` or `Ctrl+Shift+R`)

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
**NOTE**: PR #1404 needs to be merged before this PR.

Multiple module tests were fixed in this PR including Crop, Tint, Overlay etc.
Modules like crop earlier were producing unexpected outputs and the corresponding tests were wrong as well.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correctly as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers Can I get an extension on this one? This one turned out to be much more complex than I had thought initially. I will also need @Divy123 or someone else's help for WebAssembly and Divy currently has no internet.

**Comment by HarshKhandeparkar** [comment]
Everyone please ask me tons of questions and try to find as many bugs as possible as I couldn't possibly find all of them. Thank you!

**Comment by HarshKhandeparkar** [comment]
Modules which work:
1. Average
2. Blur
3. Brightness
4. Channel
5. Color Temperature
6. Color Map
7. Contrast
8. Convolution
9. Dither
10. Dynamic
11. Exposure
12. Gamma Correction
13. Grid Overlay
14. Import Image
15. Paint Bucket
16. Saturation
17. Thresholding
18. Tint

Modules which don't work:
1. Add QR
2. ColorBar
3. Crop
4. Draw Rectangle (This one's funny, the rectangle resizes every frame)
5. Edge Detect
6. FisheyeGL (It doesn't use pixel manipulation I think)
7. Flip Image
8. Gradient
9. Invert
10. Minify Image
11. Overlay
12. Replace Color
13. Resize
14. Rotate
15. Text Overlay

Modules which I am not sure about:
1. Canvas Resize
2. Blob Analysis
3. Blend
4. Decode QR? (Should it even be used on a GIF?)
5. Histogram
6. NDVI
7. NDVI Colormap
8. Noise Reduction
9. WebGL Distort

Whew. That was a big list. 
Can somebody confirm the above list or check if the modules that I'm not sure about, are working or not? Thank you!

**Comment by HarshKhandeparkar** [comment]
**Update**:
- Fixed DrawRectangle module
- Fixed FlipImage
- Fixed Invert
- Fixed Gradient
- Fixed ReplaceColor
- Fixed EdgeDetect

**Comment by HarshKhandeparkar** [comment]
@jywarren

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
**Update**:
- Add QR module fixed, revamped, the code is cleaner and simpler
- Crop module fixed, revamped
- Text Overlay is almost fixed.

**NOTE**: Modules using the `imagejs` library don't seem to be working.
Also, minifyImage module is broken

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers @jywarren

**Comment by HarshKhandeparkar** [comment]
Guys please try to run this locally.

**Comment by HarshKhandeparkar** [comment]
**Update**:
The rotate module was working. I just didn't know this.

**Comment by HarshKhandeparkar** [comment]
**Update**:
- I just managed to fix the resize module(also improved its code a bit). The code is much more readable now
- I also cleaned up the Rotate module code.

**Comment by HarshKhandeparkar** [comment]
**Update**: 
- Canvas Resize is also working.

**Comment by HarshKhandeparkar** [comment]
**Update**:
- Blob Analysis fixed

**Comment by HarshKhandeparkar** [comment]
**Update**:
- NDVI, NDVI Colormap, and Noise Reduction work
- WebGL works for still images but can be extended to GIFs. This one's a bit more difficult than others. Can this be done in a separate PR? @publiclab/is-reviewers @jywarren

**Comment by HarshKhandeparkar** [comment]
**Current Status**:
- Most modules are working with GIFs
- Some complicated ones are not working which I will fix in separate PRs as they work with still images anyway.
- Travis is also passing
- I have improved the code of many many modules
- **IMP**: WebAssembly is not working and I will need @Divy123's help in this who is currently offline due to inet issues.

@jywarren @publiclab/is-reviewers

**Comment by ataata107** [comment]
getImageDimensions seems not be working correctly

**Comment by HarshKhandeparkar** [comment]
I will fix the image dimensions today. Now. Is anything else broken? I also have to add some comments and some docs...

**Comment by HarshKhandeparkar** [comment]
Fixed the image dimensions!

**Comment by HarshKhandeparkar** [comment]
I added some comments and cleaned up some code. Please review this @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
The GIF part of this PR has been moved to #1404. This PR only fixes module tests now.

**Pull request closed without merging**
