### PR TITLE
WIP towards importImage module

### PR DESCRIPTION
**Pull request by jywarren**
Solves #233

@tech4gt @ccpandhare check it out -- stuck!

### CODE REVIEW

**Comment by jywarren** [comment]
Also wondering why we aren't seeing a failed test... I feel like we should have a test that just chains all the modules and just confirms that there are no errors.

**Comment by jywarren** [comment]
This also doesn't have super great separation of UI and function. :-/

**Comment by ccpandhare** [comment]
Will have a look!

**Comment by jywarren** [comment]
@tech4gt check it out! I think this is ready to go, what do you think?

**Comment by jywarren** [comment]
I wonder if it could simplify the demo code too, and generally make it unnecessary to have a special starter module.

**Comment by tech4GT** [comment]
Closing in favor of #264

**Pull request closed without merging**
