### PR TITLE
Added Basic CLI

### PR DESCRIPTION
**Pull request by ccpandhare**
I have added basic CLI.
The main file is `./index.js`

## Usage

```
$ ./index.js OPTIONS
```

## Options

```
    -V, --version           output the version number
    -i, --image [PATH/URL]  Input image URL
    -s, --step [step-name]  Name of the step to be added.
    -o, --output [PATH]     Directory where output will be stored.
    -h, --help              output usage information
```

`-i` and `-s` are required flags. not specifying either will throw an error and call `process.exit(1)`

### CODE REVIEW

**Comment by jywarren** [comment]
oooooooooooooo 🎈

**Comment by ccpandhare** [comment]
I will make keep on making changes on this PR.
next, I shall add support for the user specific options.

**Comment by ccpandhare** [comment]
Then I will add the rest as FTO issues as you suggested earlier.

**Comment by jywarren** [comment]
@nadyapeek check this out! commandline interface!

**Comment by jywarren** [comment]
Yes and let's add a CLI section to the README to show just a simple example of the usage, like:

```sh
$ ./index.js -i file.jpg -s "invert"
```
What is the filneame of the output?

**Comment by ccpandhare** [comment]
I have added the outputs feature. Now modules' text outputs are shown in this manner:
```
➜  ./index.js -i examples/images/IS-QR.png -s decode-qr
---
Files will be exported to "./output/"
[decode-qr]: qrval = http://github.com/publiclab/image-sequencer
---
```

**Comment by ccpandhare** [comment]
Since CLI is the least developed part of image sequencer, I see immense opprtunity of creating FTOs here. As you had suggested earlier @jywarren, I think It would be a good idea to shift development to other issues and add some of the semaining CLI features as FTOs. Sounds cool?

**Comment by ccpandhare** [comment]
If yes, then I think we should merge this in and then I can start writing FTOs for CLI!

**Comment by jywarren** [comment]
Yes!!

**Pull request merged**
