### PR TITLE
Fix meta module bug

### LINKED ISSUE #1239: problem with meta-modules
There are many errors occuring while using meta-module(colorbar and ndvi-colormap).
Steps to reproduce
1 .chose nvdi-colormap(or colorbar)
2.then chose any other module and change the value that is not the default value
it would now change image produced by the above mentioned module as well .

Screencastfrom29-08-19095222PMIS

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by blurry-x-face**
Fixes #1239 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers

**Comment by keshav234156** [comment]
@blurry-x-face can you please upload a gif

**Comment by blurry-x-face** [comment]
Peek 2020-01-06 19-45

**Comment by Divy123** [comment]
Great I think this is good to go.

**Comment by keshav234156** [comment]
Nicely Done!!!

**Comment by jywarren** [comment]
Awesome. Thanks! And hi, @Divy123 !!!

**Comment by Divy123** [comment]
Hi @jywarren !! How are you?

**Comment by jywarren** [comment]
Great!!! So good to hear from you. I got your email, i'm just behind a bit as usual 😅

**Comment by Divy123** [comment]
No probs !! So good to be back here. And definitely missing our weekly calls.

**Pull request merged**
