### PR TITLE
Add-button-dim

### PR DESCRIPTION
**Pull request by kevinkmmak**
Dim the button onLoad, then enable it when something is selected.

### CODE REVIEW

**Comment by kevinkmmak** [comment]
Sure, here you are.
screen shot 2018-07-24 at 10 03 09 pm
screen shot 2018-07-24 at 10 03 40 pm

**Comment by kevinkmmak** [comment]
Thank you. Afterall, this is my first real contribution. I am now confident to look for more issues that I can contribute. Thank you again for opening this first-timer-only issue.

**Comment by tech4GT** [comment]
@jywarren this ready to be merged in😄

**Comment by tech4GT** [comment]
Welcome to our community @kevinkmmak😄🎉

**Comment by jywarren** [comment]
Thank you!!!!

**Pull request merged**
