### PR TITLE
Added insert step button at every step

### LINKED ISSUE #466: Add an "insert step" button on each step UI
This code shows the excellent "insert step" method in use:

https://github.com/publiclab/image-sequencer/blob/5f57123503993e889fbd3869cdcbc356c7d0bf6b/test/modules/image-sequencer.js#L139-L144

We should add a new button (next to the trash button) which lets you insert a new module:

sketch-1541958834514 png

See this for how the add step UI works, that could be adapted here:

The available modules are added to the select here:

https://github.com/publiclab/image-sequencer/blob/4d996b9968f95fd7f6158bde3034d9f5c43f6737/examples/demo.js#L11-L16

Here is how the "add step" button is triggered:

https://github.com/publiclab/image-sequencer/blob/a17d1a6ccd78e91043d823b134722c80a61ea491/examples/demo.js#L34

Here is the function that's run when the button is pressed; this could be adapted to accept a 'step' parameter too, so the insertion could happen at a different place in the sequence:

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/examples/lib/defaultHtmlSequencerUi.js#L38-L60

@holykol perhaps you'd be interested in this one? Or someone else? We'd love some help!

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #466 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@publiclab/reviewers please review.

**Comment by HarshKhandeparkar** [comment]
@Divy123 please provide a gif/screenshot for the PR.

**Comment by HarshKhandeparkar** [comment]
Also you should probably change the arrow functions to normal ones as it is not supported by all browsers

**Comment by HarshKhandeparkar** [comment]
Also you can add a fontawesome icon to the btn if you want.

**Comment by tech4GT** [comment]
@Divy123 Were you able to figure out the correct index to run the sequence from?

**Comment by Divy123** [comment]
@tech4GT  actually I tried to run it from the current index and some other related values but then I realized that run was only responsible for producing output and the UI that was being added was due to insertSteps() which inserted it correctly in the steps array so I reloaded the page after every insert step which correctly displays all steps in correct order. Hope that is correct.

**Comment by Divy123** [comment]
Sure @tech4GT please take a look.

**Comment by tech4GT** [comment]
Okay Divy, I am getting a couple of errors here, I think Image not loading is because of some errors in defaultStepUI file, which is preventing the javascript on the page to run any further. Let me fix this up a little. Thanks.

**Comment by tech4GT** [comment]
Ok, I have isolated the problem here, the defaultStep UI always appends the new step at the end, we need to fix it to append at the right position, then it'll work perfectly!
cc @jywarren @Divy123

**Comment by tech4GT** [comment]
@Divy123 Please allow edits from maintainers, then I'll push the changes here directly, thanks!

**Comment by tech4GT** [comment]
@Divy123 Pull these changes and try it out, I think this should work now! :smile:

**Comment by Divy123** [comment]
@tech4GT yes its working perfectly. Thanks a lot :smile: . The Travis is failing at one test for node v6 at npm install. Can you please guide on that?

**Comment by tech4GT** [comment]
Divy try opening and closing the pull request.

**Comment by Divy123** [comment]
@tech4GT  all tests passed. I think it is ready now. Thanks a lot for your help :smile: .

**Comment by tech4GT** [comment]
Divy, I think this needs a bit more work, I don't think this is working correctly for sequences and I noticed that saving sequences is also not working out correctly. I'll push the fixes in and then we can merge.

**Comment by Divy123** [comment]
Sure @tech4GT . I am upon it and thanks for your help.

**Comment by Divy123** [comment]
@tech4GT please have a look.

**Comment by tech4GT** [comment]
Great! I think we are good to go here! :tada:

**Comment by jywarren** [comment]
Fantastic!

**Pull request merged**
