### PR TITLE
UI test fix

### LINKED ISSUE #714: UI test not working
The UI test `HTML UI contains notify function` doesn't work.

screen shot 2019-01-25 at 2 20 16 am

### Please show us where to look

https://github.com/publiclab/image-sequencer/blob/c445070937a9eb069745ced983f210b2f16da40b/test/ui/user-interface.js#L9

### Browser, version, and operating system

Chrome, OSX

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #714

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
f
@publiclab/reviewers have a look :)

**Comment by VibhorCodecianGupta** [comment]
@Divy123 I don't think it's an OSX issue. Rather it's a javascript issue. The import isn't supposed to work like that. Since it checks for a `typeof window` in the original file, and while running tests it doesn't run in a browser, the `.defaultStep` import doesn't work. Can you post a screenshot of the test running in your environment?

**Comment by HarshKhandeparkar** [comment]
@Divy123 you must have tried an old version. In the new version, the UI code was refactored to use `require`

**Comment by Divy123** [comment]
Ohh then its a good catch.
Thanks @VibhorCodecianGupta :smile:

**Comment by VibhorCodecianGupta** [comment]
closing in favour of #720

**Pull request closed without merging**
