### PR TITLE
fixed the bug

### LINKED ISSUE #997: Image is getting deleted after clicking enter
The image is getting deleted after entering the changes and click enter.
Instead the changes should get applied to the image and not get deleted.

Screenshot from 2019-04-07 17-36-26

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Fixes #997 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers review it.

**Comment by Harshithpabbati** [comment]
Now the changes are being applied when i hit enter.

**Comment by jywarren** [comment]
Hi! Shall we write a UI test to confirm this and protect it? Thanks!!!

**Comment by Harshithpabbati** [comment]
@jywarren I am interested in the improving the test for UI. But I don't know what it is and how to start?? Can you say me some things to do it.

**Pull request merged**
