### PR TITLE
Added x and y input for custom resize

### LINKED ISSUE #464: Add x and y inputs to Resize module
We have a great new Resize module by @KusioDev! 

Try it here: http://sequencer.publiclab.org/examples/#steps=resize{resize:25%25}

It's super. Let's expand on it by allowing resize to be done either with locked aspect ratio (the current, where both x and y are scaled the same) or separately by x and y:

image

See the resize code here: https://github.com/publiclab/image-sequencer/tree/main/src/modules/Resize/

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #464 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
screen shot 2018-12-31 at 12 09 31 am

This is how the UI looks, and the resizes work well. However, we need a more foolproof method to let the user choose between custom and to scale resize. For now, I have placed a flag which checks whether the custom height/width has the default `125%`. If they do, it assumes the user made changes according to to-scale resize, and if they don't , it is assumed the user changed the custom parameters. The problem occurs when the user has resized according to custom methods, but wants to again resize to-scale. Now because to-scale has 125% and the custom values are already changed, it wont read the changes made to to-scale parameters. Perhaps a checkbox could work fine? UI changes will have to be made. 

@publiclab/reviewers
@tech4GT

**Comment by jywarren** [comment]
ah i see... what if we have a checkbox that says "preserve proportions"
which then links the two - so a change to one affects the other -- but if
it's not checked, the two can be changed and don't affect one another?

**Comment by VibhorCodecianGupta** [comment]
@jywarren oh yes, that's a good idea. I'll try writing the code and push it by today.

**Comment by jywarren** [comment]
If you get to resolving this, please don't bother adding dist files; we will start to test not requiring them in PRs, and then it won't go out of sync, ok? Thanks!

**Comment by Harshithpabbati** [comment]
Was this done ???

**Comment by HarshKhandeparkar** [comment]
Yes. Not merged yet.

**Comment by Harshithpabbati** [comment]
Can I work on this in that case??

**Comment by HarshKhandeparkar** [comment]
This has become quite old. Closing for now. You may reopen if you want :)

**Pull request closed without merging**
