### PR TITLE
Header opens a new page

### LINKED ISSUE #568: Make "Image Sequencer header" reload the page with no steps.
This is a sub-issue of #487 .
####  where to look

http://sequencer.publiclab.org...

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #568

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, are the changes from package-lock related at all? Perhaps we should leave it out unless they're updates?

**Comment by aashna27** [comment]
> Hmm, are the changes from package-lock related at all? Perhaps we should leave it out unless they're updates?

no not related, okay I ll keep that in mind for the next time .

**Comment by aashna27** [comment]
@jywarren are there any changes required ?

**Comment by jywarren** [comment]
Merging - next time maybe we can leave it out, though? Thank you!!!

**Pull request merged**
