### PR TITLE
Make the site responsive

### LINKED ISSUE #1381: Make the site responsive
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

Screenshot_20191220_191525

Screenshot_20191220_191502

The current version of the site is not responsive. :cry: 
Your job is to make it look great on mobile devices. :iphone: 

Don't worry though, it will only take you a few simple edits. 📝

### 🚩 Goal

Screenshot_20191220_191935

Screenshot_20191220_192013

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** image-sequencer/examples/demo.css
Below `#gif` selector(line 154) add this code:

- line `47` -> remove `min-width` rule
- line `69` -> remove `min-width` rule

```css
@media(max-width: 768px) {
    #dropzone {
      margin: 0 0% 30px;
    }
}
```

**Open** image-sequencer/examples/index.html
- line `58` remove inline styles from header

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by adamg703**
Fixes #1381   (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
@adamg703 I can confirm that you did a great job making the website responsive.
However, I have a few suggestions. 📝

I've noticed that you've named the PR title "Worked on issue #1381".
It is really a bad naming convention since a reviewer doesn't know what exactly you tried to accomplish with the PR.

Your second mistake is closely related to the first one and that is committed messages.
In the first commit, your message is "Removed line 47 & 68, added line 154".
The reviewer doesn't know what is line 47 or 68, right?
Also, in the future line can change and it is no longer a valid commit message.
Commit messages purpose is to tell us what was changed and most importantly why it was changed.

The same applies to your second commit.

Finally, you should edit your PR message.
`Fixes #1381` and mark checkboxes.

I know this was a lot for you first-time contribution(PR).
My purpose was not to discourage you, but quite the opposite, to make you a better programmer.
We all make mistakes and that is alright, but mistake is not a mistake if you've learned something from it :smile: 
You'll make your life and the life of your colleagues easier when you look back at this a few months later.

**Comment by VladimirMikulic** [comment]
Also, don't work on the `main` branch!
You should always create a new branch when you want to introduce a change.

Close this PR and open another one with the suggested improvements.
The maintainers won't merge this.

**Comment by HarshKhandeparkar** [comment]
@jywarren this one is ready too.

**Comment by jywarren** [comment]
I agree, approved! Once it passes, let's merge it!

**Comment by jywarren** [comment]
Nice! Thank you so much!

**Pull request merged**
