### PR TITLE
Disable the Save Sequence button until one step is added

### LINKED ISSUE #395: Disable the Save Sequence button until one step is added
# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Issue
The `save-sequence` button in the UI should be disabled until some step is added in the sequence.

Here's where the `save-sequence` button is made:

https://github.com/publiclab/image-sequencer/blob/9168c15cf9ece28521e92c5fb1d5dd453518c937/examples/index.html#L99

We can make the button disable at the start and then enable it on first click of Add step button. We have to also disable the button if all the steps are removed.

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #395 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Divy123** [comment]
@publiclab/reviewers
Please review.

**Comment by Divy123** [comment]
@publiclab/reviewers
Please review

**Comment by Divy123** [comment]
@tech4GT please review.
Unable to tag @publiclab/reviewers .

**Comment by ho-dor** [comment]
Can I work on this @Divy123 ?

**Comment by Divy123** [comment]
@ho-dor I have already created the PR for this. You may look forward to some other issue.

**Comment by jywarren** [comment]
Hi! I was thinking, perhaps this could be more easily determined using `sequencer.images.image1.steps.length` ?

**Comment by Divy123** [comment]
Closing this pull request as I have committed wrong files by mistake.

**Comment by jywarren** [comment]
Ah, did this ever get resolved or re-opened? Thank you!!!

**Pull request closed without merging**
