### PR TITLE
Fix overlay

### PR DESCRIPTION
**Pull request by tech4GT**
@jywarren Please merge this, contains some more tweaks here and there. :D

### CODE REVIEW

**Comment by tech4GT** [comment]
Also please publish this to npm and we should have everything for a basic exporter on the cloud :tada:

**Comment by Divy123** [comment]
@tech4GT request request you to look into #400. It's the task of this week
for me. Please help.

**Comment by tech4GT** [comment]
Divy, I am really sorry but I am kind of swamped right now! I'll still try to take a look tonight.

**Comment by Divy123** [comment]
Thanks @tech4GT that will be great help.

**Comment by jywarren** [comment]
OK, great!

**Comment by Divy123** [comment]
@jywarren can you please help me ith #400 ?

**Comment by jywarren** [comment]
OK, and released as `v3.3.5` -- noting for @publiclab/is-reviewers !

**Pull request merged**
