### PR TITLE
TakePhoto functionality added

### LINKED ISSUE #494: Add 'Take a photo' as another option for initial load image step
### Please describe the problem (or idea)
We can add another button -  **Take a photo** as an alternative to the **Choose file** in the initial load image step.

> What did you expect to see that you didn't?

screenshot 36
A **'take a photo'** button will basically open the camera of the user device, click a picture 📸  and then load it in the initial image load step.
### Please show us where to look

https://sequencer.publiclab.org

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #494

giff

image

Thanks!

### CODE REVIEW

**Comment by tech4GT** [comment]
@aashna27 This looks great!! I'll try this out in my browser and then we can merge!! Great work! :smile:

**Comment by jywarren** [comment]
oh cool, is it possible to see a screenshot of this or even a gif? Very
cool, thanks Aashna!

**Comment by aashna27** [comment]
@jywarren i have attached a gif in the pull request.

**Comment by tech4GT** [comment]
I think we are ready to merge here! :tada:

**Comment by jywarren** [comment]
This is really cool by the way!!!!

**Pull request merged**
