### PR TITLE
pixel value on hover in ndvi fixes #307

### LINKED ISSUE #307: UI feature: display value of pixel under mouse while hovering over image (NDVI module)
This would be GREAT and is much requested in the https://github.com/p-v-o-s/infragram-js project

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>
screen shot 2018-08-04 at 6 16 00 pm

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren Please have a look at this too.!!

**Comment by jywarren** [comment]
Great, can we have it say "NDVI: ___"? Awesome!!!

**Comment by tech4GT** [comment]
@jywarren Sure!! putting this up in 2 mins!

**Comment by tech4GT** [comment]
@jywarren Done!!

**Comment by jywarren** [comment]
Awesome!!! You're on a roll!

**Comment by tech4GT** [comment]
@jywarren Thanks haha! I'll rebase the other pr now and I'll try to put in the colorbar pr in a few hours!! Awesome!!

**Comment by jywarren** [comment]
wow!

**Pull request merged**
