### PR TITLE
save dropdown connectivity

### LINKED ISSUE #1192: Save Button is unresponsive
#### The save button for different saving options, saving sequence string download gif and save image png is unresponsive. The link does not exist rendering the functionality useless. 

save

I would like to work on this but I need some connecting dots for what do the individual dropdown options do.

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #1192 

Right now I have figured out for only 3 dropdown option-> 

- [x] save png
- [x] save sequence in browser
- [x] save gif
- [ ] save sequence string

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by aashna27** [comment]
The gif shows the 3 functions working, not really understand the use for the save sequence string and where to store it.
dropdown-shown

**Comment by jywarren** [comment]
Hi! This is great. The "save sequence" function i think doesn't really belong in this menu, but we don't have to address this right now. 

It's purpose was to allow people to save the entire sequence as a named sequence which would actually appear in your list of modules you can add. 

But it's a bit confusing to mix it with image exporting, and also it's confusing because it's not clear what it is, or how it works, and also not clear that you're not saving it in a way that /other/ people can see. I think maybe we need something like "submit sequence to gallery" or something which encourages people to develop new sequences and share them with other people. So let's just put that whole big idea aside (in a new issue?) and focus on just image exporting. 

How does that sound? Thanks, @aashna27 !!!! 🎉

**Comment by aashna27** [comment]
The json sequence string is stored in the local storage but the the string
save sequence seems irrelevant.

**Comment by aashna27** [comment]
Sequence export seems a cool idea, but the url I believe can be shared with
those specific settings applied. And we also have download gif to maybe
share the output.

**Comment by jywarren** [comment]
Yes, let's just open a new issue (would you mind doing this?) to discuss
the sequence export possibilities. I think we'll want a modal to explain
the options, since there are pros/cons, and no matter what we'll want more
explanation shown. Thanks!

**Comment by aashna27** [comment]
i have opened issue and what about merging this one, I ll remove the "save string string" from the dropdown.

**Comment by jywarren** [comment]
ok, that sounds good, then are we ready to merge here then? Thanks!!!!

**Comment by aashna27** [comment]
Yes i think it's good to go

**Comment by jywarren** [comment]
Hi, looks like it needed an update, so i triggered it to sync. Would you consider writing a UI test for this functionality to preserve it? Thank you @aashna27 !!!

**Comment by aashna27** [comment]
The ui testing is yet to be figured out. So maybe if before that we can
merge this.

**Comment by jywarren** [comment]
OK, sounds good. Thanks!

**Pull request merged**
