### PR TITLE
added gif feature

### LINKED ISSUE #344: Add a function to create a gif from the outputs of all steps
@jywarren We can add an option which enables sequencer to export the whole sequence as a gif, I think this makes sense since right now we do not have any way of exporting the complete sequence as a single file. What do you think, would this be useful?

### PR DESCRIPTION
**Pull request by rockstar777**
Fixed #344

### CODE REVIEW

**Comment by rockstar777** [comment]
gif_step

**Comment by tech4GT** [comment]
@rockstar777 2 things
- Please make the button say `Download as GIF`
- Please make the gif a little slower in the sense that give more time to each image, currently it's very difficult to make sense of the gif because it changes too quickly

**Comment by tech4GT** [comment]
But great work! Thanks for your pr!😄

**Comment by rockstar777** [comment]
please review
thanks

**Comment by avsingh999** [comment]
margin

**Comment by avsingh999** [comment]
@rockstar777  can you post gif of this pr where I can understand what have you done

**Comment by rockstar777** [comment]
exm

**Comment by avsingh999** [comment]
@rockstar777 Place  Download as a gif button along with download and add step It would be better

**Comment by rockstar777** [comment]
it would look better but we are considering gif for all images of each step.

**Comment by jywarren** [comment]
Yes, i think we're eventually going to have to have a whole region just for
adding new steps, maybe with preview thumbnails for different steps. So it
may eventually need more space in that area.

And then a separate "downloading" area with all the download options. What
do you think? Thanks!!!

**Comment by rockstar777** [comment]
@jywarren agree with that one area for step section and one for download option could look better.

**Comment by rockstar777** [comment]
screenshot 27

@jywarren So what about this?

**Comment by jywarren** [comment]
I love it! And the gif itself - perhaps we center it at the bottom with
`padding: 50px` ?

Is it a bit squished? Maybe we need to set the dimensions?

**Comment by rockstar777** [comment]
No not at all, we just has to create some extra attributes like id for gif element.
and for dimension i think 400px wide and 350px could be perfect.
What say @jywarren ?

**Comment by rockstar777** [comment]
screenshot from 2018-10-01 14-33-16
@jywarren how about this?

**Comment by jywarren** [comment]
ah, i believe you can retrieve the dimensions of the original image via the
sequencer API, unless I'm mistaken -- through the `options` parameter:
https://github.com/publiclab/image-sequencer/blob/5a362f5c9afe19cbf20c7cab942d6e486078ab99/src/modules/Crop/Crop.js#L14-L15

**Comment by jywarren** [comment]
that looks lovely! Were you able to get the right dimensions?

**Comment by rockstar777** [comment]
let me try

**Comment by tech4GT** [comment]
@jywarren @rockstar777 I was thinking of downloading the gif and not displaying it in the page, do you think this will be better? Also @rockstar777 looks like we have to rebase here.

**Comment by rockstar777** [comment]
That is a good idea, but we should provide a demo to our users so that he could decide whether he should download or not? just my opinion what do you think @jywarren @tech4GT 
@tech4GT , just rebasing my branch at my end.

**Comment by avsingh999** [comment]
@rockstar777  solve conflicts

**Comment by tech4GT** [comment]
Hmm, @rockstar777 maybe we can do like a small eye logo which displays the preview but I don't think that's required since the preview is the sequence itself, we are just exporting it as gif. Nothing new is being generated.

**Comment by avsingh999** [comment]
@tech4GT  I think @rockstar777  is right if we want to download as gif user will preview for that gif before download if wants any changes in that gif he/she can change

**Comment by tech4GT** [comment]
@avsingh999 The gif is just all the step outputs combined together, the output of each step is already visible, the idea behind `exporting as gif` was to just make it possible to export the complete sequence as a single file

**Comment by tech4GT** [comment]
Previewing the gif will just show the sequence of images which are already visible separately, don't you think?

**Comment by rockstar777** [comment]
@tech4GT @avsingh999 we should not fight on this, but one thing we can do,
 instead of preview on the same page, let's make a pop-up box which will preview a user and if he wants, he could download it. what say @tech4GT @avsingh999 ?

**Comment by jywarren** [comment]
I think that sounds great. Different people may often have different UI preferences, so talking through them is a good idea. But it's hard to predict exactly what will be most natural for people. 

Thanks everyone for being patient and thinking carefully here. Whenever possible please remember to be as helpful as possible to one another, even when we're in a rush! I often say my opinion and then ask "what do you think?" 😄 🤝 🙌

**Comment by jywarren** [comment]
And a "please" and "thank you" are never out of place! 🎉

**Comment by rockstar777** [comment]
@jywarren I think we could make it as an issue for GCI candidate?
What do you think @jywarren @tech4GT @avsingh999?

**Comment by jywarren** [comment]
Yes, I think that's appropriate. Generating the Gif and displaying it below is a good initial step and we could imagine follow-up issues for a) displaying it in a popup (using Bootstrap) and b) forcing a download with a 2nd button.

How does that sound, folks?

**Comment by rockstar777** [comment]
Sounds great :tada:
So are we ready to merge this?
What do you think @jywarren?
Thanks

**Comment by tech4GT** [comment]
@jywarren @rockstar777 Is the gif removed from the UI if another step is added after generating the gif?

**Comment by rockstar777** [comment]
@tech4GT yes, till now in current PR gif, gets removed when we add new step.

**Comment by tech4GT** [comment]
@rockstar777 Please make the gif  `click to download` and rebase this, I think we will be ready to merge then. Good work!!

**Comment by tech4GT** [comment]
@rockstar777 I think you misunderstood me there, the button name was fine, I meant clicking on the gif should download it, like we do for the step images in the sequence. Thanks!

**Comment by rockstar777** [comment]
ok got it @tech4GT but that funtion aldready works in this PR.:smile:
So now again changing click to download to download as gif
Thanks

**Comment by tech4GT** [comment]
Great work @rockstar777 I think we are ready to merge here, but first a couple of pointers for you
- You can always remove your commits(not that it matters in this case), so ideally for rolling back on something in a PR we just undo the last commit.
- To solve the conflicts in dist files, use `git pull` in your local branch, the automatic merge will fail and it will prompt you to manually resolve the conflicts. If there are conflicts in any file other than dist/ resolve the issues and save the files. Then use the `grunt build` command to generate new dist files. commit the changes and push to this pr.
Please settle the conflicts and then we can merge. Again much thanks for your patience!

**Comment by jywarren** [comment]
Almost done here, the checks were not appearing properly so I restarted them. Great teamwork folks. Thanks to everyone!!

**Comment by jywarren** [comment]
Ah, I see! This needs a quick rebasing... Are you able to give it a try? If so I can merge as soon as you're done, or I can help out. 

Sorry to introduce the conflicts by merging another PR; sometimes this happens!!!

**Comment by rockstar777** [comment]
@tech4GT @jywarren finding difficulty in rebasing, please provide some help
Thanks

**Comment by tech4GT** [comment]
Okay no worries I'll rebase this!

**Comment by jywarren** [comment]
Awesome, ready to merge then? 

Here's some resources on rebasing!!!

https://publiclab.org/wiki/developers#Resources

**Comment by jywarren** [comment]
Fantastic!!! I will publish this soon but would you like to open a pull request to increment or "bump" the version number in accordance w http://semver.org?

This is essentially a new feature so I believe itd be a 0.x.0 type change. Does this make sense?

**Pull request merged**
