### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by iKshitiz**
This commit fixes the issue #408

### CODE REVIEW

**Comment by Dhiraj240** [comment]
@iKshitiz next time please do not delete the PR template and in that just add the issue link without touching anything in the PR template.

**Comment by iKshitiz** [comment]
Sure :)

**Comment by iKshitiz** [comment]
Closed the pull request as it's duplicate and already merged

**Comment by Dhiraj240** [comment]
Alright :+1:

**Pull request closed without merging**
