### PR TITLE
Add issue and pull request templates into image sequencer repository

### PR DESCRIPTION
**Pull request by sashadev-sky**
This is for publiclab/plots2#3685.

### CODE REVIEW

**Comment by sashadev-sky** [comment]
Can I please get a review from @publiclab/reviewers?

**Comment by jywarren** [comment]
Any additional rewrites of text that'd be helpful for the templates for
this particular repository? Thanks!!!

**Comment by sashadev-sky** [comment]
@jywarren As a new contributor, I think the templates are clear! If we wanted to be more specific we could ask the user to consider if their issue pertains to a specific module, since many of the recent issues in this repository do.

**Comment by jywarren** [comment]
Awesome, thank you, and thanks for the feedback too! I'll merge this now. 👍

**Pull request merged**
