### PR TITLE
fixes bugs in gamma-correction module

### LINKED ISSUE #1255: bugs in gamma-correction module
- [ ] gamma-correction is not working as expected 

with gamma value of 0.5 the expected output should be 
download (34)
but output that is given by IS is
download (35)

what i found is that we are dividing val by defaults.adjustment which is 0.2 instead it should have been an OR operator.
https://github.com/publiclab/image-sequencer/blob/d782c147c5c11379f0c40a242c742bc13358fae3/src/modules/GammaCorrection/Module.js#L14

- [ ] slider is not working at all in gamma-correction module

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #1255 
fixing of the slider
Screencast from 16-09-19 04_50_35 PM IST

val was being divided by defaults.adjustment which was 0.2.this might have been done by mistake in PR #763 
before changes for gamma value equal to 0.5
64894910-a26df900-d698-11e9-916d-634051bd5315

after changes  for gamma value equal to 0.5
rotate (9)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@HarshKhandeparkar @jywarren @aashna27 can you please review this PR!!!

**Comment by keshav234156** [comment]
@jywarren  @HarshKhandeparkar  can you please review this PR!!!

**Comment by HarshKhandeparkar** [comment]
I am so sorry that I can't review this yet. I have a test coming up. Will you please hold on till Monday? I will surely review it that day.

Apologies.

**Comment by keshav234156** [comment]
@jywarren @HarshKhandeparkar can you please review this PR!!

**Comment by keshav234156** [comment]
@jywarren can you please review this PR!!!

**Comment by jywarren** [comment]
This is great. Thank you for the fix!!!

**Pull request merged**
