### PR TITLE
Disable-save-button

### PR DESCRIPTION
**Pull request by Mridul97**

### CODE REVIEW

**Comment by Mridul97** [comment]
Disable the save button when created, and enable it when any value in any input field is changed. The save button is disabled again when the save button is clicked.

**Comment by tech4GT** [comment]
Hi @Mridul97 Great work!! Can you please share some screenshots. You can insert an image in github comments by directly dragging and dropping it in the input box😁

**Comment by Mridul97** [comment]
Yes, here you go
screenshot 6
screenshot 7
screenshot 8
screenshot 9
screenshot 10
screenshot 11

**Comment by Mridul97** [comment]
No, changing input for one step will enable save button for that step only. Save buttons for all the other steps will remain disabled. I have tested this.

**Comment by tech4GT** [comment]
Very Nice @Mridul97 this looks good then!!
Let's wait for @jywarren to give a final review before merging this in!! Good work!!😊

**Comment by jywarren** [comment]
Looks fantastic. Thanks!!!

**Comment by jywarren** [comment]
We'd love to work with you more if you're interested!

**Comment by Mridul97** [comment]
Yes, I am interested and want to work more!

**Comment by jywarren** [comment]
Super! Maybe some of these might interest you?

https://github.com/publiclab/image-sequencer/issues/305

https://github.com/publiclab/image-sequencer/issues/232

**Comment by Mridul97** [comment]
Yes, I would like to work on #232. Can I work on this issue ?

**Comment by jywarren** [comment]
absolutely!

**Pull request merged**
