### PR TITLE
Implement multithreading in Run.js (WIP)

### LINKED ISSUE #1069: Implementing web workers for multithreading pixelManipulation.js
### Please describe the problem (or idea)
Implementing web workers with threads.js

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
lit2017001

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #1069   (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren @tech4GT @HarshKhandeparkar I am facing some difficulties running the currently implemented code in Run.js file.

The code is running good in node environment, though in browser, I see this error:

```js
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at image-sequencer.js:114608
```

Please help me with this. Unfortunately Google did not help me with this!!

**Comment by Divy123** [comment]
Travis also fails here:
https://travis-ci.org/publiclab/image-sequencer/jobs/559880521#L1202

**Comment by Divy123** [comment]
What I think here, I have to implement both node and browser code independently. What do you think @jywarren @tech4GT ?

**Comment by jywarren** [comment]
I think it's possible! Maybe @HarshKhandeparkar has input too?

**Comment by Divy123** [comment]
Any examples or something?

**Comment by Divy123** [comment]
@jywarren any suggestions here??

**Comment by HarshKhandeparkar** [comment]
Maybe we could wait until node properly implements workers? Maybe they will never be implemented. Multithreading comes with a lot of caveats and is not really very easy to deal with.

I think we should focus on utilising the GPU more. That is easier and more beneficial.

**Comment by HarshKhandeparkar** [comment]
Also, this one is outdated. Closing for now, feel free to rebase and reopen.

**Pull request closed without merging**
