### PR TITLE
Step links fix

### LINKED ISSUE #1288: Downloading image after modules contianing external links is applied
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

Downloading modules contianing external links redirects to that link.the modules that are having external  links are ndvi,gamma-correction,edge-detect,dynamic,dither,convolution

the file where the changes are to be made is
https://github.com/publiclab/image-sequencer/blob/cff82c998f351907e724a7151670885745100066/examples/lib/defaultHtmlStepUi.js#L284-L298

Untitled_ Oct 31, 2019 3_09 AM

### PR DESCRIPTION
**Pull request by tsparksh**
Fixes #1288
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.

links-fix

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, this looks really good; I wonder if we could write a test which demonstrates exactly what this does? Why do we no longer need the `for` loop? Could a simple UI test make this easier to review? Thank you!!!

**Comment by jywarren** [comment]
@keshav234156 i think you asked for a review from me, i'd love to hear your thoughts on my question above as well; would the UI test framework help answer this question?

**Comment by tsparksh** [comment]
> Hi, this looks really good; I wonder if we could write a test which demonstrates exactly what this does? Why do we no longer need the `for` loop? Could a simple UI test make this easier to review? Thank you!!!

It fixes the issue when you click on the step download button and you are being redirected to an external site. 
If I understood correctly, ```for``` loop is for searching for step output (and issue is if ```step.linkElements[index].href``` is not a base64 it redirects to that address), but we already have ```step.output``` so I used it

**Comment by jywarren** [comment]
OK! I'll go ahead and merge this, as it looks good. What I mean is that we should write a UI test to actually try this feature out during tests, automatically. That way if any future code breaks this feature, we'll be warned! We're coordinating this here, if you're interested! https://github.com/publiclab/image-sequencer/issues/1369

**Comment by jywarren** [comment]
🎉 !!!

**Pull request merged**
