### PR TITLE
Fixed Unresponsive Select Step Box

### LINKED ISSUE #924: A small bug in UI
### Please describe the problem (or idea)

download (1)

### PR DESCRIPTION
**Pull request by rohithGoudM**
Fixes #924

Both the select and button elements are stashed in a row.
One with col-md-8 and the other with col-md-4 respectively.

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Hey rohith, this includes the changes from your other pr as well.

**Comment by HarshKhandeparkar** [comment]
Cannot differenciate which ones are which.

**Comment by rohithGoudM** [comment]
I'll create a new folder and clone the whole thing 
Give me 5 min

**Comment by HarshKhandeparkar** [comment]
Also please provide a screenshot or gif(preferably gof to show if the changes are responsive on all screen sizes, you can show different sizes of browser by resizing it and taking different screenshots or in a gif). The title of your pr doesn't explain much, can you change that too?

**Comment by rohithGoudM** [comment]
Ok
So I have to make changes from the original(master) branch, not the one that I have already changed..?
Then I have to repeat the whole process or just checkout from start
I'll figure this out, please be patient

**Comment by HarshKhandeparkar** [comment]
You can remove the other pr changes from this branch and commit. That would be better

**Comment by HarshKhandeparkar** [comment]
Also image-sequencer uses `main` branch as its default not `master`.

**Comment by rohithGoudM** [comment]
I'm having trouble in removing the old commits in the pr
could you please help with that

**Comment by HarshKhandeparkar** [comment]
You can type `git rebase -i HEAD~4`. This will open a text editor. That editor will have instructions for reverting commits. Or you can just delete the changes and push a new commit.

**Comment by rohithGoudM** [comment]
s1
s2
here are the screenshots

**Comment by HarshKhandeparkar** [comment]
LGTM! Nice work!

**Comment by rohithGoudM** [comment]
I tried reverting but it seems that didn't work
I'll delete all the changes one by one

**Comment by rohithGoudM** [comment]
I have deleted changes related to cursor bug.
But the unresponsive bug has been dealt with

**Comment by HarshKhandeparkar** [comment]
Great!

**Comment by rohithGoudM** [comment]
How would I know if my changes have been merged with the project..?
Was just curious.

**Comment by HarshKhandeparkar** [comment]
You will get a notification when your pr gets merged.
Your changes will be seen on https://beta.sequencer.publiclab.org in a day or 2

**Comment by HarshKhandeparkar** [comment]
We have two maintainers, @tech4GT and @jywarren. @tech4GT hasn't been very active these days. @jywarren lives in the US so if you live in India (guessed from ur name). You will have to wait and the pr will be merged at night time.

**Comment by HarshKhandeparkar** [comment]
https://sequencer.publiclab.org is updated less frequently (only stable builds are published). Maybe it is updated every 20d or so.

**Comment by aashna27** [comment]
great work !! can the unneccary commits be deleted please ?

**Comment by jywarren** [comment]
It's OK, i can "squash and merge" from GitHub. Thanks, doing that now, thanks for your help! 

I'd like to expand the maintainers group but first we should get in a good workflow of getting 2 reviews from reviewers -- #656 -- thank you all for your help!!!

**Pull request merged**
