### PR TITLE
Infos updated for new title/description format

### PR DESCRIPTION
**Pull request by jywarren**

### CODE REVIEW

**Comment by jywarren** [comment]
@tech4GT @ccpandhare -- new info module parsing all working and tested locally -- both title and description are now set in `info.json` and checked in tests. This makes `info.json` kind of like our version of `package.json` and simplifies the module functions themselves (fewer "setters", more consistent format).

**Comment by jywarren** [comment]
I think then we should update documentation as well and bump a version number. Would this be a `v0.x.0` or even `vx.0.0` http://semver.org level?

**Comment by tech4GT** [comment]
@jywarren This is amazing🎉 
Also I think this should be a `x.0.0` bump since the previously styles of modules are obsolete after this

**Comment by jywarren** [comment]
Agreed. I'll work on the docs a bit and do this.

**Comment by jywarren** [comment]
OK, docs rewritten!

**Comment by jywarren** [comment]
OK! Merged!!!

**Pull request merged**
