### PR TITLE
Install GPU.js v2.3.1

### LINKED ISSUE #1292: Bugs in Blur module and modules which are using blur module
there is a bug in blur module and modules that are using it(edge-detect).This works fine for me on desktop site but on mobile device it as shown
Screenshot_20191105-151912_Chrome (1)

### LINKED ISSUE #1348: Installation error
When I ran sudo npm run setup, I got that error:
Running "browserify:core" (browserify) task
>> Error: Cannot find module './utils' from '/home/md37/image-sequencer/node_modules/gpu.js/dist'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! image-sequencer@3.5.1 setup: `npm i && npm i -g grunt grunt-cli && grunt build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 setup script 'npm i && npm i -g grunt grunt-cli && grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the image-sequencer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && npm i -g grunt grunt-cli && grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs image-sequencer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls image-sequencer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/md37/image-sequencer/npm-debug.log

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #1348   (<=== Replace `0000` with the Issue Number
Fixes #1292

NOTE: This is a continuation of #1356 

- Installed GPU.js v2.3.1 which fixes Blur module on small screen sizes
- @robertleeplummerjr the browserify error for gpu.js

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Other Changes:
- Text Overlay and Blob Analysis module tests failed due to the absence of WebGL in node. They also don't use puppeteer so they will not be tested. An issue regarding this will be opened soon.

**Comment by keshav234156** [comment]
https://travis-ci.org/publiclab/image-sequencer/jobs/627365619#L1479

**Comment by keshav234156** [comment]
test benchmarks are running now .Great!!!

**Comment by HarshKhandeparkar** [comment]
Have a look at https://github.com/publiclab/image-sequencer/issues/1375

**Comment by HarshKhandeparkar** [comment]
Also:
1. More modules eg: FisheyeGL and WebGLDistort which use puppeteer are now benchmarked.

**Comment by HarshKhandeparkar** [comment]
Travis still fails though. I will find a solution for that.

**Comment by HarshKhandeparkar** [comment]
@jywarren @keshav234156 @publiclab/is-reviewers This is working - at least locally. With the help of @robertleeplummerjr I was able to successfully browserify the tests and run them. v2.3.1 of gpu.js and the later versions can be used now. The Blur module bug on smaller screens has been fixed now.

**Comment by HarshKhandeparkar** [comment]
The installation errors should also be fixed now. Awesome!

**Comment by robertleeplummerjr** [comment]
Woot!

**Comment by HarshKhandeparkar** [comment]
:smile:

**Comment by jywarren** [comment]
This is awesome!!!!

**Comment by keshav234156** [comment]
Awesome!!

**Comment by keshav234156** [comment]
@HarshKhandeparkar https://travis-ci.org/publiclab/image-sequencer/jobs/628126608#L1408
Why are we getting Bad image Path

**Comment by HarshKhandeparkar** [comment]
We'll have to fix this separately

**Pull request merged**
