### PR TITLE
Drag to crop fixes #205

### LINKED ISSUE #205: add "drag to crop" UI feature to Crop module
I was thinking that the ability to drag a region to be cropped using the Crop tool would be great, when using the default HTML UI. It might take a couple hundred lines of code, however, and I'm not sure we'd want that in the core library. Is this an example of something we should develop as a separate module entirely?

### PR DESCRIPTION
**Pull request by tech4GT**
@jywarren drag to crop is done for #205 🎉
screen shot 2018-04-18 at 6 50 59 pm

### CODE REVIEW

**Comment by jywarren** [comment]
This is looking amazing. Does it act upon the image in the previous module? Maybe we need to think about #215 to make the interface "live" within just the current step, no? 

What do you think?

This is so exciting!!!

**Comment by tech4GT** [comment]
@jywarren actually I think that drag to crop should be enabled on the current image step only and not on previous steps and that's what I have implemented right now, the drag ability is only available on current step if crop is selected😁

**Comment by jywarren** [comment]
oh, i see, but i guess the screenshot is a bit confusing to me then - it
looks like it's running on the image in the Load-Image module. By "current"
do you mean the final image? For example, what happens if you add the crop
module as a step; does it then start a UI for dragging on its own thumbnail
image, and what we're seeing is just for the "add" interface?

I guess this is why i feel the ambiguity of being able to use settings both
on add and on existing added steps is confusing.

**Comment by jywarren** [comment]
Ah, i see. That makes sense -- the crop should be drawn on the output of the previous module. But maybe for UI clarity, we should simply show the uncropped image in the crop module and have the crop be done on that and then hide the drag interface. Then have an "edit crop" button to reactivate it?

img_20180419_162855

**Comment by tech4GT** [comment]
@jywarren so after the crop is applied we want to hide the selection on the previous image and give a button to edit that right?

**Comment by tech4GT** [comment]
@jywarren Currently after crop is applied the selection on the original images gets hidden and it functions like it was copped by normally entering coordinates

**Comment by jywarren** [comment]
I guess I imagined (in the sketch) that we show the drag UI on the
uncropped image within the Crop UI, not the previous image -- and then hide
it once you "save" your crop. make sense?

**Comment by tech4GT** [comment]
Absolutely Correct!
screen shot 2018-04-20 at 2 10 53 am
screen shot 2018-04-20 at 2 11 00 am
screen shot 2018-04-20 at 2 11 13 am
This is the current workflow

**Comment by tech4GT** [comment]
@jywarren is this the desired output or we need to add something?

**Comment by jywarren** [comment]
I think this works -- but I do think that the UI of each module should
probably be self-contained, though. I just think unexpected things could
happen in the future if one step assumes things about prior steps. Does my
alternative workflow make sense, where the original uncropped image with
drag UI is shown /within the crop module UI/ until you click "save crop",
and then it shows the output image? But that you could "reactivate" the
drag UI by clicking "Edit Crop"?

**Comment by tech4GT** [comment]
@jywarren should I rebase this or we need some changes here?? Thanks :smile:

**Comment by tech4GT** [comment]
@jywarren This makes sense, we'll come here once #215 is done. Also now i completely understand the workflow you are after :)
Thanks

**Comment by jywarren** [comment]
OK - now #215 is complete -- if you could rework this one using the new UI convention, it'll be ready to go!

Excited......!!!!!!

**Comment by tech4GT** [comment]
@jywarren I'll do it tomorrow itself!!

**Comment by jywarren** [comment]
awesome :-))))

**Comment by tech4GT** [comment]
screen shot 2018-04-29 at 6 04 17 pm
screen shot 2018-04-29 at 6 04 28 pm
screen shot 2018-04-29 at 6 05 30 pm
screen shot 2018-04-29 at 6 05 51 pm
@jywarren Done like you specified, now after the crop step is added the upper image can be dragged to select and then save will update the result. It is also resizable.

**Comment by jywarren** [comment]
OK - i still think one more change is needed -- sorry! I'd really like to ensure that the UI of each step only touches its own HTML -- that way nothing unexpected happens. Imagine if one step chooses not to display an image, but overrides the UI somehow. I just think we should not assume. So, this is just right except:

1. when you first add it, it should show the whole image within its own step HTML region -- not the previous one, and with the dotted box
2. when you click "save crop" it then hides the whole image, and will just show the successfully cropped region
3. but when you click "edit crop" it then hides the cropped version and shows the original again, but still only within its own UI region. 

Make sense? Sorry this is taking forever, but I think this'll be a quick change. And i think it'll result in less potential for bugs later to keep each step only interacting with its own UI's HTML code.

**Comment by tech4GT** [comment]
@jywarren actually for that we would have to change default parameters for the crop module so that by default nothing gets cropped, should I do that?

**Comment by jywarren** [comment]
oh but we could show the default crop using the dotted box, no? Just not
"saved" yet?

**Comment by tech4GT** [comment]
@jywarren No, I don't think that's possible here, since that box is user drawn and not code generated .

**Comment by tech4GT** [comment]
@jywarren I think i can do that, but i have a doubt. So should I make it this way such that whenever crop is applied it shows the same image with a selection until the user clicks save. So I should call the crop function on clicking save and not addStep?

**Comment by jywarren** [comment]
> that box is user drawn and not code generated .

Aha, I see. But you're saying you have a workaround? 

> call the crop function on clicking save and not addStep?

Hmm, that does seem right... can you think of any reason why that would cause trouble? I know it's not a the same behavior as usual. Is it possible to have this behavior only for this module and not others?

**Comment by tech4GT** [comment]
@jywarren I think I figured this out, I am working on this right now!!

**Comment by jywarren** [comment]
Oh awesome

**Comment by tech4GT** [comment]
@jywarren we do not have a edit step button in the ui as of now right?

**Comment by tech4GT** [comment]
@jywarren adding an edit crop button is calling for some UI work. Can we merge this without edit crop functionality and add that in later when we work on the UI?

**Comment by tech4GT** [comment]
@jywarren I have come up with a better solution, as soon as the user starts selecting the resultant image it starts showing original

**Comment by tech4GT** [comment]
screen shot 2018-04-30 at 12 00 42 am
screen shot 2018-04-30 at 12 00 56 am
screen shot 2018-04-30 at 12 01 06 am

**Comment by jywarren** [comment]
Ooh, it looks great but is the Edit button yet added? How do I start dragging a second time?

**Comment by jywarren** [comment]
Ah, i see:

> without edit crop 

Sure! Of course! We can always break things up. Ready to merge then? This looks great.

**Comment by tech4GT** [comment]
@jywarren actually you can just start dragging on the cropped image and it will expand to it's Original form😁

**Comment by tech4GT** [comment]
As in the second image

**Comment by tech4GT** [comment]
@jywarren Actually this plugin is not distributed via npm, what we can do is we can publish it there what say?

**Comment by tech4GT** [comment]
Maybe we can merge this in right now and later we'll publish it on npm and get it from there

**Comment by jywarren** [comment]
Oh it's possible to peg npm to a got repo and commit hash, I'll do it later
today no worries!

**Comment by tech4GT** [comment]
Thanks a ton @jywarren

**Comment by tech4GT** [comment]
@jywarren should I refactor on this issue only?

**Comment by jywarren** [comment]
OK -- i know this is a lot, but take a look here. I've done a lot of the breaking up of the demo code into smaller, better organized files, which will be easier to debug, maintain, and test. There's still more to do, but the most important thing is that I've managed to get the cropping UI into the module code. 

I think it's possible we may want to separate it out within the module folder, into a `ui.js` file, but we definitely don't want it in the generic UI code. Now there are:

`examples/lib/defaultHtmlSequencerUi.js` and

`examples/lib/defaultHtmlStepUi.js`

And demo.js is much much simpler. 

What do you think? @ccpandhare and @MayankKashyap if you're available for a look too, i'd love to hear your input. 

There are now a few bugs with the selection code. I'm sorry to leave it like this, but since you're more familiar with the functionality of the code, @tech4GT do you think you could have a go at fixing the interaction in the new code organization? If you're preparing for exams and have no time, I understand, though!

**Comment by jywarren** [comment]
And apologies for doing refactoring on a separate feature's PR; i usually don't do this and it's not great. But since I really wanted to get the crop code working, and the demo code was all mixed together, I wanted to make some advances on overall architecture. I think it's worthwhile, and I hope you do too!

**Comment by tech4GT** [comment]
@jywarren it's ok. No issues. I'll go through this as soon as I can and thanks a lot for helping out with this!!

**Comment by tech4GT** [comment]
@jywarren Actually i won't have that much time right now, I'm sorry but I can do it after exams, we can keep it on hold up until then?

**Comment by MayankKashyap** [comment]
Yeah @jwarren I agree with you, but due to exams I am little bit busy, so whenever I have time I go through this.

**Comment by MayankKashyap** [comment]
@jwarren it's great now....

**Comment by jywarren** [comment]
@tech4GT no problem of course! Good luck!!!

Thanks @MayankKashyap!

I'm actually encountering a lot of issues as I'm working on debugging this. A module ought to have easy access to:

1. the input image
2. the current output image

But I'm having trouble getting clear references to them from inside the module. I think we need to build out the module API more clearly -- what values are accessible inside the module and how? Some is in #137, but in general as we approach #122 (simplify module requirements) we'll need also to demonstrate how to get to values like the above. 

I won't do this in this PR since it's already gigantic (bad, i know! Sorry!) but we should follow up.

**Comment by jywarren** [comment]
screenshot 2018-05-03 at 11 46 41 pm

(invert bug -- i wonder if it's somehow an aliasing thing... off by one pixel... not sure!)

**Comment by tech4GT** [comment]
@jywarren that's a bug in the crop module itself actually #213 so we can handle tha5 separately

**Comment by jywarren** [comment]
OK, that's great. I'm going to rebase this and merge it!

I've put a lot of thoughts from going through this refactoring into #242 -- lots of great follow-ups!

**Comment by jywarren** [comment]
OK - I had some trouble merging from here, but have #245 all ready to go and am going to merge over there after final testing!

**Pull request closed without merging**
