### PR TITLE
named export for single image basic mode fixes #297

### LINKED ISSUE #297: Named Exports
Ability to define the directory, name and extension of the images that will be exported.

### PR DESCRIPTION
**Pull request by tech4GT**
This adds the ability to save the image as whatever(even different extension) (only works with basic mode)
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by jywarren** [comment]
looks like it needs a rebase, but sounds great!

**Comment by jywarren** [comment]
Is there a corresponding help response to the CLI that would clarify when a directory will be made? Cool!

**Comment by tech4GT** [comment]
@jywarren sure that sounds good.

**Comment by tech4GT** [comment]
@jywarren oh sorry I put the earlier comment on the wrong issue, sorry for that
Everything works like it did, but now while in basic mode we can name the output as well

**Comment by tech4GT** [comment]
so we can say `-o ./output` and also `-o ./output/image.png`

**Comment by tech4GT** [comment]
so it is not 2 different things, it is the same but now we have the extra ability to define the image name as well, directory will be created just as before(if it does not exist)

**Comment by jywarren** [comment]
ok awesome!

**Comment by tech4GT** [comment]
Awesome!!!!🎉

**Comment by jywarren** [comment]
yeah super!!!

**Pull request merged**
