### PR TITLE
[FIXED]Draw rectangle's rectangle shinking down with every frame in gif's

### PR DESCRIPTION
**Pull request by root00198**
output

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by root00198** [comment]
@publiclab/is-reviewers

**Comment by blurry-x-face** [comment]
Why is this open as a PR? Shouldn't you open a issue instead? Or is this already solved, In that case please share the working Gif!

**Comment by root00198** [comment]
output

@blurry-x-face  Fixed GIF...

**Comment by root00198** [comment]
It was an issue only in gif's. A test do exist in my GIF's Test PR.....

**Comment by blurry-x-face** [comment]
How is test for draw rectangle passing on that other PR?

**Comment by blurry-x-face** [comment]
We can get this merged soon and then you can correct the test on this accordingly!

**Comment by HarshKhandeparkar** [comment]
I remember I had fixed this nonsense when I added GIFs for the first time.
Maybe dome other PR broke it. Anyway. All you have to do to fix this is to
not edit the initial `options.size` make the options immutable and just use
the value. Pretty simple.

**Comment by root00198** [comment]
@blurry-x-face the test written in #1530 is correct. That is why it's failing... Once this PR gets merged, it will pass itself.

**Comment by root00198** [comment]
@publiclab/is-reviewers @jywarren @HarshKhandeparkar SOMETHING IS BROKE, npm test is failing in like 30 tests.

**Comment by root00198** [comment]
found it, #1533 changed the PixelManipulation.js, that's the issue....Maybe consider reverting back the PR....

**Comment by jywarren** [comment]
Ah, thanks for being careful here, is this resolved? 

> found it, #1533 changed the PixelManipulation.js, that's the issue....Maybe consider reverting back the PR....

**Comment by root00198** [comment]
Nope, The modules test are still failing....

**Comment by root00198** [comment]
@jywarren can we merge this and #1530 today?

**Comment by jywarren** [comment]
Great, sorry for slow review here, just waiting for last checks and will merge this then look at #1530!

**Comment by jywarren** [comment]
Perfect! Thank you!

**Pull request merged**
