### PR TITLE
Added doc for grid-overlay

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@jywarren just added the doc for the grid overlay module.

**Comment by Harshithpabbati** [comment]
@jywarren was this ok???

**Comment by jywarren** [comment]
Thank you @Harshithpabbati !!!!

Hey, if you're interested, we have some bugs we'd like to resolve in https://github.com/publiclab/image-sequencer/issues/987 and https://github.com/publiclab/image-sequencer/issues/979, that I thought you might have an insight on? Thank you!!

**Comment by Harshithpabbati** [comment]
Sure @jywarren i will work on it once i completed the surge. As it is important one :smile:

**Pull request merged**
