### PR TITLE
Benchmarks

### PR DESCRIPTION
**Pull request by tech4GT**

### CODE REVIEW

**Comment by jywarren** [comment]
Wow great!!!

```
    ############ Benchmarks ############
    Module average ran in: 83 milliseconds
    Module blend ran in: 72 milliseconds
    Module blur ran in: 442 milliseconds
    Module brightness ran in: 33 milliseconds
    Module channel ran in: 34 milliseconds
    Module colorbar ran in: 141 milliseconds
    Module colormap ran in: 279 milliseconds
    Module contrast ran in: 181 milliseconds
    Module convolution ran in: 270 milliseconds
    Module crop ran in: 35 milliseconds
    Module decode-qr ran in: 106 milliseconds
    Module dither ran in: 41 milliseconds
    Module draw-rectangle ran in: 50 milliseconds
    Module dynamic ran in: 80 milliseconds
    Module edge-detect ran in: 2690 milliseconds
    Module fisheye-gl ran in: 0 milliseconds
    Module histogram ran in: 107 milliseconds
    Module gamma-correction ran in: 47 milliseconds
    Module gradient ran in: 48 milliseconds
    Module import-image ran in: 0 milliseconds
    Module invert ran in: 48 milliseconds
    Module ndvi ran in: 49 milliseconds
    ndvi
    {}
    colormap
    {}
    Module ndvi-colormap ran in: 349 milliseconds
    Module paint-bucket ran in: 417 milliseconds
    Module overlay ran in: 193 milliseconds
    Module resize ran in: 221 milliseconds
    Module rotate ran in: 242 milliseconds
    Module saturation ran in: 194 milliseconds
    Module threshold ran in: 156 milliseconds
    Module tint ran in: 192 milliseconds
    Module white-balance ran in: 187 milliseconds
    ####################################
```

**Comment by tech4GT** [comment]
Yeah! We just have one small issue that expanding meta modules break this, but since we are ending support to that this should be fine :)

**Comment by tech4GT** [comment]
@jywarren Should we merge this?

**Comment by jywarren** [comment]
Ah ok so the only issue is that this doesn't run each step against the original image, but against the output of the previous step. While that makes sense for regular processing, we need to run all benchmarks against the same image or there may be variations. Think about if things run after crop, all following steps will run faster. 

It's not a big deal because we're going to track changes in runtime against the previous run of that step, but I think it's probably worth being able to compare between steps too. Could we insert an importImage step between each time to refetch the original image src?

**Comment by tech4GT** [comment]
Actually @jywarren ImportImage is not working in node context since it uses `new Image()` which is not supported in node.

**Comment by tech4GT** [comment]
Okay let me look at a workaround here :)

**Comment by jywarren** [comment]
And hmm, it seems like we should be able to run import image off of browser mode, right, to pull in a new image?

**Comment by jywarren** [comment]
Ah ah you're right. Ok...

**Comment by tech4GT** [comment]
Yeah but let's solve that in another PR?

**Comment by jywarren** [comment]
Yep agreed. There must be another way here.

**Comment by tech4GT** [comment]
@jywarren The problem here is that blend cannot run without prior steps and future modules might not as well, for example some module might use an image with offset -2. We won't be able to handle that if we run one steps at a time.

**Comment by jywarren** [comment]
Can we load a standard initial step, like brightness, so we do brightness
crop reset brightness blend reset brightness saturation reset...

What do you think?

**Comment by tech4GT** [comment]
@jywarren I found a way I think!

**Comment by jywarren** [comment]
Very nice!! Ready to merge then? Great work!

I did notice a weird error here dunno if it's related:

https://travis-ci.org/publiclab/image-sequencer/jobs/494228325#L1755

If unrelated, go ahead and merge! Great work Varun!!! 🙌🏽

**Comment by tech4GT** [comment]
That's actually some error in some node_module! Might be a version mismatch, but our code is fine! :)

**Pull request merged**
