### PR TITLE
Revived Crop Module

### PR DESCRIPTION
**Pull request by ccpandhare**
## What this PR contains
Hello!
I have revived my first module, the crop module!
## Usage
```js
sequencer.loadImages('PATH_TO_IMAGE').addSteps('crop',options);
```
### Where:
Crop Manual
* `options.x` is the x-offset of the crop from the left
* `options.y` is the y-offset of the crop from the top
* `options.w` is the width of the resultant crop
* `options.h` is the height of the resultant crop

### Defaults:
`options.x` : 0
`options.y` : 0
`options.w` : half of image width
`options.h` : half of image height

### CODE REVIEW

**Comment by ccpandhare** [comment]
I remember, @jywarren, you were mentioning of a 'crop' test which checks final dimensions of image. I shall add that soon, now that I have the crop module in place.

**Comment by jywarren** [comment]
Super. Maybe we need a new page called docs/modules.md to include this
great picture? :-)

**Comment by ccpandhare** [comment]
That's not a bad Idea... We need to maintain a documentation for modules anyways.
But I think that should go separately. Should this be merged? Or should I make the documentations of all modules first?

**Comment by jywarren** [comment]
Sure, separately is fine! Merge!

**Pull request merged**
