### PR TITLE
autocomment bot to call @publiclab/is-reviewers.

### LINKED ISSUE #844: Bot to call publiclab/is-reviewers after sending the pull request.
### A bot which helps to call reviewers team when we sent a pr.

 So we just don't need to call reviewers team

Check [this](https://probot.github.io/apps/delete-merged-branch/) out for reference.

### PR DESCRIPTION
**Pull request by harshithpabbati**
Fixes #844 
#903 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers @jywarren see this.

**Comment by Harshithpabbati** [comment]
@jywarren need to install this it is a probot
https://probot.github.io/apps/auto-comment/

**Comment by Harshithpabbati** [comment]
@jywarren see this you need to configure this
https://probot.github.io/apps/auto-comment/

**Comment by jywarren** [comment]
Hi @Harshithpabbati -- this looks really nice! But does it do what our welcomebot config already does? 

https://github.com/publiclab/image-sequencer/blob/ddea283ce55cacfffd032985879845a95b924d75/.github/config.yml

**Comment by jywarren** [comment]
oh let me read the issue...

**Comment by jywarren** [comment]
Oh is this able to mention reviewers where welcomebot was not?

**Comment by Harshithpabbati** [comment]
May be this can be done when we add the bot as a member. I guess. Can we do that??

**Comment by HarshKhandeparkar** [comment]
Seems like bots cannot mention teams

**Pull request closed without merging**
