### PR TITLE
grid of thumbnail previews

### LINKED ISSUE #247: grid of thumbnails showing step options in addStep ui
We could generate a tiny thumbnail of the final image and run 5 or so of the most popular or useful modules, showing very low res previews of what they'd look like. Sort of like in Instagram!

(Low priority but fun, also dependent on a scale module)

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes #247

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

I've been looking into the documentation for generating a preview of the current image with a saturation layer. I've currently just created a new sequencer object, so this is still work in progress. Help from @publiclab/image-sequencer-guides would be really appreciated!

### CODE REVIEW

**Comment by jywarren** [comment]
Ooh cool - any screenshots? Thanks!

**Comment by JonathanXu1** [comment]
There's no change in the frontend except a red square to mark the div where I'm trying to insert images. Still don't know how to do this with the sequencer though.
image

**Comment by jywarren** [comment]
ah, sorry - try passing the output of the final step to a new Sequencer
instance, following the README --
https://github.com/publiclab/image-sequencer/#quick-usage

I'll circle back tomorrow if you are still stuck, or perhaps you can ask
(@)tech4gt for help. Thanks!

**Comment by tech4GT** [comment]
@jywarren @JonathanXu1 Can you guys fill me in here? Do we close this one?

**Comment by jywarren** [comment]
I believe this was resolved through a collaborative effort in another PR! #539 maybe?

**Comment by jywarren** [comment]
Yep! Closing :-)

**Pull request closed without merging**
