### PR TITLE
skip-writing-defaults

### LINKED ISSUE #281: Skip writing defaults into toString
So if the step settings match the defaults, let's not write them into the `toString` output. That way we can keep it pretty short. 

For example in https://publiclab.github.io/image-sequencer/examples/#steps=import-image,blend,ndvi,colormap

Now we have #278 fixed, when you click that, it correctly loads all the steps, BUT the URL quickly gets really long due to the defaults getting saved into it. It's great that the URL writing is working, but we can skip any settings which are already the defaults, and then the URL can stay a bit shorter. 

This isn't the most important thing but it's really helpful and convenient!

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #281

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
This is what the job log is showing:
/home/travis/build/publiclab/image-sequencer/src/Run.js:79
      var prevstep = ref.images[image].steps[json_q[image] - 1];
                                      ^
TypeError: Cannot read property 'steps' of undefined

I will try to solve it!

**Comment by jywarren** [comment]
Got stuck or need help? Thanks @Mridul97 !!

**Comment by Mridul97** [comment]
@jywarren actually my semester exams are going on, I will try to solve it soon!

**Comment by tech4GT** [comment]
Awesome!! Sorry @Mridul97 Some health issues came up, were you able to modify the tests? Let me know if you need any help! :smile:

**Comment by Mridul97** [comment]
@tech4GT I didn't modify the tests. Could you please tell what exactly do I have to modify in tests? :smile:

**Comment by tech4GT** [comment]
Oh the thing is that there are some tests based on strings which need to change :)

**Comment by Mridul97** [comment]
@jywarren @tech4GT I solved the errors but when I tried to rebase the branch there were large number of merge conflicts in dist/image-sequencer.js and dist/image-sequencer.min.js So I created a another PR #497 Please have a look! Closing this one now!

**Pull request closed without merging**
