### PR TITLE
removed typos as mentioned in issue #408

### PR DESCRIPTION
**Pull request by sagarwala**

### CODE REVIEW

**Comment by jywarren** [comment]
👍 🎉 Thank you!!!

**Comment by jywarren** [comment]
Varun, are you able to merge to the `gh-pages` branch and push to `publiclab:gh-pages`? I think you ought to be able to. I usually:

1. pull the latest main branch
2. switch to my local `gh-pages` branch
3. merge from master branch
4. run `npm install` if there were any new npm dependencies added
5. `git push` to `publiclab:gh-pages`
6. test it out to be sure at https://sequencer.publiclab.org (new url!)
7. if it works, I then often publish a new version with `npm publish` if there was a version increase. 

@sagarpreet-chadha perhaps you could do the same for `leaflet-environmental-layers` since you wrote it? 

I'll check but both of you ought to have the rights to do this. I think @ryzokuken has a lot of experience in npm versioning and publishing also, in case you have questions!

**Comment by tech4GT** [comment]
@jywarren I think I'm not a collaborator on npm, I'll need that to publish, right?

**Comment by tech4GT** [comment]
@jywarren I have pushed to gh-pages, please have a look!

**Comment by tech4GT** [comment]
Also, should we increase version?

**Comment by jywarren** [comment]
Yes, oh, did I add you since this message? Yes lets bump version again?

**Comment by tech4GT** [comment]
OK! I'll publish all the new changes on gh-pages and increase a minor version! Thanks!

**Comment by tech4GT** [comment]
I don't think I'm added on npm.

**Comment by tech4GT** [comment]
Yes

**Comment by jywarren** [comment]
Ah, i've added you!

**Pull request merged**
