### PR TITLE
Fixed Setup Script Typo

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #0000  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
This could fix a lot of installation issues that people have been facing.

**Comment by HarshKhandeparkar** [comment]
@jywarren

**Comment by jywarren** [comment]
Can you explain what happens? Looks good to me, but want to be careful!

**Comment by HarshKhandeparkar** [comment]
We want to run grunt build after the installation is complete. Also `$$` is
a typo.

**Pull request merged**
