### PR TITLE
mobile-view issue solved

### PR DESCRIPTION
**Pull request by AmanGarg97**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@AmanGarg97 welocme and thanks for your first pr :tada: . A few suggestions:
1. You can remove the #[add issue number here] and replace it with issue link.

2. Also you can ask @publiclab/is-reviewers for review next time.

Thanks!!

**Comment by HarshKhandeparkar** [comment]
Also please provide a screenshot/GIF

**Comment by HarshKhandeparkar** [comment]
@AmanGarg97 please merge the branch with `main` and rebase. Thanks!

**Comment by AmanGarg97** [comment]
Hey @HarshKhandeparkar 
Thanks for the information , I will follow these.
Attached the screenshot below , Do let me know for any other requirements.
screenshot from 2019-01-13 11-36-51

Thanks

**Comment by AmanGarg97** [comment]
Hey @HarshKhandeparkar
Thanks for the information , I will follow these.
Attached the screenshot below , Do let me know for any other requirements.

screenshot from 2019-01-16 23-00-08

**Comment by HarshKhandeparkar** [comment]
@AmanGarg97 please fix the conflicts. Thanks.

**Comment by HarshKhandeparkar** [comment]
Also please run `grunt serve` and upload the `dist/image-sequencer-ui.js` and `dist/image-sequencer-ui.min.js` files.

**Comment by AmanGarg97** [comment]
Hi I was trying to resolve the given conflicts but I am not able to get through it.
Could you please help for that?
Thanks!

**Comment by HarshKhandeparkar** [comment]
@AmanGarg97 you can `git merge upstream/main` and resolve the conflicte manually in a code editor. The conflict marker will be added to the files automatically and the editor will understand that. After resolving conflicts, you can push the changes.

**Comment by AmanGarg97** [comment]
Hey @HarshKhandeparkar  thanks for the help. I have followed the step of resolving conflicts.
Is there anything else to be done?
Thanks!

**Comment by HarshKhandeparkar** [comment]
@AmanGarg97 it seems like you have kept the marker as it is and commited it. What you should do instead is combine the incoming change from `upstream/main` with the changes that you have made and do it in such a way that everything works fine and both the changes are implemented.  Please remove the marker and combine the changes and commit the result. Please ask here if you need any assistance 😊

**Comment by HarshKhandeparkar** [comment]
Oh wait I guess I had seen something else before maybe? There is no marker there now. Sorry for the inconvenience but I had seen the marker somewhere. Maybe in the commit but the changes look good.

**Comment by HarshKhandeparkar** [comment]
@AmanGarg97 there is no need to upload dist/image-sequencer.js if you have not touched the source code of the library.

**Comment by HarshKhandeparkar** [comment]
@jywarren please have a look at this as the package-lock.json file has changed and I don't know what to do. The rest of the changes look good to me.

**Comment by HarshKhandeparkar** [comment]
I don't know if the files are going to cause any problem so please have a look at this. Otherwise it is ready to merge. Thanks @AmanGarg97 :tada:

**Comment by gauravano** [comment]
Hi all, as reported here- https://github.com/publiclab/image-sequencer/issues/484#issuecomment-457890905, the issue is solved as part of some other PR, so closing this PR. Thank you so much @AmanGarg97 for your work here.

**Comment by jywarren** [comment]
Also, I'm sorry I missed this! In general however, if we've added to package.json we can regenerate the package-lock.json, but if not we better do updates in a separate PR, kind of like how dependabot does it!

**Pull request closed without merging**
