### PR TITLE
Support External Images

### PR DESCRIPTION
**Pull request by ccpandhare**
Now browsers can load in external images onto the sequencer (or local ones) using just the path of the file. Earlier, it was required to provide a DataURL to Image Sequencer.

This can be done as long as CORS Restrictions aren't violated.

Should this be done via XMLHttpRequest? I don't see the benefit of doing that actually.

Discussion started in #78

### CODE REVIEW

**Comment by jywarren** [comment]
Can you add a README docs and inline code example demonstrating this?

**Comment by ccpandhare** [comment]
Suppose this is my file directory:

```
.
├── index.html
├── images
│   └── image.jpg
└── js
    └── image-sequencer.js
```

And now in `index.html` we can directly do the following, as far as CORS Restrictions don't dome into picture:

```
sequencer.loadImage('images/image.jpg');
sequencer.loadImage('http://domain/path/file.jpg');
```

I shall add a short explanation to README.md too

**Comment by jywarren** [comment]
this is great documentation, thanks!

On Wed, Jul 26, 2017 at 11:05 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
I have updated the README.

While we are at this, Should Image Sequencer allow Users on Node.js to directly load images from a URL?

**Comment by jywarren** [comment]
yes!

**Comment by ccpandhare** [comment]
Done that. Some notes here:

* Since images from URLs or large sized images take time to load, I have made it compulsary for loadImages(), loadImage() to get a callback. It can not be chained like before (all other method chainings are intact).
    
    This no longer works:
    
    ```js
    sequencer.loadImage(URL).addSteps('step-name')
    ```
    This is how it is now:
    
    ```js
    sequencer.loadImage(URL,function(){
        this.addSteps('step-name').run();
    ```
* Images can be loaded directly from a URL now, like this:
    
    ```js
    sequencer.loadImage('https://domain/path/to/image.png');
    ```
    The URL need not end in `.jpg` or `.png`. Any URL which returns a header with `content-type: image/FORMAT` will work.
* I have documented all this in README.md
* I have written a Unit Test to confirm this new feature works as expected.

**Comment by jywarren** [comment]
Looks great! merge if you like, bump minor version number in keeping with SemVer - (new features). 

Do data URLs still work synchronously? If not, and the callback is now required, that's a breaking API change, so we should release a `v1.0.0` -- a major version bump. See semver.org for explanation! :-) this is great though!

**Comment by ccpandhare** [comment]
Thanks for all the kind words :-)

No, DataURLs don't work synchronously now because large DataURLs will cause a problem and can trigger `addSteps` before the image loads leading to a `ReferenceError`.

So do we call this a major update? We're still working on basic stuff, and specifications might change relatively rapidly, so maybe let's just wait for publishing a new version... What do you think about this? If we don't publish it it, we don't have to bump the version right?

Sorry if I am being naïve here, I haven't handled versions before. These are just my thoughts...

**Comment by jywarren** [comment]
It's ok to bump the version number, in semver it's just a means of
communication to users and we don't have any yet!

**Comment by ccpandhare** [comment]
Yep! Okay!
Merging!

**Pull request merged**
