### PR TITLE
Use browserify for ui js files and refactor ui js files

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
@jywarren please review this!

**Comment by jywarren** [comment]
This looks great. I'd love a review from someone else in @publiclab/is-reviewers too!

**Comment by jywarren** [comment]
Really good work here. This'll let us write UI tests!

**Comment by Mridul97** [comment]
Yes, I will like to write UI tests once this gets merged! :smile:

**Comment by jywarren** [comment]
Have you tested out the UI pretty thoroughly? Also, how shall we merge this with the toggle PR... Which first?

**Comment by Mridul97** [comment]
Let's merge the toggle PR first, I will test the ui more and then rebase it! :)

**Comment by Mridul97** [comment]
@jywarren I have rebased the branch! I think we should add the ui js files in watch so that the webpage updates for changes in ui js files!

**Comment by Mridul97** [comment]
> @jywarren @Mridul97 how about breaking up demo.js into different files.

Nice idea! This would increase the code readability and help in code organisation!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 will this change affect the servoce worker?

**Comment by Mridul97** [comment]
> @Mridul97 will this change affect the servoce worker?

I don't think so!

**Comment by HarshKhandeparkar** [comment]
Will the cached files have to be changed?

**Comment by HarshKhandeparkar** [comment]
Does `localhost:3000` work offline?

**Comment by Mridul97** [comment]
> Will the cached files have to be changed?

Yes, cached files will have to be changed if any change is made in any of the ui files!

**Comment by Mridul97** [comment]
@jywarren Please have a look at this! I think it is ready to be merged!

**Pull request merged**
