### PR TITLE
Improved Docs, Chainable Methods

### PR DESCRIPTION
**Pull request by ccpandhare**
### Documentation has been updated. (Issues #39, #41)

* The concept of multiple images has been explained in a separate section
* TravisCI build information is now of publiclab:master instead of jywarren:master
* Return Value of functions specified

### Return Value (Issue #40)

* addSteps, loadImages, loadImage, removeSteps, insertSteps now return the sequencer. This enables chaining of methods.

### Single Image Usage

* Now `loadImage` exists too. And supporting #39 and #40, now `loadImages` can be called without giving names to an image. the image is given the name "default" by default.

### CODE REVIEW

**Comment by jywarren** [comment]
Looks great! go ahead and merge! 🎈

**Comment by ccpandhare** [comment]
Why are we having this issue of builds failing sometimes and the same builds passing later on TravisCI? Do you know what can be done about this?

**Comment by jywarren** [comment]
Sometimes there's a timeout in the upstream libraries. There is a way to cache these if you find it's causing you a lot of trouble!

**Comment by ccpandhare** [comment]
I did a small search about this.
We have tests in multiple files.
The message TAPE gives is "test exited without ending"
This is known to happen if the tests of one file complete before the other file has loaded.
This was fixed in Tape v4.7.0
Image Sequencer's package.json says:
```json
"tape": "^3.5.0",
```

Changing this to 
```json
"tape":">=4.7.0"
```
might work

**Comment by jywarren** [comment]
give it a try!

**Comment by ccpandhare** [comment]
That did the trick!
This won't happen again.

**Pull request merged**
