### PR TITLE
Sliders added

### LINKED ISSUE #588: Provide sliders for modules
### Provide sliders for contrast , rotate , saturation and edge-detect module.
This is a sub-issue of #487.

### where to look

http://sequencer.publiclab.org...

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #588 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by aashna27** [comment]
@jywarren please have a look.

**Comment by jywarren** [comment]
Looks awesome! I'm going to build, rebase and merge.

**Comment by aashna27** [comment]
> Looks awesome! I'm going to build, rebase and merge.

Thanks a lot @jywarren

**Comment by jywarren** [comment]
OK, i made a few more small default settings tweaks I thought I could sneak in here since I've been doing so much rebuilding! If this all passes, we should be good to go and I'll merge.

**Comment by jywarren** [comment]
Whew! Finally done! Thank you!!!! 👍

**Comment by aashna27** [comment]
Thanks so much for all the building trouble. 😃

**Pull request merged**
