### PR TITLE
createMetaModule generator

### LINKED ISSUE #200: "Meta" modules -- modules made of other sequences of modules
If someone composes a sequence and tweaks the settings, they have a process which is really useful. 

And if we can concisely store that in the URL itself, then they can share that workflow (sequence + settings) with other people, or bookmark it, and we don't have to use a database to save it. We do this now, though we don't save the settings, just the sequence:

https://publiclab.github.io/image-sequencer/examples/#steps=invert,crop

(@ccpandhare -- i think we had a partial implementation of settings, do you remember? Ah -- https://github.com/publiclab/image-sequencer/issues/127)

We wouldn't save images, just the workflow itself. But we might want to start collecting these too -- they could in theory become "meta modules" with names of their own. Maybe that's a feature in its own right?

Another aspect of this is that if we have a consistent string-based way to save a sequence and its settings, that's a good format to use for remote REST commands down the road when we decide to do that -- #198 -- and also we could base a "meta module" system around such a string. 

> A meta module could be a module which contains a string describing a set of modules and their configurations, that can itself be re-used. 

Meta, but very powerful!

We could even, if the UI is good enough, have this prompt people to save their sequences as a module -- to propose a module based on the current state of their sequencer! This could help with #190 as well.

### LINKED ISSUE #315: Non-expanding, fully opaque meta modules
The new meta modules is very powerful! You can select one like `NDVI-Colormap`, and it expands to:

https://publiclab.github.io/image-sequencer/examples/#steps=ndvi(filter:red),colormap(colormap:default)

But, right now, if you want to use a meta module like `NDVI-Colormap`, you can't just use it in a string like:

https://publiclab.github.io/image-sequencer/examples/#steps=ndvi-colormap

`Module NDVI-Colormap not found.`

A modification of meta-modules would be great, where:

1. they are, to all external appearances, just normal modules that don't expand
2. they contain other modules, but 'secretly' -- i.e. they run a mini-sequencer inside themselves, so they simply accept an incoming image, and produce an output image, and act in every way like a normal module
3. they would remain shown as a single step, permanently

Then you could modify the internals of a meta module -- say, to optimize it -- and nobody would ever know!

@tech4GT this may be too much to accomplish before the end of SoC, but I'm interested to hear your thoughts!

### PR DESCRIPTION
**Pull request by tech4GT**
Builds up on #765 , fixes #200, fixes #315

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren So dow we want to support expanding meta modules? I say let's just stop supporting that API entirely and move all meta modules to this new architecture, what do you think?

**Comment by tech4GT** [comment]
Also I am returning the complete module from `createMetaModule` so if the function is called from node context by a user like `image-sequencer-app` we can the load it directly by passing it to the loadNewModule

**Comment by jywarren** [comment]
Oh, yes, that sounds right on both counts. Thanks Varun!!

**Comment by tech4GT** [comment]
@jywarren Should I open a new pr removing the boilerplate code from modules or should we do it here itself?

**Comment by jywarren** [comment]
Well, it demonstrates how to set defaults and how to map inputs to the
internal modules, so I think it's a good example. We might also show what
happens if you don't supply a map function. For example what if there are
two internal brightness steps? What appears externally as the parameters
you can set in the UI?

**Comment by tech4GT** [comment]
Hmm, I think we would need to make some changes to support 2 brightness modules with different inputs, since there can be only one value of `options.brightness`

**Comment by tech4GT** [comment]
Maybe we can allow for making the value of an input an array, then this will be passed inside options to the module and the module can then use them as it needs?
```js
// for example
module.exports = require('../../util/createMetaModule.js')(
  function mapFunction(options) {

    // return steps with options:
    return [
      { 'name': 'brightness', 'options': { 'brightness': options.brightness[0] } },
      { 'name': 'brightness', 'options': { 'brightness': options.brightness[1] } }
    ];
  }, {
    infoJson: require('./info.json')
  }
)[0];
```

**Comment by jywarren** [comment]
Well, let's just document that both will get the same values unless
specified in the map function? We can demonstrate this with a test.

**Comment by tech4GT** [comment]
@jywarren Actually what I am suggesting is that the infoJson of the module can define the attribute as an array and give it's default value as an array, since all the generator function is doing is getting the values from infoJson, it will work.
What we would have do do here is add support for array type inputs in sequencer UI and this should be ready to go as it is!

**Comment by tech4GT** [comment]
I'll demonstrate with an example, so I know my meta-module calls the brightness module 2 times, I can define it as an array in my infoJSON
```js
{
 "inputs":
          {
"brightness": {
            "type": "array",
            "desc": "",
            "default": ["2","3"],
        }
          }
}
```

**Comment by tech4GT** [comment]
I'll get this array in my options argument of the map function and I can use it as required, so we don't need that boilerplate code still.
One more thing we can Allow this like a string too!
We can then split the input on space if the type is array, this will simplify things even further.
I'll go ahead and implement this right now, maybe It'll clearer to see it in action! :)

**Comment by jywarren** [comment]
Hmm, it makes sense but it's a bit strange to use array order in one module
to set a param in the order of steps... You know? Like what if there are
lots of mixed modules inside, it'd be really tough to keep track. Also what
does the UI display for the inputs for an array of values?

I like the idea of infojson being used to set the defaults (although the
map function would still determine which external values are assigned to
internal ones most clearly). But shouldn't it set the defaults of the
externally exposed parameters only, so the module doesn't expose any of
it's internals to the outside? The defaults of the internal modules would
(if they're different than their already existing defaults) need to be set
internally, so the map function still makes sense there, I think. How does
this sound?

**Comment by tech4GT** [comment]
Hmm, I think you are right, So let's keep the map function to allow customized mapping but still set the defaults in the create function itself, so the module just gets a list of values and can consume them whichever way it chooses to.
The UI can just display a string input which we can split on spaces.
How does that sound?

**Comment by jywarren** [comment]
Awesome. We may come up with better ideas soon but this is a good starting
point. Thanks!

**Comment by tech4GT** [comment]
@jywarren On second though maybe we should leave it up to the module how it wants to consume multi-value inputs like you originally suggested. We can add a section about this in the documentation with an example using space separated values like we do for convolution, but basically the input type will be string.(They can use whatever delimiter they want).
How does that sound?

**Comment by jywarren** [comment]
This sounds great. Thanks Varun!

**Comment by tech4GT** [comment]
Okay updating the docs now! We can then merge yay! :tada:

**Comment by jywarren** [comment]
🎉🎉🎉

**Comment by tech4GT** [comment]
@jywarren Please have a look at the docs, if we need to add something.
Let's also update a major version after this update since it breaks the old metaModule API

**Comment by tech4GT** [comment]
Okay the test pass, docs are ready. Merging this in now! Awesome!

**Pull request merged**
