### PR TITLE
ImportImage

### LINKED ISSUE #233: Add an "import image" module
A module that fetches a remote image via URL (or data URL) and overlays it on the canvas (at a given `x, y, w, h` ?)

Based on the initial load image code:

https://github.com/publiclab/image-sequencer/blob/master/src/ui/LoadImage.js

Plus the UI code from the demo for selecting an image: https://github.com/publiclab/image-sequencer/blob/master/examples/lib/imageSelection.js

This should allow selecting a 2nd image, and overlaying it over the first. 

Later, we could offer "blend modes" between the previous image and the new one we're overlaying, pending access to earlier steps' image outputs.

### PR DESCRIPTION
**Pull request by tech4GT**
fixes #233

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren I think this is ready😁

**Comment by jywarren** [comment]
Yep!!!!!

**Comment by jywarren** [comment]
Let's bump the version number in package.json by a minor version number - `v0.x.0` -- ok? Once we implement the full Step API, we may want to bump a major version number, update the docs, and tell people not to use the old way of writing modules with the various output steps currently in the docs. (copying this also to #242 )

**Comment by tech4GT** [comment]
@jywarren Yeah that makes sense

**Comment by jywarren** [comment]
image

AWESOMEEEEEEEEE 🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by MayankKashyap** [comment]
Awesome work @tech4GT

**Pull request merged**
