### PR TITLE
[WIP] Matcher core integration

### PR DESCRIPTION
**Pull request by rexagod**
cc @jywarren

### CODE REVIEW

**Comment by rexagod** [comment]
``
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/publiclab/matcher-core.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-08-08T00_25_49_592Z-debug.log
The command "npm install" failed and exited with 1 during .
``

**Comment by rexagod** [comment]
Communicating with @HarshKhandeparkar to get this one ready.

**Comment by rexagod** [comment]
@HarshKhandeparkar I still can't build IS for some reason. I mean, the "new" build won't show up. It's the same old build everytime. I've saved and ran every grunt command individually with no luck whatsoever. Have you encountered something like this before, or do you believe it's some permission issue on my machine preventing this?

**Comment by HarshKhandeparkar** [comment]
I have encountered permission issues before but never this specific issue.
Try changing permissions. Try 777 directly.

**Comment by rexagod** [comment]
Still the same problem, Harsh. Let me run this on ubuntu. Maybe Arch has a restricted shell env that's preventing me from this?

**Comment by HarshKhandeparkar** [comment]
I haven't used arch much. Yes, try ubuntu. Does travis work though?

**Comment by jywarren** [comment]
Hi @rexagod -- any progress here? Thanks!

**Comment by rexagod** [comment]
Sorry for the delay, Jeff. I was a bit occupied in finishing up the docs for the gsoc evaluation url. 

Working.

**Comment by jywarren** [comment]
Thanks!

**Comment by rexagod** [comment]
@jywarren @publiclab/is-reviewers Is there any other module in this lib that employs asynchronity (async/await) to work? Something like the sample below? Note that this is just a representation and not the final code since that'll obviously be a lot more cleaner, but this one's just to explain better.

```js
    async function changePixel(r, g, b, a, x, y) {

      async function asf() {
        new Matcher(
          "examples/images/small.jpg",
          "examples/images/big.jpg",
          async function(q) {
            var res = await q;
            this.results = res.points;
          }
        );
      }

      asf().then(function(points){

        for (var i = 0; i < 500; i++) {
          if (
            Math.abs(points[i].x - x) <= 10 &&
            Math.abs(points[i].y - y) <= 10
          ) {
            return [0, 255, 0];
          }
        }

        var rgba = [r, g, b, a];
        this.rgba = rgba;
      });

      return await this.rgba;
      
    }
```

**Comment by rexagod** [comment]
For some reason making `changePixels` async makes chrome run out of memory?

**Comment by jywarren** [comment]
I don't believe we use await but @aashna27 @HarshKhandeparkar @Divy123 may
know better than I.

**Comment by rexagod** [comment]
@jywarren I've managed to get the points in the module namespace but for some reason the `output` function is now undefined?

image

Code is @ https://github.com/rexagod/image-sequencer/blob/e0025c1faa175420145547e226e5c0186c6d6cb5/src/modules/Matcher/Module.js#L27

**Comment by rexagod** [comment]
The points are being fetched. No bugs there.

image

**Comment by rexagod** [comment]
@HarshKhandeparkar @Divy123 @aashna27 Any ideas why this could be happening?

**Pull request closed without merging**
