### PR TITLE
Add spinner while gif is generating

### LINKED ISSUE #516: Show spinner icon while gif is generating
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

After clicking on "View GIF" while Gif is generating we can not see spinner icon. 
image

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [examples/demo.js](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.js) in the image-sequencer repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a -) which lines to remove, and in green (and a +) which lines to add:
```DIFF
$('.js-view-as-gif').on('click', function(event) {
    // Prevent user from triggering generation multiple times
    if (isWorkingOnGifGeneration) return;

    isWorkingOnGifGeneration = true;

    var button = event.target;
    button.disabled = true;
+   button.innerHTML='<i class="fa fa-circle-o-notch fa-spin"></i>'

...

          button.disabled = false;
+         button.innerHTML='View GIF';
          isWorkingOnGifGeneration = false;
        }
      });
    }
    catch(e) {
      console.error(e);
      button.disabled = false;
+     button.innerHTML = 'View GIF';
      isWorkingOnGifGeneration = false;

    }
  });
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by lohitha02**
Fixes #516

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Please provide a GIF. Thanks.

**Comment by HarshKhandeparkar** [comment]
Also please rebase

**Comment by lohitha02** [comment]
Screenshot from 2019-03-09 20-00-07

**Comment by HarshKhandeparkar** [comment]
Can this also add a text beside the spinner ? Something like 'Generating' or 'Generating GIF'?

**Comment by lohitha02** [comment]
It is not for generating GIF it's for viewing GIF

**Comment by HarshKhandeparkar** [comment]
My question was can you add a text like 'generating GIF' besides the
spinner to notify that the GIF is still being generated and will be
available for viewing soon?

**Comment by lohitha02** [comment]
Yes we can add it. If it is needed

**Comment by HarshKhandeparkar** [comment]
Do you think that will look good? Or is it good as it is?

**Comment by lohitha02** [comment]
I think it looks good as it is.

**Comment by HarshKhandeparkar** [comment]
Cool, please rebase though.

**Pull request closed without merging**
