### PR TITLE
Add ui tests to .travis.yml

### PR DESCRIPTION
**Pull request by jywarren**
Re: #740

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@jywarren I think `npm run test-ui` would work

**Comment by VibhorCodecianGupta** [comment]
Hmm still failing. Looking into it.

**Comment by jywarren** [comment]
Hmm, any ideas here?

**Comment by VibhorCodecianGupta** [comment]
@jywarren solved and merged in #791

**Comment by jywarren** [comment]
Oh yeah I had thought so. Thanks!

**Pull request closed without merging**
