### PR TITLE
fixes add-QR and color-picker in draw-rectangle,grid-overlay

### LINKED ISSUE #1247: Bugs in AddQR,Draw-rectangle,Grid-overlay after #1188
- [x] AddQR is not working as expected 
Screenshot from 2019-09-04 13-45-19

- [x] Color-picker is not working in Draw-Rectangle
Screenshot from 2019-09-04 22-44-25

- [x] Color-picker is not working in Grid-overlay
Screenshot from 2019-09-04 22-51-22

These modules are working fine with beta version.These bugs occurred after merging PR #1188 
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #1247 
draw-rectangle after changes
Screenshot from 2019-09-07 00-14-03
grid-overlay after changes
Screenshot from 2019-09-07 00-13-01
add-qr after changes
Screenshot from 2019-09-07 00-11-46

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
cc: @jywarren @HarshKhandeparkar

**Comment by keshav234156** [comment]
@HarshKhandeparkar by mistake pressed re-review  button.can you please approve it again
Sorry  for the inconvenience caused.

**Comment by aashna27** [comment]
Sorry for the mistakes! This is correct, also can you also check for other modules. I ll share the pr link which had the pixel setter, please verify if the changes made for modules work with them.https://github.com/publiclab/image-sequencer/pull/1188 Thanks

**Comment by keshav234156** [comment]
Have already checked it.They are working as expected.

**Comment by keshav234156** [comment]
@jywarren i think it's good to merge.

**Comment by jywarren** [comment]
Great, thanks all! 🎉

**Pull request merged**
