### PR TITLE
Added removeStep() functionality

### PR DESCRIPTION
**Pull request by ccpandhare**
## The Function removeStep
```
  function removeStep (id) {
    for (i=0;i<steps.length;i++) {
      if (steps[i].options.id == id && steps[i].options.name != 'image-select'){
        console.log('removing step "'+steps[i].options.name+'"');
        if (options.inBrowser) $('div#sequencer-'+id).remove();
        steps.splice(i,1);
        run(options.initialImage);
      }
    }
  }
```

## Parameters
It accepts a parameter `id` which is the uniqueID of the step (This is with respect to the sequential uniqueID system I implemented in addition to the one in `/src/userInterface.js`, we still have to decide whether to use a sequential or random one.) This is a draft and hence, open to discussion.

## Action
Resultingly, the step is removed from the array `sequencer.steps`. And so is the HTML UI for that step.
Then `sequencer.run()` is called so that the steps after  the removed step get the correct *new* input image, not the previous one.

## Notes and Explanation
In `UserInterface.js`, I added a button 'Remove Step'. Also I gave the main parent DIV an id of 'sequencer-$id' where $id is the sequential ID of that step. The 'Remove Step' has an `onclick` attached to it. This was a problem as from outside, as `removeStep` must be called from outside as 
`instanceName.removeStep(id)` where 'instanceName' is the name with which we initiated ImageSequencer. We don't have this instanceName

So in order to implement this, I had to introduce a new variable ImageSequencer.options.instanceName. I added the following lines of code at the beginning of `addStep()` and `loadImage()`: (I'll explain why I did so in a moment.)
```
if (typeof(window) != "undefined")
      for(var variable in window)
        if(window[variable] == this)
          options.instanceName = variable;
```

As long as ImageSequencer isn't initiated, `this` in the above function is simply `window`. As soon as we instantiate it as
```
sequencer = ImageSequencer();
```
`this` will now be `sequencer`. `variable` will now point to `"sequencer"`, which is what we wanted.
Since we dont have __init__ functions in JavaScript, I added these lines to the functions which are called as soon as ImageSequencer is initiated, Namely: `addStep()` and `loadImage()`. This did the trick.

### CODE REVIEW

**Comment by ccpandhare** [comment]
There's a small build error. I'll do that in a while.

**Comment by ccpandhare** [comment]
@jywarren Please help me
`npm test` runs properly on my machine but still Travis build is failing. What can I do?

**Comment by ccpandhare** [comment]
I get a `window` is not defined on Travis even though I modified my code to be something like this
```
    if (typeof(window) != undefined)
      for(var variable in window)
        if(window[variable] == this)
          options.instanceName = variable;
```

What should I do? Should I do a dummy initialization like this?
```
window = window || "Something123";
```

**Comment by ccpandhare** [comment]
I was missing the quotes wrapping the `undefined`.

@jywarren, I think the method removeStep() is now ready. What are your views?

**Comment by jywarren** [comment]
Wow, so much hard work here! Thank you!!! Let me read this through tomorrow morning and reply then. Just went through a really big merge over in the `plots2` repository, time for sleep!

**Comment by ccpandhare** [comment]
@jywarren I added the `removeStep()` to /src/ImageSequencer.js because the `addStep()` method is also present in /src/ImageSequencer.js. But I think I should implement the step
```
if (options.inBrowser) $('div#sequencer-'+id).remove();
```
in /src/UserInterface.js as was proposed in the comments in the /src/UserInterface.js file.

What do you think?

**Comment by jywarren** [comment]
As to your UserInterface question, I agree!

**Comment by ccpandhare** [comment]
I'll make the necessary changes.

**Comment by ccpandhare** [comment]
@jywarren There have been major changes here, like the `removeStep` itself, followed by the new `instanceName` and the `id` properties. It would be great if you tell me what you think about this.

**Comment by ccpandhare** [comment]
@jywarren  Did you get time to have a look at this?

**Comment by jywarren** [comment]
OK, I think this looks great, but that we should be testing the removeStep function. I don't think that'd be too hard; do you think you could add a simple step which just checks the before/after steps count?

**Comment by ccpandhare** [comment]
Yes. But I think some refactoring has to be done. Will make a blueprint
soon.

**Comment by jywarren** [comment]
Sounds good -- but let's work in small steps! Opening several smaller PRs are easier to review and check through, and help to not change two things at once (which complicates testing, too!). 

If you modularize and test your changes, you can submit a messier initial version because your test confirms the external behavior. Then you can go back in and refactor, and as long as it still passes the test (the "external promise", you might say), you're safe!

**Comment by ccpandhare** [comment]
Okay I agree. Will do that soon.

**Comment by jywarren** [comment]
Hi, @ccpandhare - how are we doing here? Waiting on #22, right? Just checking :-)

**Comment by ccpandhare** [comment]
Doing great, @jywarren !
Please see #24. I will add detailed explanations to everything soon and upon your approval of the structure, will write a test for the same!

**Pull request merged**
