### PR TITLE
Eslint configs

### PR DESCRIPTION
**Pull request by aashna27**
These are the error types that are occuring in our codebase for now I have disabled them as the occurence of these errors will prevent people from pushing commits. I will push commits as I mentioned earlier to remove these errors and also add eslint documentation to make contributors aware of our coding practises followed and information about eslint.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

Thanks!
@ubliclab/is-reviewers

### CODE REVIEW

**Comment by aashna27** [comment]
@jywarren

**Comment by jywarren** [comment]
Great!!!

**Comment by jywarren** [comment]
Hi! Should we apply this perhaps only to /src/ and /example/ files, and not to /dist/ files? What do you think?

**Comment by jywarren** [comment]
Also, let's add some docs to the README! 

I'll add, very briefly, `We are now using eslint and husky to help format our code. If we want husky to not verify the commit and push it, it's possible to use
git commit -m "message" --no-verify.`

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer/blob/main/CONTRIBUTING.md#linting

If you want to add to that, please do! Thanks!!!

**Comment by aashna27** [comment]
Yeahh! This will also improve the time for checks probably.

**Comment by aashna27** [comment]
Yeahh i ll add them! Just give me a day.

**Comment by jywarren** [comment]
No rush! Yeah, it was taking a while, that makes sense!

Thanks!

**Pull request merged**
