### PR TITLE
Made the image flip in correct way

### LINKED ISSUE #826: Issue with flip-image.
### Image flips in different way.
It flips vertically when we flip it horizontally and even same with the vice-versa.

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers review it

**Comment by HarshKhandeparkar** [comment]
The input is for the axis. The image is flipped ON THE selected axis. Which means that the image is flipped vertically ie on the x-axis when the horizontal input is selected and the image is flipped on the vertical axis(y-axis) ie. It is flipped horizontally

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar checkout this https://pinetools.com/flip-image.Try to flip the image in the website.

**Comment by HarshKhandeparkar** [comment]
You can try using CSS transforms on any image and try rotating the image/html-element by 180deg on x or y axis.

**Comment by HarshKhandeparkar** [comment]
Also the app in the link you posted doesn't flip the image on the specified horizontal/vertical axis. Ot just flips it in the direction. Vertical means it will swap the bottom and top pixels. This flipImage module rotates the image on the given axis by 180deg.

**Comment by Harshithpabbati** [comment]
> Also the app in the link you posted doesn't flip the image on the specified horizontal/vertical axis. It just flips it in that direction. Vertical means it will swap the bottom and top pixels. This flipImage module rotates the image on the given axis by 180deg.

yeah we need the same right. I guess there's no use of taking something as an axis(horizontal or vertical).

**Comment by HarshKhandeparkar** [comment]
Then maybe you can change the inputs to x-axis and y-axis instead of horizontal and vertical

**Comment by HarshKhandeparkar** [comment]
Make this a standalone PR(which doesn't fix any issue).

**Comment by Harshithpabbati** [comment]
I sent the pr which fixes it right???

**Comment by HarshKhandeparkar** [comment]
No. What I meant was that you can change the input options which are currently "vertical" and "horizontal" to "x-axis" and "y-axis" which will be better to describe an axis. Let the rest of the code be the same i.e. it should flip the image ON THE selected axis. Thanks.

**Comment by Harshithpabbati** [comment]
> No. What I meant was that you can change the input options which are currently "vertical" and "horizontal" to "x-axis" and "y-axis" which will be better to describe an axis. Let the rest of the code be the same i.e. it should flip the image ON THE selected axis. Thanks.

ok then lets have an option of selecting with respect to x-axis or y-axis and then vertical or horizontal.

**Comment by HarshKhandeparkar** [comment]
You can either keep the current code and change the input names to x-axis and y-axis or you can change the code to flip it horizontally or vertically based on the input (like what the app in your link does).

**Comment by HarshKhandeparkar** [comment]
Flipping the image ON THE selected axis is more like a standard and technical behaviour compared to the other one suggested by you which is mostly used on phones etc.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers what are your thoughts?

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers what are your thought on it???

**Comment by jywarren** [comment]
Hi all! This is a tough one. What if we have the drop-down option say "horizontal" or "vertical" but if you choose horizontal it says next to it "flip over y-axis" to clarify? Or "horizontal over y axis" together?

**Comment by Harshithpabbati** [comment]
If we set it to vertical then it flips x-axis and the vice versa

**Comment by Harshithpabbati** [comment]
@jywarren I made the change and sent the pr please review it.

**Comment by Harshithpabbati** [comment]
I just made the horizontal to vertical

**Comment by jywarren** [comment]
Hm, did you push up a commit? I don't see a change yet...? Thanks!!!

**Comment by Harshithpabbati** [comment]
Yup i did it.

**Comment by Harshithpabbati** [comment]
This was the one.

**Comment by Harshithpabbati** [comment]
https://github.com/publiclab/image-sequencer/pull/827/commits checkout this @jywarren

**Comment by jywarren** [comment]
Ah, ok - can you add some clarification about "over the x-axis" etc to the description so there's a bit more guidance? 

And, would you mind rebasing over the latest main branch? Thank you!

**Comment by Harshithpabbati** [comment]
Hello @jywarren what do you say???
Just checkout the image-sequencer rotate module and checkout the someother online tools for the image editing.

**Comment by jywarren** [comment]
Ah, can you add to this line:

https://github.com/Harshithpabbati/image-sequencer/blob/e8bfbb776ed1542de74f9b60288061a843288759/src/modules/FlipImage/info.json#L7

So instead of `axis` it says `Flips the image over the specified axis`?

Thank you!!!

**Comment by Harshithpabbati** [comment]
@jywarren made the change.

**Comment by jywarren** [comment]
I think this needs a rebase but let's wait for #824 which is really huge, first! Then it should be good to merge!

**Comment by Harshithpabbati** [comment]
sure @jywarren

**Comment by jywarren** [comment]
Can you rebase this or remove the dist files and we can then merge it? Thanks!!!!!

**Comment by Harshithpabbati** [comment]
should I remove the dist files??

**Comment by jywarren** [comment]
You can if you want, I mean from the PR (not deleting them entirely) and we
can do the grunt build step later. That's how we will start to do things to
make merging contributions easier. Thanks!

**Comment by Harshithpabbati** [comment]
https://github.com/publiclab/image-sequencer/pull/854
Checkout this @jywarren

**Pull request closed without merging**
