### PR TITLE
Draw Rectangle default values

### PR DESCRIPTION
**Pull request by root00198**
There are no default values set for endx and endy in Draw Rectangle Module. In this PR I set thoses values as 10px as default.
Perviously, There will no rectangle by default. But now, There will be a rectangle(square) of 10x10 pixels.
BEFORE SETTING DEFAULTS
before

AFTER SETTING DEFAULTS
after

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by root00198** [comment]
@publiclab/is-reviewers

**Comment by jywarren** [comment]
Hi, sorry but could you resolve the conflicts? Thank you!

**Comment by root00198** [comment]
@jywarren, could you please review it...

**Comment by jywarren** [comment]
Great work, thank you!

**Pull request merged**
