### PR TITLE
new circular gradient without merge conflicts

### PR DESCRIPTION
**Pull request by niravasher**
Fixes #0000  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by niravasher** [comment]
@jywarren @publiclab/is-reviewers please review and merge this. 
Happy to take any and all suggestions. Thankyou @HarshKhandeparkar for helping me solve git problems

**Comment by jywarren** [comment]
Hi @niravasher ! Can you link to the original, and share screenshots again? Thank you!!!

**Comment by jywarren** [comment]
Was it #869 ?

**Comment by blurry-x-face** [comment]
Another PR for the same is open #1496

**Pull request closed without merging**
