### PR TITLE
Add codecov

### LINKED ISSUE #774: Add code coverage
1. Code coverage might be good addition to show the percentage of code tested.
2. A `codecov` badge can be added to the `README`.

https://codecov.io/ can be used for this.

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #774 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren I have added code coverage here.
Please review.
Thanks!!

**Comment by Divy123** [comment]
Also it works successfully by adding the live status of our code coverage like this to the readme.

Codecov

**Comment by jywarren** [comment]
This is great!!! I'll merge now and we should see if we can get coverage to appear in PR comments or checks!!

**Comment by jywarren** [comment]
Ok! I turned on the integration!

**Comment by jywarren** [comment]
Hmm, @Divy123 do you see this? https://github.com/publiclab/image-sequencer/pull/1015 isn't it supposed to leave a comment?

**Comment by jywarren** [comment]
Aha https://docs.codecov.io/docs/pull-request-comments#section-configuration

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer/pull/1016

**Comment by Divy123** [comment]
Thanks @jywarren so much for this!!
We will now have report at every PR.

**Pull request merged**
