### PR TITLE
Add replace color module

### PR DESCRIPTION
**Pull request by Mridul97**
Discussion #694

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
@jywarren @publiclab/is-reviewers Please review! 

screenshot from 2019-01-28 02-08-08

**Comment by HarshKhandeparkar** [comment]
@Mridul97 can you please try this on an image where a color is distinct(like an image with colored text)?

**Comment by HarshKhandeparkar** [comment]
Also the screenshot you've provided doesn't seem like its providing the desirable output. @jywarren?

**Comment by Mridul97** [comment]
Actually @jywarren suggested here https://github.com/publiclab/image-sequencer/issues/694#issuecomment-456983112 to replace with a greyscale pixel

**Comment by HarshKhandeparkar** [comment]
Ok then. NP but please provide a screenshot of an image with a distinct color like the one used in the instagram video linked in the issue

**Comment by Mridul97** [comment]
@HarshKhandeparkar Please have a look! 

screenshot from 2019-01-28 02-35-08

**Comment by HarshKhandeparkar** [comment]
@Mridul97 this looks awesome. I had a suggestion which might be unnecessary but we could ask the user to select what the pixels should be replaced by either greyscale or user provided value or even it can be replaced by the most dominant pixel. In the above case the most dominant pixels is white. Thoughts?

**Comment by Mridul97** [comment]
@HarshKhandeparkar Sounds good!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 another thing is that if grey is the folor the user wants to separate then averaging will not work.

**Comment by jywarren** [comment]
Ooh! I like the idea of replacing with a given or default value... That
might actually change the module name to be "replace color"? Which is kind
of a more general purpose way to approach this narrower purpose, no?

Great work!!

**Comment by Mridul97** [comment]
Great! will make the changes, I think we can use radio-button to select either grey-scale or desired color by the user

**Comment by HarshKhandeparkar** [comment]
@Mridul97 I think there are many PRs which have received 1 review. Would you please give them a second review and add the label if neccessary? Too many PRs are open which need review before they are completely ignored. Thanks! @publiclab/is-reviewers . Sorry for going off topic.

**Comment by Mridul97** [comment]
@jywarren @HarshKhandeparkar Please have a look! 

replcecolor

**Comment by jywarren** [comment]
Wow! Very cooll! Great work. Do you think you could write a module test for this one in the new /test/modules/ area?

**Comment by Mridul97** [comment]
@jywarren I have added the test, Please have a look!

**Comment by Mridul97** [comment]
@jywarren I have rebased the branch! :)

**Comment by jywarren** [comment]
Merging this as soon as I rebase it!

**Pull request merged**
