### PR TITLE
Add: UI test script to Travis

### LINKED ISSUE #774: Add code coverage
1. Code coverage might be good addition to show the percentage of code tested.
2. A `codecov` badge can be added to the `README`.

https://codecov.io/ can be used for this.

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Addresses #740 partially

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@publiclab/is-reviewers @publiclab/reviewers

**Comment by dojutsu-user** [comment]
@VibhorCodecianGupta 
I think @Divy123 was already working on implementing this feature.
I would suggest closing this PR because it was not assigned to you.
Thanks.
cc: @jywarren

**Comment by Divy123** [comment]
@VibhorCodecianGupta I was working on this issue and following the discussion, you should have asked me if I was already working on it or not.
Since I am working on some other issues as well #606 #488 .
I request you to please close this PR so that a good workflow is maintained.

**Comment by VibhorCodecianGupta** [comment]
@Divy123 Oh! That's totally my fault, I'm really sorry. Didn't mean to at all. I actually did not realise you had claimed this one, I had the wrong impression that you were working on module tests rather than code coverage 😅 
I'll undo the code coverage stuff, and just leave the ui test part in. Apologies!

**Comment by VibhorCodecianGupta** [comment]
This now addresses adding ui tests to travis. @jywarren 
@Divy123 you can go ahead and implement codecov, apologies again!

**Comment by jywarren** [comment]
Very cool! Great work, @VibhorCodecianGupta !!!

**Pull request merged**
