### PR TITLE
fix: Upgrade GPU.js to v2.3.0 and handle browserifying it

### LINKED ISSUE #1348: Installation error
When I ran sudo npm run setup, I got that error:
Running "browserify:core" (browserify) task
>> Error: Cannot find module './utils' from '/home/md37/image-sequencer/node_modules/gpu.js/dist'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! image-sequencer@3.5.1 setup: `npm i && npm i -g grunt grunt-cli && grunt build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 setup script 'npm i && npm i -g grunt grunt-cli && grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the image-sequencer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && npm i -g grunt grunt-cli && grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs image-sequencer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls image-sequencer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/md37/image-sequencer/npm-debug.log

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
Fixes #1348  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Thanks a lot, @robertleeplummerjr.

@jywarren this is a very important fix. Please merge it ASAP.

**Comment by keshav234156** [comment]
@HarshKhandeparkar why is travis failing?

**Comment by HarshKhandeparkar** [comment]
Uh. I'll look into it.

**Comment by HarshKhandeparkar** [comment]
Omg. There are a lot of errors.

**Comment by HarshKhandeparkar** [comment]
Continued in #1374

**Pull request closed without merging**
