### PR TITLE
Dithering module added

### LINKED ISSUE #138: Add a Dithering module
I see two existing modules for this: 

https://stackoverflow.com/questions/12422407/monochrome-dithering-in-javascript-bayer-atkinson-floyd-steinberg

https://dpiccone.github.io/ditherjs/ (this uses Canvas, so is less suitable for node/browser cross-compatibility)

I think the first one has a very nice `monochrome()` function here that we could use for thresholding as well: 

https://github.com/meemoo/iframework/blob/gh-pages/src/nodes/image-monochrome-worker.js

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #138

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below
giphy

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Just a suggestion you can use `case` for algorith `type`.

**Comment by aashna27** [comment]
> Just a suggestion you can use `case` for algorithm `type`.

yess but then i ll have to commit again and then rebase 😴

**Comment by aashna27** [comment]
@jywarren please have a look.

**Comment by jywarren** [comment]
This is so cool!!!

**Pull request merged**
