### PR TITLE
adds default values to input fields for all module steps ( fixes #382 )

### LINKED ISSUE #382: Provide a function signature for blend step
I have noticed that some actions, like blend require a function as input. I think it would be great to provide a function signature for the same, to make it more descriptive.
fnsignature

### PR DESCRIPTION
**Pull request by Ankit-Singla**
Provides default input values in input of all step modules to indicate the input values on which the module step is running. This also provides a function signature for inputs that require a function.

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren let's merge this one in!

**Comment by jywarren** [comment]
🎉 👍 👍 👍

**Comment by jywarren** [comment]
publishing it too! we'll need a new version number pretty soon!

**Comment by jywarren** [comment]
@Ankit-Singla this is great. Would you want to take a look at this one too? It is UI centric and I think would be really cool to see: https://github.com/publiclab/image-sequencer/issues/247

Just in case it catches your eye! 🙌

**Comment by jywarren** [comment]
Ah, oops! The defaults are great, but they override the URL-specified values! Take a look:

https://publiclab.github.io/image-sequencer/examples/#steps=convolution{constantFactor:0.1111111111111111|kernelValues:0 -1 0 -1 5 -1 0 -1 0}

These are then overridden by the defaults :-(

Would you mind taking a look? unfortunately this is not live on the demo! 

Thank you!

**Comment by tech4GT** [comment]
Aha! I’ll see this!! Silly me!!

**Comment by Ankit-Singla** [comment]
Sorry, but I didn't quite understand the meaning of 'overriding URL-specified values'. @jywarren 
Can you please help me understand it better? @tech4GT

**Comment by tech4GT** [comment]
@Ankit-Singla the thing is that the input values that are taken from the url are being overriden by the value parameter, I'll figure this out!! Thanks for all the help!!

**Pull request merged**
