### PR TITLE
Capitalize the Gif text on View Gif button

### LINKED ISSUE #436: Enhance gif view
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## The Problem
Enhance gif view, Gif should show in popup view instead of it showing in same page.
some thing like this.
 https://www.w3schools.com/bootstrap/bootstrap_modal.asp

## The Solution
check this link
https://getbootstrap.com/docs/4.0/components/modal/
write html code here
https://github.com/publiclab/image-sequencer/blob/main/examples/index.html#L90
 js if reqiured here
https://github.com/publiclab/image-sequencer/blob/965399a2b4a3322354f371a1dbc674059f42d436/examples/index.html#L100
and css if required here
https://github.com/publiclab/image-sequencer/blob/965399a2b4a3322354f371a1dbc674059f42d436/examples/demo.css#L134

Thanks
**Instance Count = 1**

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #436 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@publiclab/reviewers @Divy123 Please take a look...

**Comment by Divy123** [comment]
Thanks for the PR :). It looks good to me.
@jywarren please review.

**Comment by jywarren** [comment]
👍 Thank you!!! We'd love more help from you if you're interested!

**Comment by Divy123** [comment]
@Rishabh570 you have mentioned the wrong issue number. Please correct it.
Thanks for your help.

**Pull request merged**
