### PR TITLE
fixed ''unable to load version number'' problem

### LINKED ISSUE #1724: Add "Loading version number" instead of "unable" message in UI
The message shown while loading the version number could use a tweak.

Screen Shot 2020-07-10 at 3 00 15 PM

It says "unable to load version number" until the page is finished loading. Maybe it should say:

`Loading version number` until it's loaded, but if it fails we rescue and try changing to `Unable to load version number`?

What do you think?

_Originally posted by @jywarren in https://github.com/publiclab/image-sequencer/pull/1567#issuecomment-656835348_

### PR DESCRIPTION
**Pull request by vivek-30**
Fixes #1724.

### CODE REVIEW

**Comment by vivek-30** [comment]
@HarshKhandeparkar and @jywarren  can you please review this?

**Comment by HarshKhandeparkar** [comment]
I saw the code but I am not sure how to check it :joy:

**Comment by HarshKhandeparkar** [comment]
From what I can tell, it looks fine :)

**Comment by vivek-30** [comment]
i have used chrome dev-tools for this . just by navigating to networks tab and then changed online mode to offline so that page renders slowly and then we can easily inspect it.

This is the working gif -
loading-version

**Review by HarshKhandeparkar — APPROVED** [review]
LGTM!

**Comment by jywarren** [comment]
This is awesome, thank you!!!!!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Hooray, thank you!!!!

**Pull request merged**
