### PR TITLE
Improved Footer

### LINKED ISSUE #898: Improve Footer
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**To Do**: The footer of the demo site [here](https://beta.sequencer.publiclab.org) has some redundancies and wrong links. It can be improved

### 📋 Step by Step
- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) in the `image-sequencer` repository (press the little pen Icon) and edit the line as shown below. 

This is the footer code
https://github.com/publiclab/image-sequencer/blob/21ff4866182ce1023c28faed975cd7f09554545f/examples/index.html#L197-L219

[see this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

Line 203 has a wrong link

```diff
-          Post a link to this and ask help from other community members on <a href="https://github.com/publiclab/image-sequencer/issues/new">Github Issues</a>
+          Post a link to this and ask help from other community members on Gitter.
```

Line 212 has a redundant link
```diff
-          This is an open source toolkit which you can help add to and improve on <a href="https://github.com/publiclab/image-sequencer/">Github</a>
+          This is an open source toolkit which you can help add to and improve on Github.
```
- [ ] 💾 **Commit** your changes
- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review
### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by vaarigupta**
Fixes #898 

* [x] tests pass 
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled

>Changed lines **203** and **212** in  **image-sequencer/examples/index.html**

@publiclab/is-reviewers (test, please ignore)

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Awesome but needs a rebase unfortunately m

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati i just edited the pr body and it does mention publiclab/is-reviewers. I don't know if that is because I edited or it is the case in general.

**Comment by Harshithpabbati** [comment]
> @Harshithpabbati i just edited the pr body and it does mention publiclab/is-reviewers. I don't know if that is because I edited or it is the case in general.

I got the message but I guess it worked because you edited it.

**Comment by vaarigupta** [comment]
> Awesome but needs a rebase unfortunately m

What's that? will you explain a little bit about it ?

**Comment by HarshKhandeparkar** [comment]
Ever since you opened this pr, some other prs were merged on publiclab's branch but the same ones were not merged on your branch. This means that both the branches have **diverged** and this pr cannot be merged automatically. This can be solved by [rebasing/merging](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).

Since the changes you have made are not very big, you close this pr and make the same changes to another branch which is even with publiclab/main or you can rebase(recommended).

Thanks.

**Comment by rexagod** [comment]
@vaarigupta [Git Rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) allows the feature branch (`vaari`, in your case) of your `forked` repository to synchronize with the `main` branch of the `upstream`(this) repository, hence resolving any "merge conflicts" that your branch may have with the current state of the `main` branch. You can,

- `git pull https://github.com/publiclab/image-sequencer main`
- `Resolve merge conflicts`
- `git push https://github.com/vaarigupta/image-sequencer vaari`

You'll be `rebasing` a lot now, so it makes all the more sense to learn all about it as soon as possible. Thanks!

**Comment by HarshKhandeparkar** [comment]
@rexagod hello! I think the git repo urls in the commands should have a .git there. E.g. https://github.... image-sequencer.gut

**Comment by rexagod** [comment]
Hey @HarshKhandeparkar! It works without the `.git` extension as well. HTTPS is cool like that. :smile:

**Comment by rexagod** [comment]
Moreover (assuming your `origin` is this repository), you can,

- `git remote add vaari-img-seq https://github.com/vaarigupta/image-sequencer`
- `git pull origin main`
- `Resolve merge conflicts`
- `git push vaari-img-seq vaari`

**Comment by vaarigupta** [comment]
Thanks @HarshKhandeparkar  and @rexagod . I look into it and correct it.

**Comment by HarshKhandeparkar** [comment]
This is ready to merge otherwise.

**Comment by HarshKhandeparkar** [comment]
@Harshithpqbbati can you please rebase this?

**Comment by Harshithpabbati** [comment]
You did it right ???

**Comment by HarshKhandeparkar** [comment]
No i didn't

**Comment by HarshKhandeparkar** [comment]
I just deleted the dist to make it easier for you to rebase.

**Comment by Harshithpabbati** [comment]
Ok now i should jst rebase it right??

**Comment by HarshKhandeparkar** [comment]
Yes, just merge with main. You know how to do that right?
You will have to clone vaari's repo
.

**Comment by Harshithpabbati** [comment]
Cloning her branch right??

**Comment by HarshKhandeparkar** [comment]
You can do
```
git clone https://github.com/vaarigupta/image-sequencer.git
cd image-sequencer

git checkout vaari
git remote add upstream https://github.com/publiclab/image-sequencer.git
git fetch upstream
git merge upstream/main
```
Fix conflicts (if any)
```
git add .
git commit -m "merge with main"
git push
```
Done!

**Comment by Harshithpabbati** [comment]
Really thanks you are helping me to learn git.

**Comment by HarshKhandeparkar** [comment]
Are ypu done with this?

**Comment by Harshithpabbati** [comment]
Yeah jst did it.

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati are you working on rebasing this?

**Comment by HarshKhandeparkar** [comment]
Oh ok. You are done with it. Sorry. Didn't read your message. Github didn't give the notification as well 🤔

**Comment by HarshKhandeparkar** [comment]
@jywarren please try to merge this one first. It is a first timer pr and needed a rebase and was just rebased.

**Comment by jywarren** [comment]
Thank you @vaarigupta!!!!

**Pull request merged**
