### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by niravasher**
Updating the already present PR #1329 as it was open for quite some time and had pending work.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by niravasher** [comment]
@HarshKhandeparkar @keshav234156 @SidharthBansal please review this

**Comment by blurry-x-face** [comment]
Hi, @niravasher there is already a open PR for this

**Comment by niravasher** [comment]
It has been open since long time and has pending work. It is of GCI which was over on 21st and that PR has merge conflicts. Suggest changes here @blurry-x-face

**Comment by blurry-x-face** [comment]
Could you add some screenshots/gifs

**Comment by niravasher** [comment]
ezgif com-gif-maker (1)
@blurry-x-face

**Comment by sharmamansi** [comment]
This black seems a bit odd, can we try with some lighter shades of black for better UI.

**Comment by niravasher** [comment]
Can you suggest me the hex or rgb code? @sharmamansi

**Comment by sharmamansi** [comment]
#616161 , #424242 , #37474f maybe you can hit and try with these

**Comment by blurry-x-face** [comment]
> This black seems a bit odd, can we try with some lighter shades of black for better UI.

Yes, I agree this black would look really good on an OLED display but on a normal IPS LCD(which most of the laptops use) this doesn't look good, So we can do this that for larger screen sizes we can use some lighter shade of black like #1f1f1f or #282828 and for smaller screen sizes(mobile phones) we can use this black as many mobile phones nowadays have OLED display and this would look really cool on an OLED!

**Comment by blurry-x-face** [comment]
I like the black theme of youtube, you could try to make something like this!

Screenshot from 2020-01-29 13-49-39

You could see how smartly they used the colors so nothing comes on too bright or too dark!

**Comment by niravasher** [comment]
Screenshot from 2020-01-30 20-38-49
How about this? @blurry-x-face @sharmamansi

**Comment by blurry-x-face** [comment]
I like this more, but remove the white colors and replace it with some shade of grey

**Comment by blurry-x-face** [comment]
Here, use these as a reference


Screenshot from 2020-01-30 22-58-00


Screenshot from 2020-01-30 22-58-37

**Comment by niravasher** [comment]
Yes, updating PR in a while @blurry-x-face

**Comment by niravasher** [comment]
Done @blurry-x-face

**Comment by harshithpabbati** [comment]
@niravasher can you the share some screenshots

**Comment by niravasher** [comment]
Screenshot from 2020-02-02 14-47-25
Screenshot from 2020-02-02 14-46-53
Screenshot from 2020-02-02 14-46-36
@harshithpabbati @blurry-x-face

**Review by HarshKhandeparkar — COMMENTED** [review]
Are CSS variables widely supported?

**Comment by HarshKhandeparkar** [comment]
I think we should close this for now. If at all we want to add a dark theme, it should be proper and should follow the [MD Guidelines](https://material.io/design/color/dark-theme.html) in my opinion.

**Pull request closed without merging**
