### PR TITLE
Added a 'Domain' in Chaining

### PR DESCRIPTION
**Pull request by ccpandhare**
## What this PR contains
For simpler usage of Image Sequencer, we allowed chaining in methods.
So there arose am ambiguity as to what the following line of code should mean:
```js
sequencer.loadImage(PATH).addSteps(STEPS).run();
```

### Before

Before this pull request, what this code did was:

* Create a new Image from the given PATH
* give it the name "default"
* addSteps STEPS to ALL images.
* run the sequencer.

In short, addSteps and other modules, according to the definition in README.md, used to by default affect ALL images. This was sensible before we allowed chaining.

### After

But now, what I propose in this PR is that, methods chained after loadImage() must only affect the newly loaded images. So the above piece of code will now mean:

* Create a new Image from PATH
* give it a random name like "image1"
* addSteps STEPS to the newly loaded image.
* run the sequencer on THAT image.

As you can see, the code is more intuitive now. Also I have added Automatic Image Naming like "image1", "image2", "image3", etc.

I have also forbidden chaining any methods after `run()` as the method will be called before `run` completes.

### CODE REVIEW

**Comment by ccpandhare** [comment]
This resolves #48

**Comment by ccpandhare** [comment]
I have tried to explain this in detail. If I have not explained something in a proper manner, please let me know :-)

**Comment by jywarren** [comment]
This sounds good. I think if we link to this description in the README and
after addsteps and other chainable methods we write a shorter version like
"Be aware that when chaining (see _chaining_), the passed steps are applied
only to the image passed via chaining, and not cached or applied to other
saved images."

**Comment by ccpandhare** [comment]
Yes that's right! I have added this to the README.md under a new section "Chaining".

**Comment by jywarren** [comment]
Perfect! Then, looks good to me!

**Comment by ccpandhare** [comment]
Merging!

**Pull request merged**
