### PR TITLE
Edge Detect Fixed!

### LINKED ISSUE #1576: Edge detect is not working correctly
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I tried running edge detect in browser and it gave following output (default values)

Screenshot from 2020-01-26 07-35-06

I tried running edge detect in node and it gave following output (default values)

image_1

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #1576   (<=== Replace `0000` with the Issue Number)

This was the simplest fix. Just had to change a global variable to a local one.

New Output:
Screenshot from 2020-02-15 21-18-28

Now it doesn't make a difference if the image is loaded first and then edge-detect is added or the other way around.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
The solution was a single line change but it took me 2 hrs to figure it out!
Also, why is Travis failing?

**Comment by HarshKhandeparkar** [comment]
Ok found that error too. Fixing it soon.
It seems Edge Detect was broken for GIFs earlier. Just compare these outputs.

OLD:
edge-detect

NEW:
edge-detect (1)

**Comment by HarshKhandeparkar** [comment]
Fixed that too.

**Comment by HarshKhandeparkar** [comment]
The tests had passed locally 😕

**Comment by HarshKhandeparkar** [comment]
I don't think the error was caused by my changes. Also, it is only failing for node 8.

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar try restarting the build once again

**Comment by HarshKhandeparkar** [comment]
I'll try that. Thanks.

**Comment by HarshKhandeparkar** [comment]
Passed!

**Comment by keshav234156** [comment]
cat

**Comment by jywarren** [comment]
This looks great, and was easy to test out in GitPod! https://gitpod.io/#https://github.com/publiclab/image-sequencer/pull/1629

image

Confirmed! Thank you!!!

**Comment by HarshKhandeparkar** [comment]
Ty!

**Pull request merged**
