### PR TITLE
Alphabetizes the modules in src/Modules.js

### LINKED ISSUE #375: Arrange the modules in alphabetical order
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Problem
Arrange the modules in alphabetical order, the modules right now are not in alphabetical order.

ss_20

# The Solution
We need to modify the src/Modules.js file. We need to arrange the modules in the src/Modules.js file in alphabetical order.

https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/src/Modules.js#L4-L26

<strong>Instance Count = 1</strong>

### PR DESCRIPTION
**Pull request by kevinzluo**
Fixes #375 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by kevinzluo** [comment]
Hello. It appears another user completed this task as well. Was my GCI task duplicated?

**Comment by rockstar777** [comment]
Great Work!
Thanks for the PR.

**Comment by kevinzluo** [comment]
I believe it is because the task was listed multiple times on the GCI Task List. I saw another instance of it yesterday.

**Comment by tech4GT** [comment]
Oh, we need to fix this!! @Souravirus @SidharthBansal I need your help here!

**Comment by Souravirus** [comment]
Yeah I can see two instances of it https://codein.withgoogle.com/dashboard/tasks/5257097257156608/ and https://codein.withgoogle.com/dashboard/tasks/6549673218146304/ . @tech4GT I don't have rights to delete a task. @SidharthBansal or @jywarren can surely help with this.

**Comment by tech4GT** [comment]
Yeah, we can do it this one time I guess, I'll take a look at the dashboard to make sure that there are no duplicate tasks though.

**Comment by jywarren** [comment]
OK, merged this one and I left a notice on another saying we'll give credit but are closing... thanks!

**Pull request merged**
