### PR TITLE
fix remove step UI

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by tech4GT** [comment]
fixes #286

**Comment by tech4GT** [comment]
@jywarren my bad!! I ran only on the last step in removeStep also!! fixed it!!

**Comment by jywarren** [comment]
Can you bump version number to 2.0.1? Thanks!!!

**Comment by tech4GT** [comment]
@jywarren bumping version!!

**Comment by tech4GT** [comment]
@jywarren Done!!

**Comment by tech4GT** [comment]
@jywarren nice catch btw!! Thanks a lot!!

**Comment by tech4GT** [comment]
@jywarren travis is behaving weirdly here!! apt-get is failing

**Comment by jywarren** [comment]
Try closing and reopening?

**Comment by tech4GT** [comment]
@jywarren this finally works!!!

**Comment by tech4GT** [comment]
Awesome!!!

**Comment by jywarren** [comment]
Oops - not a big deal, but for bugfixes, you can put `v0.0.x` level fixes. `v0.x.0` means a new feature added!

**Comment by tech4GT** [comment]
oh should I change that @jywarren or do that in the future?

**Comment by jywarren** [comment]
Just in the future -- we can't go backwards once it's published!

**Pull request merged**
