### PR TITLE
trying this out [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by tech4GT**
cc @jywarren

### CODE REVIEW

**Comment by jywarren** [comment]
How did it go? Cool!!!

**Comment by tech4GT** [comment]
Hi @jywarren I think we might need to re-write a lot of the code for this to work, at which point it only makes sense to separate the node and browser code for gl based modules.
Can you list some basic functions which I can try and implement from scratch using the 'gl' module.

**Comment by tech4GT** [comment]
Okay so I have narrowed done the current issue, it lies with the `gl.texImage2D()` function, it is not loading the image into gl properly

**Comment by jywarren** [comment]
Let's not give up and do a big refactor just yet... if you do want a simple WebGL demo to try, you could look at:

* https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Basic_2D_animation_example
* maybe something from https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial ?

You could also potentially search the `headless-gl` repo for `texImage2D` - @Divy123 already posted on this but there's evidence that the function does exist: https://github.com/stackgl/headless-gl/search?q=texImage2D&type=Issues

**Comment by jywarren** [comment]
Noted links in @Divy123's issue here: https://github.com/stackgl/headless-gl/issues/143

**Comment by tech4GT** [comment]
@jywarren SO the official documentation says we can just drop a Uint8 array image data and it should work, but that clearly is not working since that is generating a type error. One of the accepted types was ImageData which I am using but the pixels in `gl` just remain the same even after running `texImage2D`

**Comment by tech4GT** [comment]
The documentation does say there is no explicit support for this.

**Comment by tech4GT** [comment]
https://www.npmjs.com/package/headless-gl#how-are-image-and-video-elements-implemented

**Comment by jywarren** [comment]
Hmm, ok, so perhaps we should add to/rename/open new issue for asking
specifically: 1. for any example code showing this in use, 2. a test
exhibiting this?

We can also ask if they can point us at the section of code where this is
accepted as a parameter and inspect how it's used there to ensure we know
exactly the format they are expecting... and/or dig ourselves a bit!

**Comment by tech4GT** [comment]
@jywarren Yeah! I also tried it the way they mentioned here https://github.com/stackgl/headless-gl/pull/53/files#diff-c24e210c8552e30550810a8b75aa1cdaR101
This is also not working, all I am getting is a black image.

**Comment by tech4GT** [comment]
@jywarren Should I open an issue over at their repository or would you?? :smile:

**Comment by jywarren** [comment]
If you could, that'd be great! Link back here please? Thank you!

**Comment by HarshKhandeparkar** [comment]
We use pupeteer now. Also this solution is not very good. We'll have to do something new. I will try to figure something out.

**Pull request closed without merging**
