### PR TITLE
[WIP]Improved Building Task

### PR DESCRIPTION
**Pull request by sakshamsaxena**
Hi! 
Summarising some changes which I felt were needed. Looking forward to hear your views on this.

- `dist` directory will now be ignored. The `grunt build` task shall now build both JS and CSS files. Why? Because I could see hard-coded paths in the JS generated in `dist` folder. It is highly inconsistent. 
- Updated the `package.json` which now has the URLs of _this_ repository (publiclab/image-sequencer). 
- [Discuss] Found inconsistent spacing indentation in `Gruntfile.js`, so used 4 Space indentation in the file. I think we must include a suitable guideline regarding this in the README, or create a linting task to check for the same, or both maybe. Would love to hear your view on this.

Apologies if I went ahead with a PR without informing! Suggestions are most welcome :smile:

### CODE REVIEW

**Comment by jywarren** [comment]
I prefer two-space indenting, and if it's all right, we could make that consistent. VERY appreciative of this PR and I love your attention to detail. A linter would be great. Also, +1 what @ccpandhare said about the dist directory although I'm happy to discuss if you have strong opinions about this.

**Comment by sakshamsaxena** [comment]
Oh thanks a lot for the feedback! 
Ignoreing dist directory helps, in my opinion, because when I cloned the repo, the newly built js file had made some changes in the absolute path in some instances. I thought that was not so standard, per se, to include in a repo a hard-coded location or path. That's why I suggested this work around. Apologies if I wasn't so clear !
Also, could you please share the discussion thread which you mentioned? I couldn't really find a dedicated issue to this. 
Finally, but alas, I'm traveling over this weekend till Monday so won't be able to push new commits for a few days, but would love to read more on this! 
Thanks again for your patience!

**Comment by jywarren** [comment]
Hi, thanks for the extra info -- here's the discussion, though there wasn't
that much: https://github.com/jywarren/image-sequencer/issues/3

Can you clarify what you mean about the absolute paths? Thank you!

Safe travels and talk to you soon!

**Comment by sakshamsaxena** [comment]
Oh I see that you are trying to keep dist directory so as to provide a direct link like a CDN. Cool!
Also, since the JS in that directory is too large for GitHub to preview, I can't exactly point out the line numbers. Here's how to emulate it :
- Get a fresh clone of this repo.
- Run `grunt build`
- `git diff dist/image-sequencer.js`
See the complete diff. I think that'll help to elaborate my point. :-) 
Thanks for your wishes! :D

**Comment by sakshamsaxena** [comment]
Here's the part of the diff which I was talking about. 
```diff
@@ -85391,7 +85393,7 @@ module.exports={
         "spec": ">=0.22.0 <0.23.0",
         "type": "range"
       },
-      "/Users/ccdpandhare/Desktop/GSoC/image-sequencer/node_modules/plotly.js"
+      "/home/saksham/Documents/image-sequencer/node_modules/plotly.js"
     ]
   ],
   "_from": "mapbox-gl@>=0.22.0 <0.23.0",
@@ -85425,7 +85427,7 @@ module.exports={
   "_shasum": "92a965547d4c2f24c22cbc487eeda48694cb627a",
   "_shrinkwrap": null,
   "_spec": "mapbox-gl@^0.22.0",
-  "_where": "/Users/ccdpandhare/Desktop/GSoC/image-sequencer/node_modules/plotly.js",
+  "_where": "/home/saksham/Documents/image-sequencer/node_modules/plotly.js",
   "browser": {
     "./js/util/ajax.js": "./js/util/browser/ajax.js",
     "./js/util/browser.js": "./js/util/browser/browser.js",
```
The hardcoded paths are generated by Browserify, which are inconsistent across versions. Although in production, this doesn't produce an issue (tested now). 
So I think it's safe to close this PR :-)

**Pull request closed without merging**
