### PR TITLE
Shift elements to the left to increase space

### LINKED ISSUE #850: remove unwanted slider
### Please describe the problem (or idea)
I think there is an unwanted slider (left-right) so I think should remove that slider.
pu4

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by niravasher**
Fixes #850

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@niravasher please ask @publiclab/is-reviewers for review.

**Comment by aashna27** [comment]
@niravasher can you please show a screenshot or gif .

**Comment by Divy123** [comment]
@niravasher can you please provide a screenshot or gif for the same if you are done and we need to do the rebase here.
Thanks!!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by HarshKhandeparkar** [comment]
This is an old PR. Closing. Please feel free to reopen if necessary.

**Pull request closed without merging**
