### PR TITLE
Opencv.js via npm for blob-detection

### LINKED ISSUE #172: blob/region detection and extraction for particle analysis
region extraction -- https://github.com/linuxenko/rextract.js

This would let us identify objects on images like these:

Read more about this stuff here: https://publiclab.org/tag/particle-imaging

Especially here: https://publiclab.org/notes/mathew/09-19-2015/using-imagej-to-process-passive-particle-monitor-samples

Step-by-step guides to analysis:

https://publiclab.org/notes/SimonPyle/05-13-2016/automating-imagej-for-particle-image-analysis

https://publiclab.org/notes/amirberAgain/01-12-2018/python-and-opencv-to-analyze-microscope-slide-images-of-airborne-particles

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #172 

This pr is a continuation pr of #1120, please refer there for all the major discussions on how the work evolved and the other module related information.

This pr adds opencv.js to Image sequencer via NPM and currently uses it for a new blob detection module. Opencv.js addition would enable the use of power image processing within IS. The npm adds opencv.js version 3.3 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Ok! Does this include all the work from the previous PR? Thanks a lot!!!

**Comment by aashna27** [comment]
Yes i have checked and the blob analysis folder is simply copied so all the work including documentation does exist here.

**Comment by jywarren** [comment]
Awesome. Have you been able to set this up in your own gh-pages branch to
offer a demo? @HarshKhandeparkar has done this and perhaps could help?

**Comment by aashna27** [comment]
Thanks to @HarshKhandeparkar I have setup the gh-pages and you can see the blob-analysis working there
https://aashna27.github.io/image-sequencer/examples/ 
Note: use google chrome

**Comment by jywarren** [comment]
I'm seeing some assorted bugs, that may or may not be related to your code:

* [ ] moving the Contrast slider doesn't enable the "Apply" button, so I can't modify that
* [ ] the slider for Brightness only showed up the second time I loaded the page; when I initially added it it was just a text input
* [ ] the Contrast pane did not show a "spinning" image while recalculating (after I dropped in a new image to the sequencer); it just showed the previous image until complete, then everything returned to normal (it showed the new image after completion)

Finally, I put this image in, and added more brightness and contrast (final sequence https://aashna27.github.io/image-sequencer/examples/#steps=brightness{},brightness{},contrast{contrast:20},blob-analysis{} due to issues with the brightness module)

Starting image: 

image


Got this out: 

image

So, i think it works! If you can try to confirm if these bugs are independent (like, do they happen in the main branch) then we can just merge this and open a new issue with these (if you wouldn't mind opening that too, that'd be helpful!) 

Thanks, @aashna27 for getting this set up. This is looking great.

**Comment by jywarren** [comment]
And, in follow-up, are there ways to adjust the blob detection sensitivity? Is it based on color, size, are there other parameters we could add? This would also be a really great follow-up issue. 

🎉 Very exciting!

**Comment by aashna27** [comment]
> I'm seeing some assorted bugs, that may or may not be related to your code:
> 
>     * [ ]  moving the Contrast slider doesn't enable the "Apply" button, so I can't modify that
> 
>     * [ ]  the slider for Brightness only showed up the second time I loaded the page; when I initially added it it was just a text input
> 
>     * [ ]  the Contrast pane did not show a "spinning" image while recalculating (after I dropped in a new image to the sequencer); it just showed the previous image until complete, then everything returned to normal (it showed the new image after completion)
> 
> 
> Finally, I put this image in, and added more brightness and contrast (final sequence [https://aashna27.github.io/image-sequencer/examples/#steps=brightness{},brightness{},contrast{contrast:20},blob-analysis{}](https://aashna27.github.io/image-sequencer/examples/#steps=brightness%7B%7D,brightness%7B%7D,contrast%7Bcontrast:20%7D,blob-analysis%7B%7D) due to issues with the brightness module)
> 
> Starting image:
> 
> image
> 
> Got this out:
> 
> image
> 
> So, i think it works! If you can try to confirm if these bugs are independent (like, do they happen in the main branch) then we can just merge this and open a new issue with these (if you wouldn't mind opening that too, that'd be helpful!)
> 
> Thanks, @aashna27 for getting this set up. This is looking great.

Sorry but I could not reproduce those bugs, and I just added the blob analysis so they are not related to the pr.
ezgif com-video-to-gif

**Comment by aashna27** [comment]
> And, in follow-up, are there ways to adjust the blob detection sensitivity? Is it based on color, size, are there other parameters we could add? This would also be a really great follow-up issue.
> 
> tada Very exciting!

Yeah it can be done in the way that right now it is doing everything itself but we can take inputs from the user for the different functions that are being used but we can let them provide inputs for all the functions as it would only need to confusion so the task would be to figure out what functions to ask arguements for.

**Comment by jywarren** [comment]
Awesome. This is great! Can you please open the follow-up PRs for the unrelated bugs and the parameters discussion? @MargaretAN9 may have input on what parameters to expose for tuning the blob detection!

**Comment by HarshKhandeparkar** [comment]
@jywarren I have to push this to beta. Were any new frontend/backend
libraries(which are included in the html) added?

**Comment by aashna27** [comment]
> Awesome. This is great! Can you please open the follow-up PRs for the unrelated bugs and the parameters discussion? @MargaretAN9 may have input on what parameters to expose for tuning the blob detection!

Yeah i ll see wasn't able to reproduce this problem.

**Comment by jywarren** [comment]
Thanks! If you can just copy in the text from my checklist for now I'll
follow-up with a gif!

**Comment by jywarren** [comment]
@HarshKhandeparkar maybe that's a question for @aashna27 ?

**Pull request merged**
