### PR TITLE
made few changes to css

### LINKED ISSUE #946: Preview gif button overflow.
### Preview GIF overflow.
savebtn

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Fixes #946 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@jywarren everything is done!!!

**Comment by aashna27** [comment]
Does this work for smaller screens?

**Comment by Harshithpabbati** [comment]
Yeah it's with bootstrap.

**Comment by Harshithpabbati** [comment]
mobilepre
see this @aashna27

**Comment by aashna27** [comment]
Okayy! Cool

**Comment by jywarren** [comment]
This is great. Did you notice the module selector is a bit too wide, covering the neighboring button? Is that just a quick css fix too?

**Comment by aashna27** [comment]
No, that hasn't been covered here, there exists a first-timer issue for it.

**Pull request merged**
