### PR TITLE
Added tests for more modules

### PR DESCRIPTION
**Pull request by aashna27**
I have added tests for a few more modules.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@aashna27 awesome!
Some screenshots of passing tests, if I may?

**Comment by aashna27** [comment]
Yeah sure, I ll do them tomorrow. Should have done before 😜 Thanks a lot for reminding.

**Comment by aashna27** [comment]
RESIZE
image

ROTATE
image

DITHER
image

COLORMAP
image


CHANNEL
image

BLUR
image

**Comment by aashna27** [comment]
Decode-qr

image

**Comment by jywarren** [comment]
Awesome @aashna27!!

**Pull request merged**
