### PR TITLE
Text overlay for GIF

### LINKED ISSUE #1462: Text-Overlay Does Not Work With GIFs
### Please describe the problem (or idea)
In the case of the gif the text overlay is in the vertical form rather than the horizontal form and the letters are a mirror image of itself. 

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ataata107**
Fixes #1462   (<=== Replace `0000` with the Issue Number)
text-overlay (5)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] ask `@publiclab/is-reviewers` for help, in a comment below
* [X] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by ataata107** [comment]
@jywarren @HarshKhandeparkar @keshav234156 Text-overlay is also now working for gifs

**Comment by root00198** [comment]
I will create a test in #1530 once this pr gets merged

**Comment by ataata107** [comment]
@jywarren ya I guess
@root00198 sure maybe we can collaborate?

**Comment by root00198** [comment]
Yes we can.You should add a `text-overlay.js` in `test/core/gifs` and when the PR's will get merged it will work automatically. Follow the format which is used in my PR for the `text-overlay.js`.

**Comment by ataata107** [comment]
Ok cool
Let’s wait for this to get merged

**Comment by jywarren** [comment]
Ok! Awesome! Thanks!!!

**Comment by HarshKhandeparkar** [comment]
@ataata107 @root00198 
What is this https://github.com/publiclab/image-sequencer/pull/1533/files#diff-547cf362f90feb6b67d8803cb64fe2edL317 for?

**Comment by HarshKhandeparkar** [comment]
Is it required? Also, the way it is implemented isn't the most optimal solution. It would be better to pass in a function that calculates the datauri *on demand* if required. Calculating the datauri for every frame and for every module even though the majority of the modules do not even use this feature.

**Comment by jywarren** [comment]
Maybe this needs it's own issue? Is this in #1547 now? thanks!

```js
frames[f] = options.extraManipulation(framePix, setRenderState, generateOutput, datauri) || framePix; // extraManipulation is used to manipulate each pixel individually.
```

**Comment by blurry-x-face** [comment]
@jywarren Yes

**Comment by ataata107** [comment]
It is required for modules which needs url, (in case of gifs,  getting url through canvas method wasnt working well) . @HarshKhandeparkar yes it can be refactored so as to not being processed for other modules.

**Comment by HarshKhandeparkar** [comment]
@ataata107 could you please open an issue for the refactor?

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar it has already been done! #1551

**Comment by HarshKhandeparkar** [comment]
Nope. I was talking about  this

> Also, the way it is implemented isn't the most optimal solution. It would be better to pass in a function that calculates the datauri _on demand_ if required. Calculating the datauri for every frame and for every module even though the majority of the modules do not even use this feature.

**Pull request merged**
