### PR TITLE
Map types to HtmlTypes

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/570

Added a new function to `examples/lib` which maps `type` from module info.json files to valid HTML input types.

new-func-channel

new-func-drawrectangle

new-func-rotate

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review. @jywarren I have added the function to `examples/lib/` as it is not required by image-sequencer main library source.

**Comment by HarshKhandeparkar** [comment]
My exams are going to start so I will not be available until 30th Jan.

**Comment by HarshKhandeparkar** [comment]
I have merged with main. @publiclab/is-reviewers please review.

**Comment by HarshKhandeparkar** [comment]
@Mridul97 I'm not able to require my MapHTMLTypes.js file due to code refactoring. Could you please help?

**Comment by HarshKhandeparkar** [comment]
Also I think it is not added to the watch task. Can you please do that?

**Comment by Mridul97** [comment]
@HarshKhandeparkar Yes, I will look into this!

**Comment by HarshKhandeparkar** [comment]
Thanks!

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers I have rebased. Please review.

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers conflicts resolved!!

**Comment by jywarren** [comment]
oh no, did you add more?

**Comment by jywarren** [comment]
i rebased... shall i wait?

**Comment by HarshKhandeparkar** [comment]
@jywarren you can go ahead.

**Comment by jywarren** [comment]
👍 great job!

**Comment by HarshKhandeparkar** [comment]
@jywarren when are you going to push to gh-pages btw?

**Comment by HarshKhandeparkar** [comment]
Oh wait. What happened to the pr? The changes? I cannot see any changes. Neither are the files added to the repo. @jywarren

**Pull request merged**
