### PR TITLE
notify users for selecting empty step

### LINKED ISSUE #1310: Mesage notification for "Add Step"
### Mesage notification for "Add Step"

Currently when we are clicking on "Add Step" option without selecting a module it simply shows nothing.

Instead when we are clicking on "Add Step" option without selecting a module it should show a message notification stating that "Please select a module first".  

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by vivek-30**
Fixes #1310.
Now a user will be notified for adding empty step .

### CODE REVIEW

**Comment by vivek-30** [comment]
This is the working clip for above issue - 

https://user-images.githubusercontent.com/75980147/108504386-cbf27180-72db-11eb-955d-6eef45ba5a17.mov

**Comment by vivek-30** [comment]
@jywarren, @HarshKhandeparkar  could you please review this ☺️ .

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Very nice! Thank you!!!

**Comment by jywarren** [comment]
Congrats!!!

**Comment by vivek-30** [comment]
@jywarren Thanks a lot sir and welcome ☺️

**Pull request merged**
