### PR TITLE
Changes to make the insert-step disable at the first step

### PR DESCRIPTION
**Pull request by Harshithpabbati**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@jywarren small changes because the insert step is not disabled.

**Comment by Harshithpabbati** [comment]
@jywarren can be merged instantly as I just changed the name of the class.

**Comment by Harshithpabbati** [comment]
Check beta.sequencer.publiclab.org :smile:

**Comment by jywarren** [comment]
Awesome, thanks!!! I think i caused this 😮

**Pull request merged**
