### PR TITLE
Clarify that saved sequence will only be available in this browser

### LINKED ISSUE #573: Have save sequence link clarify that it will only be available in this browser
#### In the box that opens when save sequence button is clicked, we can add a message clarifying that the saved sequence will only be available in this browser. 

This is a sub-issue of #487.

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #573 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@Mridul98, I think the message will look better if the `...` at the end are removed.

**Comment by jywarren** [comment]
I could go either way on `...` - happy to defer to Mridul on this. I do
think we should add "It will appear as a module in the Add Step menu" - so
people know where to find it!

**Comment by Mridul97** [comment]
@jywarren I have added a message showing where the saved sequences can be found #586 here. Please have a look!

**Comment by jywarren** [comment]
Yes ok great! Super - then this looks good!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 you can use ternary operator for result. 
`result = result ? result + ' (local)' : null`

**Comment by Mridul97** [comment]
@jywarren I have made the changes and also rebased the branch. :smile:

**Comment by Mridul97** [comment]
@HarshKhandeparkar we can do that but if is also doing the same thing!

**Comment by HarshKhandeparkar** [comment]
This was just a suggestion. Makes the code look cleaner.

**Comment by HarshKhandeparkar** [comment]
Also something you could do is that save the sequence only if result is a non empty string else do nothing or `window.prompt()` something else.

**Comment by Mridul97** [comment]
Yes, I agree the code will look cleaner! I will try it out. Thanks!

**Comment by Mridul97** [comment]
> Also something you could do is that save the sequence only if result is a non empty string else do nothing or `window.prompt()` something else.

Yes, the sequence is only saved when the string is non-empty, otherwise it is not saved!

**Comment by HarshKhandeparkar** [comment]
Ok then NP!!

**Comment by HarshKhandeparkar** [comment]
> @HarshKhandeparkar we can do that but if is also doing the same thing and do you think it will work when the user leaves the textbox empty and clicks ok?

Yes, it will work. it basically does the same thing but instead of running some code based on some logic, it returns some code if statement is true or returns somwthing else if statement is false.

**Comment by Mridul97** [comment]
Great!

**Comment by Mridul97** [comment]
@HarshKhandeparkar I tried out using ternary operator, but when a user leaves the textbox empty and clicks ok, then the sequence is getting saved by the name 'null'.

**Comment by Mridul97** [comment]
@HarshKhandeparkar actually both the approaches were saving the sequence by the name of 'null' on when the user clicks cancel button. But I have fixed this error!

**Comment by Mridul97** [comment]
@jywarren Please review this!

**Comment by jywarren** [comment]
Looks awesome. Great teamwork, folks!!!

**Pull request merged**
