### PR TITLE
Allow upload of only image file types in import-image module

### LINKED ISSUE #429: Allow upload of only image file types in import-image module
### We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI !

Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# Task:

The "import-image" makes user to upload a file.
Currently, while uploading "All files" types are allowed. 
###### The module
image

###### Upload File 
image

###### File Types 
image

### PR DESCRIPTION
**Pull request by thesparks**
Fixes #429 
image

### CODE REVIEW

**Comment by thesparks** [comment]
@Rishabh570 @aashna27 @vikul1234 please review

**Comment by aashna27** [comment]
@thesparks great work! but there are still some conflicts, also the 3 image file types you mentioned aren't the only image types.

**Comment by thesparks** [comment]
@aashna27 what types of image you need? All image/* mime types?

**Comment by thesparks** [comment]
Task has only tag html. Maybe js check is not needed at all?

**Comment by Rishabh570** [comment]
@thesparks Yep, the task has HTML tag only...you don't need to worry about server-side validation of the file uploaded for this task...just `accept=image/*` thing would make it?
@aashna27 Thoughts?

**Comment by aashna27** [comment]
Yeah! true js won't be needed. 😅

**Comment by thesparks** [comment]
@Rishabh570 , @aashna27 fixed) please confirm CGI task

**Comment by Rishabh570** [comment]
@thesparks One more thing, make sure your commits are related to this PR only...I see a commit containing GIF related code...and you should squash your changes into a single commit (for PR containing small changes) to make the commit history as clean as possible...

**Comment by thesparks** [comment]
image/* didn't work on Linux, so i added js


> @thesparks One more thing, make sure your commits are related to this PR only...I see a commit containing GIF related code...and you should squash your changes into a single commit (for PR containing small changes) to make the commit history as clean as possible...

Sorry, I thought I could merge commits after sending

**Comment by aashna27** [comment]
The "image/* "  would work, see while uploading file , the file manager would no longer show "All files."
you can merge the commits you have pushed. and remove the ones not required.
https://help.github.com/articles/about-git-rebase/ this would help you to learn how to merge commits.

**Comment by thesparks** [comment]
> The "image/* " would work,
This works at on windows computer, but not on Linux notebook (maybe its bug of deepin file manager):
image

> To squash and merge pull requests, you must have write permissions in the repository, and the repository must allow squash merging.

I can't change anything here, but I can do it before future commits, right?

**Comment by aashna27** [comment]
Squash the commits, to make them 1.

**Comment by aashna27** [comment]
You need to squash the multiple commits that have been made into 1.

**Comment by thesparks** [comment]
@aashna27, but i cant get new task until pass the last

**Comment by aashna27** [comment]
@thesparks as i mentioned please squash your commits its difficult to review multiple commits, can't keep track. https://help.github.com/articles/about-git-rebase/ this would help you learn the commands to merge the commits.  😄 
I really appreciate your enthusiasm and work 👍

**Comment by thesparks** [comment]
i dont understand how this works...

**Comment by handlerug** [comment]
+1. It will trigger some strange merge conflicts
screenshot 2018-10-24 at 23 53 05

**Comment by Rishabh570** [comment]
@thesparks do `git rebase -i` it will open a list of recent commits, then replace the word `pick` with `s` (in front of the commit message you wanna squash) to squash that commit into its previous commit...Here is the example GIF


squash_commit

Here I did `git rebase -i main` (because I was on different branch than `main`)

Hope this helps, ask if you still have queries...!!!

**Comment by Rishabh570** [comment]
You need to provide a commit hash, eg. `git rebase -i {seven_characters_hash}` in order to do interactive rebase after that commit or you can do something like `git rebase -i HEAD~n` where n is number of commits you wanna do rebase onto...(like if you have 6 commits in your PR, so you might wanna do `git rebase -i HEAD~6`)
Some explanation [here](https://stackoverflow.com/questions/6485508/git-interactive-rebase-no-commits-to-pick)

**Comment by handlerug** [comment]
`git rebase -i HEAD~4` or `git rebase 1935967` shows nearly 16 commits, and when I pick or squash that commits, git says to resolve merge conflicts. So I've looked into Sourcetree and there are 3 branches, one of them has @thesparks commits. How to rebase only main branch?

**Comment by tech4GT** [comment]
Also don't worry about squashing commits, we would be merging all the changes done in one pull request as one commit only.

**Comment by tech4GT** [comment]
Hmm, I see...
A piece of advice for you, never make changes directly to your main branch, make a new branch for the changes you make and then open a pull request from there. As for this, I'll try and fix this. Thanks!

**Comment by tech4GT** [comment]
Hmm @thesparks I figured out what happened here, nothing went wrong, you merged the branches correctly but the line you added is already present in the code, you did not see it because you did not pull the latest changes.
Is this your gci task?

**Comment by thesparks** [comment]
@tech4GT, yes its gci task

**Comment by tech4GT** [comment]
Since this one is already fixed in the code but you made the right efforts for it, you can move on to the next task and I'll make sure you get the credit for this one. Thanks! 😄 
cc @jywarren

**Comment by thesparks** [comment]
> Since this one is already fixed in the code 
> you did not see it because you did not pull the latest changes.

strange i did everything through githab.com (https://github.com/publiclab/image-sequencer/pull/440/commits/1935967202b2b42db3d5bc8cbaddde1601e36e66)

**Comment by tech4GT** [comment]
These things happen sometimes, don't worry about it. Thanks a lot for your patience😊

**Pull request closed without merging**
