### PR TITLE
Removes remnant div after removing crop step

### LINKED ISSUE #352: Patch on delete a sequence after crop
There occurs a black patch when we delete the crop sequence.

Issue can be reproduced like this

aaa ogv

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #352 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@publiclab/reviewers
@tech4GT please review :)

**Comment by VibhorCodecianGupta** [comment]
@jywarren @tech4GT is this an acceptable fix? Please review :)

**Comment by VibhorCodecianGupta** [comment]
crop

@tech4GT here is the gif

**Comment by VibhorCodecianGupta** [comment]
@jywarren @tech4GT here :)

**Comment by jywarren** [comment]
Oh, i was going to rebuild this but I think actually the dist files are unrelated to your code! Would you mind just removing them from this PR? Thanks!

**Comment by VibhorCodecianGupta** [comment]
@jywarren removing them as in? Do you mean rebasing changes? The changes made have to reflect in the dist files, so I don't get how they're unrelated...

**Comment by VibhorCodecianGupta** [comment]
@jywarren Ah, I see. I'll open a fresh PR then. Removing files here is going to be messy.

**Pull request closed without merging**
