### PR TITLE
Fixes crop module bug

### LINKED ISSUE #979: Colorimetry plan
I'm documenting all of the steps required to go through a dual color analysis sequence for one of the #707 real-world use cases: colorimetric comparison!

Working [from this post](https://publiclab.org/notes/haines241/03-06-2018/smart-form-badge-lighting-analysis-experiments), i found a sample image of a colorimetric badge that reacted to formaldehyde, where one side got darker over a few hours. 

Here's the test image: 

badgelittle

**Note:** we assume that we can guide people to photograph the badge with consistent framing. That may be its own design challenge! We can show examples, and we can also show an overlay on the initial step's preview, so people can tell if their images are properly framed. 

My process was to crop the image so that we see only color from one of the two sides, so I used the crop module, but it had some bugs (that I think we can solve and then protect with better tests!). 

Screen Shot 2019-04-02 at 7 21 08 PM

The issues were mostly to do with the units in the `x` and `y` values I input. The image is 244x184 pixels, but here are the values I had to enter to get the left and right sides nicely cropped:

* Left: https://sequencer.publiclab.org/examples/#steps=crop{x:130|y:110|w:50|h:50},average{}
* Right: https://sequencer.publiclab.org/examples/#steps=crop{x:500|y:110|w:50|h:50},average{}

So, `130` for the left, and `500` for the right. Which can't be quite right! 

### Process

So, I think we could basically approach this use case in 2 ways:

1. We could have the starting module trigger 2 sequences, one for left and one for right. Each crops, then averages. Once both are done, we compare, for example, the average red channel of each. 
2. We run the left side (crop and average), then use the `import-image` module to re-import the original image, then run the right side. At the end, we look back and fetch the outputs from the two `average` steps (left and right), and compare the red channels of each. 

In both case we display the ratio of the red channel (for example) between the two sides.

Doing this manually, i get:

Left:

image

Right: 

image

### Next steps

So to list out the bugs we need to address, i think:

1. the main one is the x,y coordinate issue in the Crop module
2. there's a bad crop bug which inverts the image, here: https://github.com/publiclab/image-sequencer/issues/213

Then, I think we can try making a new demo file in `/examples/`, which displays the ratio from the above process!

### LINKED ISSUE #987: Drag to select crop UI is broken
#205 added this nice interface for cropping -- drag selection -- and #229 was supposed to build on this. However it seems broken now -- 

image

Looks like we're running `imgAreaSelect` on `imgEl` here:

https://github.com/publiclab/image-sequencer/blob/0e7323efa928972bfa26fd360bc616402b3e9957/src/modules/Crop/Ui.js#L74-L77

But `sequencer.steps[1].imgElement` doesn't return anything anymore.  It's supposed to be set here:

https://github.com/publiclab/image-sequencer/blob/985c67847e135806d99798f6f62cf7d7926e971f/examples/lib/defaultHtmlStepUi.js#L71

And `$("a img.img-thumbnail");` still returns elements, so that /should/ work...

Did I break it here? 

https://github.com/publiclab/image-sequencer/pull/960/files#diff-8fab943ef984aa24b7a63cbe4442daeaR71

Would love help fixing this! Then we should write a UI test for it -- send a click event to the image, and ensure that a selection box appears.

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #987    

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren please review.
I will be adding UI tests once its ok to you.

**Comment by Divy123** [comment]
ezgif-1-eefec2b8c744

**Comment by Divy123** [comment]
ezgif-1-eefec2b8c744

**Comment by Divy123** [comment]
@Divy123 please have a look!!

**Comment by jywarren** [comment]
Oh this looks good; can you test out the exact reproducible crop parameters
from the original issue? Thank you!

**Comment by Divy123** [comment]
If I am correct do you mean to write a UI test with these coordinates:

Screenshot from 2019-04-17 01-36-08

**Comment by Divy123** [comment]
If I am getting it correct, it means to have a UI test with these coordinates as input:
Screenshot from 2019-04-17 01-37-46

**Comment by jywarren** [comment]
Ah, sorry, actually the even older one, but it runs on the default image:
https://github.com/publiclab/image-sequencer/issues/213

This had been reliably reproducing the error:
https://sequencer.publiclab.org/examples/#steps=crop{x:127|y:127|w:266|h:266}

However, now maybe we are getting a new error, unfortunately... i'll file
this separately, but i see `Uncaught TypeError: Cannot read property
'description' of undefined` when i use this URL.

**Comment by jywarren** [comment]
OK, it was a cache issue related to #605 #953 -- now there's no error; however, it doesn't crop:

image

In any case this should be fixed by your code, no? Can you try these dimensions specifically? Thank you so much!!!

**Comment by jywarren** [comment]
And, shall we try adding a module test to protect this feature in the future? We could do a simple `looks-like` comparison like this:

https://github.com/publiclab/image-sequencer/blob/6fa8b1b8808d202355f51f9e3471d2f0423d3288/test/core/modules/contrast.js#L27-L40

**Comment by VibhorCodecianGupta** [comment]
@jywarren 
> OK, it was a cache issue related to #605 #953 
I'm not so sure. I was still able to reproduce this, on certain values of x and y. I'll recheck and post back here. I was looking into #213 and it's pretty confusing as to why the image is being altered. I'll try and see if it indeed is just a cache issue.

**Comment by HarshKhandeparkar** [comment]
Maybe it is because of the util functions which are included. I think this only occurs when the offset values are included

**Comment by Divy123** [comment]
> In any case this should be fixed by your code, no? Can you try these dimensions specifically? Thank you so much!!!

There are some issues related to crop module involving the way pixels are manipulated that's why these problems are arising.
Doing some changes here.

> And, shall we try adding a module test to protect this feature in the future? We could do a simple looks-like comparison like this:

Sure @jywarren!!

**Comment by Divy123** [comment]
@HarshKhandeparkar which of the util functions are you talking about?
What I am able to see this error is happening when x coordinates are changed.

When we change y ones, there are no errors its perfectly working.

**Comment by HarshKhandeparkar** [comment]
Probably parseCornerCoordinates. I don't know why I feel like the util func is a prob but I do.

**Comment by Divy123** [comment]
To this, actually the problem existed even before the utility was added. You can refer #213 is an year old issue. Also the func only generates the exact coordinates if user enters in %. The code you can see and is pretty simple. I don't think there might be a bug. @HarshKhandeparkar if you think there is can you point out please towards the line where it can be.

**Comment by jywarren** [comment]
Sorry, to clarify:

> OK, it was a cache issue related to #605 #953

I meant that the js error was a cache issue, not the color problems in the crop module. Thanks!

**Comment by jywarren** [comment]
And there are some good clues on what's causing the color issue... sometimes it's missing a blue channel, sometimes a red channel! So, it seems likely due to a 4-color-channel pixel manipulation error of some kind.

**Comment by Divy123** [comment]
Screenshot from 2019-04-17 20-45-55
@HarshKhandeparkar this is the o/p as seen after removing the utility function. I think  there is something other to it.

**Comment by Divy123** [comment]
@jywarren the problem is arising when we change the 'x' coordinates and not in case of y coordinates.
What d you think can be a probable reason for this?

**Comment by VibhorCodecianGupta** [comment]
Yes, @Divy123 I noticed the same in the afternoon. Have been trying to figure it out. I tried looking for issues with the jquery plugin itself, couldn't find one pertaining to this.

@jywarren thoughts on using some other well-maintained library for rewriting the module?

**Comment by Divy123** [comment]
I don't think this is related to imageareaselect. There is somewhat missing in pixel manipulation.
Figuring it out, will try to come up with a solution soon.

**Comment by HarshKhandeparkar** [comment]
@Divy123 no I don't have any doubts. Wait I'll look into the rest of the code in a min.

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HarshKhandeparkar** [comment]
Ah look at this file https://github.com/publiclab/image-sequencer/blob/main/src/modules/Crop/Crop.js
It creates a new unit8Array and saves the pixels itself. This is an old module. I think we should try using the extraManipulation func of PixelManipulation API.

**Comment by HarshKhandeparkar** [comment]
@Divy123 it doesn't even use PixelManipulation properly.

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Divy123** [comment]
@HarshKhandeparkar It does not matter if it uses old or new functionality, it should be correct.

Looking into it now.

Thanks!!

**Comment by HarshKhandeparkar** [comment]
Maybe the older functionality didn't include the 4th channel, alpha. Anyways, updating to the latest is to be done in any case.

**Comment by Divy123** [comment]
ezgif com-video-to-gif

@jywarren working as desired now!!
Please have a look!!
Will add the test if it's ok to you!!

**Comment by jywarren** [comment]
oh this is super. Yes! a test would be wonderful!!!

**Comment by HarshKhandeparkar** [comment]
What was the problem @Divy123.

**Comment by Divy123** [comment]
@HarshKhandeparkar there were a ceratin number of problems:
1) We were using incorrect parent of input
2) Somehow the css for imageareaselect was missing
3) Input was not triggered by change in imageareaselect
4) The pixels were manipulated incorrectly. I mean the logic used was partially incorrect.

**Comment by VibhorCodecianGupta** [comment]
@Divy123 great catch :D

**Comment by HarshKhandeparkar** [comment]
@Divy123 why don't you update this to use PixelManipulation API? That will also make it future proof.

**Comment by HarshKhandeparkar** [comment]
And a lot simpler to read and manage.

**Comment by Divy123** [comment]
I think restructuring can be made in another PR of all those modules that run on older modules.
Thanks !!

**Comment by Divy123** [comment]
The code-cov increases by 2.5% here after adding the test.
Hurraayy :tada: :tada: 
@jywarren please have a look!!

**Comment by jywarren** [comment]
Awesome!!!

**Comment by jywarren** [comment]
Great work!!!

**Pull request merged**
