### PR TITLE
Make progress bars on UI true

### PR DESCRIPTION
**Pull request by tech4GT**
@jywarren Please have a look, this should only draw progress bars if we pass ui true.

### CODE REVIEW

**Comment by tech4GT** [comment]
@Divy123 Can you leave the new benchmarks and the old ones here too! I think, not drawing the progress logs should give us a performance boost as well.

**Comment by Divy123** [comment]
Ya sure @tech4GT !!
Also request you to review:
https://github.com/publiclab/image-sequencer/pull/1093

**Comment by Divy123** [comment]
https://travis-ci.org/publiclab/image-sequencer/jobs/545906882#L647

https://travis-ci.org/publiclab/image-sequencer/jobs/545906882#L1317

**Comment by tech4GT** [comment]
Okay I compared, the improvement is not a lot, but it's definitely there!

**Comment by tech4GT** [comment]
Okay @Divy123 @jywarren I would appreciate if you guys can go through this and see if there's something I missed. After that we can merge! Moving on to is-app now!

**Comment by Divy123** [comment]
Thanks @tech4GT . The PR is ready to be merged!!

**Comment by jywarren** [comment]
This looks good! Needs a rebase but we can merge it then! Thanks!!

**Comment by tech4GT** [comment]
Oh! My bad looks like I rebased again! haha

**Comment by tech4GT** [comment]
Ok @jywarren I think we can merge this!

**Comment by jywarren** [comment]
Next time please "approve" it so we get to 2 approvals -- but it's OK i can override the limit 💪

**Comment by jywarren** [comment]
Did you need to bump the npm version?

**Comment by tech4GT** [comment]
I suppose this is not a very major change maybe we can do a path version or something?

**Comment by jywarren** [comment]
I think a 0.x.0 is fine!

**Comment by tech4GT** [comment]
Sure! Once you release on npm, I will update the dependencies in is-app and we should be able to see logs a little more clearly there.

**Pull request merged**
