### PR TITLE
Added how to run the debug script

### PR DESCRIPTION
**Pull request by Gayathrir1666**

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren this looks good, can be merged👍

**Comment by Gayathrir1666** [comment]
Thanks:)
I will create a new branch from next time.

**Comment by jywarren** [comment]
This is great. @tech4GT if you want to do a "review" and "approve" PRs, or even mark them `ready` i can merge these in a bit faster. Thanks a million to both of you, this is great.

**Comment by tech4GT** [comment]
@jywarren by marking ready you mean approving and commenting 'ready to be merged' right? I apologise i didn't understand exactly😅

**Comment by jywarren** [comment]
Yep! Thanks!

**Comment by tech4GT** [comment]
@jywarren no prob, always happy to help😁

**Comment by tech4GT** [comment]
@jywarren Oh i get it you were talking about adding a label to it😅
Actually I don't have the rights to label issues and prs yet...

**Comment by tech4GT** [comment]
@jywarren thanks a ton, now it's working, I'll be labelling prs with ready-to-merge from now on😁

**Pull request merged**
