### PR TITLE
Try To fetch latest data first then shift to cached one.

### LINKED ISSUE #1237: service worker responds with cache to fetch requests everytime its available
### Please describe the problem (or idea)

> What did you expect to see that you didn't?

[This](https://github.com/publiclab/image-sequencer/blob/main/examples/sw.js#L27) line in `sw.js` is responsible for responding with cache to every fetch request whenever the cache is available. Does this mean user would be getting a cached response every time? Do we have any cache invalidation techniques to make sure cache doesn't get stale?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by vivek-30**
Fixes #1237.
finally there is no such problem of having cached data every time . Service worker will now look for latest data first and then shift to cached one if request became unsuccessful.

### CODE REVIEW

**Comment by vivek-30** [comment]
@jywarren , @HarshKhandeparkar  could you please review this ☺️

**Comment by HarshKhandeparkar** [comment]
Sorry but my knowledge about service workers is just shy of -1 :joy:

**Comment by vivek-30** [comment]
> Sorry but my knowledge about service workers is just shy of -1 😂

No problem @HarshKhandeparkar  😊. you have a wide spectrum of knowledge though😅.

**Comment by jywarren** [comment]
Ah, interesting. Is this something we can write a test for as well? 

Is there a loading indicator shown while trying to fetch? I'm imagining a slow internet connection, or a 502 error, and if there'd be an option to bypass the wait and use the cache? 

Thank you @vivek-30 this is cool!

**Comment by vivek-30** [comment]
@jywarren i will add a loading animation for this and taking about the test . i have already created it when i solved another problem related to service worker
for this problem i have modified some code accordingly

**Comment by vivek-30** [comment]
hope you remember. btw great to see you after 3 days 😊

**Comment by vivek-30** [comment]
trying to bypass the wait is something which i feel is a little impractical. may be as the rendering time will be so quick even in slow connection and switching in the timeframe may lead to some unavoidable issues

**Comment by vivek-30** [comment]
still i will see what cool stuff i can generate meanwhile thanks☺️

**Comment by vivek-30** [comment]
@jywarren Did all the requested changes - 

https://user-images.githubusercontent.com/75980147/109126346-27f14600-7773-11eb-90af-2cc3300b5f83.mov

Also the loading animation is already present in the sequencer 😅   ,and thing which you want will require some ajax requests but as this is a single page application that kind of loading will not be required at all 
but now there will be a good offline experience for a user.it will be pre-cached auto. while installing a new service worker.

**Comment by vivek-30** [comment]
hope you like this 😊

**Review by jywarren — APPROVED** [review]
Very nicely done. Thank you so much!!!

**Pull request merged**
