### PR TITLE
Double Inversion Test

### PR DESCRIPTION
**Pull request by ccpandhare**
#### This Pull Request Includes:
* Fix for ImageManipulation.js
* An Additional Invert Module
* A new test - Double Inversion Test : As suggested in #29, This verifies that upon applying the `Invert` module, the image must change and upon applying the `Invert` module again, the resultant image is the original image.
* Removed the old `./examples/ndvi` folder

### CODE REVIEW

**Comment by jywarren** [comment]
omg this is tremendous. Ready to merge, yes?

**Comment by ccpandhare** [comment]
Yes, it's ready to merge!

**Comment by jywarren** [comment]
Uh oh, looks like this broke the build... Any idea why?

https://travis-ci.org/publiclab/image-sequencer/builds/248752455?utm_source=email&utm_medium=notification

**Comment by ccpandhare** [comment]
This is really weird... It passed on my Fork...
https://travis-ci.org/ccpandhare/image-sequencer
Will have a look.

**Comment by ccpandhare** [comment]
Surprising.
I just restarted the build and now it works!?
What might have happened?

**Pull request merged**
