### PR TITLE
Add: white balance module

### LINKED ISSUE #488: White balance module
I think this could be done with the OpenCV.js module which is under development in #237 -- but for what it's worth, it'd be great to have a white balance module:

https://stackoverflow.com/questions/51372779/color-balance-formula-adding-too-much-white

could help!

We'd love help with this one!

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #488 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
Follow up to PR #585 where the module was more of a colour temperature module, hence renamed in this PR. Added the white balance module according to this [algorithm](https://en.wikipedia.org/wiki/Color_balance#Scaling_monitor_R.2C_G.2C_and_B).
The whitest pixel data is used to scale the colours of all the other pixels in the image to render neutral colours better.
This PR is limited to explicitly specifying the RGB values in textboxes for the module, but this can be followed up by #796 to pick up the pixel values of the image and auto-fill the textboxes for RGB values. Once this is merged, I'll start working there.

Here is a working snapshot:

Screen Shot 2019-04-12 at 8 32 01 PM

@jywarren @tech4GT @publiclab/is-reviewers

**Comment by VibhorCodecianGupta** [comment]
@jywarren @tech4GT @publiclab/is-reviewers

**Comment by jywarren** [comment]
Hi, this is awesome!!

I'm really wanting to ask for tests on all modules these days so we gradually bring down our debt, so I hope it's all right if I ask for one here! Thanks @VibhorCodecianGupta !!!

**Comment by VibhorCodecianGupta** [comment]
@jywarren tests added!

**Comment by jywarren** [comment]
Awesome!!!!! Thanks!

**Pull request merged**
