### PR TITLE
Fixed Save Button

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/340

Save button gets enabled whenever there is a change in the value of the input.

fixed-save-btn-sequencer

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
I found out an issue. This doesn't work for select type input, the initial value is different.

**Comment by HarshKhandeparkar** [comment]
It also didn't use to update the initValue so saving more than once would break the save buttons. But this is fixed now in 'fix update initValue' commit.

**Comment by HarshKhandeparkar** [comment]
@tech4GT I have a suggestion, Can you open a new issue to change all the module inputs types to match their actual types. For e.g. angle for rotate module is a text type.

**Comment by HarshKhandeparkar** [comment]
Text-based input:

text-based-input-save-btn

I tried changing the field type to number but it only gives string type input. For number type inputs, 0.2 and 0.20 are actually considered as different even though they are not.

**Comment by HarshKhandeparkar** [comment]
I actually fixed this

**Comment by HarshKhandeparkar** [comment]
Fix: 

fixed-integer-inputs

**Comment by HarshKhandeparkar** [comment]
Hey I found something else. The form can be submitted through enter even though the button is disabled.

**Comment by HarshKhandeparkar** [comment]
I had to add the `e.preventDefault()` since the form reloads the page on submitting by default and adds some useless get methods to the URL.

**Comment by HarshKhandeparkar** [comment]
fix-save-to-enter-1

**Comment by HarshKhandeparkar** [comment]
fix-save-to-enter-2

**Comment by HarshKhandeparkar** [comment]
This solution works but I noticed that it slows down the browser significantly. What should I do?. @publiclab/reviewers please help.

**Comment by HarshKhandeparkar** [comment]
I found a better solution to this which works fast.

fast-save-1


fast-save-2

**Comment by HarshKhandeparkar** [comment]
The newer solution doesn't slow the browser down. How good is it? Can it be improved? @tech4GT @jywarren

**Comment by jywarren** [comment]
oh this is really nice!!!

**Comment by HarshKhandeparkar** [comment]
Please don't merge it as I want to test it for errors.

**Comment by tech4GT** [comment]
This is Great work Harsh! Awesome! I'll try this out in my browser :+1:

**Comment by HarshKhandeparkar** [comment]
@twch4GT this is broken for multi input forms. I am working on that. Will push a commit in a few mins.

**Comment by HarshKhandeparkar** [comment]
I will not be able to commit this today. Will do that tomorrow. Sorry

**Comment by HarshKhandeparkar** [comment]
The main change detection functionality is ready. The only problem I'm facing is that the `.input-form` is not wrapping all inputs including save button. I'll push one commit with the functions change detection now. I'll fix the form too but later today.

**Comment by HarshKhandeparkar** [comment]
This is also broken 


cache-remove-twice

**Comment by HarshKhandeparkar** [comment]
My fix in action:

multi-input:


dynamic-works



Range:


range-works

Value below it doesn't update though

Select:


select-works



Number:


number-works

**Comment by HarshKhandeparkar** [comment]
@tech4GT @jywarren please have a look at this. Also can you please test this on your own browsers Safari Chrome Edge etc. if possible? That will be helpful as I don't have Safari or Edge.

**Comment by HarshKhandeparkar** [comment]
@tech4GT @jywarren please have a look.

**Comment by jywarren** [comment]
OK, I'm merging https://github.com/publiclab/image-sequencer/pull/608 soon, but could you resolve the conflict in the defaultHtmlStepUi.js file? Thank you! And thanks for all the hard work, we'll get this merged soon!

**Comment by jywarren** [comment]
#608 is merged!

**Comment by HarshKhandeparkar** [comment]
@tech4GT @jywarren please have a look. Also I wanted to ask if ES6 features like `arrow functions`  and `template literals` can be used in the example page code?

**Comment by HarshKhandeparkar** [comment]
@jywarren I have an idea. Can we add a new module which takes text as input and adds a qr code to any place in the image like at the corners etc. Maybe to make a photo with a link or something?

**Comment by HarshKhandeparkar** [comment]
@jywarren can we use es6 in the example page code?

**Comment by jywarren** [comment]
What browsers is es6 compliant in? If almost all, then sure, but if there's an easy alternative, maybe not?

**Comment by HarshKhandeparkar** [comment]
I think arrow functions and template literals are supported by all
modern(>IE) browsers. https://kangax.github.io/compat-table/es6/

**Comment by HarshKhandeparkar** [comment]
@jywarren @tech4GT you can review this.

**Comment by HarshKhandeparkar** [comment]
@jywarren @tech4GT I have resolved conflicts please review. Also please look at my suggestion above 👆👆

**Comment by jywarren** [comment]
Hi, this is great. I'd like one more person to review it if possible -- maybe @Mridul97 ? Also be aware I'd like to merge this before https://github.com/publiclab/image-sequencer/pull/627, but after that one we may be able to start adding UI tests, which would be great to preserve and maintain these complex UI interactions. Great work!

**Comment by HarshKhandeparkar** [comment]
Thanks.

On 08-Jan-2019 12:02 AM, "Jeffrey Warren" <notifications@github.com> wrote:

Hi, this is great. I'd like one more person to review it if possible --
maybe @Mridul97 <https://github.com/Mridul97> ? Also be aware I'd like to
merge this before #627
<https://github.com/publiclab/image-sequencer/pull/627>, but after that one
we may be able to start adding UI tests, which would be great to preserve
and maintain these complex UI interactions. Great work!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/pull/562#issuecomment-452034356>,
or mute the thread

**Comment by HarshKhandeparkar** [comment]
@jywarren how is my suggestion about a new module above 👆 👆

**Comment by jywarren** [comment]
Hi, sure - perhaps you could open a new issue for that? it could be called `add-qr`

**Comment by HarshKhandeparkar** [comment]
> Hi, sure - perhaps you could open a new issue for that? it could be called `add-qr`

Thanks for the green signal. I will open the issue tomorrow.

**Comment by HarshKhandeparkar** [comment]
Thanks @Mridul97

**Comment by jywarren** [comment]
Awesome, thank you!!!

**Comment by HarshKhandeparkar** [comment]
Thanks @jywarren
I think https://github.com/publiclab/image-sequencer/issues/377 also should be closed?

**Pull request merged**
