### PR TITLE
fixed the demo

### LINKED ISSUE #290: drag/drop error on 1st step of demo
I tried uploading an image to the demo in gh-pages and got an error... a no module error, in https://publiclab.github.io/image-sequencer/examples/#steps=import-image,blend,ndvi,colormap

Can you check on this Varun? Thanks!!!

### PR DESCRIPTION
**Pull request by tech4GT**
fixes #290 
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren This should fix it!! Also I was wondering if I should push such small changes directly?

**Comment by jywarren** [comment]
No, i think it's good to be in a very consistent habit of PRs. As this is not part of the core module (yet) I'm not going to bump the version, but we should consider moving the /examples/lib/ demo code into the library -- we can break it into it's own repository eventually but let's get it building and tested first!

**Comment by tech4GT** [comment]
@jywarren i am now working on the minimize requirements issue, then I’ll complete the steps api core functions that we have discussed then let’s move to meta modules
I plan on completing all this before first evaluation, would this be enough?

**Comment by jywarren** [comment]
ambitious but sounds great!!! :-)

**Pull request merged**
