### PR TITLE
Added Eslint and husky

### LINKED ISSUE #1039: Code consistency with ESLint and Husky
To ensure that our commits and code-base remains consistent which makes understanding easier for the new contributors as well as the regular ones.

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #1039 
This pr references the pr #1048!

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

@publiclab/reviewers 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Great work, @aashna!!!

**Comment by aashna27** [comment]
Thanks a lot!! 😊😊😊

**Comment by jywarren** [comment]
Hi @aashna27 - i found I was unable to commit new code from the main branch into stable due to this running, i think. Any advice?

https://github.com/publiclab/image-sequencer/blob/main/package.json#L95

**Comment by jywarren** [comment]
@tech4GT i'm trying to publish your fixes, so just heads up here. If you can make a clean built PR against stable I'd merge it and publish.

**Comment by tech4GT** [comment]
@jywarren what do you mean by a “clean” pr? Sorry if that’s basic :sweat_smile:
Also are we distributing from the stable branch now? And what about the dist?

**Comment by jywarren** [comment]
Well I mean if you can compile dist and open a PR with it against stable, I
can release. Because yeah, we are releasing from stable, because we no
longer track dist in main. Thanks!!!

**Comment by jywarren** [comment]
Ah ok, so i temporarily disabled the pre-commit hook for husky, so I can commit and publish. Just checking, @aashna27 and @tech4GT -- what is the preferred workflow without doing that? 

v3.3.2 should be published shortly!

**Comment by tech4GT** [comment]
@jywarren do we still need the other pr?

**Comment by jywarren** [comment]
released 3.3.2!

**Comment by jywarren** [comment]
nope! by disabling husky for a bit, i was able to commit and publish. I still want to learn from @aashna27 what the ideal workflow is! But, for your project @tech4GT you can go ahead now.

**Comment by tech4GT** [comment]
Awesome! I’ll update the dependencies and tryout a full workflow. 😄

**Comment by aashna27** [comment]
Hey jywarren! Yeah husky will not let commits be pushed if the file being pushed has some errors according to the standards that have been set! And for now to not stop the commits being pushed i set those standards to not be followed and made this pr https://github.com/publiclab/image-sequencer/pull/1063
And also for future if we want husky to not verify the commit and push it  we use 
`git commit -m "message"  --no-verify`. So basically using `--no-verify` with the commit command. Thanks for your patience! 😊

**Comment by jywarren** [comment]
Ok got it! Thanks!!! And thank you for your patience too!

**Pull request merged**
