### PR TITLE
Updates to Demo

### PR DESCRIPTION
**Pull request by ccpandhare**
## Changelog
- Added "select" option for inputs with input type defined as "select" in their `info.json`
- Added loader

## Issues Solved
- #142 
- #120

### CODE REVIEW

**Comment by ccpandhare** [comment]
## Changelog 2
- Fixed "Select Image" (FileReader object was not defined)

**Comment by jywarren** [comment]
+1!

**Comment by jywarren** [comment]
Please go ahead and merge this if it's ready!

**Comment by ccpandhare** [comment]
Sure! :-)

Sorry I haven't been up-to-date recently, are there any more suggested
changes for the demo?

**Comment by jywarren** [comment]
Merging this! Well I just found some errors in the new Dynamic module, so if you have a chance... but yeah i think the next big thing will be trying to make new module creation steps even easier.

**Pull request merged**
