### PR TITLE
circular gradient module

### PR DESCRIPTION
**Pull request by niravasher**
#869

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by niravasher** [comment]
Screenshot from 2020-01-14 16-22-59
fixing some previously remaining bugs. @HarshKhandeparkar

**Comment by root00198** [comment]
Insted of creating a new module, we can give 'Circular' option in the gradient module.

**Comment by niravasher** [comment]
Ok! Will do that @root00198

**Comment by root00198** [comment]
It's just an idea, Let a reviewer comment on it, before you start working....

**Comment by niravasher** [comment]
Okay

**Comment by HarshKhandeparkar** [comment]
> Insted of creating a new module, we can give 'Circular' option in the gradient module.

Nice idea!

**Comment by niravasher** [comment]
@root00198 @HarshKhandeparkar PR updated. Please review

**Comment by niravasher** [comment]
Yes, will do that @jywarren

**Comment by niravasher** [comment]
Benchmark is the datauri of the circular gradient

`options = {
    gradientType = circular
}
testModule('gradient', options, benchmark);
`
What is the cmd to test only one module? @jywarren @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Only one module meaning? I didn't get you. What are you trying to do?

**Comment by niravasher** [comment]
Ahh, done. Should I open up a new PR for this or update this one? @jywarren @HarshKhandeparkar

**Comment by root00198** [comment]
update this one

**Comment by niravasher** [comment]
Please merge this PR, I write test in a follow up PR. I am stuck with some merge conflicts @jywarren

**Comment by HarshKhandeparkar** [comment]
Try to solve the conflicts. This will help you in the future.

**Comment by niravasher** [comment]
This module is complete with test. Please review and merge this. @jywarren @root00198

**Comment by niravasher** [comment]
Please merge this PR @jywarren

**Comment by jywarren** [comment]
Awesome!!

**Pull request merged**
