### PR TITLE
Adding an installation message to user in the CLI

### PR DESCRIPTION
**Pull request by mynkdhmn**
This is my first PR. I am open to suggestion.

### CODE REVIEW

**Comment by tech4GT** [comment]
@mynkdhmn This issue has been reserved for GCI, It would be great If you could take up an issue which is not labelled with `gci`. Thanks for your PR!😄

**Comment by mynkdhmn** [comment]
Okay! Thanks.

**Comment by jywarren** [comment]
@tech4GT maybe we should not tag reserved issues as FTOs just yet then? Just as fto-candidate?

**Comment by tech4GT** [comment]
Sure! I'll make the changes!

**Comment by tech4GT** [comment]
@jywarren Okay so now I have tagged the `small` gci-candidate issues as fto-candidates, does it seem fine now?

**Comment by jywarren** [comment]
Sure I'm just thinking any full "first-timers-only" issue will attract
people before we're ready so we could delay the labeling until they're
launched. Make sense? Thanks!

**Comment by tech4GT** [comment]
Yeah, I get it! I'll take care of the labelling more closely now! Thanks!

**Pull request closed without merging**
