### PR TITLE
Change row major to column major

### LINKED ISSUE #1570: Corrupted pixels.data for some modules
### Please describe the problem (or idea)
Some modules like decode-qr, text-overlay ,fisheye-gl don't work for gifs and we have to use get-dataurl to solve the problem 
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ataata107**
Fixes #1570   (<=== Replace `0000` with the Issue Number)

1. In #1533 we had started using getdataurl method in [module](https://github.com/publiclab/image-sequencer/blob/main/src/modules/TextOverlay/Module.js#L13) itself this pr will solve that
2. In #1466 the data required by the jsqr [module](https://github.com/publiclab/image-sequencer/blob/main/src/modules/DecodeQr/Module.js#L24) should be column major in order to be decoded. This PR will solve that. Right now only the gifs having same width and height could be decoded (being row major doesn't affect them) 
3. After merging this PR it will also solve FishEyegl module

Unlike gifs the images had their pixels stored in column major form. This is from where i got the idea. This issue was a really nice one XD

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] ask `@publiclab/is-reviewers` for help, in a comment below
* [X] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by ataata107** [comment]
@publiclab/is-reviewers

**Comment by ataata107** [comment]
Can someone review this as it will solve the issues faced by some modules right now.

**Comment by blurry-x-face** [comment]
@ataata107 why are tests failing? Can you please restart the build

**Comment by HarshKhandeparkar** [comment]
Can we work on this after February?  Is it extremely important? Does it fix something?

**Comment by HarshKhandeparkar** [comment]
Oh, it fixes a bug? What does it fix? I couldn't understand what it does.

**Comment by ataata107** [comment]
dither
This was the output using floydsteinberg algorithm in the main branch of the dither module. I guess the above output is incorrect. This is the output by this pr
dither (1)
This is why the tests were failing also I have modified the same

**Comment by ataata107** [comment]
Same is happening with edge detect, I will change that too soon

**Comment by ataata107** [comment]
Yes it fixes bugs faced by gifs. Actually you can see the bug by printing the stride of pixels in the console. Pixels of the gifs and the images have different strides( which should not be the case)

Some modules don’t require pixels as whole but specifically pixels.data 
Stride information is only stored in pixels. I feel this could be reason why some modules had been behaving differently for images and gifs as the modules expect the pixels.data to be stored in column major

**Comment by HarshKhandeparkar** [comment]
Oh no! Why was the stride different?

**Comment by HarshKhandeparkar** [comment]
Outdated slightly. Closing for now. Please feel free to rebase and reopen :)

**Pull request closed without merging**
