### PR TITLE
Fix ExtraManipulation

### LINKED ISSUE #1547: Problem in extraManipulation
After #1533 some modules are facing problem because of 
https://github.com/publiclab/image-sequencer/blob/2b3e5a2915262acb41cd6a9e39ab4b20807a5eb1/src/modules/_nomodule/PixelManipulation.js#L317
My #1546 was working fine before addition of this code but after its addition it has broken for some reason.
Also many of the tests were also failing [ref](https://github.com/publiclab/image-sequencer/pull/1542#issuecomment-576289735)

We need to fix this soon!

### PR DESCRIPTION
**Pull request by blurry-x-face**
Fixes #1547 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by root00198** [comment]
It looks good though..

**Comment by jywarren** [comment]
Hmm @blurry-x-face @root00198 this is oddly taking a long time...?

**Comment by root00198** [comment]
I think you can restart the build...

**Comment by jywarren** [comment]
Going to try restarting it.

**Comment by jywarren** [comment]
OK Awesome! I'll merge this, can you warn some other PR folks to rebase theirs? Thank you!

**Pull request merged**
