### PR TITLE
[GCI] Added Lightning Bolt for WASM accelerated modules

### LINKED ISSUE #1320: Add lightening bolt icon at the top of step panel to show if the step is wasm accelerated.
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Add lightening bolt icon at the top of step panel to show if the step is wasm accelerated.

### Please show us where to look

https://beta.sequencer.publiclab.org

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #1320   (<=== Replace `0000` with the Issue Number)

I think the issue asks to show an icon for modules that support WASM. But WASM can also fail. So I added an extra bit - Check if it succeeded or not and notify the UI. This makes it so that the icon is shown only if the WASM succeeds. 
I also added a nice tooltip to the icon.

What works:
- The tooltip is shown!
- The icon is shown only when `useWasm` flag is set to `true`, the module uses it **and** wasm succeded

wasm-tooltip

What doesn't work:
- Meta modules cannot transfer information about whether WASM succeded or not because of the way they are built - Also since meta modules are a combo of many other modules, they can individually succeed or fail in WASM so the final output is indeterminate.
- Some modules just don't use WASM. eg: Crop, WebGLDistort, etc.
- WASM just fails for some modules eg: Contrast. IDK why.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Out of the 41 file changes, most are just repeated `Module.js` code changes. Same change everywhere.
Overall I changed:
1. `defaultHtmlStepUi.js`
2. `demo.css`
3. `PixelManipulation.js`
4. `src/Run.js`
5. `Module.js` x 37

**Comment by HarshKhandeparkar** [comment]
@jywarren @Divy123 could you please review this?

**Comment by jywarren** [comment]
Hi! If wasm fails maybe we should show a red lightning icon?

This is really nice. Is there anything we should think of that's changing documentation for module requirements that we should include in the readmes? Thanks!

**Comment by jywarren** [comment]
Also, I believe it needs a rebase! Thanks Harsh!

**Comment by HarshKhandeparkar** [comment]
@jywarren I'll do the rebase. I don't think the red bolt is required
because it is just a UI, red would be for debugging purposes. Users don't
care whether wasm worked or not. As for the debugging, it already logs an
error to the console. Also the code doesn't differentiate between `wasm
failed` and `wasm not used`.

I had checked the docs, I don't think we need to add anything. If we have
to, we will have to add a lot more. Many things like the
`pixelManipulation.js` are not fully documented. Maybe this can be a GCI
issue?

**Comment by HarshKhandeparkar** [comment]
@jywarren please try to merge this today. I want to claim the HoF task (about caching). I had done some work on it around 9 months back. I want to continue the work. Remember the PR for using package.json version for cache?

**Comment by jywarren** [comment]
Awesome!!!!

**Pull request merged**
