### PR TITLE
Surge to generate the demo

### LINKED ISSUE #832: Use Surge to generate working demo from each PR?
Wow, surge is pretty cool!  https://surge.sh/

@subhahu123 has opened this PR on the `community-toolbox` project to auto-generate a static site from each PR. We could potentially have this generate a working version of `image-sequencer` based on each PR... what do you think? 

https://github.com/publiclab/community-toolbox/pull/147/checks?check_run_id=71695437#

### PR DESCRIPTION
**Pull request by harshithpabbati**
Fixes #832 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers review it :)

**Comment by Harshithpabbati** [comment]
@jywarren see this.

**Comment by Harshithpabbati** [comment]
I need to include the node modules isn't it ???

**Comment by Harshithpabbati** [comment]
And the dist files.

**Comment by subhahu123** [comment]
> I need to include the node modules isn't it ???

check the above surge link to know more

**Comment by Harshithpabbati** [comment]
Yeah I seen it. I need to build it and then pushing all the dist files and node modules.

**Comment by subhahu123** [comment]
@Harshithpabbati  i  u want something to add to deploy which it ignores by default like github does 
u can create a file .surgeignore to ignore them or config according to ur need
go to doc to know more

**Comment by subhahu123** [comment]
> Yeah I seen it. I need to build it and then pushing all the dist files and node modules.

i don't know much about this repo so it's only u ............

**Comment by Harshithpabbati** [comment]
Fine I will make it out.

**Comment by subhahu123** [comment]
> Fine I will make it out.

include the surge link in ur pr comment also so that others developers can help u also by reviewing that
link

**Comment by HarshKhandeparkar** [comment]
Subhahu, can we force commit something to surge which is gitignored in the repo?

**Comment by subhahu123** [comment]
> Subhahu, can we force commit something to surge which is gitignored in the repo?

yes using .surgeignore
for more info u can check it's docs

**Comment by Harshithpabbati** [comment]
I will check the docs and will make the change

**Comment by Harshithpabbati** [comment]
I have a doubt surge is used for providing the static sites but how can this deploy a dynamic one ???

**Comment by Harshithpabbati** [comment]
@aashna27 see this.

**Comment by aashna27** [comment]
Ohh ohkayy! I see you have some trouble here, ohkayy, I ll have a read of surge and then we will be able to solve this.

**Comment by subhahu123** [comment]
@Harshithpabbati  node modules are not included in the surge links;

**Comment by HarshKhandeparkar** [comment]
Branch deleted

**Pull request closed without merging**
