### PR TITLE
media query for buttons

### LINKED ISSUE #582: Improving buttons for smaller screens
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The buttons `save sequence` and `view gif` are too wide and have no margin at all in mobile and tablet views. They even flow out of the div, and hence out of the device screen. This is undesirable, buttons should change their shape according to the device.

screen shot 2018-12-31 at 10 33 56 pm

screen shot 2018-12-31 at 10 34 28 pm

> What did you expect to see that you didn't?

Well-aligned and spaced buttons

### Please show us where to look

http://sequencer.publiclab.org

> This can help us diagnose the issue:

Observe the mobile/tablet view

### Browser, version, and operating system

Chrome/Safari; OSX 10.13

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #582 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
Fixed buttons. Introduced margin and proper width. @jywarren @tech4GT please have a look

screen shot 2018-12-31 at 11 02 05 pm

screen shot 2018-12-31 at 11 02 16 pm

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta what about the quick buttons? They too overflow. Can you fix those? Its really annoying on smaller screens.

**Comment by HarshKhandeparkar** [comment]
How about giving the preview images a bootstrap class of `.img`?

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar will look into it!

**Comment by HarshKhandeparkar** [comment]
Sorry I think the class is `.img-fluid` which makes the image responsive.

**Comment by VibhorCodecianGupta** [comment]
@jywarren yes, this can be achieved using btn-block as well, but the white panel behind the two buttons doesn't adjust it's size, and additional css might be required there (which I haven't figured out yet). Example:

screen shot 2019-01-03 at 11 22 20 am

How would you suggest we proceed? Using `btn-block` gets the desired result without changing the size of the background `panel` though.

**Comment by HarshKhandeparkar** [comment]
How about arranging the buttons one below the other on small screens?

**Comment by HarshKhandeparkar** [comment]
I'm not. LOL I'm actually a GCI student. I met publiclab in GCI this year. 😅

**Comment by VibhorCodecianGupta** [comment]
Oh! Hahaha, that's great. Nice to see you stuck with the Org!

**Comment by HarshKhandeparkar** [comment]
Yep JS is my favourite programming language so I like publiclab/image-sequencer.

**Comment by jywarren** [comment]
I think btn-block sounds good for now, too -- if we're going to do a larger
redesign, best not spend too much time on custom media queries, perhaps,
until we're sure how it will look? Thank you!

**Comment by VibhorCodecianGupta** [comment]
Nice. I'll push the changes in a minute then.

**Comment by VibhorCodecianGupta** [comment]
@jywarren have a look if you may, pushed the easy fix. Looks like so:

**Tablet view**
screen shot 2019-01-04 at 11 19 52 pm

**Mobile view**
screen shot 2019-01-04 at 11 20 01 pm

**Comment by jywarren** [comment]
This looks ok for now. Would you want to try adding "overflow:scroll;" CSS
to the thumbnails container? I'm not sure it'll work, but potentially in
touchscreens people could drag it back and forth. Small improvement -- we
could do it in a follow-up if you want, or here!

**Comment by VibhorCodecianGupta** [comment]
@jywarren scrolling works for the quick icons. Had to write a media query for the mobile screens because of the `brightness` icon not aligning with the left border of the panel by default like so:

screen shot 2019-01-05 at 1 43 39 pm

after putting the scroll and the media query to justify evenly (for mobile screens only, because it works perfectly otherwise), here is how it looks like (notice the scrollbar :D) :

screen shot 2019-01-05 at 1 45 13 pm

**Comment by jywarren** [comment]
Rebased and rebuilt!

**Comment by jywarren** [comment]
Done. Nice!!!

**Pull request merged**
