### PR TITLE
Used `pixels.set` To Refactor DrawRectangle

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Found a better way to do this using `pixels.set` method.

Works just fine:

refactor-rectangle-again

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@Mridul97 I have posted a GIF in the PR body itself.

**Comment by Mridul97** [comment]
> @Mridul97 I have posted a GIF in the PR body itself.

oh! sorry my bad, Looks good, great work!

**Comment by HarshKhandeparkar** [comment]
Thanks!

**Comment by jywarren** [comment]
Sorry, one more time, thanks! I'm now also using `needs-rebase` so we can coordinate which PRs need rebasing as we go. Thanks! (and noting this to @publiclab/is-reviewers)

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers conflicts resolved!!

**Comment by HarshKhandeparkar** [comment]
Thanks!! Cannot believe this was 20d old. Seems like yesterday 😄

**Comment by jywarren** [comment]
😁🙌🎉

**Pull request merged**
