### PR TITLE
Accept type images in input field Fixes#364

### PR DESCRIPTION
**Pull request by aashna27**
Fixes: 364

The old input field was accepting all kinds of files
**Changes**: Added accept attribute to add images only.

### CODE REVIEW

**Comment by rockstar777** [comment]
@aashna27 you should have first claim to solve an issue.
awesome work
thanks

**Comment by tech4GT** [comment]
Thanks a lot for your pull request @aashna27 
I'll take a look at this! Meanwhile do try other issues. Thanks! 😄

**Comment by tech4GT** [comment]
Okay so the accept attribute is not supported on edge as far as I remember,  so let's wait to hear from @jywarren 
@aashna27 maybe you can look for some workaround for edge.Thanks!

**Comment by aashna27** [comment]
I would like to share a gif of the image upload field.

The earlier one was accepting All files for upload.
animated gif-downsized_large 2

The changer one 
animated gif-downsized_large 1

**Comment by jywarren** [comment]
Hmm, what happens on edge? Will it still work but just won't limit the file type? Thanks!!!

**Comment by jywarren** [comment]
🎉

**Pull request merged**
