### PR TITLE
NPM Audit Fixes

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #0000  (<=== Replace `0000` with the Issue Number)

**20k** Audit fixes.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
oof, a few errors but maybe not too bad? 

```

5.93s$ grunt tests && npm run core-tests
Running "browserify:tests" (browserify) task
>> Error: Parsing file /home/travis/build/publiclab/image-sequencer/node_modules/fast-glob/out/readers/stream.js: Unexpected token (16:10)
Warning: Error running grunt-browserify. Use --force to continue.
Aborted due to warnings.
The command "grunt tests && npm run core-tests" exited with 6.
```

```
> image-sequencer@3.5.1 test-ui-2 /home/travis/build/publiclab/image-sequencer
> node ./node_modules/.bin/jest
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! image-sequencer@3.5.1 test-ui-2: `node ./node_modules/.bin/jest`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 test-ui-2 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-10-16T16_12_12_994Z-debug.log
The command "npm run test-ui-2" exited with 6.
```

**Comment by jywarren** [comment]
I wonder if this is related to the breaking change in the jQuery bump? https://github.com/publiclab/image-sequencer/pull/1666#issuecomment-704396082

**Comment by jywarren** [comment]
Will try restarting to see if anything changes, just in case...

**Comment by jywarren** [comment]
Regarding the `jest` error --

https://github.com/facebook/jest/issues/7803 or https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle maybe?

**Comment by HarshKhandeparkar** [comment]
I was thinking of including this in v3.6.0

**Comment by jywarren** [comment]
sure if we can get it to pass! If not, we can address it as a priority in
3.6.1 perhaps.

**Comment by HarshKhandeparkar** [comment]
Doesn't look like this is a jquery issue. We will see in 3.6.1 :)
cc: @jywarren

**Comment by HarshKhandeparkar** [comment]
Outdated.

**Pull request closed without merging**
