### PR TITLE
refactor and remove hysteresis

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>
related to #323 
- Refactored edge-utils.js and blur.js files according to our coding style
- Removed `data-uri-to-buffer` from dev-dependency since it is already a production dependency
- Removed `hysteresis` step from edge detector, responsible for connected component labelling until I am able to implement an efficient algorithm for this. This will result in a little more noisier product but it's not going to be that noticeable.
screen shot 2018-09-04 at 9 37 26 pm

### CODE REVIEW

**Comment by jywarren** [comment]
Great, and yes, we can do that as a separate or add-on module later. Ready to merge here?

**Comment by tech4GT** [comment]
Ready to merge

**Comment by jywarren** [comment]
Oops, forgot to merge this! I just bumped the version number and then will merge in. 

@tech4GT how are things going? How's school work? 

I was thinking about what's next with this... in terms of prioritization. What do you think? I'm wondering also how big a project the fully-isolated meta modules #315 will be. I'm sure you have a lot of work though! Just excited :-)

**Comment by tech4GT** [comment]
@jywarren School's great! I've been mostly busy with campus recruitment and recently got an offer from Expedia group😄I'll try to put in the opaque meta-modules work asap but again I have mid terms coming up, but I'll try to wrap this up before that. i've been thinking about this and i guess it's not that complex as we originally though it would be :laughing:

**Comment by jywarren** [comment]
ooh! very cool! congrats and best of luck!

For sure and that'd be awesome to see. Thanks, Varun!

**Pull request merged**
