### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by tech4GT**
@jywarren presenting sequencer version 2!!! 🎉🎉🎉

### CODE REVIEW

**Comment by jywarren** [comment]
Great and if you tweet, highlight the new Run syntax!

**Comment by tech4GT** [comment]
@jywarren shouldn't we tweet from publiclab's handle??

**Comment by tech4GT** [comment]
@jywarren who handles publiclab's twitter??

**Comment by jywarren** [comment]
If you tweet, we will retweet!

**Pull request merged**
