### PR TITLE
Enable processing on an alternate thread

### PR DESCRIPTION
**Pull request by Mridul97**
Issue #159

### CODE REVIEW

**Comment by jywarren** [comment]
Just a heads up that I've made a new url for the demo!

http://sequencer.publiclab.org

:-)

@rockstar777 @ccpandhare @tech4gt

**Comment by tech4GT** [comment]
@Mridul97 Hi! how's it going? SO where are we with this one? I mean what is the current state, are we getting any errors or unexpected behavior?
PS Thanks for your patience!

**Comment by Mridul97** [comment]
Hi! we are not getting any errors but we are also not getting the desired output. Actually we are not getting any output.

**Comment by tech4GT** [comment]
Hmm, I'll pull your branch and look into it!

**Comment by gauravano** [comment]
@tech4GT

**Comment by HarshKhandeparkar** [comment]
@Mridul97 @jywarren let's revive this PR by opening a new issue and a new PR.

**Pull request closed without merging**
