### PR TITLE
Try Failing Travis

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #[Add issue number here.]
 Checking if travis fails in node 6 if  `set -e` command is used
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren travis has failed but not because of reasons that it has to fail, it has failed due to a different totally unexpected reason. Please check out the job log.

**Comment by HarshKhandeparkar** [comment]
I reverted the changes and it passed again.

**Comment by jywarren** [comment]
OK, so the take-away here is that we should drop Node 6? Thank you! Did you want to try removing it from our .travis.yml file?

**Comment by HarshKhandeparkar** [comment]
I tried adding set -e and travia failed. I added set +e(which is thde default)  and removed set -e and it passed. But it didn't fail because of the error but it failed because cc reporter said that kt cannot find anything. Please have a look at the job log.

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta please have a look

**Pull request closed without merging**
