### PR TITLE
Add grid of thumbnails

### PR DESCRIPTION
**Pull request by JonathanXu1**
Solves https://github.com/publiclab/image-sequencer/issues/247#issuecomment-441116832
A continuation of https://github.com/publiclab/image-sequencer/pull/535, this PR includes all its features while improving on the UI of the solution. Here's a screenshot:
image

Images are zoomed in for better viewing, and scaled to fit a square div without affecting aspect ratio. Icons are overlaid above as well.

@okonek is welcome to apply these changes to his PR as I don't have push access to his branch.

### CODE REVIEW

**Comment by jywarren** [comment]
This is super! Great work both of you!!!

**Comment by JonathanXu1** [comment]
@jywarren I've claimed this task on GCI. There's only 4 hours left on it so it might expire soon! Thanks!

**Comment by tech4GT** [comment]
I just approved your task, awesome!😄

**Comment by JonathanXu1** [comment]
Wow I really appreciate the speedy response from you guys! <3 public lab

**Pull request merged**
