### PR TITLE
Added Threshold

### LINKED ISSUE #723: Add Threshold Module
### A threshold module is used to convert images to binary form, reducing most of the noise. There are various ways by which it's done

> What could this idea solve?

It is useful to be able to separate out the regions of the image corresponding to objects in which we are interested, from the regions of the image that correspond to background. Thresholding often provides an easy and convenient way to perform this segmentation on the basis of the different intensities or colors in the foreground and background regions of an image.

### Please show us where to look

http://sequencer.publiclab.org...

## Thank you!

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #723 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

image

image

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by aashna27** [comment]
I ll be pushing more commits here , the module isn't complete yet .. but I am a little busy for next 7 days and wanted to atleast start with this , so I pushed just this much. Would be adding more algorithms once am free, probably for automatic threshold and maybe some more.

**Comment by HarshKhandeparkar** [comment]
@aashna27 can you please link this pr to another issue(maybe a new one) as it links to a discussion issue which will get closed once the pr is merged which should not happen.

**Comment by aashna27** [comment]
> 
> 
> @aashna27 can you please link this pr to another issue(maybe a new one) as it links to a discussion issue which will get closed once the pr is merged which should not happen.

Oops too many mistakes.

**Comment by HarshKhandeparkar** [comment]
We all make mistakes 😊

On 28-Jan-2019 12:30 AM, "aashna27" <notifications@github.com> wrote:

@aashna27 <https://github.com/aashna27> can you please link this pr to
another issue(maybe a new one) as it links to a discussion issue which will
get closed once the pr is merged which should not happen.

Oops too many mistakes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/pull/722#issuecomment-457944369>,
or mute the thread

**Comment by HarshKhandeparkar** [comment]
@aashna27 your pr links to another pr not an issue 😅

**Comment by aashna27** [comment]
> 
> 
> @aashna27 your pr links to another pr not an issue 😅

I am messing so much 😭

**Comment by HarshKhandeparkar** [comment]
> > @aashna27 your pr links to another pr not an issue sweat_smile
> 
> I am messing so much

🤣

**Comment by aashna27** [comment]
ezgif com-video-to-gif 1

**Comment by aashna27** [comment]
Thanks @VibhorCodecianGupta

**Comment by aashna27** [comment]
@jywarren

**Comment by jywarren** [comment]
Hi, this is super! In the spirit of the new per-module tests, can I ask that this be submitted with a simple test as in the examples in `/test/modules/...`, using `looks-like`? Thank you!!!

**Comment by aashna27** [comment]
@jywarren please have a look, I have added the tests and rebased.

**Comment by jywarren** [comment]
Rebasing one more time as i'm doing a few in a row!

**Comment by aashna27** [comment]
> 
> 
> Rebasing one more time as i'm doing a few in a row!

yeaa am rebasing again due to the conflicts

**Comment by aashna27** [comment]
> 
> 
> > Rebasing one more time as i'm doing a few in a row!
> 
> yeaa am rebasing again due to the conflicts



> 
> 
> Rebasing one more time as i'm doing a few in a row!

Do you want me to wait till you clear the backlog ?

**Comment by jywarren** [comment]
Oh oops i had pushed a rebase here already! But let's see how yours does too. Thanks!

**Comment by aashna27** [comment]
> Oh oops i had pushed a rebase here already! But let's see how yours does too. Thanks!

😆 Now it's ready

**Comment by jywarren** [comment]
Great, super work!

**Pull request merged**
