### PR TITLE
Add contrast module

### LINKED ISSUE #157: Add a Contrast module

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #157 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
Some screenshots of the output:

Original Picture:
ss_23

Contrast : 30
ss_24

Contrast : 70
ss_23

**Comment by jywarren** [comment]
This is looking great, but I think it may need to be rebased since some time has passed. But very grateful for this new module!!!

**Comment by Mridul97** [comment]
I have rebased it. Please have a look! :smiley:

**Comment by jywarren** [comment]
Hmm, do you know why the tests are failing? If it seems unrelated to your work you could close and reopen to rerun the tests...

Thanks @Mridul97 !!

**Comment by Mridul97** [comment]
In the job log, It is showing: Error: Cannot find module './modules/Contrast' from '/home/travis/build/publiclab/image-sequencer/src'. Trying to figure out why this is happening.

**Comment by Mridul97** [comment]
Its solved. Please have a look! :smiley:

**Comment by jywarren** [comment]
Perfect, great work!!!

**Comment by jywarren** [comment]
Wow, this project is really moving fast! So many new modules... 👍 

You've really been doing good work :-)

**Pull request merged**
