### PR TITLE
The cursor changes to pointer when hovered over select element

### LINKED ISSUE #913: cursor should change into pointer
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you `gift_heart`

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Please describe the problem (or idea)

Peek 2019-03-21 22-07

Peek 2019-03-21 22-11

### PR DESCRIPTION
**Pull request by rohithGoudM**
Fixes #913

This is my first PR, so please let me know even if it is wrong.
I really want to contribute here (publiclab)
Any kind of reply would be greatly appreciated

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Ok you opened a pr. @publiclab/is-reviewers will review your pr.

**Comment by subhahu123** [comment]
@rohithGoudM  can u provide a preview link
u can use github pages

**Comment by HarshKhandeparkar** [comment]
Hey @subhahu123 you are quite good. Would you like to be a reviewer?( A member of publiclab/is-reviewers)

**Comment by subhahu123** [comment]
> Hey @subhahu123 you are quite good. Would you like to be a reviewer?( A member of publiclab/is-reviewers)

Yes

**Comment by rohithGoudM** [comment]
> Can you put the styles in `examples/demo.css` ?

Yes,
But I also want to know what should I do to get into publiclab for gsoc2019.

**Comment by HarshKhandeparkar** [comment]
Check out issue #656 for the prerequisites and ping jywarren to request a join.

**Comment by HarshKhandeparkar** [comment]
@rohithGoudM
> Yes,
But I also want to know what should I do to get into publiclab for gsoc2019.

Nothing. Wait for this pr to be merged. You will get an invite to join publiclab and you can participate.

**Comment by subhahu123** [comment]
> Check out issue #656 for the prerequisites and ping jywarren to request a join.

done

**Comment by HarshKhandeparkar** [comment]
You should know the codebase well. You can solve a few issues and you will be well acquainted with the codebase. 😊. I don't know much about gsoc and the proposals etc. You can ask @gauravano @jywarren @tech4GT or other @publiclab/is-reviewers

**Comment by subhahu123** [comment]
> > Can you put the styles in `examples/demo.css` ?
> 
> Yes,
> But I also want to know what should I do to get into publiclab for gsoc2019.

as far as i know ( i m also applying ) u should continue contributing to publiclab and select ur project u want to work on and prepare a propoal for that

**Comment by rohithGoudM** [comment]
> > > Can you put the styles in `examples/demo.css` ?
> > 
> > 
> > Yes,
> > But I also want to know what should I do to get into publiclab for gsoc2019.
> 
> as far as i know ( i m also applying ) u should continue contributing to publiclab and select ur project u want to work on and prepare a propoal for that

I want to work on image-sequencer
I like the idea but how can i make any impression on publiclab's recruiting team

**Comment by subhahu123** [comment]
> > > > Can you put the styles in `examples/demo.css` ?
> > > 
> > > 
> > > Yes,
> > > But I also want to know what should I do to get into publiclab for gsoc2019.
> > 
> > 
> > as far as i know ( i m also applying ) u should continue contributing to publiclab and select ur project u want to work on and prepare a propoal for that
> 
> I want to work on image-sequencer
> I like the idea but how can i make any impression on publiclab's recruiting team

ur contibution is only way to get an impression and then after ur proposal idea

**Comment by rohithGoudM** [comment]
> Can you put the styles in `examples/demo.css` ?

Done.

**Comment by rohithGoudM** [comment]
Is my PR eligible for merging..?
Can I solve other issues that has `first-timers-only` issues..?
If not could you refer some issues here so I can try solving them..?

**Comment by subhahu123** [comment]
> Is my PR eligible for merging..?
> Can I solve other issues that has `first-timers-only` issues..?
> If not could you refer some issues here so I can try solving them..?

https://github.com/publiclab/image-sequencer/issues/924
solve this one

**Comment by HarshKhandeparkar** [comment]
You can solve any issue. I don't think there are any more First-Timers-Only issues left but there may be some which are marked as `fto-candidate` issues and also there are some with the label `small`. Also which field are you best in? Js/html/css? We can assign you issues based on that. Of you are good with js, you can see check out some core library issues with the `module` label.

**Comment by rohithGoudM** [comment]
> > Is my PR eligible for merging..?
> > Can I solve other issues that has `first-timers-only` issues..?
> > If not could you refer some issues here so I can try solving them..?
> 
> #924
> solve this one

ON it.

**Comment by rohithGoudM** [comment]
> You can solve any issue. I don't think there are any more First-Timers-Only issues left but there may be some which are marked as `fto-candidate` issues and also there are some with the label `small`. Also which field are you best in? Js/html/css? We can assign you issues based on that. Of you are good with js, you can see check out some core library issues with the `module` label.

I have a little background in js through node js. Also happy to help with html and css.

**Comment by HarshKhandeparkar** [comment]
@subhahu123 is this ready to merge? Have you checked out the changes locally?

**Comment by subhahu123** [comment]
> @subhahu123 is this ready to merge? Have you checked out the changes locally?

i have not checked this locally

**Comment by subhahu123** [comment]
@HarshKhandeparkar 
what are the changes in package.json
it  was not required

**Comment by subhahu123** [comment]
i have just notice this

**Comment by subhahu123** [comment]
moreover he has to squash his commit also
@HarshKhandeparkar

**Comment by rohithGoudM** [comment]
> @HarshKhandeparkar
> what are the changes in package.json
> it was not required

those changes were in package-lock.json not in package.json,
I didn't know if those changes were useful.

**Comment by HarshKhandeparkar** [comment]
No need to squash commits. They are squashed while merging.

**Comment by subhahu123** [comment]
> No need to squash commits. They are squashed while merging.

Ok

**Comment by rohithGoudM** [comment]
> I can see that the dist files have been changed directly. Please make the appropriate changes to the src files in examples/lib directory as well.

I have added the class to examples/lib files too

**Comment by subhahu123** [comment]
> > I can see that the dist files have been changed directly. Please make the appropriate changes to the src files in examples/lib directory as well.
> 
> I have added the class to examples/lib files too

where there is a change in package.json

**Comment by rohithGoudM** [comment]
> > I have added the class to examples/lib files too
> 
> where there is a change in package.json

I didn't get you exactly.

**Comment by subhahu123** [comment]
> > > I have added the class to examples/lib files too
> > 
> > 
> > where there is a change in package.json
> 
> I didn't get you exactly.

what changes u have done in package.json
i was not required u should remove it
@rohithGoudM

**Comment by aashna27** [comment]
"csrtoptr" can the class name be made a little more descriptive ??

**Comment by gauravano** [comment]
hey @rohithGoudM, you need any help finishing this one? Thanks!

**Comment by HarshKhandeparkar** [comment]
This has been fixed already.

**Pull request closed without merging**
