### PR TITLE
Bump to v3.6.0 for new npm release

### PR DESCRIPTION
**Pull request by jywarren**
This accounts for a TON of changes over the past 13 months. Compiling some highlights:

* GPU acceleration for some modules #1038 
* WASM acceleration for some modules #1093 (see icons in #1365 when this happens!)
* Jest full-stack testing
* a TON of rewrites and refinements of the UI
* GIF support
* lots of new modules

I am surely missing a ton here. But much appreciation to the following contributors during this period:

@keshav234156 @blurry-x-face @aashna27 @HarshKhandeparkar @root00198 @ataata107 @tech4GT @anthony-zhou @Divy123 @VladimirMikulic @Ryan10145 @tsparksh @yottabytedev @vgadodia @vaibhavmatta @tudoranghelina91 @sanjana091001 @samagragupta @pythongiant @ovsundal @ojurkiewicz @nisarhassan12 @niravasher @kirito-k @johanuribe03 @ikayz @freerangeandy @duyquangnguyenhac @dnhuan @arghac14 @Olusamimaths @Deogle @28-ys @sashadev-sky @bhavayAnand9

Please feel free to chime in with big updates to be added to the changelog if you like! 🎉 

And, try out our new GitPod integration allowing us to more quickly and effectively review PRs due to on-the-fly interactive builds for each PR pushed up.

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Cool. Let's release it! Pushing to beta.

**Comment by HarshKhandeparkar** [comment]
Has it been 13 months? Wow! We need to publish sooner...

**Comment by jywarren** [comment]
@HarshKhandeparkar yes we do! This Gitpod thing plus all the fantastic UI testing we have will make this easier -- #1000. I'd like to call for more UI testing to be implemented, to further secure our base feature set, as well as ask for any help with the #1694.

**Comment by HarshKhandeparkar** [comment]
Can you wait before my latest PR gets merged?

**Comment by jywarren** [comment]
Before releasing this one? Sure, which PR?

**Comment by jywarren** [comment]
I'd also like to try to set a new requirement that any new feature has:

1. a good test demonstrating its use and guaranteeing it against future breakage
2. a line in the README describing the function and how to use it. 

That'll help us stabilize things a lot from here out!

**Comment by HarshKhandeparkar** [comment]
#1696, part of bug stomp feb, yet I opened the PR in July :joy:

**Comment by jywarren** [comment]
@HarshKhandeparkar why don't we just release `v3.6.0` and you can have more time to finish the test fixes for edge detection, and we'll just immediately release `v3.6.1`. We should be releasing more often anyways!

**Comment by jywarren** [comment]
Hmm. only `4603.8 jest-puppeteer UI tests (full browser env)` failed.

**Comment by jywarren** [comment]
Looks like a timeout when fetching deps. Restarted.

**Comment by HarshKhandeparkar** [comment]
> @HarshKhandeparkar why don't we just release `v3.6.0` and you can have more time to finish the test fixes for edge detection, and we'll just immediately release `v3.6.1`. We should be releasing more often anyways!

Sure. I forgot to add the tests actually :sweat_smile:

**Comment by jywarren** [comment]
OK, let's do this!!! Releasing as `v3.6.0` and we'll do this more often now!

**Comment by jywarren** [comment]
Wait, i need to coordinate building this and the new script at https://github.com/publiclab/image-sequencer/pull/1703... hang on...

**Review by HarshKhandeparkar — APPROVED** [review]

**Comment by HarshKhandeparkar** [comment]
@jywarren Do you mind if I make a tag along with the changelog in the releases page for this? I will also push to the `stable` branch.

I have an idea for how to do the npm packages which I will mention in https://github.com/publiclab/image-sequencer/issues/1692

**Comment by HarshKhandeparkar** [comment]
@jywarren check out the new project I opened.

**Comment by jywarren** [comment]
> @jywarren Do you mind if I make a tag along with the changelog in the releases page for this? I will also push to the `stable` branch.

Sure, ok! You mean after this is merged. What other PRs should we try to merge before this, or should we just go ahead with 3.6.0 and do others in a follow-up?

**Comment by HarshKhandeparkar** [comment]
This is ready for merge unless @publiclab/is-maintainers want some other PR/issue to be fixed (in which case, add it to the v3.6.0 project) :)

**Comment by jywarren** [comment]
Agreed, I merged or approved a couple dependabot prs so we can merge this after!

**Comment by jywarren** [comment]
OK, running final update!

**Comment by jywarren** [comment]
Merged! Let's publish `v3.6.0`! @HarshKhandeparkar what is our checklist, can we organize the checklist here?

* [x] finalize and merge to `main` branch
* [ ] build and publish `/dist/` files (should this be part of the PR that finalizes the bump, i.e. should we have done that here @HarshKhandeparkar et al?)
* [ ] merge to `stable`
* [ ] create a release on GitHub and use features description from (this) release PR to add release notes
* [ ] tag version number
* [ ] publish to `npm`
* [ ] publish to live `github-pages` demo (with https://github.com/publiclab/image-sequencer/pull/1703 eventually)

How does this look?

**Comment by HarshKhandeparkar** [comment]
Umm, we don't add dist files to the `main` branch anymore. I will do the pushing to `stable` and the release notes :) It is 2AM here so may I do it tomorrow?

**Comment by HarshKhandeparkar** [comment]
Also, the team discussions are turned off, is that intentional? If not, we can make these checklists there ig...

**Comment by jywarren** [comment]
> Also, the team discussions are turned off, is that intentional? If not, we can make these checklists there ig...

Yes, i've found it's quite hard to find the team discussions as they don't work the same way as issues. I prefer to use issues for all discussions, which i feel is more transparent, sound good? Thanks Harsh! 

The steps i noted prob need to be reordered and corrected -- can you edit my comment or copy it? I think we should keep a standard checklist for each release!

**Comment by jywarren** [comment]
Maybe we can do a template, which we use to run the release process from within. It seems GitHub [doesn't do multiple pull requests templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates), but we could run the release within an issue using an issue template, and that makes sense anyways because there are steps /after/ merging the pull request, so the issue would stay open until the very end of the checklist. 

How does that sound?

**Pull request merged**
