### PR TITLE
Hide ui on each draw

### LINKED ISSUE #1558: Crop module UI
### Please describe the problem (or idea)
There is UI on top left corner when we select crop module. Some PR might have caused that

Screenshot from 2020-01-22 13-08-55

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by ataata107**
Fixes #1558   (<=== Replace `0000` with the Issue Number)
ezgif com-video-to-gif (1)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] ask `@publiclab/is-reviewers` for help, in a comment below
* [X] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@ataata107 instead of hiding the UI can we display it on top of image?

**Comment by jywarren** [comment]
Hi, can you explain this change a little bit? 

Also, i wonder if we can mock the `ui.hide()` function in the module tests to confirm that this is done at the right time?

**Comment by jywarren** [comment]
Thank you!!

**Comment by ataata107** [comment]
I hid the UI on the starting as it is not required because the default crop value that we are using is 100% width and 100%height hence there is no need to put ui on top at the start. What are your views @blurry-x-face @jywarren

**Review by HarshKhandeparkar — APPROVED** [review]

**Pull request merged**
