### PR TITLE
Improve Code Quality and Optimize

### PR DESCRIPTION
**Pull request by tech4GT**
Some changes Include making changePixel optional to prevent it from running for every module that uses pixelManipulation, also added a preComputation function in pixelManipulation.
I have also removed extra spaces and reIndented the code to Our standards.

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren Have a look!
Also please don't merge any other prs before this one, merge conflicts are gonna be a nightmare :sweat_smile:

**Comment by jywarren** [comment]
Oh no, i didn't see your note!!! Will look now. Apologies. Hopefully it's just a matter of rebuilding since GH is not detecting conflicts in the `src` directory.

**Comment by jywarren** [comment]
@tech4GT this looks good. See the work i'm doing in #768 and #767 to quantify the optimizations!

I think we can merge this once we rebuild `dist`. Thanks!

**Comment by tech4GT** [comment]
@jywarren I'll rebuild now!

**Comment by jywarren** [comment]
Wow, awesome!

**Comment by tech4GT** [comment]
@jywarren One major change here is that we don't iterate over the image calling changePixel for all the pixels if it is not required, that alone should speed things up for some modules quite a bit! :)

**Comment by jywarren** [comment]
Great!!!

**Pull request merged**
