### PR TITLE
skip writing defaults into toString

### PR DESCRIPTION
**Pull request by Mridul97**
Changes : to not write defaults in the url to make url shorter and more readable.

### CODE REVIEW

**Comment by Mridul97** [comment]
@jywarren help needed with the failed checks.

**Comment by Mridul97** [comment]
@jywarren please help with the failed checks.

**Comment by Mridul97** [comment]
Please help with the failed checks😅

**Comment by tech4GT** [comment]
@Mridul97 I'll take a look at this tonight! Thanks for the PR!😊

**Comment by tech4GT** [comment]
Hmm I see, @Mridul97 some tests need to be modified here, I'll push in a fix to this shortly!

**Comment by tech4GT** [comment]
Actually I don't have my mac and tape just refuses to run on my windows machine, I'll take care of the tests later but I think this concise code looks better, don't you think?

**Comment by Mridul97** [comment]
Done! Yes, I agree concise code is definitely better!

**Comment by jywarren** [comment]
Oh is this almost ready to go?

**Comment by Mridul97** [comment]
It was working fine on my system but there were some checks failing. I will rebase the branch and check again!

**Comment by Mridul97** [comment]
Somehow I was not able to rebase it properly. So I have open another PR for this issue #478. Please have a look! Closing this one now!

**Pull request closed without merging**
