### PR TITLE
Update Crop.js

### PR DESCRIPTION
**Pull request by tudoranghelina91**
Added var keyword before backgroundColor at line 20

Fixes #0000  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by tudoranghelina91** [comment]
@publiclab/is-reviewers could you please take a look?

**Comment by HarshKhandeparkar** [comment]
Will take a look in a few mins or maybe half an hour.

**Comment by HarshKhandeparkar** [comment]
@tudoranghelina91 seems like you have opened multiple PRs. Could you just open a single PR with all the changes. If you don't know how to do that, I will explain.

**Comment by tudoranghelina91** [comment]
> Will take a look in a few mins or maybe half an hour.

Hello, @HarshKhandeparkar , do you mean to open one single pull request per file?

**Comment by HarshKhandeparkar** [comment]
Could you open a PR with all the file changes? Not one for each but one for
all.

**Comment by aashna27** [comment]
Yeah @tudoranghelina91 please open a single pr with all the requested changes these are too many prs also I have left comments for few of the prs please have a look at them and made the required changes. Thanks a lot!

**Comment by HarshKhandeparkar** [comment]
This has been fixed already.

**Pull request closed without merging**
