### PR TITLE
Material icon

### PR DESCRIPTION
**Pull request by tech4GT**
@jywarren in concert with #211

### CODE REVIEW

**Comment by jywarren** [comment]
Depending on how big this is, do you want to exclude the icons in `package.json`? Or not, just an idea. Thanks!!!

**Comment by tech4GT** [comment]
@jywarren Sorry i didn't understand? This icon will be useful for the demo so maybe it's not required in package.json , is this what you're asking?

**Comment by tech4GT** [comment]
@jywarren oh that makes sense, so this is ready to merge right or something else?
Thanks

**Comment by jywarren** [comment]
It's ready but there is a merge conflict right now -- can you rebase or resolve? thanks!!!

**Comment by tech4GT** [comment]
@jywarren done👍

**Comment by jywarren** [comment]
Perfect. Done!!!

**Pull request merged**
