### PR TITLE
gitignore dist and update links

### LINKED ISSUE #773: Discuss: workflow for managing Dist files (i.e. on a 'stable' branch)
A new `demo` folder should be created, containg the deployment code, so that each time `dist` folder does not raises `Merge Conflict` errors.

* A `demo` folder or a separate branch can be created from where the code can be deployed. This will ensure that if any wrong code commited to `main` branch does not get deployed immediately.
* Also this will solve the problem of having `Merge Conflicts` with the `dist` files.
* `dist` folder should be added to `.gitignore`.

What's your thought on this? @jywarren @tech4GT

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #773

* Gitignores dist files.
* Deletes dist files.
* Fixes/updates all readme and contributing file links.
* Makes future provisions for stable branch by linking to stable branch in readme.
* Links the user to minified dist file(in stable branch) instead of normal ones in readme file.
* Stable branch is yet to be created which will resolve the problem of dist file conflicts.
* Optionally, an unstable branch can also be added.
* Every npm version bump should be pushed to stable branch.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren this completes the process of dist file management on stable branch and gitignores the dist. A stable branch is only left to be created. A maintainer will have to create it as it will have to be a protected branch.

cc @publiclab/is-reviewers @tech4GT

**Comment by HarshKhandeparkar** [comment]
@jywarren please review :)

**Comment by HarshKhandeparkar** [comment]
@jywarren any changes reqd?

**Comment by jywarren** [comment]
I wanted to get some final input and feedback from other reviewers - @publiclab/is-reviewers how does this look?

Thank you so much, @HarshKhandparkar!!

**Comment by HarshKhandeparkar** [comment]
@subhahu123 please review.

**Comment by subhahu123** [comment]
> @subhahu123 please review.

@HarshKhandeparkar  changed files also include .js file
have u changed any js code or they r just because of grunt build

**Comment by HarshKhandeparkar** [comment]
I have deleted the dist files.

**Comment by HarshKhandeparkar** [comment]
@jywarren are any changes required or can this be merged now? This is very important as some contributors change the files from the brwser and cannot build the dist files. Also are you going to create the stable branch?

**Comment by jywarren** [comment]
I just created a stable branch, but we actually want the files in there. Now if I merge this to `main`, we'll retain them in stable (if we use the new tasks) and stop tracking them in `main`, right? @tech4GT @Divy123 @VibhorCodecianGupta does this look good to you all? Thanks everyone, just want to be sure, this is a big step!

**Comment by HarshKhandeparkar** [comment]
Yes it will. Everything will work fine. The dist will be deleted in main. Also you can build using the production task on gh-pages. I have checked it out. It **significantly** reduces load times. Especially in India because of bad internet(😅).

**Comment by HarshKhandeparkar** [comment]
@tech4GT @Harshithpabbati @Divy123 @VibhorCodecianGupta please review this pr :)

@jywarren do you think that any changes are reqd? I am asking as this is a very big step yet very important. Atleast the newcomers won't get confused by the dist files. Sometimes (mostly?) due to fto-templates, they update the files in the browser and are not able to build the dist or are confused about how to test the changes locally or directly update the dist files instead of changing src files. Also these dist files create the

**Comment by HarshKhandeparkar** [comment]
@jywarren (Comment continued) create the biggest conflicts while rebasing which itself is a big problem for newcomers and the dist files make it even more difficult.

**Comment by HarshKhandeparkar** [comment]
@Divy123 thanks for reviewing especially at this time⏰⏱️⏲️⌚!!!

**Comment by HarshKhandeparkar** [comment]
@jywarren I just saw that stable isn't a protected branch. Please take appropriate action.

**Comment by HarshKhandeparkar** [comment]
@jywarren I am going to open a new pr as this one has conflicts. Please note that the stable branch is not protected. Also are you going to merge this one next? It has received 2 reviews.

**Comment by HarshKhandeparkar** [comment]
Maybe @aashna27 can review?

**Comment by aashna27** [comment]
I have seen all the files , I like the idea of maintaining a stable branch and ignoring the dist file !! 
Great step .. and all the files and idea look really neat to me . Great work @HarshKhandeparkar .. really helpful.

**Comment by HarshKhandeparkar** [comment]
@aashna27 since you can commit. I wanted to ask, are you using your pc? If yes, will you be able to rebase this?

**Comment by aashna27** [comment]
And since the conflict is in dist files, simply deleting those files , would solve the problem!!

**Comment by HarshKhandeparkar** [comment]
Ironically, the pr which tries to resolve dist file conflicts has a dist file conflict. 😂

**Comment by aashna27** [comment]
> 
> 
> @aashna27 since you can commit. I wanted to ask, are you using your pc? If yes, will you be able to rebase this?

Yeah sure , I ll give it a try.

**Comment by aashna27** [comment]
> 
> 
> Ironically, the pr which tries to resolve dist file conflicts has a dist file conflict. 😂

Yeahh !! thats what I was thinking .. 🤣

**Comment by HarshKhandeparkar** [comment]
Thanks! I was going to open a new pr. Thanks a lot! You saved me a lot of trouble.

**Comment by aashna27** [comment]
> 
> 
> Thanks! I was going to open a new pr. Thanks a lot! You saved me a lot of trouble.

How about deleting the dist file ?? in git itself?

**Comment by HarshKhandeparkar** [comment]
What do you mean by deleting in git itself?

**Comment by aashna27** [comment]
I have resolved the conflict . 👍

**Comment by HarshKhandeparkar** [comment]
Oh that's a lot of commits. This pr should also add a commit to your contributions [here](https://github.com/publiclab/image-sequencer/graphs/contributors). Thanks a lot for this! Especially at this time of the day(night)!

**Comment by aashna27** [comment]
> 
> 
> Oh that's a lot of commits. This pr should also add a commit to your contributions [here](https://github.com/publiclab/image-sequencer/graphs/contributors). Thanks a lot for this! Especially at this time of the day(night)!

Hahaha .. Oh how  I wish it did 🤣 😆

**Comment by HarshKhandeparkar** [comment]
Maybe you can squash the commits into just two, one which only has your name on it and one which has my name on it, can you do that. Then it can be merged without squashing and that might add a commit to your contributions. Will that work?

**Comment by jywarren** [comment]
Hi folks, i'm sorry but i'm just going to squash it -- I'm sure you both have tons of commits, so i hope this is OK with you! 👍 Thank you and I appreciate your eye for getting credit!

**Comment by HarshKhandeparkar** [comment]
Thanks @jywarren !

**Pull request merged**
