### PR TITLE
Fixed Service Worker

### LINKED ISSUE #972: Service Worker is not working properly
### Please describe the problem (or idea)

Checkout out the developer tools you will see an error in application tab
Service worker is showing error 
And when you make it offline and try to reload  it  , not working

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #972

Fixed the broken service worker

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@subhahu123 @publiclab/is-reviewers

**Comment by aashna27** [comment]
Sorry to say but I tried it locally, the changes don't work.

**Comment by HarshKhandeparkar** [comment]
What is the error shown?

**Comment by aashna27** [comment]
> What is the error shown?

image

**Comment by HarshKhandeparkar** [comment]
So I think the service worker **has** to be in exmaples/ right?

**Comment by HarshKhandeparkar** [comment]
Ok I'll fix that. Wait a min.

**Comment by subhahu123** [comment]
> Ok I'll fix that. Wait a min.

Can u provide the preview link also 
@HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Try it out locally now.
@aashna27 @subhahu123

**Comment by subhahu123** [comment]
> Try it out locally now.
> @aashna27 @subhahu123

@HarshKhandeparkar i think  this repo really  needs deploy links which automatically generates pr

**Comment by HarshKhandeparkar** [comment]
You are working on it right?

**Comment by HarshKhandeparkar** [comment]
Surge?

**Comment by Harshithpabbati** [comment]
We can use stackblitz for this. We can import code from github from a particular branch and host it we will be getting a link to it. Check this for reference.
https://stackblitz.com/docs

**Comment by subhahu123** [comment]
@Harshithpabbati  @HarshKhandeparkar  we can go for both

**Comment by subhahu123** [comment]
> We can use stackblitz for this. We can import code from github from a particular branch and host it we will be getting a link to it. Check this for reference.
> https://stackblitz.com/docs

@Harshithpabbati i have use it various time i dont think so that it allows importing projects from gitthub

**Comment by subhahu123** [comment]
> Surge?

@HarshKhandeparkar  can u work on that please i m working on my gsoc projects

**Comment by HarshKhandeparkar** [comment]
I have exams and I have no experience with it. Sorry.

**Comment by Harshithpabbati** [comment]
If you are busy @harshkhandeparkar then I would like to do that.

**Comment by subhahu123** [comment]
> I have exams and I have no experience with it. Sorry.

me also

**Comment by subhahu123** [comment]
> If you are busy @HarshKhandeparkar then I would like to do that.

please go for it @Harshithpabbati

**Comment by HarshKhandeparkar** [comment]
Good luck !

**Comment by Harshithpabbati** [comment]
But the case is i don't have experience with it. Fine i will do it somehow.

**Comment by subhahu123** [comment]
> But the case is i don't have experience with it. Fine i will do it somehow.

i don't think so u require any experience with it u can refer to my PR for surge console command

**Comment by subhahu123** [comment]
> But the case is i don't have experience with it. Fine i will do it somehow.

Knowing about the building or compiling of code is enough

**Comment by HarshKhandeparkar** [comment]
> But the case is i don't have experience with it. Fine i will do it somehow. 

Np, you will only get to learn something new. If at all you get stuck, we are here to help!

**Comment by subhahu123** [comment]
> > But the case is i don't have experience with it. Fine i will do it somehow.
> 
> Np, you will only get to learn something new. If at all you get stuck, we are here to help!

@HarshKhandeparkar  u can also provide a preview link for this pr using surge
it is only about three commands and u r done

**Comment by HarshKhandeparkar** [comment]
I am using my phone so I cannot do anything. Srry.

**Comment by Harshithpabbati** [comment]
Was surge implemented anywhere???

**Comment by subhahu123** [comment]
> Was surge implemented anywhere???

community toolbox pr 
working properly with no error

**Comment by Harshithpabbati** [comment]
Fine cool!

**Comment by aashna27** [comment]
I would like to work on surge, is it available?

**Comment by Harshithpabbati** [comment]
I did half of it. You can continue it.
Thanks.

**Comment by aashna27** [comment]
Okay

**Comment by aashna27** [comment]
So you create your pr, and then I ll commit my changes and we can get them merged.

**Comment by Harshithpabbati** [comment]
I already opened a pr.

**Comment by HarshKhandeparkar** [comment]
@jywarren could you please merge this?

**Comment by jywarren** [comment]
Ok!!

**Comment by HarshKhandeparkar** [comment]
Thanks a lot!!

**Pull request merged**
