### PR TITLE
Added the download button

### LINKED ISSUE #391: Add download button to download image from a specific module
In order to download the image, we need to click on it to do this. But if a button can be made to this, which is a good pattern to follow. 

UI for download button can be 

screenshot from 2018-10-06 02-32-26

Files need to be changed in order to add the button 
https://github.com/publiclab/image-sequencer/blob/2e7e042baab7e0bf43b821ea9e197cacf6efeac2/examples/lib/defaultHtmlStepUi.js#L40

### PR DESCRIPTION
**Pull request by harshithpabbati**
Fixes #391 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers i was done with adding the button but i can't make it to download can someone help me out in this case...

**Comment by HarshKhandeparkar** [comment]
Harshith, please refer to this to add the download functionality

https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js#L238-L244

**Comment by Harshithpabbati** [comment]
Why was that needed as we already have a function to download??? 
$('#download-btn').click(function() {
    $('.step-thumbnail:last()').trigger("click");
    return false;
  });
I am trying to use #download-btn id to it but i can't do it .

**Comment by HarshKhandeparkar** [comment]
This function that you are talking about will only click the last step
image. It will not work if we want to remove the click-to-download
functionality of the images(which we are planning to do)

**Comment by aashna27** [comment]
Please provide a screenshot.

**Comment by aashna27** [comment]
Hey can the conflicts be resolved here ? and a screenshot be made available because I have to proceed with this for one of my tasks so if you allow I would add the download button along with my task.

**Comment by harshithpabbati** [comment]
@aashna27 you can go with it

**Comment by aashna27** [comment]
Can we close this then.

**Pull request closed without merging**
