### PR TITLE
text-overlay in Node

### PR DESCRIPTION
**Pull request by aashna27**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by aashna27** [comment]
@HarshKhandeparkar any idea on this?

**Comment by aashna27** [comment]
@tech4GT

**Comment by tech4GT** [comment]
Looks like colorbar was affected somehow, that's the test which is failing. Try running it maybe you'll find the problem.

**Comment by aashna27** [comment]
@jywarren @publiclab/reviewers I have changed this and text-overlay now works for node. Please review

**Comment by Divy123** [comment]
Great finding @aashna27 and is there something to change in the docs?

Rest I think this is ready to be merged :tada:  :tada:

**Comment by aashna27** [comment]
> Great finding @aashna27 and is there something to change in the docs?
> 
> Rest I think this is ready to be merged tada tada

Thanks! we dont have docs I ll add them! :see_no_evil:

**Comment by Divy123** [comment]
> Thanks! we dont have docs I ll add them! 

Yeah, thanks a lot!!

**Comment by jywarren** [comment]
Hooray!!! Great work!!!

**Comment by HarshKhandeparkar** [comment]
lol, I was reviewing this.

**Comment by jywarren** [comment]
Sorry, I saw only docs required and 2 reviews (myself included!) so I went ahead! Sorry Harsh, let's try to coordinate better in the future, I'll keep a closer eye out. The pending reviewers are not easy to see from mobile view!

**Comment by HarshKhandeparkar** [comment]
It actually doesn't matter much. I was the one who delayed this.

**Comment by aashna27** [comment]
Thanks a lot everyone for the quick merge! 🤗

**Pull request merged**
