### PR TITLE
Adding Test modules for GIF's

### LINKED ISSUE #1479: Add more GIF tests
### Please describe the problem (or idea)
GIF manipulation is in an experimental stage as of now. One of the most important steps towards making it a permanent feature would be adding more tests.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by root00198**
Fixes #1479

I am creating this PR again, because the #1490 PR created some serious conflicts.
@HarshKhandeparkar @jywarren, please review it..

There are some issue that I tried to address in the previous PR, like the histogram module issue. I will create a seperate PR for that.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, tests didn't pass on one of these but it needed updating again anyways... let's see what happens!

**Comment by root00198** [comment]
Module which didn't passed, will get passed once #1535 PR got merged...

**Comment by jywarren** [comment]
Looks like it passed after all, is this then ready for a merge? Thank you!

**Comment by root00198** [comment]
Let's Go!!

**Comment by blurry-x-face** [comment]
@root00198 I see tests failing in the logs
https://travis-ci.org/publiclab/image-sequencer/jobs/639046685#L2623
Were they passing before merging #1533?

**Comment by root00198** [comment]
Yes they were passing. My one module draw-rectangle was failing but it was not because of the code in this PR. It was because of the reason in #1535.

**Comment by jywarren** [comment]
Hm. My update didn't seem to help. I think this may need a true rebase?

**Comment by blurry-x-face** [comment]
The tests won't pass until #1535 gets merged!

**Comment by jywarren** [comment]
Updating branch! Let's see.

**Comment by jywarren** [comment]
Awesome. Great work!!!

**Comment by jywarren** [comment]
Thank you!!!!

**Pull request merged**
