### PR TITLE
display add step menu with common modules as "quick" buttons

### PR DESCRIPTION
**Pull request by JonathanXu1**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Hi there,
I'm competing in CodeIn, and I've made a basic selector with commonly used buttons in response to #432 .
image

Some things I still need help on:
- [ ] Deselect a dropdown option when a button is pressed
- [ ] Send the button values to the addStepUi, or the dropdown values if no button is selected

This will be my first pull request on this repository, so I'd appreciate it if you let me know if there's any issues with my pull request. Thanks for your time!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, what if clicking the icon buttons just add automatically, without having to press add step, so then the deselect of the drop-down wouldnt matter?

**Comment by JonathanXu1** [comment]
That sounds like a good idea.
image
Could I get a pointer to how ui.addStepUi works? Also where can I find modulesInfo, specifically the name? 

I'm thinking of changing the selected value in the dropdown and call the addStepUi function when a corresponding button is pressed.

**Comment by jywarren** [comment]
Oh that's awesome. Can you upload a gif of how it works?

**Comment by JonathanXu1** [comment]
@jywarren here it is. 
sequence

**Comment by JonathanXu1** [comment]
I believe that I've applied the changes, but **grunt serve** is not reflecting any of the changes, whether it be css, js or html. The page loads fine and there are no errors, just that it is loading an old version somehow. Is there a way to resolve this?

**Comment by jywarren** [comment]
I just resolved the merge conflicts here, let's see!

**Comment by jywarren** [comment]
Also, there is a cache, so you may have to open it in the dev console, and then clearing cache that way. 

screenshot 2018-11-20 at 10 08 04 pm

I'll check, there is supposed to be a message in the footer with a link to clear the cache.

**Comment by JonathanXu1** [comment]
Thanks for merging the pull request. Grunt is still serving an old version of the site, after I cleared cache, restarted the browser, reinstalled grunt and restarted my computer. It started yesterday and I'm not sure why.
image
As you can see in the console, it's still referencing an error in **demo.js** line 163 despite it being only 148 lines long now.

**Comment by jywarren** [comment]
Hmm, actually it shouldn't need to be watching for changes at all, since demo.js is not compiled... Hmm

**Comment by jywarren** [comment]
Did you try clearing cache with the reload button menu as in my screenshot? I am pretty sure the cache is in the browser and not the backend. 

Another temporary fix would be to use an incognito window, which wouldn't use the cache.

**Comment by jywarren** [comment]
Could you push up your changes and rebase (or merge should be fine too) so once we resolve the issues i can merge this in? Thanks!

**Comment by JonathanXu1** [comment]
Thanks, it turns out Firefox doesn't clear the browser cache even when I manually do it in the settings. In private mode I was able to view the changes. I've applied the changes you've requested:
image

**Comment by JonathanXu1** [comment]
Yep, I just fixed the merge conflicts. I kept the stepmodule stuff in the js.

**Comment by jywarren** [comment]
Re-added `package-lock.json` which had been removed, and then i'll merge! 👍 🎉

**Comment by jywarren** [comment]
Publishing to gh-pages so we can try it out! Fantastic!!

**Comment by jywarren** [comment]
This is a pretty interesting alternative way to select a step, which you might be interested in as a next issue: https://github.com/publiclab/image-sequencer/issues/247

it's a big one, but if you'd like, I'm happy to make a GCI issue from it!

**Comment by jywarren** [comment]
It's live, by the way!!!! Amazing!!!

**Pull request merged**
