### PR TITLE
parseCornerCoordinateInputs bug fix

### LINKED ISSUE #606: Uncaught TypeError: parseCoordInputs.parseCornerCoordinateInputs is not a function
https://github.com/publiclab/image-sequencer/blob/35f7605a248ac99371650503a31b27ebd00c09a6/src/modules/Overlay/Module.js#L18

Hi @Divy123, i'm seeing an error as above in this line - strangely, this line was compiled into the `/dist/` folder instead of being browserified:

```js
    var parseCoordInputs = require('../../util/ParseInputCoordinates');
```

So of course it can't do require in the browser. Do you know what's going on? Related to PR https://github.com/publiclab/image-sequencer/pull/592

Thank you!

A bit of urgency because this is deployed to the demo already, affects Crop and Overlay modules.

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #606 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@publiclab/reviewers please review :)

**Comment by jywarren** [comment]
Oops can you rebuild and rebase? Thanks!!

**Comment by jywarren** [comment]
Rebased and rebuilt. Hope this works!

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
