### PR TITLE
Fix choose file option and insert step functionality

### LINKED ISSUE #711: Choose file option is not loading the chosen file
Choose file option is not loading the chosen file. Please see the GIF below :- 

file

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #711 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
@jywarren @publiclab/is-reviewers Please review!

file2

**Comment by aashna27** [comment]
This was happening with me also yesterday but then i retried by building again and in another browser so it worked correctly.

**Comment by HarshKhandeparkar** [comment]
Insert step was not working for me. @Mridul97 can you please see if that's working

**Comment by Mridul97** [comment]
@HarshKhandeparkar yes, insert step is not working for me as well

**Comment by HarshKhandeparkar** [comment]
@Mridul97 does this PR fix it?

**Comment by Mridul97** [comment]
@HarshKhandeparkar not yet, but will make the changes to do that!

**Comment by aashna27** [comment]
Can i work on insert step? If you don't mind? @Mridul97

**Comment by HarshKhandeparkar** [comment]
Please change the name of the PR to maybe "fix interMediateStepUi.js". Also you can change the issue to say that none of those functions imported from that file work.

**Comment by Mridul97** [comment]
> Can i work on insert step? If you don't mind? @Mridul97

Actually it has an easy fix, and I think opening another pr for it maybe an overkill! Thanks!

**Comment by aashna27** [comment]
Ohh okay! Go ahead.

**Comment by aashna27** [comment]
great work !! but the choose file works for me, would you mind checking again in a different browser.

**Comment by Mridul97** [comment]
@jywarren Please review this!

**Comment by Mridul97** [comment]
@jywarren I have rebased the branch! :)

**Comment by jywarren** [comment]
Great!!!

**Pull request merged**
