### PR TITLE
Add meta description with keywords for SEO

### LINKED ISSUE #978: Document Does Not Have A Meta Description
### Please describe the problem (or idea)
The Lighthouse says that the document does not have a meta description 
> What happened just before the problem occurred? Or what problem could this idea solve?

For SEO, we should add desciption to the head of our index.html.
Example https://developers.google.com/web/tools/lighthouse/audits/description

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #978

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren please have a look!!
I have added meta description for SEO.
Also its great to see the code coverage report.

**Comment by Divy123** [comment]
@jywarren please review !!

**Comment by jywarren** [comment]
Did you test this out locally? I see a few HTML changes and just want to be sure. Thanks!!!

**Comment by Divy123** [comment]
@jywarren @HarshKhandeparkar yes actually I improved some spacings and
basically have done some linting then.

Rest it's all fine.

**Comment by Divy123** [comment]
@jywarren Actually those are some linting changes, not the code ones.
I think we can merge this.

**Comment by jywarren** [comment]
Awesome, thanks all!!!

**Pull request merged**
