### PR TITLE
Add resize module

### PR DESCRIPTION
**Pull request by KusioDev**
Added resize module.
If you set resize value equal to 100%, the image will get twice as big, and when you set -100%, the image will be two times smaller.

It is my first module, so if something is wrong, tell me, and I'll fix it 😄

### CODE REVIEW

**Comment by KusioDev** [comment]
https://github.com/publiclab/image-sequencer/issues/435

Can you review it @publiclab/reviewers? 😃

**Comment by tech4GT** [comment]
Thanks for your pull request! 😊

**Comment by KusioDev** [comment]
It's hard to review it based on screenshots because it's hard to see a difference. But I'll add them when I get home.
I've changed the test file because I did some previous pull request with blend module, and now I've checked that there was an unused variable, and the test was pasted twice.

**Comment by KusioDev** [comment]
In browser: 
When resize is set to 25%
https://prnt.sc/lc0sg8

When resize is set to -25%
https://prnt.sc/lc0st9

Original image
https://prnt.sc/lc0syl

+25% resize
https://prnt.sc/lc0t34

-25% resize
https://prnt.sc/lc0t6x

**Comment by KusioDev** [comment]
Ok, I've changed the resize calculation, and now it's taken as proportion.

However, I've got a questions that would help me understand this code fully, because I've copied some parts from other modules.

What this code does?
`progressObj.stop(true);
 progressObj.overrideFlag = true;`

**Comment by jywarren** [comment]
This manages the progress bar UI -- it may be documented in the readmes,
but we may need to hear from @tech4gt once he is no longer as busy with
school!

**Comment by jywarren** [comment]
Is this otherwise ready? Thank you!!!

**Comment by KusioDev** [comment]
I think it is 😄

**Comment by jywarren** [comment]
🙌🏽⚡⚡🚀

**Pull request merged**
