### PR TITLE
Corrected brightness default view

### LINKED ISSUE #491: Correct default view for brightness module
### Problem

The brightness module when selected displays a white screen in the image area instead of the image from the previous step or the selected image.
image

However the default view should be something like this

image

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by oorjitchowdhary**
Fixes #491 

oorjitrunningoraclevmvir

oorjitrunningoraclevmvir 1

@publiclab/reviewers Pls review and approve on GCI... 😄 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@bhavayAnand4 Cheers 🎉 😃

**Comment by HarshKhandeparkar** [comment]
@oorjitchowdhary  you can check all of the boxes to make it easier for @publiclab/reviewers to review it.
Also spell the branch name correctly next time  😜

**Comment by oorjitchowdhary** [comment]
> @oorjitchowdhary you can check all of the boxes to make it easier for @publiclab/reviewers to review it.
> Also spell the branch name correctly next time 😜

Yess 😆 😆 
I found that out when I pushed the commits..

**Comment by oorjitchowdhary** [comment]
@aashna27 pls approve on gci too

**Comment by oorjitchowdhary** [comment]
@jywarren this will be merged right? 😄
Happy to help and hope to contribute more..

**Comment by jywarren** [comment]
Awesome, yes!!! Great work!!!

**Comment by jywarren** [comment]
I don't have a problem with moodules 😆 

Thanks for the teamwork everyone!

**Pull request merged**
