### PR TITLE
Add search functionality in choose Module select 

### LINKED ISSUE #747: select module box with a search option
### Please describe the problem (or idea)
As our list of modules is increasing it'll be getting difficult to find a particular module from the select box. So I think it'll be more convenient if we add a search option.

imagine you just know the module name so instead of searching for the module in that list we can start typing and filtering out that module from the list.

### Please show us where to look
something like this...
https://codepen.io/tipdub/full/AXJpKj
https://codepen.io/Rio517/full/NPLbpP

http://sequencer.publiclab.org...

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #747 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
ezgif com-gif-maker 1

@publiclab/is-reviewers please review.

**Comment by VibhorCodecianGupta** [comment]
@Divy123 was this not achievable by vanilla JS? A minified library would make the code heavier.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I don't think the whole lib is needed. It has CSS as well. Maybe a search library which maybe a searches a string keyword in a string might be enough. The CSS can be custom? Thoughts??

**Comment by HarshKhandeparkar** [comment]
Oh wait. Regex is a thing! Will that be sufficient?

**Comment by Divy123** [comment]
@HarshKhandeparkar @VibhorCodecianGupta actually I discussed but Warren suggested this library to work with.

**Comment by Divy123** [comment]
> Oh wait. Regex is a thing! Will that be sufficient?
I agree but I want you people to go through this discussion.
https://github.com/publiclab/image-sequencer/issues/747

**Comment by jywarren** [comment]
I think including this from a remote dependency (not compiling it in) is OK, though thank you for thinking of the overall code weight. I think this lets us not have to maintain this part of the code, and it affects just the HTML UI. 

`  <script src="lib/selectize.min.js"></script>`

I'm +1 on this but also want to hear other input!

**Comment by Harshithpabbati** [comment]
Was this done ??

**Comment by Divy123** [comment]
Ya this is done.

**Comment by jywarren** [comment]
Hi, could we switch to npm to include this module? Thank you!!!!!

**Comment by Divy123** [comment]
@jywarren if I am correct, you mean to achieve this functionality through an npm module?

**Comment by HarshKhandeparkar** [comment]
Jywarren asked if the lib was available in npm instead of including it through `lib/` folder

**Comment by jywarren** [comment]
yes, that's right! I think it probably is - you can search NPM too. And if
not, we could release a module based on the GitHub repo of that library.
Thanks!

**Comment by Divy123** [comment]
Sure, I will look into.

**Comment by Divy123** [comment]
@jywarren @HarshKhandeparkar I found this npm package 
https://www.npmjs.com/package/selectize
for selectize.js which I am currently implementing by including minified js and default css files.
But no proper doc is available how to use it by requiring through npm module.
Can you please help me with this?

**Comment by Harshithpabbati** [comment]
There will be usage documentation and examples right ??

**Comment by Divy123** [comment]
Well none about using it with npm.
All the way I did it earlier by including minified js and default css files.

**Comment by HarshKhandeparkar** [comment]
You can include in in a script tag in html. With the src attribute equal to "../node_modules/path/to/selectize/dist". This format is used to include dependencies like jquery and bootstrap in the index file itself.

**Comment by Harshithpabbati** [comment]
Yeah thats the way but if we need any changes in default then we need to have them in local.

**Comment by HarshKhandeparkar** [comment]
I didn't understand what you are trying to tell. Could you please elaborate?

**Comment by Divy123** [comment]
Thanks @HarshKhandeparkar .
@Harshithpabbati can you please elaborate on this?
Thanks!!

**Comment by Harshithpabbati** [comment]
http://selectize.github.io/selectize.js/ see this @slytherin

**Comment by Divy123** [comment]
@Harshithpabbati still not clear.
Please elaborate!

**Comment by Divy123** [comment]
@HarshKhandeparkar  moving ahead with your suggestion.

**Comment by HarshKhandeparkar** [comment]
Ok. Great.

**Comment by Divy123** [comment]
@jywarren please have a look.

**Comment by jywarren** [comment]
This looks awesome. Thanks a bunch! so cool!!!!

**Pull request merged**
