### PR TITLE
Refactored resize

### PR DESCRIPTION
**Pull request by blurry-x-face**
Concerns #1560 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar If this looks good I can start refactoring other modules too in the similar manner

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers

**Review by HarshKhandeparkar — APPROVED** [review]

**Comment by HarshKhandeparkar** [comment]
The refactor is fine but I did find an issue in the resize module itself...

**Comment by jywarren** [comment]
Hi harsh, I had requested a module test for this, just FYI... Can you be careful to check the comments before merging? Thanks!!

**Comment by HarshKhandeparkar** [comment]
Isn't there a test for it already? :eyes: The review was an approval so I thought... :sweat_smile:
Sorry.

**Comment by HarshKhandeparkar** [comment]
And I did check everything in gitpod, now and also sometime back when I had reviewed it :)
Also, the resize module has a test.

**Comment by jywarren** [comment]
OK, thanks, good to hear! no problem. I'll be more careful of approve vs. comment now we are co-maintainers!

**Pull request merged**
