### PR TITLE
New design layout for Save and Add areas

### LINKED ISSUE #735: New design layout for Save and Add areas
I'd like to reorganize the Save and Add boxes a bit, because they're a bit confusing, i think. 

image

Brainstorming some issues:

1. the difference between Save sequence and Save image may be confusing
2. we should have a place to output the whole string syntax of the current sequencer, besides just the URL bar
3. maybe View Gif and Download PNG should be near each other since they're kind of similar?
4. We should highlight the most common actions and de-emphasize ones that are a bit more obscure, maybe?

What about something like this?

image

Love to hear ideas and input!

### PR DESCRIPTION
**Pull request by IgorWilbert**
Fixes #735 

confirm

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by IgorWilbert** [comment]
@jywarren @HarshKhandeparkar is this what you had in mind for #735 ? Please notice this is all HTML "hard coded" to discuss the UI layout with you, I didn't implement any functionality yet.

**Comment by HarshKhandeparkar** [comment]
@IgorWilbert thanks for your contribution. This looks really cool. One concern I have is that the user may click on clear steps by mistake since its right below the dropdown thinking of it as a save button not intentionally but maybe absrnt mindedly. Maybe add a confirm button for the dropsown itself and move the clear button somewhere else? We can add the functionality later.

**Comment by HarshKhandeparkar** [comment]
@IgorWilbert cool. It does look better now. But I'm not sure if clear steps button should be kept above the add step btn. It seems a bit odd. Maybe remove it from the add step box?

**Comment by HarshKhandeparkar** [comment]
Any of your suggestions are welcomed as well

**Comment by jywarren** [comment]
This is awesome! 

A few thoughts -- i agree maybe Clear needs to be just text and be below Add Step, just so its available but not as emphasized. Second, if `as PNG` is shown pretty clearly in the dropdown, i guess we don't need to say it above, as I'd shown in my original mockup -- seeing it like this it's pretty clear. 

Maybe the `Save` button should be `btn-primary` to be more emphasized? 

Finally, shall we remove the blue buttons below `add steps` as they're no longer needed? 

Thanks! This is fantastic!

**Comment by IgorWilbert** [comment]
Thanks @jywarren ! Indeed it makes sense that the **Clear** button needs to be close to **Add Step**, but I suppose turning it into text wouldn't look good. I suggest changing the text from `Clear All Steps` to just `Clear`, so that it will fit in the same row, on the left of the drop down. What it does seems to be obvous enough. I agree, `Default download is PGN` doesn't seem necessary. Sure, Save button should be `btn-primary`. As for the buttons, I can eliminate `Download PGN` but I think `View GIF` should be kept. Otherwise how are you going to see your GIF before/without downloading it?

**Comment by IgorWilbert** [comment]
@jywarren @HarshKhandeparkar PR and GIF updated, please review. Thanks!

**Comment by HarshKhandeparkar** [comment]
@IgorWilbert please rebase the branch. Thanks.

**Comment by IgorWilbert** [comment]
@HarshKhandeparkar sure, I know I still need to rebase and remove a few commented lines. I just want to know if it is ok from the GIF I sent or should I change something else. Thanks!

**Comment by HarshKhandeparkar** [comment]
@IgorWilbert sure the buttons etc. look good. We can do more brainstorming on it. @jywarren and @publiclab/is-reviewers may have other ideas. But right now I asked you to rebase since travis is stuck and I just wanted to see if rebasing fixes it. Please do so. Also rebasing now will help you as rebasing later will make fixing fonflicts more difficult. Thanks! 😊

**Comment by jywarren** [comment]
OK awesome!!! A few notes:

1. what if we change it to "View Gif" but keep it as a menu item under Save? i mostly think it should be associated with the Save box, since it's like a kind of output. So alternatively we could say "Generate GIF" which is a kind of output - but we could have that pop up the modal and display the gif, and you can choose to download it if you want. How's that?
2. Clear all steps looks great!
3. "or click ARROW..." maybe isn't needed, above the Save dropdown?

Then we should be good to go!!!

**Comment by IgorWilbert** [comment]
Sorry guys, I made a mess during rebase, I'll look into it soon

**Comment by HarshKhandeparkar** [comment]
@jywarren travis worked after rebase. Any thoughts?

**Comment by jywarren** [comment]
Looks good - would you mind uploading a final screenshot? Need not be a GIF, just something quick for final confirmation. Thanks!

**Comment by IgorWilbert** [comment]
Sorry for the late reply, at the time I commented I had only rebased. Now I have made the changes you suggested Jeff. If the conflicts don't disappear I will rebase again. Thanks!

**Comment by jywarren** [comment]
Awesome job!!!

**Pull request merged**
