### PR TITLE
Adds image dimensions at the bottom of each image

### LINKED ISSUE #1023: Display width and height of image at each step
### Please describe the problem (or idea)

What we very casually come across is getting the dimensions of the image we are processing, so I think we can provide these details somewhere in our panel. Maybe we can provide a button which can show or hide these details as per the choice of user.

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #1023  

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren @HarshKhandeparkar please review!!

**Comment by VibhorCodecianGupta** [comment]
@Divy123 wouldn't this be simply achievable using javascript in `defaultStepUI`? You would just need to access the canvas width and height, is it necessary to embed this functionality inside a sequencer instance?

**Comment by Divy123** [comment]
@VibhorCodecianGupta like this  it can be a utility in node as well, if someone needs which won't be there the other way.

**Comment by HarshKhandeparkar** [comment]
Screenshots/GIFs?

**Comment by Divy123** [comment]
Not getting. Can you please elaborate??

**Comment by HarshKhandeparkar** [comment]
Make a new file inside `src/util/` named whatever you want. This file exports this getDimensions function. Require this file inside the ImageSequencer.js and export it. Sorry I wrote that in a hurry.

**Comment by Divy123** [comment]
Thanks @HarshKhandeparkar . This is cool!!

**Comment by Divy123** [comment]
@jywarren @HarshKhandeparkar   please have  look!!
I have also added the test for the new utility function.

**Comment by Divy123** [comment]
dim

**Comment by HarshKhandeparkar** [comment]
This is absolutely optional though.

**Comment by Divy123** [comment]
Can be made centered but the problem is that if the size of image diminishes then it won't accomodate. I have made it bold and it looks better now.
dim

**Comment by HarshKhandeparkar** [comment]
Can you put it inside a button which is disabled or a label of bootstrap has a class like that. See the rgb values which are displayed? They look really good and they stand out. Do you want to do that? Otherwise this is ready to merge.

**Comment by Divy123** [comment]
Screenshot from 2019-04-17 01-36-08
How about this? @HarshKhandeparkar

**Comment by Divy123** [comment]
demo
How about this @HarshKhandeparkar ?

**Comment by Divy123** [comment]
Or this?
demo

**Comment by aashna27** [comment]
This is really great, specially with the tests. 😊😊How about having an icon that displays information when we hover or click? https://fontawesome.com/v4.7.0/icon/info-circle

**Comment by HarshKhandeparkar** [comment]
> Or this?
demo

🚀🚀😍😍

**Comment by jywarren** [comment]
Oh I like the hover or click idea. Also maybe aligned-right? This'll be
great!

**Comment by HarshKhandeparkar** [comment]
Hover on click is awesome but it may remain unnoticed or users may not know what it is. Also hovering will not work on mobile devices. Thoughts?

**Comment by aashna27** [comment]
We can go with click then, considering mobile users, and as for the unnoticing we can add a tooltip, for the icon as is added for all the icons commonly asking the user to maybe click for image stats.

**Comment by HarshKhandeparkar** [comment]
How about automatically showing dimensions when users clicks on an input which requires dimensions? We can add a tooltip below the input containing the dimensions.

**Comment by HarshKhandeparkar** [comment]
[Tooltip.js](https://popper.js.org/tooltip-examples.html) is a perfect library for this. Developed by the devs of popper.js!

**Comment by jywarren** [comment]
Also a `...` menu can work, as in GitHub comments in mobile view. It'd remain clickable and could contain other metadata and more obscure tools.

**Comment by jywarren** [comment]
Screenshot_20190511-121805

**Comment by HarshKhandeparkar** [comment]
Fixed in a separate PR.

**Pull request closed without merging**
