### PR TITLE
[Fixed] Add Qr Module not working

### PR DESCRIPTION
**Pull request by root00198**
Add Qr Module was not working..
output
output

#1532 Broke the addQr Module. The funtion that it removed was not redundant.
By mistake, I created some changes in my travis-fix PR. Which were not ment to be pushed...But I pushed them accidentally, hence breaking the test. This PR will fix all those issues. That's why #1532's travis test passed....

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by root00198** [comment]
Node v-8 test for add QR if failing consistently...

**Comment by blurry-x-face** [comment]
Hi @root00198 this is already fixed in #1564

**Comment by root00198** [comment]
Okay, Can you also fix the add-qr test module...

**Comment by blurry-x-face** [comment]
Yea sure!

**Pull request closed without merging**
