### PR TITLE
Add manifest.json and cache static assets for offline use

### PR DESCRIPTION
**Pull request by Mridul97**

### CODE REVIEW

**Comment by Mridul97** [comment]
Fixes #326 

Changes: add a manifest.json file and cache static assets for offline use

**Comment by tech4GT** [comment]
@Mridul97 One thing, since the issue is a multi-task issue we don't want to close it with this pull request but the `fixes` commit will close it automatically. We should avoid this since we can miss re-opening. Great work though!!

**Comment by tech4GT** [comment]
I'll test your branch out in my browser now!!

**Comment by Mridul97** [comment]
Oh I didn't know that. Thanks! I will keep that in mind for the future.

**Comment by tech4GT** [comment]
hmm @Mridul97 I was trying this out in my browser and this doesn't seem to work. I'm sorry actually I'm a little busy right now so I'll review this asap.

**Comment by Mridul97** [comment]
Could you please tell me that which all files are to be added in cache storage? as there are a lot of files in the project. Thanks!

**Comment by jywarren** [comment]
I think everything in /examples/ and in /dist/ and that should be everything?

**Comment by jywarren** [comment]
Ah yes, and some files in /node_modules -- whatever's included into `examples/index.html`!

**Comment by tech4GT** [comment]
I got an idea! One thing we can do is just cache every outgoing request. Since our project does not consume any API as of now that should work perfectly and we'll not miss anything.

**Comment by Mridul97** [comment]
Great! I will implement this approach to cache every outgoing request. So, we won't cache anything on the install event of the service worker? and all the required files will be cached as and when the request is made by the user?

**Comment by Mridul97** [comment]
Cool! but if we update any of the files and change the cache name, then the user will have to send each request again to store those files in cache. So will this approach be better than caching all the files on install event in our case? Just a thought.

**Comment by tech4GT** [comment]
Yeah that's true. But since we don't update our files that often anyway (all data is static) it shouldn't be a problem.

**Comment by Mridul97** [comment]
Great! I will implement this approach and push changes. Thanks!

**Comment by Mridul97** [comment]
I have made the changes. Please take a look.

**Comment by jywarren** [comment]
@tech4gt, would you mind testing this one out? Thanks!

**Comment by tech4GT** [comment]
Hmm, this does not seem to work. I'll try to fix this up and push the changes.
I think something is wrong with sw.js, taking a look now!!

**Comment by tech4GT** [comment]
Hmm, could you please allow edits from maintainers on this. Thanks!

**Comment by Mridul97** [comment]
Allow edits from maintainers check-box is already ticked. Do I have to do anything else to allow edits from maintainers?

**Comment by tech4GT** [comment]
Oh sorry, my bad!! I just made a small change that enables caching on the first page load itself!! Have a look.

**Comment by tech4GT** [comment]
Ok!! Looks good to me! @jywarren please have a look and I think we can merge this in then.🎉

**Comment by tech4GT** [comment]
@jywarren We could but that would seem quite unrelated since it is a browser based feature, I don't think we should add a button for clearing the cache in the browser on the page since that can be done from inspecting the page anyway.
Also I was trying to think of the right UX for this and it won't quite fit anywhere since it would be unrelated to everything else on the page, what say?

**Comment by tech4GT** [comment]
I think we should add a prompt to install the app, that way service worker won't be installed without user permission?

**Comment by Mridul97** [comment]
I think prompt will be a good option that way user can also add the app to home screen of the device! Should I add a prompt to the web app?

**Comment by jywarren** [comment]
Yes, let's do that! Good idea.

**Comment by Mridul97** [comment]
Could you please elaborate 'after the addition of first step'. I didn't quite get it. Sorry.

**Comment by tech4GT** [comment]
Oh, I meant when add step is clicked for the first time then after adding the step we prompt the user asking to install the app.

**Comment by Mridul97** [comment]
I have made changes to prompt the user to install the app after adding the step. Just one thing, beforeinstallprompt event is not getting triggered itself but I have tested the functionality by manually triggering the event. Please have a look!

**Comment by tech4GT** [comment]
Okay so the browser compatibility for the prompt is very low, it’s basically just chrome. I don’t think we should go with this. 
@Mridul97 also you are right it’s not firing the event, could it be because localhost is not https ?

**Comment by Mridul97** [comment]
Oh okay I will try to make it compatible with other browsers. Yes, I think that could be the reason for event not firing, can't think of any other reason for event not firing. Thanks!

**Comment by Mridul97** [comment]
Actually I am not able to test the prompt on other browsers because I am not getting how to manually trigger the event in other browsers.

**Comment by tech4GT** [comment]
@Mridul97 Let's wait to hear what Jeff says on this, I don't think he would want to include a feature with limited browser compatibility!

**Comment by Mridul97** [comment]
I think the event will be triggered in other browsers as well because criteria for triggering the event is quite similar in all the browsers. Your thoughts please! @tech4GT

**Comment by Mridul97** [comment]
@jywarren @tech4GT I would love to be a mentor for Google Code-in. Is there any process to apply for the same?

**Comment by jywarren** [comment]
Is there a fallback system we could add for other browsers, or a notice
that a feature exists but is not compatible with the current browser?

**Comment by tech4GT** [comment]
@jywarren we can do that but since this is available on only chrome and there too this is sort of janky from what I read on stackOverflow, maybe we can keep this a separate long term issue, what say?

**Comment by tech4GT** [comment]
We are already ahead of the curve, providing offline support so maybe we can wait on install prompt until better browser compatibility.

**Comment by jywarren** [comment]
Yeah I think that's reasonable. Let's leave this open and think about ways
to name next steps.

On Sep 28, 2018 10:05 PM, "Varun Gupta" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> we can do that but since this is
available on only chrome and there too this is sort of janky from what I
read on stackOverflow, maybe we can keep this a separate long term issue,
what say?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/pull/331#issuecomment-425613871>,
or mute the thread

**Comment by tech4GT** [comment]
Okay so I'll create a separate issue for this, so I think we can merge this one in then! I'll take a final look to make sure everything is in place and then lets merge! Yay!!

**Comment by tech4GT** [comment]
#349

**Comment by jywarren** [comment]
Hi @tech4gt did you take a final look at this? I'm happy to merge it so!

**Comment by tech4GT** [comment]
I did but I'll do it again. I just want to be extra sure with this since I don't want someone to be stuck with the old version of files.

**Comment by tech4GT** [comment]
I'll test this out one last time and after I'm done I'll put the `ready-to-merge` label on this.

**Comment by jywarren** [comment]
Actually if it's possible to post some screenshots of this in action that'd be really helpful! To demonstrate the interaction it makes. I'd like to list out the behaviors exactly in this PRs description for good documentation as well. 

Thanks!!!!!

**Comment by tech4GT** [comment]
@Mridul97 Can you please get rid of the prompt parts in the code. Thanks!

**Comment by Mridul97** [comment]
> @Mridul97 Can you please get rid of the prompt parts in the code. Thanks!

Done!!

**Comment by tech4GT** [comment]
@Mridul97 I don't think you pushed it in😅

**Comment by Mridul97** [comment]
Actually I didn't create a new commit I just removed the last commit which added the prompt!

**Comment by tech4GT** [comment]
Oh Great!! @Mridul97 If it's not too much could you host this on your gh-pages? That way we can be absolutely sure that we got everything right!

**Comment by tech4GT** [comment]
We can then have other reviewers take a look at it as well! Once again thank for all the work you put into this!!

**Comment by tech4GT** [comment]
@Mridul97 I tried changing the cache name to v2 but my browser still says v1, can you please check this? I don't think cache is being updated.

**Comment by Mridul97** [comment]
It worked for me. Actually to change the cache name we have to change the cache name in sw.js file. I did that and committed the changes. Then a new version of the service worker is created and the new version is activated when we next time visit the website.

**Comment by tech4GT** [comment]
@Mridul97 I tried doing it, but it did not work for me. I wonder what might be the reason for this? As for the scope do you think we can use relative path?

**Comment by jywarren** [comment]
Hi, we could move the demo to a custom domain like https://image-sequencer.publiclab.org if that helps. Or could it be done relative, like without a leading slash `/`?

I ran your gh-pages branch and see:

```
sw.js:4 Attempting to install service worker
sw.js:8 [ServiceWorker] Activate
demo.js:68 Service worker registration failed, error: TypeError: Cannot set property 'onstatechange' of null
    at demo.js:59
```

is that an issue?

**Comment by jywarren** [comment]
Exciting, thanks!

**Comment by jywarren** [comment]
I'm glad we tried the `gh-pages` to catch this relative path thing...

**Comment by jywarren** [comment]
> @jywarren We could but that would seem quite unrelated since it is a browser based feature, I don't think we should add a button for clearing the cache in the browser on the page since that can be done from inspecting the page anyway.

I was thinking about this again... i'm just afraid people may get stuck in a version when a new one is available. This has happened to me with older versions of offline manifests, and having a small, dim, grey link at the very bottom of the page saying `This page is cached. Click here to flush the cache if you have trouble.` could help in the unusual case that someone gets stuck with, for example, a buggy cached version that cannot be refreshed. Anyways, not a big deal but it's from an abundance of caution 😄

**Comment by tech4GT** [comment]
@jywarren This sounds cool!!
- Let's do the button to clear the cache
- I think moving to a different domain is a good idea regardless of if we can use relative path or not, since it seems more natural to me, what say?
- That message is not an error, more of a warning, actually I put that part of the code in and it refreshes the page when the service worker is installed for the first time automatically so that everything is cached, we can easily work around it by using an if condition.

**Comment by tech4GT** [comment]
@Mridul97 Awesome work on this!!

**Comment by jywarren** [comment]
Ah, and one more thing -- when we add the button to flush cache, can we also add in the warning message the date at which the last cache was saved? (or next to the button -- it could say `This page was cached on ____________. Click here to flush the cache if you have trouble.`

Thanks SO MUCH for your work on this. It's really amazing and I appreciate your willingness to add on a few more things to ensure it goes smoothly when we roll out the caching. I've just been in a few nightmare scenarios where I release a new version of something but nobody gets it because there is an error in a previous version which stops it from auto-fetching the new version! Weird but true! 😨 

👍 👍 👍

**Comment by jywarren** [comment]
Just confirming that all files seem to have loaded from the service worker:

image

Once we have the flush link and save time, let's test one more time then merge it! Way to go!

**Comment by Mridul97** [comment]
Great! I will set up the flush link. Thanks!

**Comment by Mridul97** [comment]
I have made changes to add a button to clear cache. By clicking on the button, all the versions of the cache will be deleted and on next reload latest version of the cache will be saved. Please have a look!

**Comment by jywarren** [comment]
awesome, can you push to your gh-pages? thanks!

**Comment by Mridul97** [comment]
Done! Please have a look!

**Comment by jywarren** [comment]
Hmm, i'm not seeing the changes. Is it possible that the previous cache is not letting the new cache through?

screen shot 2018-10-05 at 2 00 16 pm

**Comment by Mridul97** [comment]
Yes, I think it is possible, because I didn't change the cache version. Could you please manually delete the old cache. Thanks!

**Comment by jywarren** [comment]
Ah, i see. and so for pull requests we should add to the template to change the cache version to ensure people see new changes. With the style changes, can you change the cache version and we'll check to see it works this time? this is good troubleshooting 😄 

Finally, let's add a page refresh when you click the "clear cache" button -- otherwise there's no feedback. Make sense?

Awesome work!

**Comment by Mridul97** [comment]
Actually it happened because I didn't change the cache version. The cache version is same as before so it didn't update the cache!

**Comment by jywarren** [comment]
Oh one more thing - can we append the cache version to the clear button, like `Clear offline cache (v___)` so that we know what version people are running? This will help with troubleshooting with people :-) 

👍 👍 👍

**Comment by Mridul97** [comment]
Awesome! I will make these changes and also change the version of cache this time!!

**Comment by Mridul97** [comment]
I have made the changes. Please have a look!

It may happen that changes are not visible at the first time. If that happens then please do not force load the page, just close the tab and try the link again. Thanks!

**Comment by jywarren** [comment]
It seems to work for me! @tech4gt you too?

**Comment by tech4GT** [comment]
oh, Jeff changed the url, it's sequencer.publiclab.org

**Comment by tech4GT** [comment]
SO It should work on examples

**Comment by Mridul97** [comment]
Great!

**Comment by jywarren** [comment]
Merged this after one final check! This is awesome. Great work, everyone!

**Comment by jywarren** [comment]
Hmm, oddly the cache footer line doesn't seem to be appearing in the demo: https://sequencer.publiclab.org/

i wonder how this happened, but the manifest line seems to be gone? Let's figure out what happened!

**Comment by jywarren** [comment]
Yikes! This was merged into master, not main. Opening a new PR to rebase and merge again!

**Pull request merged**
