### PR TITLE
brightness module not working on default value 175

### PR DESCRIPTION
**Pull request by bhavayAnand9**
Fixes 
brightness module has default value set to 175 in `info.json` file but in `module.js` file the `option.brightness` value is assigned 100 so when app boots up the slider is set to 175 but image brightness value is still 100. This PR just changes the `options.brightness` value to 175.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

before:
screenshot 2019-01-06 at 18 31 27

after changes:
screenshot 2019-01-06 at 18 31 40

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@bhavayAnand9 many such other defaults were changed in https://github.com/publiclab/image-sequencer/pull/607. Maybe you can fix those too?

**Comment by jywarren** [comment]
Thanks for the catch! How can we have these all driven from the same values
in a consistent place?

Thank you!!!!

**Comment by HarshKhandeparkar** [comment]
@jywarren how about running the sequencer once after the default options have been applied in the html page? Or loading the defaults from the `info.json` in the `module.js` file or maybe even in the `imageSequencer.js` file?

**Comment by HarshKhandeparkar** [comment]
Maybe we can add a util function called `loadDefaults()` which loads the defaults from `./info.json` file which is relative to the `module.js` file. This function can return an object with all the default values.

**Comment by jywarren** [comment]
Can module.js access the info.js defaults directly?

**Comment by HarshKhandeparkar** [comment]
> Can module.js access the info.js defaults directly?

We will have to `JSON.parse()` the file and iterate through the `inputs` array or object .

**Comment by jywarren** [comment]
Hmm, then a helper does sound good. But doesn't it get parsed in the UI
code?

**Comment by HarshKhandeparkar** [comment]
The info.json files do get parsed in UI code. We could add a new helper
function for the library so that we could run it at the start of every
module if required and manage the defaults directly from the info.json
file. No need to manage two file.

**Comment by jywarren** [comment]
That sounds great!

**Comment by HarshKhandeparkar** [comment]
Will you add a new issue for that?

**Comment by jywarren** [comment]
If you're interested, please go ahead and add one! I +1!

**Comment by HarshKhandeparkar** [comment]
Its 12AM here in India so I will add it tomorrow or you can add it if you want.

**Comment by jywarren** [comment]
oh please get some rest! :-)

**Comment by HarshKhandeparkar** [comment]
Surely, but I'm an owl anyways.

**Comment by Mridul97** [comment]
@jywarren @HarshKhandeparkar This idea seems quite interesting, if no one is working on this, I would like to work on this!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 you cab open the issue and work on it then 👍

**Comment by bhavayAnand9** [comment]
If we're implementing a util helper function there's no use for this PR, should I close it?

**Comment by bhavayAnand9** [comment]
@jywarren should I close this PR?

**Comment by bhavayAnand9** [comment]
cool!

**Pull request closed without merging**
