### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by tech4GT**
Update version

### CODE REVIEW

**Comment by tech4GT** [comment]
cc @jywarren

**Comment by HarshKhandeparkar** [comment]
@tech4GT is this version backwards compatible?

**Comment by tech4GT** [comment]
Nope

**Comment by HarshKhandeparkar** [comment]
What is new? Shouldn't it be documented? Or is it done already?

**Comment by tech4GT** [comment]
Harsh the releases are documented separately, as for the code I have updated the docs.

**Comment by HarshKhandeparkar** [comment]
I meant the code. I didn't follow the changes that happened. They happened really rapidly. Sorry

**Comment by HarshKhandeparkar** [comment]
How about merging https://github.com/publiclab/image-sequencer/pull/777 as well before version bump?

**Comment by tech4GT** [comment]
That's okay, I do that sometimes lol.
As for the changes we are now using a meta module generator for opaque meta modules. 
As for the old module generation api, those modules can't be generated but it's good practice to support the ones already made  up till the next major version with a deprecated tag. :)

**Comment by tech4GT** [comment]
Oh that pr has a lot work that it needs and since no module manipulates the steps directly it should not breal anything.

**Comment by HarshKhandeparkar** [comment]
Ok, cool! I was concerned since that pr might evolve into a backwards incompatible change.

**Comment by jywarren** [comment]
We'll merge this after #824!

**Pull request merged**
