### PR TITLE
Compilation of ui js files

### PR DESCRIPTION
**Pull request by Mridul97**
Issue #598 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
@jywarren I would like to refactor this to use require() and browserify. I think we can do it in a follow-up PR, will open one soon! Thanks :)

**Comment by jywarren** [comment]
oh ok! I'm not sure if this will conflict with https://github.com/publiclab/image-sequencer/pull/562 but I want to merge that first. Thanks, then will merge this.

**Comment by HarshKhandeparkar** [comment]
@jywarren @Mridul97 i think `image-sequencer.js` is included in the ui. Can we include the minified file in the minified ui files?

**Comment by jywarren** [comment]
Oh wait, sorry, `grunt build` is already in the tests! Awesome! Then I think this is good for now. Next up is `require()`!

**Pull request merged**
