### PR TITLE
Touch draggable sliders added for various modules using RangeTouch

### LINKED ISSUE #500: Make sliders for range values touch-draggable
This issue is a sub-issue of #487 , which is to be broken down into smaller issues.

As you can see in the link below, the image sequencer can take range values for many adjustments. What we would need to do is to make sliders that are touch-draggable  (similar to the slider for brightness) in steps such as contrast (below brightness). 

Since this page uses the Bootstrap library, I'd highly recommend you check out https://seiyria.com/bootstrap-slider/ to build your sliders with bootstrap.

TODO:

- [ ] Add touch-draggable slider for each range input
- [ ] Ensure all sliders are stylistically uniform

### Please show us where to look

http://sequencer.publiclab.org/examples/#steps=brightness{brightness:100},contrast{contrast:70}
image

### What's your PublicLab.org username?

JonathanXu1

### Browser, version, and operating system

Firefox63, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #500 
Touch sliders added for 4 other modules as well.

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
I think this can be achieved using css.

```
.input[type=range]{
    touch-action: manipulation
}
```

**Comment by aashna27** [comment]
> I think this can be achieved using css.
> 
> ```
> .input[type=range]{
>     touch-action: manipulation;
> }
> ```
> Can also add
> 
> `user-select: none;`

Its good to know 😄  so what do you suggest ??

**Comment by HarshKhandeparkar** [comment]
How about adding css instead of a new library for just one thing. The touchrange library has many other functions which are of no use for us as of yet. I have looked into its source code. It adds a few css properties.
```
user-select: none;
-webkit-user-select: none;
touch-action: manipulate;
```
Rest are just helper methods etc.
I found info about `touch-action` on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Also css is added to the examples/ directory so its not going to be included in the root library source directly. I think adding a few lines to the css is better than changing the package.json for adding some redundant libraries.

**Comment by HarshKhandeparkar** [comment]
Even if we want to use range-touch, downloading it in the examples/ directory or a CDN would be better than node_modules/

**Comment by aashna27** [comment]
> Even if we want to use range-touch, downloading it in the examples/ directory or a CDN would be better than node_modules/ because the library has to be included and then also packaged.

Amazing , i ll push a new one then 😄 Thanks a lot @HarshKhandeparkar

**Comment by jywarren** [comment]
oh cool!

**Comment by aashna27** [comment]
@HarshKhandeparkar Thanks. I ll look for something for this.

**Comment by HarshKhandeparkar** [comment]
Ok NP. Thanks!

**Comment by HarshKhandeparkar** [comment]
@aashna27 @jywarren the sliders are working for me on my phone in firefox as well as chrome. Haven't tested on safari yet.

**Comment by HarshKhandeparkar** [comment]
Maybe they were not working because of some bug and not incompatibility? The bug might have gotten fixed unknowingly.

**Comment by HarshKhandeparkar** [comment]
Adding the CSS might make it a little smoother perhaps and it might start working on other browsers if it is not already. So if it already works then we can add the CSS as a safeguard. Thoughts? @jywarren @aashna27

**Comment by aashna27** [comment]
> Adding the CSS might make it a little smoother perhaps and it might start working on other browsers if it is not already. So if it already works then we can add the CSS as a safeguard. Thoughts? @jywarren @aashna27
Sorry for the late reply , got a little lost. Yea it works for my phone as well now. The css can be added but I think its working for everyone now and i dont think that anything else is required anymore. @HarshKhandeparkar yea right possibly some update or bug might have fixed this. Thoughts ??

**Comment by HarshKhandeparkar** [comment]
I don't really know. I haven't tested it on safari. If it works on safari
as well as other browsers then maybe this issue can be closed and if the
issue is found again then it can be reopened.

**Comment by HarshKhandeparkar** [comment]
The CSS just removes the delay between touch events and nothing more than that. That kight have potentially smoothened the dragging but I don't think that is necessary.

**Comment by HarshKhandeparkar** [comment]
Cool, I guess this can be closed.

**Comment by aashna27** [comment]
> 
> 
> Cool, I guess this can be closed.

yes sure. 😄

**Comment by jywarren** [comment]
Oh cool! Thanks all!

**Pull request closed without merging**
