### PR TITLE
Switch to npm for gifshot

### LINKED ISSUE #687: Switch to npm for gifshot
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: the file [package.json](https://github.com/publiclab/image-sequencer/blob/main/package.json) as following: 
Add the line : **"gifshot": "^0.4.5",** after the **"get-pixels": "~3.3.0",** line

- [ ] **Delete** the following file [gifshot.js](https://github.com/publiclab/image-sequencer/blob/main/examples/gifshot.js)

- [ ] 📝 **Update**: the file [index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) as following: 
Change line 28 from **<script src="gifshot.js" type="text/javascript"></script>** to **<script src="../node_modules/gifshot/dist/gifshot.min.js" type="text/javascript"></script>**

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by atsutton**
Fixes #687

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by atsutton** [comment]
@publiclab/is-reviewers  -- I made this a fork instead of a branch. I hope that doesn't cause an issue? Let me know if I've overlooked something. Thanks!

**Comment by HarshKhandeparkar** [comment]
@atsutton making a fork is not a problem but creating a new branch with a descriptive name is always helpful for reviewing.

**Comment by atsutton** [comment]
Great, thank you.

**Comment by atsutton** [comment]
@HarshKhandeparkar I pushed a new commit with an updated package-lock.json file. It appears to have passed the checks. Please let me know if you need anything else.

**Comment by atsutton** [comment]
@HarshKhandeparkar Sure -- pasted below. 

sample

**Comment by atsutton** [comment]
@HarshKhandeparkar - Sorry, I'm not sure what you mean about the cache. Can you elaborate?

**Comment by HarshKhandeparkar** [comment]
Image Sequencer caches all its assets offline so it can actually even work
offline but when it is online, it doesn't update to the latest version
directly. It loads the old version which was cached offline. Therefore,
there is clear offline cache button at the bottom of the page which clears
all cache. You have to click it each time you update something even for
`localhost`. Please make sure you had cleared the cache. Thanks!

**Comment by atsutton** [comment]
@HarshKhandeparkar - I cleared the cache and resynced with the main branch. Please let me know if they're is anything else.

**Comment by HarshKhandeparkar** [comment]
@atsutton you are good to go! :+1:

**Comment by HarshKhandeparkar** [comment]
@jywarren this is ready for a final review.

**Comment by atsutton** [comment]
@HarshKhandeparkar - awesome, thanks for your help.

**Comment by HarshKhandeparkar** [comment]
@atsutton you don't have to commit anything after clearing the cache. The cache is just a local browser thing which needs to be cleared in order to view the latest changes.

**Comment by atsutton** [comment]
@HarshKhandeparkar - Hah! Thank you for clarifying that. I was pretty confused, thinking, "If I clear the cache, how is that going to impact the commit? I don't see any changes! Oh well, do it anyway." But I understand now, thanks.

**Comment by HarshKhandeparkar** [comment]
:+1: 😊

**Comment by jywarren** [comment]
Fantastic work here! Thanks very much!!!!

**Pull request merged**
