### PR TITLE
Html type in info files

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/570

Added separate property `htmlType` to `info.json` files to make the `type` property more specific.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren I fixed the issues with the last PR and the tests pass locally.

DOCS:
https://github.com/HarshKhandeparkar/image-sequencer/blob/htmlType-in-info-files/CONTRIBUTING.md#info-file

**Comment by HarshKhandeparkar** [comment]
@jywarren @tech4GT please have a look.

**Comment by HarshKhandeparkar** [comment]
@jywarren @tech4GT please review this.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review this.

**Comment by HarshKhandeparkar** [comment]
@Mridul97 @VibhorCodecianGupta can you guys please review this?

**Comment by HarshKhandeparkar** [comment]
@jywarren

**Comment by dojutsu-user** [comment]
@HarshKhandeparkar 
Please be patient as this is not the only PR to be reviewed by the team. https://github.com/publiclab/image-sequencer/pulls

**Comment by HarshKhandeparkar** [comment]
@dojutsu-user who are an old contributor?

**Comment by HarshKhandeparkar** [comment]
Or a reviewer for some other project like plots?

**Comment by dojutsu-user** [comment]
@HarshKhandeparkar 
I am just another open-source enthusiast and full-stack developer who WAS looking to contribute towards this organisation but seeing this kind of behaviour as seen above, I feel regretful to change my decision.

> Seems like all the V. Guptas contribute to image-sequencer

Also, this is not a social media paltform, this is a PR. I request @jywarren @tech4GT to please look into this rude and insignificant behaviour.

Also tagging @VibhorCodecianGupta  to bring this comment to his notice.

**Comment by HarshKhandeparkar** [comment]
@dojutsu-user I was a bit impatient as I am going to be busy for the next 2 years and I have only 1 month time window before I stop doing anything. Sorry if you felt that I was a bit rude. My apologies 😣😣

**Comment by HarshKhandeparkar** [comment]
Sorry I will delete my comment

**Comment by HarshKhandeparkar** [comment]
To me, that was just a comment. I was really happy to see this community grow. I am really sorry if it hurt anybody's feelings. I didn't mean to do that.

**Comment by HarshKhandeparkar** [comment]
Please contribute to image sequencer. Don't feel hurt by my comments. We would like your help. Welcome to the image sequencer community. I am just a GCI student btw

**Comment by HarshKhandeparkar** [comment]
Also the first question that i asked
> Who are an old contributor?

That was a typo. I meant to ask if you were an old contributor. I have updated that comment now.

**Comment by dojutsu-user** [comment]
@HarshKhandeparkar 
I am not an old contributor of publiclab.

**Comment by HarshKhandeparkar** [comment]
Thanks @gauravano for adding that label

**Comment by HarshKhandeparkar** [comment]
@jywarren @gauravano based on @dojutsu-user's first comment, I thought that he might be an old contributor or a reviewer whom I haven't met before so I wanted to ask him that question but while I was typing the question, I reframed it once but while doing that I made a typo.

Istead of writing 

> Are you an old contributor?

I wrote

> Who are an old contributor?

This question kind of seems like a rhetorical one even though it was not meant to be. This might have created a misunderstanding and the comment might have looked a little rude to @dojutsu-user. As for the second comment about contributors, I accept my mistake and I have apologised already. Sorry, I will not repeat such behaviour again and think twice before comment. 😞😞😞😞

**Comment by jywarren** [comment]
Hello all - I apologize for not commenting earlier. I agree with @gauravano that this was regrettable and @dojutsu-user thank you for bringing this to our attention. @HarshKhandeparkar your apology is appreciated and I'll just add that we can all experience moments of impatience or frustration, but taking a moment to consider before replying is often a good habit in these moments. 

@dojutsu-user (and anyone else as well), please feel free to reach out to moderators@publiclab.org if you feel you'd like to discuss this further off this thread. 

Thank you for upholding our Code of Conduct and I hope we can build a constructive way forward from here.

**Comment by HarshKhandeparkar** [comment]
I don't think this is needed anymore due to changes suggested in https://github.com/publiclab/image-sequencer/issues/570#issuecomment-454173658

**Pull request closed without merging**
