### PR TITLE
Changed the warning log

### PR DESCRIPTION
**Pull request by Ronaq13**
Since our execution is not exactly async, hence the corresponding change in
the log message is more suitable log.

close 194

### CODE REVIEW

**Comment by tech4GT** [comment]
@Ronaq13 this looks good, thanks a lot😁👍

**Comment by Ronaq13** [comment]
Is it ready to merge? @tech4GT

**Comment by tech4GT** [comment]
Yeah totally, in the meantime feel free to browse through other issues
Thanks😁

**Comment by jywarren** [comment]
Hooray!!!! 🎉

**Pull request merged**
