### PR TITLE
Test for Brightness module

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
It sounds great! I was also thinking to compare the images. I will implement it and push the changes. Thanks!

**Comment by jywarren** [comment]
Ah shall I merge this then?

**Comment by Mridul97** [comment]
We have to add a test for image comparison, then should we do it in a follow-up pr?

**Comment by jywarren** [comment]
Either way! Just looking at the json error.

On Jan 8, 2019 10:48 PM, "Mridul97" <notifications@github.com> wrote:

We have to add a test for image comparison, then should we do it in a
follow-up pr?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/pull/624#issuecomment-452562467>,
or mute the thread

**Comment by Mridul97** [comment]
Oh Then let's merge this one, and I will open a follow-up pr for the image comparison test! :)

**Comment by jywarren** [comment]
Great!

**Pull request merged**
