### PR TITLE
Headless Browser testing using tape-run

### PR DESCRIPTION
**Pull request by ccpandhare**
This PR adds headless browser testing to Image Sequencer.

There are three files in the `test/` folder.
Out of these three, two JS files run perfectly in the headless browser test. But one doesn't. That file is `test/image-manip.js` Hence I have not included that file here. Can you help me? I tried a lot, but I couldn't realize why this may be failing.

Shell command to test the file:
```
$ browserify test/image-manip.js | tape-run
```

These are the tests that file contains:

```js
var sequencer = ImageSequencer({ ui: "none" });
var image = "SOME DataURI";
sequencer.loadImages(image);

sequencer.addSteps(['do-nothing-pix','invert','invert']);
sequencer.run();

test("Inverted image isn't identical", function (t) {
  t.notEqual(sequencer.images.image1.steps[1].output.src, sequencer.images.image1.steps[2].output.src);
  t.end();
});

test("Twice inverted image is identical to original image", function (t) {
  t.equal(sequencer.images.image1.steps[1].output.src, sequencer.images.image1.steps[3].output.src);
  t.end();
});

```

### CODE REVIEW

**Comment by ccpandhare** [comment]
This fixes #38

**Comment by jywarren** [comment]
Wow, cool, so this runs the entire suite in both Node and PhantomJS? 

If it fails in one or the other, does it indicate whether if failed in one or the other?  Maybe we just need a little more labeling in the tests? 

I think there are some libs to make tape output a bit more readable, it could be worth a search around. Or just log out some notes like "Starting/ending phantomjs in-browser tests"  and such. You could intersperse with `#####################` to delineate a bit more too.

:-)

**Comment by ccpandhare** [comment]
Okay I will have a look at those modules.

First, the normal Node based `tape test` is run. (ALL TESTS)
Then, `tape-run` is run. (ALL TESTS)
Both these are triggered by the `$ npm test` command.

We can easily make out where the test is failing -- Node, or Browser.

What `tape-run` does: It runs the tests separately in `Electron` and outputs standard TAP output, just like tape.

**Comment by ccpandhare** [comment]
### Changes
* I have added descriptions for each test.
* I have added `tap-spec` module for beautification

**Comment by ccpandhare** [comment]
So is this good? What do you think?

**Comment by jywarren** [comment]
yep! merge!

**Pull request merged**
