### PR TITLE
Corrected default view for Saturation module

### LINKED ISSUE #801: Issue with saturation
### When we open the saturation then the images are turning to a black screen. 

saturation

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #801 
Fixes the problem:
image

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by aashna27** [comment]
> 
> 
> Awesome! I used to hate the saturation module. Once I even thought that my flipImage module was not working since the older step was saturation.
> 😊😊

😆 😆  sorted now ...

**Comment by jywarren** [comment]
Ah, is the screenshot above depicting the problem, not the solution? Can you screenshot the saturation module working correctly? Thank you @aashna27 this is great! The new defaults system will make a lot of this smoother now.

**Comment by aashna27** [comment]
> 
> 
> Ah, is the screenshot above depicting the problem, not the solution? Can you screenshot the saturation module working correctly? Thank you @aashna27 this is great! The new defaults system will make a lot of this smoother now.

yea this one is the problem .

Solution:

ezgif com-video-to-gif 2

**Comment by jywarren** [comment]
Perfect. Varun has a big open PR he doesn't want to rebase so let's give him some time. I'll mark this as ready and if you have any input on my most recent two PRs I'd love some help!

**Comment by aashna27** [comment]
> 
> 
> Perfect. Varun has a big open PR he doesn't want to rebase so let's give him some time. I'll mark this as ready and if you have any input on my most recent two PRs I'd love some help!

yea .. I did comment to go forward with the benchmark one , if you would like that.Thanks

**Comment by aashna27** [comment]
@jywarren how about merging this one, I have rebased it.

**Comment by jywarren** [comment]
:tada:

**Pull request merged**
