### PR TITLE
Brightness module

### PR DESCRIPTION
**Pull request by tech4GT**
@jywarren please review

### CODE REVIEW

**Comment by jywarren** [comment]
Thanks a lot! This is a great one. The images will help w documentation and just to be sure how it looks in the browser.

**Comment by jywarren** [comment]
Also, I'm thinking about using this PR as an example to others for how to submit a module. But I'd like to exclude the spacing changes from it. Do you think you could submit the spacing changes as a separate PR i could merge first so that this one reads more cleanly? But not super important, just thinking of how to encourage more module contribution.

**Comment by tech4GT** [comment]
@jywarren should i add the pictures in the readme?

**Comment by tech4GT** [comment]
@jywarren an surely i can pr the rest of the changes first in a separate pr😁

**Comment by jywarren** [comment]
Oh, just here in the PR is fine. But if you add a test demonstrating the
module function you might add some there too. We have a tiny image in
base64 we use for some of the tests. :-)

**Comment by tech4GT** [comment]
@jywarren please have a look at https://github.com/publiclab/image-sequencer/pull/160 and then https://github.com/publiclab/image-sequencer/pull/161

**Pull request closed without merging**
