### PR TITLE
Adds Minify-Image module

### LINKED ISSUE #1142: Minify Image module
@jywarren I am working on a minify-image module whose workflow is:

min

For this I need to convert the input datauri to a image file like a png/jpeg file (which will be deleted later). Can you help me out with how can I approach this?

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #1142   

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren the current functionality is working good in both node and CLI interfaces though in browser, I see the following error:

Screenshot from 2019-07-03 03-52-37

Please help with this!!

This appears as soon as I click on add-step button after selecting minify-image module option.

**Comment by jywarren** [comment]
It looks like you're trying to use the `fs` library somehow? It's referencing `fs.js` in any case. Can you rebase this so we see a clean commit history?

**Comment by Divy123** [comment]
Let me give rebase a try.

**Comment by Divy123** [comment]
@jywarrrn can you please guide me on the part that I have already made merges so how should I proceed with a rebase like I know these two are options of each other, so what should be the case here?

**Comment by Divy123** [comment]
Closing this for a rebase.

**Comment by jywarren** [comment]
Moved to https://github.com/publiclab/image-sequencer/pull/1149

**Pull request closed without merging**
