### PR TITLE
Opaque meta module test - colorbar

### PR DESCRIPTION
**Pull request by jywarren**
Re #315 -- an attempt to refactor the colorbar module to be a fully opaque meta module - that is, a module which:

1. contains other modules
2. acts like a normal module in every way
3. contains an independent sequencer in order to pass an input through a sequence and produce an output

If this works (and it's not running yet -- I'm stuck for some reason because `draw()` is not executing... help!) then we may be able to create a generator for these, which is to say, a way to automate the creation of opaque meta modules given:

1. a JSON object or string of steps
2. a function which maps the outer module options to the options objects of the internal steps (or falling back to the defaults if mapping is not provided)
3. a set of overriding defaults for internal steps (which could be done via the mapping function too)

@publiclab/is-reviewers take a look here, i got inspired and tried it out, but need a bit of help to debug my work!

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren Looking into this right now!

**Comment by HarshKhandeparkar** [comment]
@jywarren how about adding a new util function. Maybe mini-sequencer? This can also be used to create semi-meta modules(modules which use other modules inside them but not fully). And sequencer.createMetaModule can use this util function. Thoughts?

**Comment by tech4GT** [comment]
Hi Jeff, Can you please allow edits from maintainers so I can push in the fix :sweat_smile:

**Comment by tech4GT** [comment]
I am not able to push to jywarren:opaque
Wonder why this is happening since it allows to me edit the pr using the inline editor??

**Comment by jywarren** [comment]
Ah, we made a mistake with `inBrowser = inBrowser || true`, essentially it could never be made false, added a fix for `(inBrowser === true)`. We should probably document this better, and run a test for it.

**Comment by tech4GT** [comment]
Yeah, I fixed it!!

**Comment by tech4GT** [comment]
Do you want me to make a pull request on jywarren:opaque ??

**Comment by tech4GT** [comment]
Also the function is sequencer.loadImage and not addImage :sweat_smile:

**Comment by jywarren** [comment]
sure, and edits by maintainers is already allowed... sorry i am on the run at the moment, but can you add a test to demonstrate it working? That's a good idea anyways! Thanks Varun!

**Comment by tech4GT** [comment]
I'll add the test and make the pr! This is working like a charm btw!! :tada:

**Comment by jywarren** [comment]
I tried a fix but didn't get the colorbar module to appear. But very happy to take your fix, thank you! Agreed this is very fun!

We can really make a generator function which essentially parameterizes everything shown in this example module; it should be pretty straightforward.

**Comment by tech4GT** [comment]
Yeah I am drawing up a design right now! :smiley:

**Comment by jywarren** [comment]
You can also just open a new PR building on these commits and close this one if you want. Thanks! Won't be able to check in for a few hours though.

**Comment by tech4GT** [comment]
Integrating the generator into createMetaModule

**Comment by tech4GT** [comment]
Oh okay will do! That's okay! :+1:

**Pull request closed without merging**
