### PR TITLE
align add-step button with select-module input

### PR DESCRIPTION
**Pull request by bhavayAnand9**
Fixes 
Align `Add Step` button with `More module...` select input.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
Hi @bhavayAnand9, can you share a screenshot your changes?
Thanks!

**Comment by bhavayAnand9** [comment]
screen shot 2018-11-30 at 13 44 24

**Comment by Rishabh570** [comment]
Oh cool! This looks great!! BTW which issues this resolves?

**Comment by bhavayAnand9** [comment]
I was a simple fix so I didn't create an issue for it. I hope it's ok

**Comment by jywarren** [comment]
Nice, thanks a lot!!!

**Comment by Rishabh570** [comment]
Ah, great work anyways :tada:

**Pull request merged**
