### PR TITLE
seprated the title and radio group file

### PR DESCRIPTION
**Pull request by keshav234156**
In continuation to PR #1366 .

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywarren in the previous PR #1366 we are actually testing radio -butttons .So changed it name and seprated it from title test .Also added all the 6 modules that are present in radio group

**Comment by keshav234156** [comment]
@jywarren can you please review the changes?

**Comment by keshav234156** [comment]
@jywarren I have updated the Branch. Is there still a conflict?

**Comment by jywarren** [comment]
Nope, all good now!!

**Comment by jywarren** [comment]
🎉

**Pull request merged**
