### PR TITLE
Modules in alphabetical order

### LINKED ISSUE #375: Arrange the modules in alphabetical order
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Problem
Arrange the modules in alphabetical order, the modules right now are not in alphabetical order.

ss_20

# The Solution
We need to modify the src/Modules.js file. We need to arrange the modules in the src/Modules.js file in alphabetical order.

https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/src/Modules.js#L4-L26

<strong>Instance Count = 1</strong>

### PR DESCRIPTION
**Pull request by aDvernichuk**
For GCI

Fixes #375 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by ho-dor** [comment]
can I work on this @aDvernichuk ?

**Comment by aDvernichuk** [comment]
yes you can @ho-dor

**Comment by ho-dor** [comment]
I think this issue has already been solved @aDvernichuk  in #375.

**Comment by jywarren** [comment]
Yes, i think that's right. Thank you in any case!!!

**Pull request closed without merging**
