### PR TITLE
Refactor Draw Rectangle Module

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/662

Removed similar code and refactored.

works fine still:

draw-rectangle-refactor

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review. @Mridul97 @jywarren?

**Comment by HarshKhandeparkar** [comment]
@Mridul97 thanks!

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta @jywarren

**Comment by jywarren** [comment]
Nicely done, thank you!!!

**Pull request merged**
