### PR TITLE
HtmlType property in info.json files

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/570

Added separate property `htmlType` to `info.json` files to make the `type` property more specific.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren @tech4GT please review.

**Comment by HarshKhandeparkar** [comment]
@jywarren should I change the docs too?

**Comment by HarshKhandeparkar** [comment]
The step toggle thing was not working so I fixed it. Was a small fix so I included it. Had to do that or otherwise, I was not able to work. I made it more efficient too!

collapse-fix

**Comment by HarshKhandeparkar** [comment]
@jywarren I found something, `grunt build` does not compile UI files only `grunt serve` does.

**Comment by HarshKhandeparkar** [comment]
@jywarren I have changed the docs

https://github.com/HarshKhandeparkar/image-sequencer/blob/main/CONTRIBUTING.md#info-file

**Comment by HarshKhandeparkar** [comment]
The tests are failing. Please help me here!

**Comment by HarshKhandeparkar** [comment]
@jywarren please help me with the errors.

**Comment by HarshKhandeparkar** [comment]
The errors are weird. Seems like channel and blur modules are causing errors.

**Comment by HarshKhandeparkar** [comment]
Those modules are having default parameters but the expected does not. How does this link to my pr?

**Comment by HarshKhandeparkar** [comment]
@jywarren If I change the line

https://github.com/publiclab/image-sequencer/blob/c72beb7359025c4ecb9d110594924e93372db61e/src/modules/Channel/Module.js#L6

to 
```js
options.channel = options.channel;

then the tests pass for the `toString()` part

**Comment by HarshKhandeparkar** [comment]
Also the same for `blur` module. Why is this happening? Does this link to my PR?

**Comment by HarshKhandeparkar** [comment]
My mistake sorry! I looked into the source code. The inputs need to have the `min` `max` `desc` etc properties as direct children. I am closing this one. Will open a new one.

**Comment by HarshKhandeparkar** [comment]
Tests are passing!!

**Comment by jywarren** [comment]
oh ok, great!

**Pull request closed without merging**
