### PR TITLE
[GCI] Standardised Blur module code comments

### LINKED ISSUE #1342: Standardise Blur module code comments
Note: **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

This is a sub-issue of #1046

The comments in the following files are inconsistent:
1. [Blur.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Blur/Module.js)
2. [Module.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Blur/Module.js)

Rules:
1. Methods must be described using [JSDoc comments](https://devdocs.io/jsdoc/)
2. Misc code comments should be inline unless it is a long sentence.
3. No use of continuous tenses, no pronouns.
4. No redundant comments.
5. Each comment should start with an uppercase letter and end with a full stop.

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #1342  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@SidharthBansal please try to get these PRs merged quickly. I don't think I will be free next month so I want to complete as many tasks as possible this month itself. Thanks!

**Comment by Divy123** [comment]
@HarshKhandeparkar I will be reviewing PRs from next week. But please be patient, as we have to make it feasible for all the mentors and participants to participate smoothly, we will try our level best. Next thing is I think Siddharth will be doing it whenever he will be here,and we have to make it open for all. So we cannot make it a personalized experience for someone.

**Comment by HarshKhandeparkar** [comment]
@Divy123 yeah sure. I am in a hurry because the task I have already accepted is about to hit the deadline and also I hadn't expected it to take such a long time. Sorry if I am causing inconvenience to others. If I had known that I would have to split this task or if the task had been split earlier, I would have left it to claim at the end. Sorry still.

**Comment by HarshKhandeparkar** [comment]
My school schedule is going to be busy now on. This is the only month when I got a bit of free time. Otherwise, I wouldn't even have participated.

**Comment by SidharthBansal** [comment]
I can review your prs tomorrow. I am busy today. He is assigned one hall-of-fame task. I asked him to divide it into multiple PRs so that we can review it easy.
Thanks all of you

**Comment by SidharthBansal** [comment]
Codeclimate is failing please check

**Comment by HarshKhandeparkar** [comment]
Is there a reason why you closed the PR?

**Comment by SidharthBansal** [comment]
By mistake

**Comment by SidharthBansal** [comment]
Please open it

**Comment by HarshKhandeparkar** [comment]
Ohk.

**Comment by HarshKhandeparkar** [comment]
@jywarren can this and the other comments GCI PRs be merged now?

**Comment by jywarren** [comment]
Yes! Let's rebase and we should be good to go! Thanks!!

**Comment by HarshKhandeparkar** [comment]
Thank you!

**Comment by jywarren** [comment]
Hmm, do you know what these errors are? Thanks!

**Comment by HarshKhandeparkar** [comment]
I'm not sure. Gifshot does use canvas but these tests don't run on GIFs so
there is no question of Gifshot. But these errors are definitely related to
canvas.

Perhaps one of the modules which requires canvas doesn't check for the
`inBrowser` flag...

**Comment by keshav234156** [comment]
@jywarren it seem like it was some travis fault.Now it's fine.

**Comment by jywarren** [comment]
Looking to merge this one next after updating branch!

**Pull request merged**
