### PR TITLE
Fixes #395:Disabled save-sequence button when no steps are added.

### LINKED ISSUE #395: Disable the Save Sequence button until one step is added
# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Issue
The `save-sequence` button in the UI should be disabled until some step is added in the sequence.

Here's where the `save-sequence` button is made:

https://github.com/publiclab/image-sequencer/blob/9168c15cf9ece28521e92c5fb1d5dd453518c937/examples/index.html#L99

We can make the button disable at the start and then enable it on first click of Add step button. We have to also disable the button if all the steps are removed.

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren please review.

**Comment by Paarmita** [comment]
@Divy123 Thanks for the PR :) It looks great.

**Comment by jywarren** [comment]
This looks great. Very nicely done! Thank you!

There are plenty of issues up for grabs in this project, we'd love more help! Great work!

**Comment by jywarren** [comment]
And thanks @Paarmita for the extra review! Are you mostly focusing on one project or another, or just looking out across all publiclab projects? So helpful!

**Comment by Paarmita** [comment]
@jywarren I'm looking out all the projects of the organization and specifically helping the students on making their PR.

**Comment by jywarren** [comment]
That is so wonderful. Thank you @Paarmita !!!

**Pull request merged**
