### PR TITLE
Change meta modules test

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, would you mind explaining this a bit more to me? Thanks!

**Comment by Mridul97** [comment]
@jywarren I think in meta modules we should check for steps[1] and steps[2] as steps[0] will be load-image and in meta modules we don't need to check for that but for steps[1] and steps[2]..

**Comment by jywarren** [comment]
Ah, ok - that makes sense. Can you test their module names as well, so we're extra sure? Thanks!!!

**Comment by Mridul97** [comment]
@jywarren yes, I will test for their module names as well!

**Comment by Mridul97** [comment]
@jywarren I have made the changes, please check if something like this is required to be done!

**Comment by jywarren** [comment]
Looks super. Can you resolve the conflict and then this is ready to merge! Thank you!!! 🎉

**Comment by jywarren** [comment]
OK, the big merge at #824 is done -- would you mind resolving the conflicts here? Thank you!

**Comment by Divy123** [comment]
@jywarren I would like to complete this one, if its feasible.
Thanks!!

**Comment by jywarren** [comment]
Yes, perhaps if @Mridul97 is busy you could help build on their work to get this completed? I think it's only a resolve conflicts issue. Thank you!

**Comment by Divy123** [comment]
Surely will..

**Comment by Divy123** [comment]
Since Varun has added the new workflow for adding metaModules along with the tests, due to which the whole workflow has changed.
These tests are incorrect now and won't work.
So I think the PR can be closed without any work on this.
@jywarren please close this PR.

**Comment by jywarren** [comment]
Oh I see, because now metamodules do not decompose into separate modules? Hm I guess you're right. Is there a need for some portions of this test still though? 

What if we tried instead making a metamodule and then comparing it's output to the same modules if they weren't in a metamodule?

**Comment by Divy123** [comment]
Sure will do that!
I will be sending a different PR for the same so closing this one.

**Comment by jywarren** [comment]
Ok, thank you so much!!

**Pull request closed without merging**
