### PR TITLE
preview optimization

### LINKED ISSUE #1184: New preview optimization - drawing from wrong image?
hi @aashna27 i tried the new beta published by @HarshKhandeparkar and saw this:

image

It seems like maybe the previews are not drawing on the last step, but the first step? 

http://beta.sequencer.publiclab.org/examples/#steps=dither{dither:floydsteinberg}

On the other hand, I tried the non-beta main site and it just stalled 😆 so we're already doing better 😄 

image

Aha, it finally ran. But it suffers the same issue. I think the preview system may always have been connected to the initial image, instead of the final step? not sure, but we should fix this!

image

Thanks, all!

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #1184 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywarren can you please review the changes!!

**Comment by jywarren** [comment]
Hi, cool! I'm not sure we do any testing for this, so would you mind sharing a gif? Thanks a ton!

**Comment by jywarren** [comment]
And/or a test, actually 😄

**Comment by keshav234156** [comment]
https://drive.google.com/file/d/1mULwSsFRxEM0f9RNRC34s9A6F78M1GON/view

**Comment by keshav234156** [comment]
@jywarren I must say that you are now better at managing your notification!!!

**Comment by jywarren** [comment]
Well, i have more time today, but i'm not sure I can keep it up!

**Comment by jywarren** [comment]
Great! Thank you!!

**Pull request merged**
