### PR TITLE
Header opens a new page with no steps

### LINKED ISSUE #568: Make "Image Sequencer header" reload the page with no steps.
This is a sub-issue of #487 .
####  where to look

http://sequencer.publiclab.org...

### PR DESCRIPTION
**Pull request by aashna27**
Fixes #568

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> I have left the button part believing that @Mridul97 would be interested to go for it.

### CODE REVIEW

**Comment by Mridul97** [comment]
Great! Looks good! I will open a PR soon with a button in the footer to start a new sequence on the same page. Thanks!

**Comment by jywarren** [comment]
Oops, conflicts!

**Comment by aashna27** [comment]
> Oops, conflicts!

yepp new commit 😄  I ll make a new one then

**Comment by aashna27** [comment]
is it okay if i dont push the dist files next time ?
cause with the new commits it gives conflicts?

**Comment by jywarren** [comment]
Maybe we need to come up with a new strategy for this, because we do need to build each time, but indeed it makes rebasing/merging a real pain! I wonder if there is a conventional way to manage this...? could bear searching around a bit...

**Comment by jywarren** [comment]
OK, discussion ongoing in https://github.com/publiclab/image-sequencer/issues/601 !

**Pull request closed without merging**
