### PR TITLE
Fixed quick buttons issue

### LINKED ISSUE #888: Error: Cannot read property 'options' of undefined
I'm seeing this on the latest main branch, when clicking a quick-add module: https://sequencer.publiclab.org/examples/

```
image-sequencer.js:68615 Uncaught TypeError: Cannot read property 'options' of undefined
    at Object.modulesInfo (image-sequencer.js:68615)
    at Object.selectNewStepUi (image-sequencer-ui.js:294)
    at HTMLDivElement.<anonymous> (image-sequencer-ui.js:83)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.y.handle (jquery.min.js:2)
```

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #888 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Divy123** [comment]
ezgif com-video-to-gif (1)

**Comment by Divy123** [comment]
@jywarren please have a look!

**Comment by Divy123** [comment]
@jywarren please have a look!

**Comment by HarshKhandeparkar** [comment]
What exactly was cauing the problem?

**Comment by Divy123** [comment]
Actually the cause was selectize itself.
It was making select display none and adding its own custom div elements due to which the select was not available . This is happening only in case of quick buttons as for the drop-down part we are not relying on that.
So passing stp name as the parameter worked.

**Comment by HarshKhandeparkar** [comment]
Oh cool!

**Comment by jywarren** [comment]
Awesome thank you!!!!

**Comment by jywarren** [comment]
This is super and I'll release it with v3.0.1. Let's think about how we could've caught this in a test beforehand! 

Great work, thanks so much everyone!

**Pull request merged**
