### PR TITLE
Fix ScopeQuery

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #0000  (<=== Replace `0000` with the Issue Number)

@Divy123 @jywarren

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren try to merge this ASAP. @Divy123 please review this. I recommend you to review this locally. Thanks a lot!

**Comment by Divy123** [comment]
@HarshKhandeparkar request you to send the following:
1. GIF of working demo, showing insert step button.
2. Screenshot of console

**Comment by HarshKhandeparkar** [comment]
@Divy123 it seems to work offline but I think it would be better if you check it on your PC itself instead of me sending a pic, to make sure everything really works.

**Comment by Divy123** [comment]
Sure!

**Comment by HarshKhandeparkar** [comment]
And the browser has no errors. Not even the `.contains` error.

**Comment by Divy123** [comment]
Checking it now.

**Comment by Divy123** [comment]
@HarshKhandeparkar facing some issues with npm right now.
@publiclab/is-reviewers please someone test this out locally and post here some screenshots.

**Comment by HarshKhandeparkar** [comment]
What is the npm issue? Maybe I can help

**Comment by Divy123** [comment]
Working too slow, looking into now!!

**Comment by HarshKhandeparkar** [comment]
What is working too slow? Download?

**Comment by Divy123** [comment]
npm install and especially electron takes a lot of time

**Comment by HarshKhandeparkar** [comment]
Hmm. I think it is the download. It downloads chromium. We should really
switch to yarn

**Comment by Divy123** [comment]
PR ready to be merged!!
Great work @HarshKhandeparkar .
Thanks a lot.

**Comment by Divy123** [comment]
I think this is great.
@jywarren request you to merge this as soon as possible. Maybe what Harsh has done here and work in my PR can get everything fixed together.

**Comment by HarshKhandeparkar** [comment]
@Divy123 thanks!
Which PR are you working on btw?

**Comment by Divy123** [comment]
Actually this PR corrects the insert-step button but the internal working is also broken, so I am working on that.

**Comment by HarshKhandeparkar** [comment]
Yes I noticed that. I first thought that it was my mistake but it wasn't.

**Comment by Divy123** [comment]
No its not your PR something else broke it. I have fixed the working but still some more things to be fixed. Working on it.

**Comment by HarshKhandeparkar** [comment]
Thanks a lot!!!

**Comment by jywarren** [comment]
Great, merged this. where is your PR now, and what's our status re: #1100 and to the urgent issue from and https://github.com/publiclab/image-sequencer/issues/833#issuecomment-505648484 ?

**Comment by jywarren** [comment]
Thank you! Just coming online after a weekend! Trying to get synced up but also working on high priority publication of MapKnitter!

**Pull request merged**
