### PR TITLE
remove redundant selectize css link

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by Harshithpabbati** [comment]
@harshkhandeparkar we need it for selectize.

**Comment by HarshKhandeparkar** [comment]
It is already included through node modules

**Comment by Divy123** [comment]
@HarshKhandeparkar the css is not there through node_modules as I havve customized some part of css in there.
So that cannot go through node_modules.
I think the PR should be closed

**Comment by HarshKhandeparkar** [comment]
Why have you customised it? That should not be done. We use node modules to maintain consistency and to do proper version bumps. Instead you can add css for the same classes in demo.css and add the `! important`.

**Comment by HarshKhandeparkar** [comment]
@jywarren ?

**Pull request closed without merging**
