### PR TITLE
Edge Detect Horizontal Edges Got Fixed

### LINKED ISSUE #1632: Edge Detect Possibly Glitching on Horizontal Edges
### Please describe the problem (or idea)

The image above is an example output of our edge detect module. It is supposed to generate finest possible edges in the non maximum suppression step itself.
But there are many thick horizontal edges (in the square at the corner for example)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #1632  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Failing travis looks promising.

**Comment by HarshKhandeparkar** [comment]
One of the angle boundaries was weird. When the angle goes to pi it changes to -pi (our trigonometry is awesome). Because of the this, the second E-W boundary is `angle > higher value || angle < lower value` instead of `lower value < angle < higher value`

**Comment by HarshKhandeparkar** [comment]
It looks slightly smoother now but I'm not sure whether it has been completely rectified.

**Comment by blurry-x-face** [comment]
Screenshot from 2020-07-13 23-13-37
It looks slightly better than before, but lower right corner is still glitching

**Comment by HarshKhandeparkar** [comment]
The lower right corner has a different color, I don't it is glitching, what is really glitching are the THICK vertical edges.

**Comment by HarshKhandeparkar** [comment]
Ty for the img :)

**Comment by HarshKhandeparkar** [comment]
FINALLY! AFTER ALMOST A YEAR! I AM LITERALLY CRYING HERE! (sorry for the caps)
edge-detect

**Comment by HarshKhandeparkar** [comment]
We have finally managed to tame this beast that is edge detect!

**Comment by HarshKhandeparkar** [comment]
edge-detect
Now I will be able to sleep properly!

**Comment by HarshKhandeparkar** [comment]
@jywarren @blurry-x-face @publiclab/is-reviewers !

**Comment by jywarren** [comment]
Great work @HarshKhandeparkar !!! 🎉  and great persistence! 

I'm going to try it in GitPod!!

**Comment by jywarren** [comment]
Hmm, what's going on with the test, @HarshKhandeparkar ?

Is this the right output? It seems to work!

Screen Shot 2020-08-05 at 4 44 32 PM

download (10)


Here's the QR code: 

image

**Comment by jywarren** [comment]
@HarshKhandeparkar can you take a look at the tests to see what's going wrong?

image

**Comment by jywarren** [comment]
Looks like, could it be due to syntax errors, or some ES6 issue? In `module.js`:

```
  lineNumber: 67,
  description: 'Unexpected token =>',
  index: 2050 }
```

**Comment by jywarren** [comment]
Perhaps it just needs to be rebased?

**Comment by HarshKhandeparkar** [comment]
The test hasn't been updated to work with the new changes.

**Comment by jywarren** [comment]
Ah ok! No rush then. Thanks, @HarshKhandeparkar !!!

**Comment by HarshKhandeparkar** [comment]
@jywarren Finally pushed the new test.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-module-maintainers Tests Passing! :tada:

**Review by jywarren — APPROVED** [review]
Hooray!

**Comment by HarshKhandeparkar** [comment]
I think this should be merged now, for v3.6.0

**Comment by jywarren** [comment]
Congrats!!

**Pull request merged**
