### PR TITLE
Is Nightly Completed

### LINKED ISSUE #857: IS Nightly
@jywarren @publiclab/is-reviewers how about creating an IS nightly website where daily builds are pushed? The page can be updated everyday after all the PRs of that day are merged. It will be different from the sequencer.publiclab.org website since only stable versions are pushed there. This will help users find bugs in the latest code easily and be like beta testers without having to clone the repo and do all the things the developers do. This can be like an end user feedback form. What are your thoughts??

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #857 

Add links to https://beta.sequencer.publiclab.org where daily/nightly builds are now going to be published!

Removed module.js and info.json files added to the root `/` directory by mistake in exposure module pr.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by jywarren** [comment]
Nice!

**Comment by Harshithpabbati** [comment]
@harshkhandeparkar i made the script to run but see there is some error see in the chrome tools.

**Pull request merged**
