### PR TITLE
(WIP)Refactor UI Code

### LINKED ISSUE #860: Minify the CSS for production
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### LINKED ISSUE #965: Break out module config UI into generateConfigUI.js file and add tests
This section of code is great, and generates the different interfaces for configuring each module, like the left side of this panel, for example:

image

The code is inside a much larger file called `defaultHtmlStepUi.js`, and we should break it out into its own file, called, maybe, `generateConfigUI.js` ?

https://github.com/publiclab/image-sequencer/blob/690c126f41b8698f654283916ecc19271fd4da75/examples/lib/defaultHtmlStepUi.js#L78-L131

Then we should use the new UI testing to ensure that each type of config UI actually gets installed, so for example something like:

```js
expect($('.step-container .details input')).not.toBe([]); // not sure of this syntax
expect($('.step-container .details input').attr('placeholder')).toBe(defaultValue);
```

https://github.com/publiclab/image-sequencer/blob/690c126f41b8698f654283916ecc19271fd4da75/spec/defaultHtmlStepUi.spec.js#L41-L43

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #860
Fixes #965

- Splits the the sequencer part of the UI code from the design and styling of the UI page. Still a Work In Progress.

- Adds a new [Materialize-renderer](https://harshkhandeparkar.github.io/image-sequencer/examples/new/)

- Check these out for discussion and screenshots PR #728, issue #708

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
New project structure:

/
|--examples/
|   |--Renderers.js(list of all renderers)
|   |--index.html(minimal index file)
|   |--index.js(loads the renderer)
|   |--manifest.json(linked inside index.html)
|   |--rendererSwitch(renderer switcher code)
|   |--images/(same images folder)
|   |--renderers/
|   |   |--materialize/
|   |   |   |--js/(all the js code)
|   |   |   |   |--index.js(main js file)
|   |   |   |--css/(all the css code)
|   |   |   |   |--index.css(main css file)
|   |   |   |--index.html(contains renderer markup)
|   |   |   |--dist/
|   |   |   |   |--renderer.js(compiled renderer js)
|   |   |   |   |--renderer.min.js(minified renderer js)
|   |   |   |   |--renderer.css(compiled renderer css)
|   |   |   |   |--renderer.min.css(minified renderer css)
|   |   |--bootstrap/(same as materialize)
|
|--ui/
|   |--index.js(main js to be inported)
|   |--index.css(optional minimal css to be imported)
|   |--DOM/(DOM Code)
|   |   |--helpers.js(notify etc.)
|   |   |--insertPreview.js(same method)
|   |--sequencer/(sequencer code)
|   |   |--setDefaultSequencer.js(initializes everything)
|   |   |--sequence/
|   |   |   |--defaultHtmlSequencerUi.js
|   |   |   |--gif.js(generates sequence GIF)
|   |   |   |--saveSequence.js(save local sequence)
|   |   |   |--setModuleSelector.js(add step)
|   |   |   |--urlHash.js
|   |   |--step/
|   |   |   |--defaultHtmlStepUi.js
|   |   |   |--intermediateHtmlStepUi.js
|   |   |   |--mapHtmlTypes.js
|   |--sw/(service worker)
|   |   |--sw.js
|   |   |--cache.js

@jywarren @publiclab/is-reviewers

**Comment by jywarren** [comment]
Oh wow... have you completed this or are you proposing it? What would be the syntax to switch or select the renderer? Also, are UI tests running on both or just the Bootstrap UI for now?

Thanks, Harsh!! Very cool! Let's link back to your older PR too for the discussion there, and to the original issue about having swappable UIs? 👍

**Comment by HarshKhandeparkar** [comment]
Hello! Answers to your questions and a few notes:

1. I am working on this. The sequencer UI code has been separated but the renderers are a WIP. Materlialize is almost done but I haven't touched bootstrap.

2. To switch renderers, the index file of the renderer is to be loaded, the index file should not contain any high level tags like `html` `body` or `head`, At its root, there should be a`div` and inside the div will be all the markup. This index file can be loaded using the jQuery `$.load()` method. Secondly, the dist js and css files should be loaded. Those files can require any dependency using either `require()` for js or `@import url()` for css and those files will be browserified for js and all the css files will be appended to the dist file so CSS can be split up into different files.

3. No UI tests work currently as the files have been shifted to `ui/` folder. I will change the tests later.

4. All the UI methods like `onLoad` and `onSetup` have their own optional callbacks which get the `step` object as an argument.

5 . Almost all parts of the page like save sequence button can have an optional custom selector. Some ones though have a default selector which cannot be changed. 

6. All the different types of input templates have a function each. This function should return html markup as a string. There are templates for default step markup and step tools(apply, insert) section as well.

7. An optional function can be passed through the options which will iterate through each of the inputs of a step, this can be used to do some initialisation if required.

**Comment by HarshKhandeparkar** [comment]
Old PR #728, issue #708, working [demo](https://harshkhandeparkar.github.io/image-sequencer/) of materialize renderer.

#### Thank You!!

**Comment by HarshKhandeparkar** [comment]
https://github.com/HarshKhandeparkar/image-sequencer/blob/bc1108277afb7da5cf5dfa15e323bceebe53575a/examples/renderers/materialize/js/index.js#L1-L64

**Comment by HarshKhandeparkar** [comment]
The way to import CSS
https://github.com/HarshKhandeparkar/image-sequencer/blob/bc1108277afb7da5cf5dfa15e323bceebe53575a/examples/renderers/materialize/css/demo.css#L1-L5

**Comment by HarshKhandeparkar** [comment]
The exports of `/ui/index.js`

- generateDefaultSequencer(): The main method to be called. Arguements:(sequencer, stepUi, sequencerUi)

- generateStepUi(): generates stepUi to be passed into generateDefaultSequencer(). Arguements: (sequencer, options)

- generateSequencerUi: same as stepUi()
- urlHash: utility(optional)
- sw: utility(optional)
- setSequenceSave: set the save sequence button
- setGifGenerator: generate sequence GIF
- setupCache: sets up the service worker

**Comment by HarshKhandeparkar** [comment]
generateStepUi() and generateSequencerUi() take an options object which can have all the templates(for stepUi), optional callbacks, optional selectors(almost all selectors can be overridden but have defaults)

**Comment by HarshKhandeparkar** [comment]
@jywarren I have explained how the ui code refactoring will work in the comments above.
Thanks.

cc @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
@jywarren did you check this out? Shall I proceed? Will merging this pr cause a big problem to other ones?

**Comment by HarshKhandeparkar** [comment]
@subhahu124 any suggestions for the Materialize renderer are welcomed here. The materialize renderer is the new UI in the demo site

**Comment by HarshKhandeparkar** [comment]
@jywarren I am going to work on this next week.

**Pull request closed without merging**
