### PR TITLE
Update CODE_OF_CONDUCT.md

### LINKED ISSUE #1249: update code of conduct
update to reflect the updates on https://publiclab.org/conduct Aug 28 2019, and also standardize its formatting to match LDI, Mk, etc.

### PR DESCRIPTION
**Pull request by sashadev-sky**
update to reflect the updates on 
https://publiclab.org/conduct Aug 28 2019, and also standardize format to match LDI, Mk, etc.

Fixes #1249   (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@publiclab/is-reviewers

**Comment by sashadev-sky** [comment]
> Thanks for updating!!
@gauravano 
Lol thank you for merging all of these!! I want to get at least the main ones.. 

We could also create one default code_of_conduct file for the organization: https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

but that would require creating a repository for storing default files, and then deleting it from every repo. What are your thoughts?

**Comment by gauravano** [comment]
Hey, thanks for sharing this link. This seems cool, and I think, we should do this, as we have many projects now and using this we would be consistent as well as updated without hassle in all of them. 
@jywarren what do you think?

**Comment by sashadev-sky** [comment]
@gauravano would it be ok to deploy this one for now lol?

**Comment by gauravano** [comment]
Sure @sashadev-sky, we can merge this one. @HarshKhandeparkar @jywarren please merge this.

**Comment by jywarren** [comment]
Great, thank you!!!

**Pull request merged**
