### PR TITLE
slider now goes all way to right & left

### LINKED ISSUE #507: Brightness slider is not going all the way
screen shot 2018-11-30 at 11 52 27 am
The brightness slider is not going all the way for full values.

### PR DESCRIPTION
**Pull request by bhavayAnand9**
Fixes #507 

here's a simple fix for slider not going all the way to right & left. It was due to form-control class in the bootstrap library which add padding of 12px to right & left. 
This PR is adding a form-control class which overrides the padding settings of the bootstrap library.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

screen shot 2018-11-30 at 17 23 34

### CODE REVIEW

**Comment by oorjitchowdhary** [comment]
@bhavayAnand9 Great work... 
Just one thing, I believe the files `dist/image-sequencer.js` and `dist/image-sequencer.min.js` aren't required in the PR...
Apologies if I'm wrong

**Comment by bhavayAnand9** [comment]
As you can see there are no changes in both files but these are automatically added by git because of different implementation of carriage returns or line endings in Windows and UNIX systems.
You'll often see this if one person edits files on Windows (where end of line is the combination of carriage return and newline characters) and you edit in Unix or Linux (where end of line is only a newline character).
Yes, they are not required but they don't do any harm.
I think I should probably remove them. Thanks for pointing that out.

**Comment by jywarren** [comment]
Yes, perhaps best to remove them, thank you!!!

**Comment by bhavayAnand9** [comment]
damn it, accidentally deleted the file. I'll create a new PR.

**Comment by jywarren** [comment]
You may be able to add extra commits to this PR if it's helpful!

**Pull request closed without merging**
