### PR TITLE
cursor change into pointer

### LINKED ISSUE #913: cursor should change into pointer
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you `gift_heart`

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Please describe the problem (or idea)

Peek 2019-03-21 22-07

Peek 2019-03-21 22-11

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #913

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by samagragupta** [comment]
@jywarren Please review.

**Comment by samagragupta** [comment]
@HarshKhandeparkar @Divy123 @jywarren Please review.

**Comment by HarshKhandeparkar** [comment]
@samagragupta do you have GIF (s)/screenshot (s). Several ones would be nice (for different parts).

Thank you!

**Comment by samagragupta** [comment]
@HarshKhandeparkar Done

**Comment by HarshKhandeparkar** [comment]
:+1: LGTM

**Comment by HarshKhandeparkar** [comment]
:+1: LGTM

**Comment by samagragupta** [comment]
@publiclab/is-reviewers @jywarren can you please review the PR

**Comment by jywarren** [comment]
Looks great! Sorry for slow response - i just resolved conflicts and if it passes, I'll merge!

**Comment by samagragupta** [comment]
@jywarren It passed 😄

**Comment by jywarren** [comment]
Great! Thanks a lot!

**Pull request merged**
