### PR TITLE
Update "Installation" section of README.md

### PR DESCRIPTION
**Pull request by Aneal-Sharma**
The following changes make the section more concise by removing unnecessary words.

Fixes #[Add issue number here.]

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Aneal-Sharma** [comment]
@publiclab/reviewers
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by Harshithpabbati** [comment]
@Aneal-Sharma can you please add the issue number.
Thanks

**Comment by HarshKhandeparkar** [comment]
Harshith, I don't think this fixes any issue

**Comment by Aneal-Sharma** [comment]
> I think those words are necessary since they describe how easy it is to use image sequencer. Instead will you try finding some typos or outdated info(if any) and fix those?? Or just improve upon what is there in general.

You are right, I decided to add "just" back into the documentation because it emphasizes the simplicity of the action.

**Comment by Aneal-Sharma** [comment]
> @Aneal-Sharma can you please add the issue number.
> Thanks

My changes do not relate to a specific issue #. I am trying to make the documentation more concise and professional.

**Comment by Aneal-Sharma** [comment]
Is there anything else I need to do before this gets merged? @Harshithpabbati

**Comment by Aneal-Sharma** [comment]
@jywarren

**Comment by jywarren** [comment]
Hi, thanks for the discussion here! I am OK with removing the text, but I think it plays an additional role - to be friendly. Could we, removing this for simplicity, find another place where we could inject a bit of friendliness into the README to compensate? Such as, perhaps, welcoming newcomers with a nice emoji? 👍 🎉 😄

**Comment by Aneal-Sharma** [comment]
I see, thank you for your response. I did not think about the "friendly" role. I will attempt to make some changes to compensate for that.

**Comment by Aneal-Sharma** [comment]
@jywarren Please have a look at the additional changes I made

**Comment by jywarren** [comment]
OK, thank you! Much appreciated; i will merge this now. We'd love more help from you!!! 👍 🎉

**Pull request merged**
