### PR TITLE
Eslint operator spacing config

### PR DESCRIPTION
**Pull request by aashna27**
As suggested by @jainaman224 I realized we were missing this operator spacing config from eslint, a complete list of all eslint rules can be found here https://eslint.org/docs/rules/ and there are still many conventions we lack, so I would go through this guide and add more and request @publiclab/is-reviewers to keep their suggestions coming. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by aashna27** [comment]
@jywarren and @jainaman224 I have added some rules each one in a different commit so that it can be referenced with the cases in our files, please have a look and let me know if you require me to add more or in case of any changes.

**Comment by jywarren** [comment]
This looks super. Can you update the branch? Then this is good to go!!!

**Comment by aashna27** [comment]
> This looks super. Can you update the branch? Then this is good to go!!!
Thanks @jywarren and are there any more conventions that we are missing so that I add them now only? Would be good to complete them in this one!

**Comment by jywarren** [comment]
Not from me! I'm relatively agnostic: two-space tabs, space after comma, and really as long as it's consistent I'm ok with it, I think! Do you like where it is?

**Comment by aashna27** [comment]
> Not from me! I'm relatively agnostic: two-space tabs, space after comma, and really as long as it's consistent I'm ok with it, I think! Do you like where it is?

Yeah I think we have many things and if we can always configure if we need new ones! Yeah then it seems done! Thanks for the quick review and approval. :smile:

**Comment by jywarren** [comment]
Great job!!!

**Pull request merged**
