### PR TITLE
User Preferences API

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes #[Add issue number here.]

Creates a user preferences API which can be used to store user preferences using indexedDB API in the browser.
* No implementation yet
* A new file added in `/src/ui/`
* Documented in `CONTRIBUTING.md`

### My future plans
* Using this to store preference about wheter to generate previews or not because the previews take a lot of time to generate.
* There is a dark theme suggestion which can benefit from this.
* Store preferences about whether to cache or not.
* User created saved sequences.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review :)

**Comment by HarshKhandeparkar** [comment]
I will add tests along with implementations in a followup. The implemention ideas are just ideas and anyone can implement them
cc @jywarren @publiclab/is-reviewers

**Comment by jywarren** [comment]
oh this is really nice! What do other @publiclab/is-reviewers think!

**Comment by Divy123** [comment]
I think this is really nice. We are using browser provisions to the fullest at thier best.
Thanks Harsh for opening this!

**Comment by HarshKhandeparkar** [comment]
@jywarren @Divy123 @aashna27 @publiclab/is-reviewers this can help in the previews part.

**Comment by aashna27** [comment]
lets see how much longer the previews take after optimization and then set if people want them or not

**Comment by HarshKhandeparkar** [comment]
This can also be used for other things(listed in the issue or new ideas). What do you think? Can you review it?

**Comment by Divy123** [comment]
I think this can be a great task.
Do you want any help on this @HarshKhandeparkar ?

**Comment by HarshKhandeparkar** [comment]
@Divy123 could you test if this works?

**Pull request closed without merging**
