### PR TITLE
Fixes unexpected behavior of step panel dropdown

### LINKED ISSUE #1327: dropdown button in each step panel is always closing the last step
The dropdown button in each step panel is always closing the last step. It should close the current step
Untitled_ Dec 6 2019 12_06 AM

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #1327 
Fixes unexpected behavior  of step panel dropdown
Untitled_ Dec 6 2019 3_24 AM

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywarren @HarshKhandeparkar Can you please review the changes!!

**Comment by keshav234156** [comment]
@jywarren So made changes as per the @HarshKhandeparkar review. I also think it good to $step , $stepAll local variable. Thanks a lot, @HarshKhandeparkar for such a constructive review

**Comment by keshav234156** [comment]
Thanks!! @HarshKhandeparkar for notifying me

**Comment by jywarren** [comment]
Great work!!!

**Pull request merged**
