### PR TITLE
update value below the slider

### LINKED ISSUE #564: The value below the slider does not updates with slider's movements
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The value below the slider does not updates with slider's movements.

pop

### Please show us where to look

https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js

### What's your PublicLab.org username?
Mridul97
> This can help us diagnose the issue:

### Browser, version, and operating system
Chrome, Windows 8.1
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

cc @jywarren  @tech4GT

### PR DESCRIPTION
**Pull request by Mridul97**
Fixes #564 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Mridul97** [comment]
@tech4GT please review this! 

Output :

pp

**Comment by tech4GT** [comment]
I think Harsh has a point here. Maybe there is a better way to do this. Nice catch though Mridul! :+1:

**Comment by Mridul97** [comment]
@tech4GT I have made the changes. Please have a look!

**Comment by jywarren** [comment]
Merged!

**Pull request merged**
