### PR TITLE
add toCliString function fixes #140

### LINKED ISSUE #140: Make demo display corresponding commandline syntax for current sequence
This would be great to emphasize in the demo how the same command can be run from the CLI interface.

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren The test for this function I will add once we merge in #293

**Comment by jywarren** [comment]
OK, looks good pending those tests!

**Comment by tech4GT** [comment]
@jywarren ready to merge

**Comment by tech4GT** [comment]
@jywarren Rebased!!

**Comment by tech4GT** [comment]
@jywarren please merge this in. Thanks!

**Pull request merged**
