### PR TITLE
Fix for Dynamic module

### PR DESCRIPTION
**Pull request by root00198**
Issues in Dynamic Modules : 

There is a input by name `monochrome (fallback)`  whose description is `Expression to return with R, G, B, and A inputs; fallback for other channels if none provided`. But when the inputs for Red, Green, Blue are not provided it should consider the default values, which it is not and hence creating issues like :- '

- The command line interface not working and shows a black image.
BEFORE FIX
cli-not-working
AFTER FIX 
cli-working

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by root00198** [comment]
ask @publiclab/is-reviewers

**Comment by root00198** [comment]
Yes, it still let user set those values...

**Comment by cesswairimu** [comment]
thanks so much for opening this :tada: could you please add the issue link to the issue this pull request fixes on your pull request on this line "Fixes issue_link" this will help other contributors while reviewing your changes. Thanks

**Comment by root00198** [comment]
A test for this module alredy exist, its options were set in such a way that the test passes, and there is no issue. The test is well written.

**Comment by jywarren** [comment]
Fantastic. Thank you!!

**Pull request merged**
