### PR TITLE
resolves #131 create output directory immediately

### LINKED ISSUE #131: Specifying a CLI output directory could offer more explanation, create directory immediately
It could indicate that `the output will be a folder containing a sequence of images` and we could allow specifying the output directory name. 

The directory should also be created immediately, rather than once the images are ready, as it's confusing when there's nothing changed immediately upon running a command. But if I misunderstand how this works, please set me right! :-)

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by tech4GT** [comment]
@jywarren please have a look😁

**Comment by jywarren** [comment]
Awesome! Do you think it would be tough to add a test for this? I guess we don't have CLI tests... what do you think?

**Comment by tech4GT** [comment]
@jywarren Not at all. Adding a test for this right away😁

**Comment by tech4GT** [comment]
@jywarren should i create a separate issue for adding cli tests so we can add tests for other stuff like validate steps as well, what say?

**Comment by tech4GT** [comment]
@jywarren actually for creating this output directory all we have done is just call a native nodejs file system function so for adding a test for this i would have to wrap this up in a function but since it is only one line it will introduce unnecessary complexity, should i do it?

**Comment by jywarren** [comment]
Actually i think making a `createDirectory` function independently is probably a good idea, no? Clearly marked as running on the CLI/node only? What do you think?

**Comment by tech4GT** [comment]
@jywarren it's done please have a look, also i found a small error that if we do not give any steps to cli it does not exit cleanly, so i also fixed that in [this commit](https://github.com/publiclab/image-sequencer/pull/167/commits/42c194f44f4b6a13171ffad8c84965acb3614600). Thanks

**Comment by jywarren** [comment]
Awesome, thanks so much!!! 🎉

**Pull request merged**
