### PR TITLE
UI Version Number Made More Readable

### LINKED ISSUE #1475: Displayed Version Number is not Visible
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
The current version of IS that is used is displayed in the UI at the top right corner but it is not visible.
**NOTE**: The version number has been highlighted manually in the image below.
Screenshot from 2020-01-12 23-20-07

You have to change the appearance of this text to make the text more readable.

Files to refer:
1. https://github.com/publiclab/image-sequencer/blob/12c422a07b55233ae94e13fc3700da2101916c65/examples/demo.js#L38-L42
2. https://github.com/publiclab/image-sequencer/blob/12c422a07b55233ae94e13fc3700da2101916c65/examples/demo.css#L318-L328

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by damn-dvlpr**
Fixes #1475  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@damn-dvlpr coud you please upload a Gif, thanks!

**Comment by jywarren** [comment]
We can now review this using GitPod. Checking!

(https://gitpod.io/#https://github.com/publiclab/image-sequencer/pull/1567)

Looks great!

Screen Shot 2020-07-10 at 3 00 15 PM

It does say "unable to load version number" until the page is finished loading. Maybe it should say:

`Loading version number` until it's loaded, but if it fails we rescue and try changing to `Unable to load version number`?

What do you think?

**Comment by HarshKhandeparkar** [comment]
This PR has got nothing to do with the unable so it can be merged, that one will need a separate issue :)

**Review by jywarren — APPROVED** [review]
Looks great! Thank you!

**Pull request merged**
