### PR TITLE
Colormap fixes!

### LINKED ISSUE #332: Error in default color map
https://github.com/publiclab/image-sequencer/blob/cce65141d284d12fbb5c6e5331a29c72cb17eab8/src/modules/Colormap/Colormap.js#L59-L63

via @MargaretAN9 shows an error in the default color bar, which has 2 "yellow" regions. We'd love help fixing this!

image

### PR DESCRIPTION
**Pull request by jywarren**
fixes #332 !!! @MargaretAN9

### CODE REVIEW

**Comment by MargaretAN9** [comment]
please tell me if I need to do anything

**Comment by jywarren** [comment]
Nope just let these tests run!!!! Glad to see you!!

**Comment by jywarren** [comment]
Did u see the progress on the opencv module? Exciting

**Comment by MargaretAN9** [comment]
not yet will check it out

**Comment by jywarren** [comment]
ok had to compile this wtih `grunt build` and pushed up the files

**Comment by jywarren** [comment]
OK, rebased, rebuilt, and one more test run but i'll go to sleep now and merge in the morning! Good night!!!

**Comment by MargaretAN9** [comment]
Cool will check on it Sat

**Comment by jywarren** [comment]
Oops, forgot to add the new colormaps to the interface! Did that in an extra commit:

image

**Comment by jywarren** [comment]
and this is ready to merge once this passes, finally! Thanks SO MUCH for your work on this, it's tremendous. Next step could be to develop a sequencer string which would output a sample 1x100 px strip for each map, so we could show them visually in the interface!

**Comment by jywarren** [comment]
it could be substantially based on the `colorbar` module!

**Comment by jywarren** [comment]
So nice!!!

**Comment by jywarren** [comment]
image

**Comment by MargaretAN9** [comment]
@jywarren 
-Checked on the 7 colormaps, 5 out of 7 are good
-2 need updates, greyscale and fastie, not sure how the error was introduced since they were fine in the original code.  This is easy to fix by going back to prior code.   Should I submit a request?
-there should be 8 colormaps in all, 'bluwhtgrngis' was not added to the list, 
-will make a post with the same picture using the different colormaps when they are complete

**Comment by jywarren** [comment]
oh ok, sorry i must've missed one, and hope i didn't introduce an error in
the others. Yes please submit a new PR! Try also running `grunt build` on
your work once you do, so it gets compiled. Thanks, and great work!

**Pull request merged**
