### PR TITLE
Allow saving onto Publiclab.org

### LINKED ISSUE #1332: Allow saving onto PublicLab.org
PublicLab.org now allows (if you're logged in) for opening an image into the editor at https://publiclab.org/post (again, must be logged in)

The docs for this are here: https://github.com/publiclab/plots2/issues/6594#issuecomment-562389677

And I've just completed this in Infragram, here:

https://github.com/publiclab/infragram/commit/7ca92dbf9f630f6010847c26f770cbada7e5a454

So, we should add one more type to the ImageSequencer "Save" box, which is "Save to PublicLab.org" -- shown here:

image

Once you do this, you should see the https://PublicLab.org/post editor open, like this:

image

You can test this out by pasting the following code into the console in https://sequencer.publiclab.org --

```js
function postToPL(imgSrc) {
  var uniq = Date.now();
  $('body').append('<form method="post" id="postToPL' + uniq + '" action="https://stable.publiclab.org/post" target="postToPLWindow"><input type="hidden" name="datauri_main_image" /></form>');
  f = $('#postToPL' + uniq)[0];
  f.datauri_main_image.value = imgSrc;
  window.open('', 'postToPLWindow');
  f.submit();
}
postToPL($('img')[0].src)
```

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #1332 
70374524-3ad2ed00-1919-11ea-8b5f-499afb697069

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywarren can you please review this?

**Comment by jywarren** [comment]
Sure, can you resolve conflicts while I do? Thanks!

**Comment by keshav234156** [comment]
@jywarren  Sure!!

**Comment by jywarren** [comment]
This is so great!!!! 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
