### PR TITLE
switch to expr-eval for dynamic module

### LINKED ISSUE #1728: CRITICAL: Dynamic module uses eval
### Please describe the problem (or idea)
The `dynamic` module uses the javascript `eval` function to evaluate expressions. But the exec method should not be used **at any cost** because it will **execute any js code that is entered in the textbox**.

image

This is a major security threat to the IS demo and any other projects that use IS.
### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #1728 by replacing `eval()` with `expr-eval` for mathematical expressions

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
It's breaking, I think we should do this in 3.6.1.

**Comment by jywarren** [comment]
Ok no problem, sounds good! Should be pretty simple to fix then. Thanks!!

**Comment by jywarren** [comment]
I'm seeing some `MinifyImage` issues related to `=>` the ES6 function syntax... odd.

**Comment by HarshKhandeparkar** [comment]
npm install must have bumped some of the deeper dependencies in the lockfile. This is the same reason that is causing the audits to fail...

**Comment by jywarren** [comment]
aha! also:

```
      throw new Error('parse error [' + coords.line + ':' + coords.column + ']: Expected ' + (value || type));
      ^
Error: parse error [1:6]: Expected EOF
    at ParserState.expect (/home/travis/build/publiclab/image-sequencer/node_modules/expr-eval/dist/bundle.js:1049:13)
    at Parser.parse (/home/travis/build/publiclab/image-sequencer/node_modules/expr-eval/dist/bundle.js:1772:17)
    at Function.Parser.parse (/home/travis/build/publiclab/image-sequencer/node_modules/expr-eval/dist/bundle.js:1784:25)
    at generator (/home/travis/build/publiclab/image-sequencer/src/modules/Dynamic/Module.js:9:1245)
    at /home/travis/build/publiclab/image-sequencer/src/modules/Dynamic/Module.js:9:1952
    at Array.forEach (<anonymous>)
    at Object.draw (/home/travis/build/publiclab/image-sequencer/src/modules/Dynamic/Module.js:9:1505)
    at drawStep (/home/travis/build/publiclab/image-sequencer/src/Run.js:9:2704)
    at drawSteps (/home/travis/build/publiclab/image-sequencer/src/Run.js:9:3842)
    at Run (/home/travis/build/publiclab/image-sequencer/src/Run.js:9:4953)
```

**Comment by jywarren** [comment]
Now the only error seems to be:

```
> TEST=true istanbul cover tape test/core/*.js test/core/ui/user-interface.js test/core/modules/*.js | tap-spec;

    Failed to parse file: /home/runner/work/image-sequencer/image-sequencer/src/modules/MinifyImage/Module.js
Transformation error; return original code
Error: Line 67: Unexpected token =>
```

which is an ES6 issue. 

Sorry, that's not an issue here, that occurs in main branch too and i made an issue: https://github.com/publiclab/image-sequencer/issues/1810

OK, so what else in that test run?

```
  dynamic module works correctly with different options


    ✖ dynamic module works correctly with initial option undefined
    ---------------------------------------------------------------
      operator: equal
      expected: true
      actual:   false
      at: Immediate._onImmediate (/home/runner/work/image-sequencer/image-sequencer/node_modules/looks-same/lib/utils.js:75:17)
      stack: |-
  Error: dynamic module works correctly with initial option undefined
  at Test.assert [as _assert] (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:228:54)
  at Test.bound [as _assert] (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:80:32)
  at Test.equal (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:389:10)
  at Test.bound [as equal] (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:80:32)
  at /home/runner/work/image-sequencer/image-sequencer/test/core/templates/options-test.js:40:11
  at /home/runner/work/image-sequencer/image-sequencer/node_modules/looks-same/index.js:183:13
  at Immediate._onImmediate (/home/runner/work/image-sequencer/image-sequencer/node_modules/looks-same/lib/utils.js:75:17)
  at processImmediate (internal/timers.js:461:21)


    ✖ dynamic module works correctly when the option is changed to undefined
    -------------------------------------------------------------------------
      operator: equal
      expected: true
      actual:   false
      at: Immediate._onImmediate (/home/runner/work/image-sequencer/image-sequencer/node_modules/looks-same/lib/utils.js:75:17)
      stack: |-
  Error: dynamic module works correctly when the option is changed to undefined
  at Test.assert [as _assert] (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:228:54)
  at Test.bound [as _assert] (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:80:32)
  at Test.equal (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:389:10)
  at Test.bound [as equal] (/home/runner/work/image-sequencer/image-sequencer/node_modules/tape/lib/test.js:80:32)
  at /home/runner/work/image-sequencer/image-sequencer/test/core/templates/options-test.js:57:13
  at /home/runner/work/image-sequencer/image-sequencer/node_modules/looks-same/index.js:183:13
  at Immediate._onImmediate (/home/runner/work/image-sequencer/image-sequencer/node_modules/looks-same/lib/utils.js:75:17)
  at processImmediate (internal/timers.js:461:21)
```

Let's see if it passed earlier tests. Maybe our new `expr-eval` doesn't handle undefineds and we need to screen.

**Comment by jywarren** [comment]
This looks like it could be a similar issue as @blurry-x-face faced using `looks-same`, as I can't see any other reason it'd be different. The test that's failing is this, and we haven't changed much before/after:

https://github.com/publiclab/image-sequencer/blob/0cbefa37bba716b7e98a2ff3fcce5563a7f3d0c6/test/core/templates/options-test.js#L37-L41

Although perhaps it's that the `expr-eval` package is generating a function differently. Let me add a test for that.

**Comment by jywarren** [comment]
OK, got it - this implementation didn't work, the generator function outputs:

```js
> generator('B+B')+''
'function () {\n      return f.apply(expr, arguments);\n    }'
```

**Comment by jywarren** [comment]
OK it was struggling with undefineds in `      let expr = Parser.parse('R = r; G = g; B = b; A = a; ' + expression);` so i'll just copy the options rather than try to assign them within the expression

**Comment by jywarren** [comment]
Nice! @HarshKhandeparkar got this to work!!!

**Comment by HarshKhandeparkar** [comment]
Wow! :tada:

**Pull request merged**
