### PR TITLE
Include a back-to-top Button on scrolling down

### LINKED ISSUE #346: Include a back-to-top Button on scrolling down
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem
We want to include a button at the bottom-right corner of the screen in the main UI when we scroll the page to make it easy to go back to top with a smooth scrolling effect, which is currently missing and can be implemented as shown below.

scrolleffect

## The Solution
We want to layout the button using an <a> tag in HTML, along with [font-awesome](https://github.com/FortAwesome/Font-Awesome), then style it using CSS and finally write a few lines of jQuery to make the scrolling part work.

A seperate JavaScript file can be made for this functionality under [examples/lib/scrollToTop.js](https://github.com/publiclab/image-sequencer/tree/main/examples/lib), containing the necessary JavaScript code.

The HTML can be included in the [examples/index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) and the CSS in [examples/demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css).

Make sure to include the JavaScript file in the `<script>` tag before the body ends and the button in the HTML markup above that. 

**Instance Count = 1**

### PR DESCRIPTION
**Pull request by thesparks**
Fixes #346 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by thesparks** [comment]
@rockstar777 @rbhatia46 @jywarren please check

**Comment by thesparks** [comment]
deepin-screen-recorder_select area_20181027123726

**Comment by thesparks** [comment]
Can i call @_publiclab/reviewers in my future GCI pull-reqests?

**Comment by rockstar777** [comment]
awesome work!
thanks

**Comment by tech4GT** [comment]
This is ready to merge! Thanks!

**Comment by jywarren** [comment]
Very cool, thank you!!!

**Comment by jywarren** [comment]
Nice implementation, too, nicely modular!

**Pull request merged**
