### PR TITLE
Assigned ref.images[image].steps[i] to a variable to stop duplication

### LINKED ISSUE #228: (multiple) Optimize code based on CodeClimate recommendations
CodeClimate shows a lot of possible improvements that could be made to this codebase. We don't have extremely high test coverage, but we can tackle these optimizations one by one, and many are suitable for [first-time contributors](https://publiclab.github.io/community-toolbox/#r=all)!

[CodeClimate issues](https://codeclimate.com/github/publiclab/image-sequencer/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)

If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is your first time, try to solve one of these yourself! Please ask for help by posting a comment below.

Each issue CodeClimate points out is listed below. Some may be able to "convert" these to issues with the button shown. Otherwise just note which you'd like to address in the comments:

image

Once you've chosen one, try opening a pull request with your improvements and we'll help you take the next step!

### PR DESCRIPTION
**Pull request by Sand038**
Fixes #228

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@Sand038 you can remove the square brackets in the issue number like I just did.

**Comment by HarshKhandeparkar** [comment]
You can also mention `@publiclab/is-reviewers` to ask for a review.

**Comment by Sand038** [comment]
Thanks. Next time I'll do those changes when I commit. Where should I mention '@publiclab/is-reviewers'? And I don't see any further refactoring in this file regarding code duplication 😃

**Comment by HarshKhandeparkar** [comment]
Cool! You can mention @publiclab/is-reviewers in the discussion (comments) of a PR.

**Comment by HarshKhandeparkar** [comment]
Also refactoring doesn't necessarily mean code repetition prevention. It can mean splitting up the file into diffetent files(not really necessary here) or changing names of functions or even changing some code(which is repeated) into functions.

**Comment by jywarren** [comment]
Great work, thank you!!!

**Pull request merged**
